### ISSUE TITLE
feat: add ReX's latest updates

### ISSUE THREAD

**Issue by federicogith** [anddea/revanced-patches#10]
### Application

YouTube

### Feature description

**1. [feat(Hide Trending Searches): Patch now also remove recommended searches](https://github.com/YT-Advanced/ReX-patches/commit/dfd841963861fb4394292adb3eb4a4716e5061a6)
2. [fix(Hook Download Button): Not worked when spoofing to older version](https://github.com/YT-Advanced/ReX-patches/commit/5162ceb01a6194cfc28be52231395fb70bc8f2db)**

### Motivation

They fix two issues.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
We discussed this personally with YT-Advanced, it's not ready yet.
