### ISSUE TITLE
feat (YT) : Hide "Latest videos" in search results when you search the name of a particular channel.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#104]
### Application

YouTube

### Feature description

When you search for the name of a particular channel, this "Latest videos" shelf also shows up. So, kindly add the ability to hide it.
![Screenshot_2024-03-22-09-47-21-76_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/dbae1742-806a-480d-a9fd-d28d564816e9)

### Motivation

There is no point of this shelf, user can just open the channel and see newest videos.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
There's an option `Hide suggested shelf` that is default now, but if you update on top, you have to go to Extended > General settings and turn it on.

**Comment by Aryan-Chauhan** [comment]
> There's an option `Hide suggested shelf` that is default now, but if you update on top, you have to go to Extended > General settings and turn it on.

It has always been on, but still showing. I'm using latest patches on v19.09.37
![Screenshot_2024-03-22-13-31-47-72_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/anddea/revanced-patches/assets/91815107/5c47075e-86e9-4b9e-826f-b2fb7f98f28f)
