### ISSUE TITLE
question: new features

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#106]
### Application

YouTube

### Question description

Keyword filter for feed and search
-> Keyword filter for home feed and search results

Keyword filter for subscriptions
-> Keyword filter for subscriptions feed

Is this right?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Yes, it is.
