### ISSUE TITLE
feat: Make `Hide fullscreen button` with ON/OFF switch

### ISSUE THREAD

**Issue by Kuddus73** [anddea/revanced-patches#11]
### Application

YouTube

### Feature description

Make `Hide fullscreen button` patch with a switch in settings.

### Motivation

It will make it more user-friendly.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
the patch works by modifying the xml file during compile time. unfortunately this cannot be done during runtime.

**Comment by Francesco146** [comment]
fixed in RVX
