### ISSUE TITLE
feat: apply ReX's `Hide Suggested Video Overlay` A/B bug fix

### ISSUE THREAD

**Issue by federicogith** [anddea/revanced-patches#112]
### Application

YouTube

### Feature description

[fix(YouTube - Hide Suggested Video Overlay): Shelves is not hidden due to A/B Testing](https://github.com/YT-Advanced/ReX-integrations/commit/855b4181ce32bc7df7c87dddfb95c86928f399aa)

### Motivation

It would fix an issue.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by federicogith** [comment]
Oh sorry, didn't see that.

Could you officially release the updates as ReVanced Manager doesn't allow patching dev releases?

**Comment by anddea** [comment]
ReVanced Manager is incompatible with RVX, use [RVX Manager](https://github.com/inotia00/revanced-manager/releases) instead. It shows dev releases.
