### ISSUE TITLE
bug: PIP mode bug

### ISSUE THREAD

**Issue by Aniblock43** [anddea/revanced-patches#114]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.09.37, Patches version v2.221.1

### Bug description

When you go into pip mode the video is not displayed properly, have to restart the app to correct it
![Screenshot_20240322_193231_One UI Home](https://github.com/anddea/revanced-patches/assets/62948980/5083d8af-d5e7-489e-8f52-ee7fe17d0f7a)

### Device Environment

Android 14, One Ui 6, Galaxy S23 ultra

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I need more specific steps to reproduce. If you disable extended > fullscreen > keep landscape mode, do you still face this issue?

Duplicate https://github.com/anddea/revanced-patches/issues/13

**Comment by anddea** [comment]
Unfortunately, I can't reproduce it, if you still face this issue and can provide more info, you can comment here.

**Comment by Aniblock43** [comment]
Hi, sorry for the late reply, but yes, the issue happens only when I have 'keep landscape' mode on. To reproduce the issue, you need to lock the screen and go to PIP mode after you unlock it while 'keep landscape' is turned on.

**Comment by anddea** [comment]
Yes, I thought so, it can cause this issue, I'll add some note to that setting. No solution for `keep landscape mode` and PIP for now. Btw, it is turned off by default in the settings now.
