### ISSUE TITLE
question: Shorts overlay buttons

### ISSUE THREAD

**Issue by AliBASE** [anddea/revanced-patches#118]
### Application

YouTube

### Question description
Youtube version: 19.09.37

I am trying to change the shorts overlay buttons to Tiktok or outlineCircle, but it's not changing. I enabled the **"Shorts overlay buttons"** patch and select TikTok, tried to patch using cli on pc, rvx manager on android and Revancify, the same thing it won't change, are there other patches to include or exclude or just the **"Shorts overlay buttons"**?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
If you're patching old YouTube version then for TikTok it'll be default YouTube icons and for OutlineCircle it'll be Outline icons. If you're patching new versions then everything should work as expected.
