### ISSUE TITLE
feat: hide videos with low views from related videos

### ISSUE THREAD

**Issue by CodeF53** [anddea/revanced-patches#122]
### Application

YouTube

### Feature description

![Screenshot_20240323-013249](https://github.com/anddea/revanced-patches/assets/37855219/fd36f874-b4e8-445a-981d-ea23642429ac)
Currently this patch only applies to the home page, it would be nice if it also applied to the feed you see while watching something. 

### Motivation

Same reason as the main patch, I don't care about some 5 year old playing roblox. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Can you share a screenshot

**Comment by CodeF53** [comment]
@YT-Advanced 
> Can you share a screenshot

![Screenshot_20240324-091515](https://github.com/anddea/revanced-patches/assets/37855219/1e7ce579-5a45-440e-90c9-2c1ee6fae342)

**Comment by anddea** [comment]
@YT-Advanced the thing is that lowViewsIdentifier = "g-highZ" is related to "home_video_with_context.eml" and not all "video_with_context", I'll check that as well, but if you find the right filter, let us know.

**Comment by YT-Advanced** [comment]
Yeah, since I don't have these video in my related video feed, so I just create a branch for you to test it

**Comment by CodeF53** [comment]
> Yeah, since I don't have these video in my related video feed, so I just create a branch for you to test it

What stuff can I enter into the RVX manager to test this branch? Or were you talking to anddea?

**Comment by anddea** [comment]
He was talking to me, you can't test branches in Managers or Revancify.

**Comment by anddea** [comment]
I've rewritten this option. Now it hides videos anywhere and you can specify your own minimum number of views. It'll be more performance-dependent if you scroll through a lot of videos that should be filtered out. Let me know if you face any issues. There's a room for improvement, so I'm gonna work on that in my spare time, you can share your suggestions.

[v2.223.0-dev.3](https://github.com/anddea/revanced-patches/releases/tag/v2.223.0-dev.3)
