### ISSUE TITLE
Please add support for newer yt music versions🙏

### ISSUE THREAD

**Issue by Xisrr1** [anddea/revanced-patches#124]

**Comment by anddea** [comment]
Support for newer versions added in [v2.222.0-dev.8](https://github.com/anddea/revanced-patches/releases/tag/v2.222.0-dev.8) and pushed to the latest stable release [v2.222.0](https://github.com/anddea/revanced-patches/releases/tag/v2.222.0).

**Comment by Xisrr1** [comment]
Hmm the suggested version didn't change. What is the latest working version?

**Comment by anddea** [comment]
> Hmm the suggested version didn't change. What is the latest working version? @anddea

All versions of YT music are supported, except for patches that show a warning if it is not supported (for example, an old-style miniplayer).

**Comment by Xisrr1** [comment]
I got you, thanks!
