### ISSUE TITLE
Does any question: 

### ISSUE THREAD

**Issue by rohith-cell** [anddea/revanced-patches#125]
### Application

YouTube

### Question description

Can any one explain how to use revanced manager to patch patch youtube using anddea path integration.

I just want to know what organisation and what patch integration I need to fill in .

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Organization is always the name of author, for anddea it is `anddea`. And sources for patches and integrations are always name of author's repos.

Patches
```
anddea
```
```
revanced-patches
```

Integrations
```
anddea 
```
```
revanced-integrations
```

**Comment by rohith-cell** [comment]
Thanks a lot for your reply bro.
