### ISSUE TITLE
[Feature] the icon of Rex setting changes based on the app icon

### ISSUE THREAD

**Issue by speedlorenzo12** [anddea/revanced-patches#126]
### Application

YouTube

### Feature description

The REX settings icon changes based on the app icon based on whether you are using custom branding or not; for example if you are using Revancify Red the Rex settings will also have the icon
(I hope I have been clear enough)

### Motivation

The reason is that it is aesthetically more beautiful

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
feature implemented in the latest dev release, consider closing this ^^
