### ISSUE TITLE
feat(YouTube): add `Enable speed overlay` patch

### ISSUE THREAD

**Issue by girshcatt** [anddea/revanced-patches#127]
### Application

YouTube

### Feature description

add `Enable speed overlay` patch to enable speed overlay for 18.35.xx and lower

### Motivation

Speed overlay is the only useful feature from the new ui, but i does not want to update to 18.36.xx+ just because of it

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
isn't this already implemented in anddea? I'm sure it is in RVX
