### ISSUE TITLE
Pip / picture-in-picture doesn't show video

### ISSUE THREAD

**Issue by Kiwikip** [anddea/revanced-patches#13]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 19.05.36

### Bug description

When entering pip it shows part of the normal layout that's not the video. Like the title or playlist (see screan shot) and sometimes it is fully translucent. If the pip is translucent, when opening the app again, the video is black screen. You are able to go to next, but it is also black.

How to reproduce? Not sure.. It happens when entering pip, but after watching while(i think). 
![Screenshot_20240311_202343_Cells](https://github.com/anddea/revanced-patches/assets/130678837/2e20d38a-e1d6-468c-8261-936356ce6e34)
.

### Solution

Restarting the app

### Device Environment

Android 14 s24ulta 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can't reproduce it. Probably, there should be specific steps to reproduce. Does this always happen?

**Comment by anddea** [comment]
Unfortunately, I can't reproduce it, if you still face this issue and can provide more info, you can comment here.
