### ISSUE TITLE
bug: Scrolling through description box behaves erratically, scrolls all the way down or up automatically

### ISSUE THREAD

**Issue by Shotgat** [anddea/revanced-patches#132]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Revanced Extended 19.05.36

### Bug description

when you are inside of a (long) description box and you press on the screen to start scrolling, the screen automatically scrolls up or down very quickly and lands on a random spot. This doesn't seem to happen if you touch the very sides of the screen and scroll up or down, only in odd spots in the centre. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by speedlorenzo12** [comment]
I did a test, as I understand it; this bug comes from normal youtube

**Comment by anddea** [comment]
Actually I couldn't reproduce it, any video link where this issue occurs would be helpful, but it's definitely should be on YouTube side.

**Comment by Shotgat** [comment]
https://github.com/anddea/revanced-patches/assets/83924131/5b2aa37d-b29d-4ed0-b859-471cfa02283e

I know you can't see my touch inputs.. but essentially everytime the screen rubberbands really quickly from top to bottom and highlights text, it's because I'm touching a part of the text (above the time stamps), and the screen treats it as if I'm holding and dragging. It seems to happen to every description box that's scrollable.

However if this is a YouTube bug I'll just wait and see if it's fixed in future releases, thanks.

**Comment by Shotgat** [comment]
> Actually I couldn't reproduce it, any video link where this issue occurs would be helpful, but it's definitely should be on YouTube side.

See my post if possible.

**Comment by anddea** [comment]
> See my post if possible.

Can you send me a link or a name of this video, so I can test it?

**Comment by Shotgat** [comment]
> > See my post if possible.
> 
> Can you send me a link or a name of this video, so I can test it?

Any video with a long description will do, but the particular one I was referencing was this:

https://www.youtube.com/watch?v=1pAwuzC1THk

Try tapping near any text at the top of the first paragraph in the description (before time stamps), it sends the page scrolling down for me, though strangely if you touch the very edges of the screen it doesn't seem to trigger it

**Comment by anddea** [comment]
Interesting, I can't reproduce it. Can you check on stock YouTube just to be sure?

**Comment by anddea** [comment]
> However if this is a YouTube bug I'll just wait and see if it's fixed in future releases

19.11 is supported now, so you can update now.

**Comment by Shotgat** [comment]
> Interesting, I can't reproduce it. Can you check on stock YouTube just to be sure?

It seems to be a bug on official YT, tested on 2 devices, others seem to have the same issue... guess it doesn't affect everyone, but it's not a huge dealbreaker, hopefully it's patched in the next release(s)
