### ISSUE TITLE
bug: unable to patch in Disable Auto HDR brightness with rvx-builder under certain circumstances.

### ISSUE THREAD

**Issue by Raven-621** [anddea/revanced-patches#133]
### Type

Error while patching

### Tools used

rvx-builder

### Application

Youtube 19.11.38

### Bug description

>Direct APK upload (for some reason, app list won't show up to me in any rvx-builder)
>Patch like usual
![firefox_yFRIQrDqjZ](https://github.com/anddea/revanced-patches/assets/141109979/d6effc7e-ca38-45c2-b00f-5c2b308d57d9)

### Device Environment

OneUI 2.0, A10

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It's removed because it's not relevant anymore. There's no auto brightness for HDR and so there's nothing to disable. Because it's disabled by default in new versions.
