### ISSUE TITLE
suggestion:  Close issues which don't make sense 

### ISSUE THREAD

**Issue by selfmusing** [anddea/revanced-patches#137]
### Application

Other

### Suggestion description

We really appreciate you hard work , but It doesn't mean that we should just put all the responsibility on your shoulders alone !!..

Issue Count reached 40 in less than a month & most of them don't even make sense , because either the original app has the same bug or google removed the code to make some features incompatible on the latest updates. 

People have to understand that new version comes with some new issues & incompatibiliies.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Fortunately, I didn't open any issues that don't make sense.

All of them are reasonable :D

**Comment by anddea** [comment]
Tbh, I even forget to cleanup issues when there's a new release fixing something or implementing a new feature.

> all the responsibility on your shoulders alone

Glad, I'm not alone, there are features/fix commits by rufusin and rex, translation commits by other memebers.
