### ISSUE TITLE
bug: Notification/create con missing from beside the search icon

### ISSUE THREAD

**Issue by Raven-621** [anddea/revanced-patches#138]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 19.11.38

### Bug description

Notification/create button disappears from beside the search button at top right corner of the app
![20240325_023728](https://github.com/anddea/revanced-patches/assets/141109979/a7393192-104c-42e3-ba8f-e5c00149775b)
Previous version of the patches version and YT don't have this problem.

### Device Environment

OneUI 2.0, A10

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It's an option in Settings > Extended > General > Hide buttons in toolbar.
