### ISSUE TITLE
Outline icons on shorts not working (YouTube)

### ISSUE THREAD

**Issue by TheWitch69** [anddea/revanced-patches#139]
### Type

Other

### Tools used

Revancify

### Application

YouTube v19.11.38

### Bug description

Trying every choice but not working with revanced manager same problem.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I can't reproduce it. Please make sure that you choose the correct patch `Shorts overlay buttons`, there you have 3 different types of icons. Make sure it's included in Settings > Extended > Misc > Patches info > Shorts.

**Comment by TheWitch69** [comment]
I am very sure. I checked several times but it doesn't work
![Screenshot_20240324_223236_YouTube](https://github.com/anddea/revanced-patches/assets/131497172/65a53f18-eb6d-4f82-98d4-ea474681c303)

**Comment by anddea** [comment]
> I am very sure. I checked several times but it doesn't work

What icons do you see now in Shorts? Can you share a screenshot?

**Comment by TheWitch69** [comment]
I try outline or outline circle but not work 
![Screenshot_20240324_224826_YouTube](https://github.com/anddea/revanced-patches/assets/131497172/58689741-968f-4ab4-99dc-1e9b3b6d6340)

**Comment by anddea** [comment]
Do you face this issue in other versions too? I still can't reproduce it on my side with 19.11.

I see that it changed toolbar buttons to Outline for you but not right-side buttons.

**Comment by TheWitch69** [comment]
> Do you face this issue in other versions too? I still can't reproduce it on my side with 19.11.
> 
> I see that it changed toolbar buttons to Outline for you but not right-side buttons.

I test 19.07.xx but same problem how to fix that? Maybe to exclude something?

**Comment by anddea** [comment]
Try clearing the storage (or cache) of the terminal where you are running Revancify and redownload it. You can also test it in the Manager, if it works fine there, then you definitely need to clear the terminal storage.

**Comment by anddea** [comment]
Clear Revancify and install. Or try Manager.

**Comment by TheWitch69** [comment]
> Clear Revancify and install. Or try Manager.

I do that nothing same

**Comment by anddea** [comment]
I have no idea what could be interefering. It might be some weird A/B testing, although it's unlikely. Are you using default patches? Send your included patches. Did you try both original ReVanced Manager and RVX? Double check that you changed your source to anddea. Send a screenshot with patches and integrations version from YouTube.

**Comment by anddea** [comment]
What if you select default patches? Or select only Shorts overlay, unselect all other patches. Just for a test to understand if there's any other patch that inerfere.

**Comment by anddea** [comment]
Also, a few question:
1. Did you use this patch before and did it work for you? If yes, what version of patches it was or something approximately?
2. Can you go to Settings > Extended> Shorts and unhide remix button, is it outline?

**Comment by TheWitch69** [comment]
Okay try everything what u suggested even with older version not working for me. I try to unhide everything in shorts tab but not working. I try again TikTok and Outline

**Comment by anddea** [comment]
Can you test latest Dev for Outline icons?

**Comment by anddea** [comment]
What is the version of latest patches you tried?

**Comment by TheWitch69** [comment]
v2.223.0-dev.11 in that moment

**Comment by anddea** [comment]
Did it work before for you? What about previous YouTube versions?

Does `enable outline icons` from other patches maintainers work?

There should be something why it doesn't work.

**Comment by TheWitch69** [comment]
Never work when i try your patches only RVX by inotiaa work. But i install 18.45.43 not work try to spoof 18.42.41, 18.40.34 and 18.38.45 also dont work, but when i spoof to 18.33.40 and below outline icons works

**Comment by anddea** [comment]
The only difference from inotia was that there was no all dpi icons, when I added them to his repo there was only xxhdpi, just like I kept in my repo which is in stable currently, but I added other DPIs in previous Dev releases and you say they still don't appear. I'll check more on that. 

Can you verify if you patch now inotia patches, will they work for you?

**Comment by TheWitch69** [comment]
I patched now youtube 19.02.39 with latest inotia patches and shorts outlines work everything is good

**Comment by TheWitch69** [comment]
Everything its fine now gj!
