### ISSUE TITLE
question: Use ReVanced Manager instead of RVX Manager to patch v2.223.0-dev.1?

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#145]
### Application

YouTube

### Question description

Use ReVanced Manager(ReVanced) instead of RVX Manager(inotia) to patch v2.223.0-dev.1?

From v2.222.0 announcement ...
... I can recommend you to use the original ReVanced Manager, as it only shows production releases....

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
As I said in the announcement of Stable Release, do not open issues for build error on `dev` pre-release. You can open other types of issues, like app crashing, bugs, etc.

**Comment by anddea** [comment]
But if you want to use dev, then you can use RVX Manager, or Revancify, or CLI.

**Comment by Aryan-Chauhan** [comment]
One more thing worth mentioning:

RVX Manager has "RipLibs" feature and ReVanced Manager doesn't.

If you want a lower APK size, RipLibs does that.

BTW, I just use ReVancify.
