### ISSUE TITLE
bug(Youtube): 'hide quality menu footer' doesnt work

### ISSUE THREAD

**Issue by 0frd** [anddea/revanced-patches#147]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Youtube 19.11.43

### Bug description

![IMG_20240326_062906](https://github.com/anddea/revanced-patches/assets/72485140/759db726-19d5-4877-af51-2278a5656604)

Hide quality menu footer doesnt work and no option in the patches list to exclude it

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
It is working fine here on v19.09.38 (latest patches). Try clearing all app data, if you haven't already.

![Screenshot_2024-03-26-10-30-14-31_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/anddea/revanced-patches/assets/91815107/d90e8ad5-3f75-4c3f-8384-64f2282cd444)

**Comment by anddea** [comment]
Can't reproduce it. Try what Aryan-Chauhan said.
