### ISSUE TITLE
question: have you added this update?

### ISSUE THREAD

**Issue by federicogith** [anddea/revanced-patches#148]
### Application

YouTube

### Question description

Just wanted to ask if you added this ReX's update:
[feat(YouTube - Hide Navigation Button): Apply fingerprint to support wider version](https://github.com/YT-Advanced/ReX-patches/commit/4a60eb59594d894ba960178808cf9d551a513715)
(Sorry if you already have added it)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Of course it was originally added in this repository. Two days before he added it.

https://github.com/anddea/revanced-patches/commit/cb02ba71f5af061a17183540537966e9ccef9332
