### ISSUE TITLE
Thumbnail preview in SeekBar does not work 

### ISSUE THREAD

**Issue by Kiwikip** [anddea/revanced-patches#15]
### Type

Cosmetic

### Tools used

Revancify

### Application

19.05.36

### Bug description

Thumbnail preview in SeekBar doesn't show

How to reproduce: play video and use seekbar
![Screenshot_20240312_105459_RVX anddea](https://github.com/anddea/revanced-patches/assets/130678837/1c203181-ac7a-4739-8c6d-2b1423a72d0a)

### Device Environment

Android 14 s24ulta samsung oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Kiwikip** [comment]
Preview works on fresh instal, but if i change the seekbar color it doesn't work anymore

**Comment by anddea** [comment]
Can't reproduce it. What color do you use?

**Comment by Kiwikip** [comment]
Any chance causes this, even turning off and and back on is enough to brake it

**Comment by Kiwikip** [comment]
https://github.com/anddea/revanced-patches/assets/130678837/1ba5628a-2f14-4a1d-af74-fda1d50279aa

**Comment by anddea** [comment]
It could be due to buffering, if you wait a little and start seeking it probably will come back, maybe internet speed or YouTube servers are slow. Still can't reproduce. I did just like you showed in your video. Seekbar color shouldn't affect that anyway. Also I see you didn't apply `Enable new thumbnail preview`, it shouldn't affect either, but I suggest you to apply that and by default it should be turned off, which will show small preview like in old versions.

**Comment by Kiwikip** [comment]
If I include the new thumbnail patch, it works (still the same netwerk, on the version without the patch it doesn't work) but If i turn on new thumbnale, the preview is gone again. 
 https://github.com/anddea/revanced-patches/assets/130678837/0e33e650-3913-4cb4-929a-2a535de94064

**Comment by anddea** [comment]
The new preview shows the preview on the entire screen of the player and stops playing the sound while seeking; the old preview, on the other hand, shows the preview in a small window, and the sound goes in the background, in the screen recording that you sent, both of them work as intended.
