### ISSUE TITLE
bug (YT) : "Hide Player Buttons Background" is working fine but showing as "excluded" in Patches Information.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#150]
### Type

Cosmetic

### Tools used

Revancify

### Application

YT v19.09.38

Patches v2.223.0-dev.3

Integrations v0.150.0-dev.1

### Bug description

In ReVancify, I've included "Hide Player Buttons Background" patch and it is working fine.

But in Patches Information section, that patch is showing as "excluded".

So, please fix this minor bug.
![Screenshot_2024-03-26-10-19-57-43_84d3000e3f4017145260f7618db1d683](https://github.com/anddea/revanced-patches/assets/91815107/e410ef07-a712-4a90-8048-f1dc93fab73a)
![1711428444381](https://github.com/anddea/revanced-patches/assets/91815107/c13d6d6c-2393-41c3-a83e-6a58db35e24d)

### Error logs

```shell
No logs.
```

### Solution

It should show "included" in the Patches Information section, because it is included & working fine as well.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro

Android 12

Skin name: Realme UI 3.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Should be fixed in the latest dev.
