### ISSUE TITLE
App crashes when pressing "Default playback speed" 

### ISSUE THREAD

**Issue by Kiwikip** [anddea/revanced-patches#16]
### Type

Error at runtime

### Tools used

Revancify

### Application

19.05.36

### Bug description

App crashes when pressing "Default playback speed" in the settings menu
How To reproduce: just tap the button in settings

https://github.com/anddea/revanced-patches/assets/130678837/57188928-7866-4c93-9347-31b13d55ff92

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I can't reproduce that on 19.09.37 and 19.05.36. Try redownload patches (delete old patches) and patch again.

**Comment by Kiwikip** [comment]
Thanx 
Rematching with revancify didn't help, I had to delete the patches and redownload them. There must have gone something wrong with revancify, I did download the latest before patching.

Thanx for all your work

**Comment by anddea** [comment]
> Thanx Rematching with revancify didn't help, I had to delete the patches and redownload them. There must have gone something wrong with revancify, I did download the latest before patching.
> 
> Thanx for all your work

So you still have this issue? Or redownloading patches helped?
