### ISSUE TITLE
feat: could you bump 6.45.xx?

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [anddea/revanced-patches#165]
### Application

YouTube Music

### Feature description

I want the patches to support this ytm version to be up to date

### Motivation

Because google make some old yt/ytm versions uncapable of playing anything if you don't update, and this can't be bypassed even by spoofing app version, i say this, because i've seen this problem on some of the users groups related to rvx/rex/revanced/etc....

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by soyDESKTOP68A2MRFT** [comment]
![IMG_20240326_133359_525](https://github.com/anddea/revanced-patches/assets/86683930/93a89c8c-6230-4061-8ec3-b498ccf2e778)

This is an example of what would happen because of a lack of bumping, this guy wanted to see a video on YT 19.09.xx and it showed the "non compatible youtube app, please update your app"  message, that is easly avoided by patching a newer yt version, my point is that the same will happen some day with YTM, so you should really consider bump versions regulary

**Comment by anddea** [comment]
It's not about bumping new versions. It's about updating patches. You can use ancient version of YouTube with latest patches and it will work fine. The error in your screenshot is fixed in dev4 release, which was released days ago.

**Comment by anddea** [comment]
Added support for latest YT Music in the latest dev release.
