### ISSUE TITLE
bug: YT couldn't even open after patchng with latest dev release

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#166]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Latest Supported

### Bug description

YT is keep crashing after patching it for GMSCore 3.1. It don't even open. Tried on my 2 devices but same result.

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Because you have to install GmsCore and stock YouTube. Otherwise it won't work.
