### ISSUE TITLE
Notification button doesn't exist despite I don't hide it

### ISSUE THREAD

**Issue by Mohammed1520** [anddea/revanced-patches#168]
### Application

YouTube

### Question description

In these 2 screenshots I have disabled hide notification button but the button disappears 
Us there a solution 
![Screenshot_20240326_193131_anddea youtube_edit_9293793688165](https://github.com/anddea/revanced-patches/assets/107951133/28b748a3-7f97-4adc-832e-1e813da04d5f)
![Screenshot_20240326_193135_anddea youtube_edit_9275460370980](https://github.com/anddea/revanced-patches/assets/107951133/124754f3-489b-4965-ab9f-b5a55a38c4f5)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Settings > Extended > General > Hide buttons in toolbar
