### ISSUE TITLE
ReVanced video play issue when sign in

### ISSUE THREAD

**Issue by DVSVIDEO** [anddea/revanced-patches#173]
### Type

Other

### Tools used

RVX Manager

### Application

any

### Bug description

When I install the youtube revanced app, it plays the video without any problems, but when I log in to my account using microG, the video does not play.
The gist of the error message is "this content is not available in this app" "can be viewed in the latest version of youtube"

### Error logs

```shell
I have been using the Youtube ReVanced app for a year now without any problems.
A few days ago, an error message appeared when playing.
I have tried 10 versions with 3 different microG and the same error...
```

### Solution

microG mod

### Device Environment

Samsung Galaxy S8+
Android 9
OneUi 1.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
In dev.4 new GmsCore support added. If you installed those patches or later, then try to disable Spoof player parameters.

**Comment by DVSVIDEO** [comment]
Thank you for your reply.
Unfortunately I am not so well versed in building applications to understand this.
I will download the .apk file and install it.
But so far I have not found any combination that solves the playback problem.
Is it possible that such a thing is made?

**Comment by anddea** [comment]
It should be fixed because of the latest switch to GmsCore by ReVanced Team. When you patch latest patches, it'll ask you to download new MicroG amd will open the download link.
