### ISSUE TITLE
feat: Allow rewinding of live broadcasts that cannot be rewound.

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#18]
### Application

YouTube

### Feature description

We would like to be able to rewind live feeds that cannot be rewound, like SmartTube.

### Motivation

This is very useful if you are in the middle of a live stream and want to rewind to the beginning or rewind to the part of the stream you want to watch.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
isn't this a feature that's already in classic YouTube (android)? 

like this:
![Screenshot_20240312_194744_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/4c9a9ec1-f7b9-4fd0-9870-a151b061946b)

**Comment by akir45** [comment]
If YouTube's DVR feature is disabled, you will not be able to rewind the live stream.

**Comment by YT-Advanced** [comment]
@akir45 Share me an example channel that turned off DVR please

**Comment by akir45** [comment]
I believe that vtubers such as Hololive often turn off the DVR.
Here is an example
https://youtu.be/8QoPUb7BA0Y
