### ISSUE TITLE
'Hide fullscreen button' patch doesn't work

### ISSUE THREAD

**Issue by Sam101011** [anddea/revanced-patches#19]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 19.09.37

### Bug description

After patching with the latest patches v2.221.0, even after including the 'hide fullscreen button' patch, the fullscreen button still shows up, misaligned with the other overlay buttons, which I have moved up 7.0 dip.
![Screenshot_20240312_154818_anddea youtube_1](https://github.com/anddea/revanced-patches/assets/90930406/255a8366-b443-4b7f-ab86-48a1cf2693aa)

![Screenshot_20240312_154846_anddea youtube_1](https://github.com/anddea/revanced-patches/assets/90930406/c1216469-a223-4a94-a825-c6a3133b20c2)

![Screenshot_20240312_154919_com android settings_1](https://github.com/anddea/revanced-patches/assets/90930406/d7633319-73a4-4d75-bff3-1f5c55a05b2c)

### Device Environment

Android 10, EMUI 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Working fine for me (it's worth noting that I'm using v18.49.37).

Maybe v19.09.37 and latest patches aren't getting along.

**Comment by Sam101011** [comment]
It was working fine for me too on v19.05.36. But on the latest release it says that the version was bumped up to 19.09.37. I guess not all patches were updated correctly.

To be clear, it's not big of a deal, but it'd be cool if it is to be fixed.

**Comment by Francesco146** [comment]
> It was working fine for me too on v19.05.36. But on the latest release it says that the version was bumped up to 19.09.37. I guess not all patches were updated correctly.
> 
> To be clear, it's not big of a deal, but it'd be cool if it is to be fixed.

yeah, I think @anddea should stick with the version v19.35.6 until all patches work (or are no more needed) in the new versions.

**Comment by anddea** [comment]
It should be fixed in the latest release. If you still encounter this problem, reopen this issue.

**Comment by Sam101011** [comment]
I can confirm the issue has been fixed.
Thank you!

![Screenshot_20240313_131824_anddea youtube_1](https://github.com/anddea/revanced-patches/assets/90930406/fc386731-8d4b-4849-ac4b-53e6af291956)
