### ISSUE TITLE
question:  Why can't I play video？

### ISSUE THREAD

**Issue by SSB-ARFCN** [anddea/revanced-patches#194]
### Application

YouTube

### Question description

It show
![Screenshot_2024-03-28-20-46-13-541_anddea youtube](https://github.com/anddea/revanced-patches/assets/107019852/8a343771-fcc5-41e8-b991-fae5175a8e2d)
![Screenshot_2024-03-28-20-48-15-065_anddea youtube](https://github.com/anddea/revanced-patches/assets/107019852/88fadb06-d19d-4dae-a78f-7e50f0b612fa)

I try to open another again andagan they all automatically jump to this video 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Whats version of patches you use?

**Comment by SSB-ARFCN** [comment]
19.11.38

**Comment by anddea** [comment]
> 19.11.38

It's YouTube version. Go to Settings > Extended > Misc > Patches info (in the end of page), and tell me what it says for patches and integrations version.

**Comment by anddea** [comment]
@SSB-ARFCN try latest [v2.223.0-dev.14](https://github.com/anddea/revanced-patches/releases/tag/v2.223.0-dev.14). You can use RVX Manager for dev releases.

**Comment by LovecraftianGodsKiller** [comment]
What do you recommend using for patching via the CLI?
(I'm a Linux user, LOVE using the Terminal and use it quite religiously)

**Comment by anddea** [comment]
> What do you recommend using for patching via the CLI? (I'm a Linux user, LOVE using the Terminal and use it quite religiously)

All managers (ReVanced, RVX), builders use [ReVanced/cli](https://github.com/revanced/revanced-cli) - [documentation](https://github.com/ReVanced/revanced-cli/tree/main/docs), or you can use [intotia00/cli](https://github.com/inotia00/revanced-cli), it has rip-libs to get rid of unnecessary architectures. If you want to build from source code, just use Gradle (gradlew in the root folder of the repo).

**Comment by anddea** [comment]
> @SSB-ARFCN try latest [v2.223.0-dev.14](https://github.com/anddea/revanced-patches/releases/tag/v2.223.0-dev.14). You can use RVX Manager for dev releases.

Let me know if you face any issues. Closing this now.
