### ISSUE TITLE
feat (YT Music) : Bring back old behaviour of Splash Screen & Header Icon.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#20]
### Application

YouTube Music

### Feature description

Before v2.203.1 of inotia00 patches, the custom icon selected by user (say, MMT icon) used to get applied at all places like launcher icon, splash screen & header icon. But now, it only gets applied to launcher icon & splash screen and header icon remains on stock icon.
This was an illogical & unnecessary change.

So, please bring back old behaviour so that MMT icon can be applied on both splash screen & header icon.

Relevant issue: https://github.com/inotia00/ReVanced_Extended/issues/1797
![Screenshot_2024-03-12-20-27-05-77_0eaaacfb1e02f862bb18505a09b95933](https://github.com/anddea/revanced-patches/assets/91815107/67db405e-6d93-4eaa-bdc3-e75f0009d443)
![Screenshot_2024-03-12-20-30-44-64_0eaaacfb1e02f862bb18505a09b95933](https://github.com/anddea/revanced-patches/assets/91815107/0ceddf29-9a38-46cc-a67b-1b265414bc47)

### Motivation

It was really illogical & unnecessary to remove such a cool feature. It was hurting nobody & not obstructing any functions. That's why it should be brought back.

It will also save a user's time who now have to decompile the APK and manually change res files to get the desired icons.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
> ### Application
> YouTube Music
> 
> ### Feature description
> Before v2.203.1 of inotia00 patches, the custom icon selected by user (say, MMT icon) used to get applied at all places like launcher icon, splash screen & header icon. But now, it only gets applied to launcher icon & splash screen and header icon remains on stock icon. This was an illogical & unnecessary change.
> 
> So, please bring back old behaviour so that MMT icon can be applied on both splash screen & header icon.
> 
> Relevant issue: [inotia00/ReVanced_Extended#1797](https://github.com/inotia00/ReVanced_Extended/issues/1797) ![Screenshot_2024-03-12-20-27-05-77_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131304-67db405e-6d93-4eaa-bdc3-e75f0009d443.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzMDQtNjdkYjQwNWUtNmQ5My00ZWFhLWJkYzMtZTc1ZjAwMDlkNDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTkxYjAwYWQ1ZDRmZTNiZGVhZThhNTcxYjVkMjNhZTI3ZDUzMDgyZDgzOTc2OTg1YzJjZDA4MmE4ZDJkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mS0_T3osWAH8uuxsX3WPML5Pzr5p9X8fegHy-YJREsM) ![Screenshot_2024-03-12-20-30-44-64_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131389-0ceddf29-9a38-46cc-a67b-1b265414bc47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzODktMGNlZGRmMjktOWEzOC00NmNjLWE2N2ItMWIyNjU0MTRiYzQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NzA5ZWE3NmU1NGQxMWU2NTg4YTk2N2M5NTk2YTdmNGFlYmNhOTMxNDY3NzA3NDIwZDBjN2I3NDBmZDAxMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_hcLSoWgXmT-w8-Ig3BRm44eY23qXTMnToi51oQtL0)
> 
> ### Motivation
> It was really illogical & unnecessary to remove such a cool feature. It was hurting nobody & not obstructing any functions. That's why it should be brought back.
> 
> It will also save a user's time who now have to decompile the APK and manually change res files to get the desired icons.
> 
> ### Acknowledgements
> * [x]  This issue is not a duplicate of an existing feature request.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  I have written the title and contents in English.

Similar thing : https://github.com/anddea/revanced-patches/issues/25#issuecomment-1994113173


You should ask @kaziMMT & @Decipher3114 to include files for splash icon for revancify & mmt icons ...

**Comment by Aryan-Chauhan** [comment]
> > ### Application
> > YouTube Music
> > 
> > ### Feature description
> > Before v2.203.1 of inotia00 patches, the custom icon selected by user (say, MMT icon) used to get applied at all places like launcher icon, splash screen & header icon. But now, it only gets applied to launcher icon & splash screen and header icon remains on stock icon. This was an illogical & unnecessary change.
> > 
> > So, please bring back old behaviour so that MMT icon can be applied on both splash screen & header icon.
> > 
> > Relevant issue: [inotia00/ReVanced_Extended#1797](https://github.com/inotia00/ReVanced_Extended/issues/1797) ![Screenshot_2024-03-12-20-27-05-77_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131304-67db405e-6d93-4eaa-bdc3-e75f0009d443.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzMDQtNjdkYjQwNWUtNmQ5My00ZWFhLWJkYzMtZTc1ZjAwMDlkNDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTkxYjAwYWQ1ZDRmZTNiZGVhZThhNTcxYjVkMjNhZTI3ZDUzMDgyZDgzOTc2OTg1YzJjZDA4MmE4ZDJkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mS0_T3osWAH8uuxsX3WPML5Pzr5p9X8fegHy-YJREsM) ![Screenshot_2024-03-12-20-30-44-64_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131389-0ceddf29-9a38-46cc-a67b-1b265414bc47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzODktMGNlZGRmMjktOWEzOC00NmNjLWE2N2ItMWIyNjU0MTRiYzQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NzA5ZWE3NmU1NGQxMWU2NTg4YTk2N2M5NTk2YTdmNGFlYmNhOTMxNDY3NzA3NDIwZDBjN2I3NDBmZDAxMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_hcLSoWgXmT-w8-Ig3BRm44eY23qXTMnToi51oQtL0)
> > 
> > ### Motivation
> > It was really illogical & unnecessary to remove such a cool feature. It was hurting nobody & not obstructing any functions. That's why it should be brought back.
> > 
> > It will also save a user's time who now have to decompile the APK and manually change res files to get the desired icons.
> > 
> > ### Acknowledgements
> > * [x]  This issue is not a duplicate of an existing feature request.
> > * [x]  I have chosen an appropriate title.
> > * [x]  All requested information has been provided properly.
> > * [x]  I have written the title and contents in English.
> 
> Similar thing : https://github.com/anddea/revanced-patches/issues/25#issuecomment-1994113173
> 
> 
> You should ask @kaziMMT & @Decipher3114 to include files for splash icon for revancify & mmt icons ...

I think they already provided those files, because before v2.203.1, MMT icon used to get applied on 3 places (launcher icon, splash screen, & header icon).

This change was done by inotia00.

**Comment by selfmusing** [comment]
> > > ### Application
> > > YouTube Music
> > > ### Feature description
> > > Before v2.203.1 of inotia00 patches, the custom icon selected by user (say, MMT icon) used to get applied at all places like launcher icon, splash screen & header icon. But now, it only gets applied to launcher icon & splash screen and header icon remains on stock icon. This was an illogical & unnecessary change.
> > > So, please bring back old behaviour so that MMT icon can be applied on both splash screen & header icon.
> > > Relevant issue: [inotia00/ReVanced_Extended#1797](https://github.com/inotia00/ReVanced_Extended/issues/1797) ![Screenshot_2024-03-12-20-27-05-77_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131304-67db405e-6d93-4eaa-bdc3-e75f0009d443.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzMDQtNjdkYjQwNWUtNmQ5My00ZWFhLWJkYzMtZTc1ZjAwMDlkNDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTkxYjAwYWQ1ZDRmZTNiZGVhZThhNTcxYjVkMjNhZTI3ZDUzMDgyZDgzOTc2OTg1YzJjZDA4MmE4ZDJkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mS0_T3osWAH8uuxsX3WPML5Pzr5p9X8fegHy-YJREsM) ![Screenshot_2024-03-12-20-30-44-64_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131389-0ceddf29-9a38-46cc-a67b-1b265414bc47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzODktMGNlZGRmMjktOWEzOC00NmNjLWE2N2ItMWIyNjU0MTRiYzQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NzA5ZWE3NmU1NGQxMWU2NTg4YTk2N2M5NTk2YTdmNGFlYmNhOTMxNDY3NzA3NDIwZDBjN2I3NDBmZDAxMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_hcLSoWgXmT-w8-Ig3BRm44eY23qXTMnToi51oQtL0)
> > > ### Motivation
> > > It was really illogical & unnecessary to remove such a cool feature. It was hurting nobody & not obstructing any functions. That's why it should be brought back.
> > > It will also save a user's time who now have to decompile the APK and manually change res files to get the desired icons.
> > > ### Acknowledgements
> > > 
> > > * [x]   This issue is not a duplicate of an existing feature request.
> > > * [x]   I have chosen an appropriate title.
> > > * [x]   All requested information has been provided properly.
> > > * [x]   I have written the title and contents in English.
> > 
> > 
> > Similar thing : [#25 (comment)](https://github.com/anddea/revanced-patches/issues/25#issuecomment-1994113173)
> > You should ask @kazimmt & @decipher3114 to include files for splash icon for revancify & mmt icons ...
> 
> I think they already provided those files, because before v2.203.1, MMT icon used to get applied on 3 places (launcher icon, splash screen, & header icon).
> 
> This change was done by inotia00.


https://github.com/anddea/revanced-patches/assets/109387456/25d9d2b7-57ae-4e1d-a054-6b61a66921b6

SIDE-BY-SIDE comparison of AFN , MMT & revancify icons , you can clearly see the difference... ( They didn't add any files for header & splash logo)

**Comment by Aryan-Chauhan** [comment]
> > > > ### Application
> > > > YouTube Music
> > > > ### Feature description
> > > > Before v2.203.1 of inotia00 patches, the custom icon selected by user (say, MMT icon) used to get applied at all places like launcher icon, splash screen & header icon. But now, it only gets applied to launcher icon & splash screen and header icon remains on stock icon. This was an illogical & unnecessary change.
> > > > So, please bring back old behaviour so that MMT icon can be applied on both splash screen & header icon.
> > > > Relevant issue: [inotia00/ReVanced_Extended#1797](https://github.com/inotia00/ReVanced_Extended/issues/1797) ![Screenshot_2024-03-12-20-27-05-77_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131304-67db405e-6d93-4eaa-bdc3-e75f0009d443.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzMDQtNjdkYjQwNWUtNmQ5My00ZWFhLWJkYzMtZTc1ZjAwMDlkNDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTkxYjAwYWQ1ZDRmZTNiZGVhZThhNTcxYjVkMjNhZTI3ZDUzMDgyZDgzOTc2OTg1YzJjZDA4MmE4ZDJkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mS0_T3osWAH8uuxsX3WPML5Pzr5p9X8fegHy-YJREsM) ![Screenshot_2024-03-12-20-30-44-64_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131389-0ceddf29-9a38-46cc-a67b-1b265414bc47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzODktMGNlZGRmMjktOWEzOC00NmNjLWE2N2ItMWIyNjU0MTRiYzQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NzA5ZWE3NmU1NGQxMWU2NTg4YTk2N2M5NTk2YTdmNGFlYmNhOTMxNDY3NzA3NDIwZDBjN2I3NDBmZDAxMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_hcLSoWgXmT-w8-Ig3BRm44eY23qXTMnToi51oQtL0)
> > > > ### Motivation
> > > > It was really illogical & unnecessary to remove such a cool feature. It was hurting nobody & not obstructing any functions. That's why it should be brought back.
> > > > It will also save a user's time who now have to decompile the APK and manually change res files to get the desired icons.
> > > > ### Acknowledgements
> > > > 
> > > > * [x]   This issue is not a duplicate of an existing feature request.
> > > > * [x]   I have chosen an appropriate title.
> > > > * [x]   All requested information has been provided properly.
> > > > * [x]   I have written the title and contents in English.
> > > 
> > > 
> > > Similar thing : [#25 (comment)](https://github.com/anddea/revanced-patches/issues/25#issuecomment-1994113173)
> > > You should ask @kazimmt & @decipher3114 to include files for splash icon for revancify & mmt icons ...
> > 
> > I think they already provided those files, because before v2.203.1, MMT icon used to get applied on 3 places (launcher icon, splash screen, & header icon).
> > 
> > This change was done by inotia00.
> 
> 
> https://github.com/anddea/revanced-patches/assets/109387456/25d9d2b7-57ae-4e1d-a054-6b61a66921b6
> 
> SIDE-BY-SIDE comparison of AFN , MMT & revancify icons , you can clearly see the difference... ( They didn't add any files for header & splash logo)

Maybe there's a possibility that even before the change in v2.203.1, separate folders for splash & header icon never existed.

Maybe splash & header icons used to get fetched from some other folders.

I don't know how to read through code.

Can you check v2.203.1 & the patch before it, to confirm what I'm saying is true?

Actually, it is true. Because you can find 3-4 people other than me, who used to use custom icon on splash & header.

So, this is not some Mandela Effect stuff LOL.

**Comment by selfmusing** [comment]
> > > > > ### Application
> > > > > YouTube Music
> > > > > ### Feature description
> > > > > Before v2.203.1 of inotia00 patches, the custom icon selected by user (say, MMT icon) used to get applied at all places like launcher icon, splash screen & header icon. But now, it only gets applied to launcher icon & splash screen and header icon remains on stock icon. This was an illogical & unnecessary change.
> > > > > So, please bring back old behaviour so that MMT icon can be applied on both splash screen & header icon.
> > > > > Relevant issue: [inotia00/ReVanced_Extended#1797](https://github.com/inotia00/ReVanced_Extended/issues/1797) ![Screenshot_2024-03-12-20-27-05-77_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131304-67db405e-6d93-4eaa-bdc3-e75f0009d443.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzMDQtNjdkYjQwNWUtNmQ5My00ZWFhLWJkYzMtZTc1ZjAwMDlkNDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTkxYjAwYWQ1ZDRmZTNiZGVhZThhNTcxYjVkMjNhZTI3ZDUzMDgyZDgzOTc2OTg1YzJjZDA4MmE4ZDJkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mS0_T3osWAH8uuxsX3WPML5Pzr5p9X8fegHy-YJREsM) ![Screenshot_2024-03-12-20-30-44-64_0eaaacfb1e02f862bb18505a09b95933](https://private-user-images.githubusercontent.com/91815107/312131389-0ceddf29-9a38-46cc-a67b-1b265414bc47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgzOTMsIm5iZiI6MTcxMDMyODA5MywicGF0aCI6Ii85MTgxNTEwNy8zMTIxMzEzODktMGNlZGRmMjktOWEzOC00NmNjLWE2N2ItMWIyNjU0MTRiYzQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NzA5ZWE3NmU1NGQxMWU2NTg4YTk2N2M5NTk2YTdmNGFlYmNhOTMxNDY3NzA3NDIwZDBjN2I3NDBmZDAxMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_hcLSoWgXmT-w8-Ig3BRm44eY23qXTMnToi51oQtL0)
> > > > > ### Motivation
> > > > > It was really illogical & unnecessary to remove such a cool feature. It was hurting nobody & not obstructing any functions. That's why it should be brought back.
> > > > > It will also save a user's time who now have to decompile the APK and manually change res files to get the desired icons.
> > > > > ### Acknowledgements
> > > > > 
> > > > > * [x]    This issue is not a duplicate of an existing feature request.
> > > > > * [x]    I have chosen an appropriate title.
> > > > > * [x]    All requested information has been provided properly.
> > > > > * [x]    I have written the title and contents in English.
> > > > 
> > > > 
> > > > Similar thing : [#25 (comment)](https://github.com/anddea/revanced-patches/issues/25#issuecomment-1994113173)
> > > > You should ask @kazimmt & @decipher3114 to include files for splash icon for revancify & mmt icons ...
> > > 
> > > 
> > > I think they already provided those files, because before v2.203.1, MMT icon used to get applied on 3 places (launcher icon, splash screen, & header icon).
> > > This change was done by inotia00.
> > 
> > 
> > 
> >   
> >     
> >     
> > 
> >     1710329924551.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > SIDE-BY-SIDE comparison of AFN , MMT & revancify icons , you can clearly see the difference... ( They didn't add any files for header & splash logo)
> 
> Maybe there's a possibility that even before the change in v2.203.1, separate folders for splash & header icon never existed.
> 
> Maybe splash & header icons used to get fetched from some other folders.
> 
> I don't know how to read through code.
> 
> Can you check v2.203.1 & the patch before it, to confirm what I'm saying is true?
> 
> Actually, it is true. Because you can find 3-4 people other than me, who used to use custom icon on splash & header.
> 
> So, this is not some Mandela Effect stuff LOL.


Only custom branding MMT icons have those resources for yt header & splash icon but it's not available in 2.203.1 & above patches...


https://github.com/anddea/revanced-patches/assets/109387456/86d3b88f-b3f5-43da-9a38-09297d508345

Patch description for YT music of v2.203.1 :

![Screenshot_20240313-173408_Chrome_Canary](https://github.com/anddea/revanced-patches/assets/109387456/cafe88d9-fae5-41a4-9bfb-986401cfd0ed)

**Comment by Aryan-Chauhan** [comment]
Bro, I cannot thank you enough for verifying that what I was saying was true.

Actually, I'm very lucky in this case. 

Because MMT icon is the only icon I like. I like MMT icon more than ReVancify & AFN icons.

Now, @anddea just have to bring back this behaviour of v2.202.1 & my feature request is complete!!!!!

(Ofcourse, whenever he wants, since he is doing all this for free)

**Comment by selfmusing** [comment]
> Bro, I cannot thank you enough for verifying that what I was saying was true.
> 
> Actually, I'm very lucky in this case.
> 
> Because MMT icon is the only icon I like. I like MMT icon more than ReVancify & AFN icons.
> 
> Now, @anddea just have to bring back this behaviour of v2.202.1 & my feature request is complete!!!!!
> 
> (Ofcourse, whenever he wants, since he is doing all this for free)



@anddea You can check this commit : https://github.com/inotia00/revanced-patches/commit/1753a427f4f2a4401afb20a95b8fc7b523404f0f

**Comment by anddea** [comment]
Implemented in the [latest release](https://github.com/anddea/revanced-patches/releases/tag/v2.221.0.2). Reopen, if you encounter any issues.
