### ISSUE TITLE
bug: Video play/pause icon sometimes goes missing.

### ISSUE THREAD

**Issue by anurag565** [anddea/revanced-patches#201]
### Type

Cosmetic

### Tools used

CLI

### Application

Rex version 19.11.39

### Bug description

![Screenshot_20240328_161552_YouTube](https://github.com/revanced-apks/build-apps/assets/143786347/2827a15c-06cc-4140-8c9a-4626107618e4)
The overlay button for play/pause on videos goes missing and it should behave like screenshot shown above. But sometimes, no matter how much you tap on screen, it just wont come. But once you close the video and reopen video, it works normally. Bug is for long time like months on even different version of youtube ReX.

### Device Environment

Android 14 One UI 6.0 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you test it on stock YouTube? It can come from YouTube itself, though I never noticed such thing myself.

**Comment by anurag565** [comment]
> Can you test it on stock YouTube? It can come from YouTube itself, though I never noticed such thing myself.

I forgot to tell, its CLI, not RVX manager. Edited now.

**Comment by anurag565** [comment]
> Can you test it on stock YouTube? It can come from YouTube itself, though I never noticed such thing myself.

Ok wait please.

**Comment by anurag565** [comment]
Noz this problem is not in stock youtube of same version or even in latest youtube.

**Comment by anddea** [comment]
> No, this problem is not in stock youtube of same version or even in latest youtube.

Is it on original ReVanced or ReX?

**Comment by anurag565** [comment]
> > No, this problem is not in stock youtube of same version or even in latest youtube.
> 
> Is it on original ReVanced or ReX? What if you disable Hide previous & next button in Extended > Player?
> 
> You said sometimes it goes missing, maybe it'll go away if you spend more time in the stock app?

Well it happens on even stock settings of ReX downloaded from here.
https://github.com/revanced-apks/build-apps/releases/tag/v2024.03.28-1430

**Comment by anddea** [comment]
> Well it happens on even stock settings of ReX downloaded from here.

Can you also check original Revanced, not Extended?

**Comment by anurag565** [comment]
> > Well it happens on even stock settings of ReX downloaded from here.
> 
> Can you also check original Revanced, not Extended?

Just saw a bug in original revanced from https://github.com/revanced-apks/build-apps/releases/download/v2024.03.28-1430/youtube-revanced-v19.09.37-all.apk
![Screenshot_20240329_211315_YouTube](https://github.com/anddea/revanced-patches/assets/143786347/ea9a182b-c774-4bb4-8b89-93d2a2af86f7)
Video keeps loading and shows that error on default settings as shown in pic.
And i couldn't find 1st error in original youtube revanced. Maybe it will show if i scroll more but if it did, i will tell asap.

**Comment by anurag565** [comment]
> > Well it happens on even stock settings of ReX downloaded from here.
> 
> Can you also check original Revanced, not Extended?

Just saw a bug in original revanced as shown in pic. Video will keep buffering and takes more time to start than normal youtube or ReX. Got app from- https://github.com/revanced-apks/build-apps/releases/download/v2024.03.28-1430/youtube-revanced-v19.09.37-all.apk

![Screenshot_20240329_212053_YouTube](https://github.com/anddea/revanced-patches/assets/143786347/6c9b37a8-1f19-4458-b853-e434ac019f66)

And i couldn't find 1st error of play/pause button missing in original youtube revanced. Maybe it will show if i scroll more but if it did, i will tell asap

**Comment by anddea** [comment]
Can you build yourself and check if it's still present?

**Comment by anurag565** [comment]
> Can you build yourself and check if this issue(s) still present?

Should i use recommend version while patching through revanced manager or the version in which i got error in ReX?

**Comment by anddea** [comment]
19.11.39 is recommended, you can patch this version of YouTube. YouTube from ApkMirror has support for armeabi v7.

**Comment by anurag565** [comment]
> 19.11.39 is recommended, you can patch this version of YouTube. YouTube from ApkMirror has support for armeabi v7. Manager supports only arm64 though.

Yes and thats what i meant. I cant patch it even if i download from apkmirror. Patch it and send me the app using google drive or anywhere else. I will check if it has that bug or not. Thats only way i guess

**Comment by anddea** [comment]
Try to build with Revancify.
