### ISSUE TITLE
question: HOW DO I USE THESE PATCH?

### ISSUE THREAD

**Issue by abdarker** [anddea/revanced-patches#206]
### Application

YouTube

### Question description

revanced extended has a repo where we can build YouTube extended through GitHub action. my question is how do i use your patches ? any guides or docs ?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
You can use [Revancify](https://GitHub.com/decipher3114/revancify) to patch YouTube with anddea patches on termux app.

**Comment by anddea** [comment]
If you ever patched any revanced then it's the same thing here. Just put anddea to the sources of Manager. Or use what selfmusing said.
