### ISSUE TITLE
bug: Show errors when patch

### ISSUE THREAD

**Issue by Kustale** [anddea/revanced-patches#207]
### Type

Error while patching

### Tools used

CLI

### Application

Youtube original 19.11.38

JDK Version :
zulu22.28.91-ca-jdk22.0.0-win_x64

Patcher : 
revanced-cli-4.5.0-all.jar
revanced-patches-2.222.0.jar
revanced-integrations-1.6.0.apk

### Bug description

A lot of errors occurred during patching.

### Error logs

```shell
Patch log is long...
Uploaded txt
```

### Additional context

Command
java -jar revanced-cli-4.5.0-all.jar patch -b revanced-patches-2.222.0.jar -m revanced-integrations-1.6.0.apk -o Youtube_Edited-Ext.apk YouTube_19.11.38_Apkpure.apk

Patch logs.txt
[logs.txt](https://github.com/anddea/revanced-patches/files/14804720/logs.txt)

### Device Environment

Windows 11 Pro

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
> revanced-integrations-1.6.0.apk 

It's not my integrations.

Get latest integrations here [v0.149.0](https://github.com/anddea/revanced-integrations/releases/tag/v0.149.0).
