### ISSUE TITLE
feat(YouTube): Hide live stream on Shorts player

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#209]
### Application

YouTube

### Feature description

Hide live stream on Shorts player

### Motivation

:)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
currently, we cannot hide videos in shorts, just like its ads

**Comment by anddea** [comment]
I don't see live streams in shorts at all, just like I can't reproduce some bugs people mention.

That's why I can't even start to work on it.

**Comment by Francesco146** [comment]
> I don't see live streams in shorts at all, just like I can't reproduce some bugs people mention.
> 
> That's why I can't even start to work on it.

what do you need? this is a live stream that I've found in Shorts:

https://www.youtube.com/live/g7YQUNIga2g

if you open this with the app, the chosen player is the Shorts' one.

here's my screen:
(latest dev patch, v19.11.38)

![Screenshot_20240412_183347_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/9a3e7f94-4cd9-4b38-a1f6-2632634467d3)

**Comment by anddea** [comment]
It opens in normal player for me. 

Is there any difference in litho between ordinary shorts and live streams inside shorts?

**Comment by Francesco146** [comment]
> Is there any difference in litho between ordinary shorts and live streams inside shorts?

not that I'm aware of. they both are swipe-able videos. litho patch can't access those information, that's the reason we can't hide ads in shorts as for now.


> There was a request to hide this live chat and only now I get what that person meant, I guess this live chat can be hidden with litho.

in my opinion the chat can be hidden by a litho patch, but this issue is not doable for now.

**Comment by anddea** [comment]
Maybe no one tried it, I'm not sure. I just don't get any live streams or ads. Can you try to capture litho elements in live stream and test it one by one in custom filter? 

And if you find live chat filter in shorts let me know. You can find that issue here in this repo, just search "live chat" and reply there for live chat filter.

**Comment by Francesco146** [comment]
> Maybe no one tried it, I'm not sure.

ReVanced and Alireza have tried, the problem is not identifying which Shorts are advertisements and which are videos. The problem is being able to block the Shorts video from YouTube's preloaded list.

> Can you try to capture litho elements in live stream and test it one by one in custom filter?

sure, when I'm done with my exams I'll play around with Logcat a bit

**Comment by anddea** [comment]
Yes, it will be a challenge. There can be implemented some auto scroll functionality. For hiding some elements, we use performclick to auto close by clicking on X sign and it's unnoticeable, maybe we can achieve the same with shorts one day.
