### ISSUE TITLE
Problem Playing Videos 

### ISSUE THREAD

**Issue by Tronak007** [anddea/revanced-patches#211]
I'm Facing A Problem In Every Video

Picture Uploaded 

![IMG-20240329-WA0000.jpg](https://github.com/anddea/revanced-patches/assets/106589892/8b81fd8f-ac94-47da-be45-e926a6fa8f52)

**Comment by Sam101011** [comment]
This was adressed in [release 2.223.0-dev 4](https://github.com/anddea/revanced-patches/tree/v2.223.0-dev.4).
Waiting for a full release.

**Comment by TaprisSugarbell** [comment]
> This was adressed in [release 2.223.0-dev 4](https://github.com/anddea/revanced-patches/tree/v2.223.0-dev.4). Waiting for a full release.
> 
> Edit:with [revancify](https://github.com/decipher3114/Revancify#installation), you can patch with the dev release to fix the issue.
> 
> Do this by switching source to **rvx-anddea**. Then go to **preferences(8)** and enable _FetchPreReleasedTools_. Then click on **FetchTools(4)**, wait for it to update, patch, install and enjoy.

Works great now, But you can't log in anymore

**Comment by Tronak007** [comment]
Thanks For The Answer,
