### ISSUE TITLE
What are "Advanced Dark Theme Background Color" & "Advanced Light Theme Background Color" ?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#213]
What are these two patch options & why do they exist?

And how to use them?

![Screenshot_2024-03-30-07-17-15-60_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/anddea/revanced-patches/assets/91815107/8f053ec8-3c80-4d70-8dfd-740fb3d2ed70)

**Comment by anddea** [comment]
They were just overwriting previous theme colors, I refactored it and now it is included inside Light and DarkThemeBackground. You can visually see all possible colors in the Manager.
