### ISSUE TITLE
bug: videos on vertical view not playing

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [anddea/revanced-patches#218]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.12.41

### Bug description

When playing a vertical video, which is not a short, the app crashes

### Error logs

```shell
Idk, is happening on already installed app
```

### Solution

Maybe bump the youtube application to latest

### Device Environment

Android 12 one ui 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
v19.12.41 is not tested and therefore not supported yet, do not rush. Do you see this error in v19.11?
