### ISSUE TITLE
question: How to use the pre-release patches?

### ISSUE THREAD

**Issue by 54m4d** [anddea/revanced-patches#224]
### Application

YouTube

### Question description

Is it possible to use the pre-release patches using the manager app? I only want to use the manager. Thanks.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by 54m4d** [comment]
I already know this, You should have paid attention that I mentioned **pre-release patches**, not stable ones.

**Comment by yue374** [comment]
this github repo have anddea pre-release patches
https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root?tab=readme-ov-file#rex-forked-by-anddea

**Comment by 54m4d** [comment]
It's very confusing, I checked mine, and it says the last update is 8 days ago (Stable) but when I open the patcher and choose a file, the version there says it's dev. (I didn't see this before) 

<details>
<summary>Here</summary>
<img src=https://github.com/anddea/revanced-patches/assets/52612348/e20d91b4-9853-4cf3-baf6-af9e465b3698>
<img src=https://github.com/anddea/revanced-patches/assets/52612348/88b1c125-cbe8-4548-af4e-1574eccaae5d>
</details>

**Comment by anddea** [comment]
Use [RVX Manager](https://github.com/inotia00/revanced-manager/releases)  or check "fetch pre-release" in [Revancify](https://github.com/decipher3114/Revancify).

**Comment by 54m4d** [comment]
@anddea Why does the manager state that the last update is 8 days ago? it's kind of confusing.

**Comment by anddea** [comment]
By default it should show stable releases only but it's a bug of Manager I guess. Because even when I publish stable release sometimes it shows several days ago. It comes from original Manager. You can verify the version if you select an app to patch and open patches list, the version will be in the top right corner.

**Comment by 54m4d** [comment]
Yep, that's what I did, and there I could see `dev.20` version.
