### ISSUE TITLE
List of all YT feature requests by me.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#225]
### Application

YouTube

### Feature description

Hi, this issue is a consolidated list of all the YT feature requests that I've opened till date on this repository. I'm going to close them, since all my requests will be written here.

**DONE** ~~**•** #21 - Premium Header + Wide Search Bar appearing simultaneously.~~

**DONE** ~~**•** #22 - Ability to hide redundant text in Settings page.~~

**DONE** ~~**•** #28 - Directly open RVX Settings when tapped on Settings icon.~~

**DONE** ~~**•** #29 - Ability to hide back button in Shorts.~~

**NOT PRACTICAL, TOO NICHE** ~~**•** #54 - Swipe Controls that can change Playback Speed.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/2015~~

**NOT PRACTICAL, TOO NICHE** ~~**•** #55 - Swipe Controls that can change Video Quality.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/2016~~

**DONE** ~~**•** #121 - Provide the user an "already fully opened" description when they open the description to prevent clicking on "...more".~~

**DONE** ~~**•** #251 - Move "SponsorBlock & Return YouTube Dislike Settings" inside RVX Settings, next to folders like General, Ads, Player, Overlay Buttons, etc.~~

**•** #23 - Keep video fullscreen when you come back to the app.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/1973
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/465

**•** #24 - Ability to hide text that are inside three-dot menus.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/2010
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/2586

**•** #27 - Small improvement in "Append video quality".
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/1469
Same request on ReVanced's repository : They don't have this patch, so cannot request.

**•** #41 - Slash, Total Duration, Bullet, Quality should be in white colour.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/1974
Same request on ReVanced's repository : They don't have this patch, so cannot request.

**•** #47 - Overlay Button that opens up Captions Menu.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/2011
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/3182

**•** #49 - Overlay Button that opens up Quality Menu.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/2012
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/3182

**•** #50 - Overlay Button that opens up Android's Native Share Menu.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/2013
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/3181

**•** #51  - Overlay Button that opens up Save To Playlist Menu.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/2014
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/3182

**•** #66 - Hide "Quality" from Player Flyout Panel.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/1976
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/3180

**•** #275 - Allow the user to keep same type of swipe control on both side of the screen.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/1975
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/3174

**•** #494 - Make `Hide Trending Searches` hide all type of context-less recommended searches.
Same request on inotia00's repository : https://github.com/inotia00/ReVanced_Extended/issues/1993
Same request on ReVanced's repository : https://github.com/ReVanced/revanced-patches/issues/873

### Motivation

Given in "Motivation" section of each issue.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
- [x] https://github.com/anddea/revanced-patches/issues/22

**Comment by anddea** [comment]
- [x] https://github.com/anddea/revanced-patches/issues/251

**Comment by Aryan-Chauhan** [comment]
Thank you, @anddea for both

**Comment by Francesco146** [comment]
some patches on compile time may be ported on Runtime with a toggle in te settings.. I'll take a look at that (looking at the one for Chapters in the player first)

**Comment by Aryan-Chauhan** [comment]
**Information:**

These features are now available in inotia00's RVX:

#21

#22

#28

#29

#121

#251

**Comment by Francesco146** [comment]
@Aryan-Chauhan could you edit the issue description, putting a line over the issues that are present in RVX or already implemented in anddea?

**Comment by Aryan-Chauhan** [comment]
@Francesco146 Done!

**Comment by anddea** [comment]
Since you reported these issues in other repos that I also check, there's no need to keep it here. If they didn't implement it, I won't be able to do that anyway.

**Comment by dasebasto** [comment]
Swipe Controls that can change Playback Speed.

is a must-have for me.
Most users watching tutorial-like or informative videos know that you constantly have to adjust the speed, depending on the speaker.
