### ISSUE TITLE
List of all YT Music feature requests by me.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#226]
### Application

YouTube Music

### Feature description

Hi, this issue is a consolidated list of all the YT Music feature requests that I've opened till date on this repository. I'm going to close them, since all my requests will be written here.

~~**•** #39 - Add support for "Enable Color Match Player" for new versions of YT Music.~~

~~**•** #296 - Move "SponsorBlock & Return YouTube Dislike Settings" inside RVX Settings, next to folders like Account, Action Bar, Ads, etc.~~

**•** #25 - Add 'Custom Branding Heading' patch.

**•** #26 - Ability to hide "Episodes for Later".
Same request on inotia00's repository : inotia00/ReVanced_Extended#1498

**•** #30 - Add 'Hide Samples Components' patch.
Same request on inotia00's repository : inotia00/ReVanced_Extended#1365

**•** #292 - Add Wide Search Bar.
Same request on inotia00's repository : inotia00/ReVanced_Extended#1981

**•** #294 - Directly open RVX Settings when tapped on Settings.
Same request on inotia00's repository : inotia00/ReVanced_Extended#1982

**•** #295 - Hook "Share Button" to open up Android's Native Share Menu.
Same request on inotia00's repository : inotia00/ReVanced_Extended#1983

### Motivation

Given in "Motivation" section of each issue.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
same here :)
