### ISSUE TITLE
General question: How to register YouTube in order to receive push notifications

### ISSUE THREAD

**Issue by 54m4d** [anddea/revanced-patches#227]
### Application

YouTube

### Question description

Hi!

How can we register YouTube app under Cloud Messaging in order to receive push notifications?

I have experimented with various settings within GmsCore, toggling them on and off, and have patiently waited for days without any success.

<details>
<summary>Screenshots</summary>
<img src=https://github.com/anddea/revanced-patches/assets/52612348/30dcf86f-7291-4013-89ef-7231bef3fab0>
<img src=https://github.com/anddea/revanced-patches/assets/52612348/74e84f37-2087-4a38-ad7c-62c0b16e3052>
</details>

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by STEK1337** [comment]
You must install GmsCore first and then ReVanced. Then you add your Google account.

**Comment by 54m4d** [comment]
Hi, I'm not sure if it makes a difference to re-install revanced, but I will try it. The system was not optimizing battery for GmsCore.

Do you receive notifications without any issues?

**Comment by STEK1337** [comment]
> Do you receive notifications without any issues?

Im not using notifications/I don't need them :)

**Comment by Cast0r-999** [comment]
You need fully reinstall RVX and GMS Core, not updating old version.

**Comment by anddea** [comment]
I hope suggestions by other members helped you. 

I have no idea, it never worked for me on any device, any microg, any patches: Vanced, ReVacned, Rex, these patches. And I never really needed notifications.

**Comment by selfmusing** [comment]
> I hope suggestions by other members helped you.
> 
> I have no idea, it never worked for me on any device, any microg, any patches: Vanced, ReVacned, Rex, these patches. And I never really needed notifications.

:⁠'⁠( GMS core killed notifications even on stock YouTube app on my device ( earlier I was getting notifications regularly ) , While I was using VancedMicroG .

But now it's completely DEAD 💀!!

**Comment by anddea** [comment]
> But now it's completely DEAD 💀!!

What about original ReVanced and ReX? Do they show notifications with new GmsCore for you?

**Comment by selfmusing** [comment]
> > But now it's completely DEAD 💀!!
> 
> What about original ReVanced and ReX? Do they show notifications with new GmsCore for you?

Nope 😐, I've also tried to clean install old patched apk file with vanced microg ( after uninstalling gms core & recently patched YT ) .
But notifications are not working on that too..
