### ISSUE TITLE
bug(YouTube): fix default seekbar color behaviour

### ISSUE THREAD

**Issue by shreyjain1998** [anddea/revanced-patches#228]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube

### Bug description

Please fix the default seekbar colors. Currently, seekbar color is always red even if **Enable custom seekbar color** is turned off. Whereas in stock and ReVanced version, it is red when focused and white otherwise.

![IMG_20240331_171303](https://github.com/anddea/revanced-patches/assets/107779107/adefc53e-d160-4f15-9097-cba751d666fe)
![IMG_20240331_170524](https://github.com/anddea/revanced-patches/assets/107779107/23edd198-8564-4055-a24d-c0b70eb5d59c)

ReVanced with focused -
![IMG_20240331_170543](https://github.com/anddea/revanced-patches/assets/107779107/abe4723c-40b8-4e0b-9f5d-8513a41b8c2d)
Normally -
![IMG_20240331_170604](https://github.com/anddea/revanced-patches/assets/107779107/9805c8b3-caa4-4702-8e82-6b0d42926904)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It should be fixed in the latest dev.

**Comment by shreyjain1998** [comment]
Thanks for the update, it is working fine now.
