### ISSUE TITLE
feat (YT) : Keep video fullscreen when you come back to the app.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#23]
### Application

YouTube

### Feature description

There is a problem with both patched & unpatched YouTube app. When a video is playing in fullscreen (landscape fullscreen), and you tap the home button, then open YT app from app drawer, the video comes out of landscape fullscreen automatically and start playing in portrait.

So, please make a patch that fixes this behaviour.

Also, in recent YT versions, there is something called "portrait fullscreen". If you tap home button while being in "portrait fullscreen", then open the app, you'll still be in portrait fullscreen.
Example of portrait fullscreen video: https://youtu.be/2uoau4UwQsY

That's the kind of behaviour I'm requesting for all videos.

### Motivation

I've personally seen many people getting annoyed because of this behaviour.

So, kindly consider this.

Also, it's the goal of ReVanced to make YT app better, so it makes sense to request a patch like this.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
ReVanced extended settings > Fullscreen > Keep Landscape mode  ( This patch was added by @inotia00 - rex ,anddea , rufusin all rvx forks also have this :)

https://github.com/anddea/revanced-patches/assets/109387456/11ff4977-a436-4ac9-968b-b1375703177c

**Comment by Aryan-Chauhan** [comment]
> ReVanced extended settings > Fullscreen > Keep Landscape mode  ( This patch was added by @inotia00 - rex ,anddea , rufusin all rvx forks also have this :)
> 
> https://github.com/anddea/revanced-patches/assets/109387456/11ff4977-a436-4ac9-968b-b1375703177c
> 
> 

It only works when you press lock button when the video is playing in fullscreen. Or when the video is paused, and phone locks itself. 

Read this convo fully for better understanding:

https://github.com/inotia00/ReVanced_Extended/issues/1920

Also, read that comment by nintendork07

Currently, it doesn't stay in fullscreen when you switch back & forth between apps.

But interestingly, portarit videos remain fullscreen no matter what you do (switch between apps all you want, it will still remain fullscreen).

You can try with this video:

https://youtu.be/2uoau4UwQsY

Make it fullscreen, then switch apps and come back to RVX.

You will find that it has remained in fullscreen mode.

**Comment by selfmusing** [comment]
> > ReVanced extended settings > Fullscreen > Keep Landscape mode  ( This patch was added by @inotia00 - rex ,anddea , rufusin all rvx forks also have this :)
> > 
> >   
> >     
> >     
> > 
> >     1710327802563.mp4
> 
> It only works when you press lock button when the video is playing in fullscreen. Or when the video is paused, and phone locks itself.
> 
> Read this convo fully for better understanding:
> 
> [inotia00/ReVanced_Extended#1920](https://github.com/inotia00/ReVanced_Extended/issues/1920)
> 
> Also, read that comment by nintendork07
> 
> Currently, it doesn't stay in fullscreen when you switch back & forth between apps.
> 
> But interestingly, portarit videos remain fullscreen no matter what you do (switch between apps all you want, it will still remain fullscreen).
> 
> You can try with this video:
> 
> https://youtu.be/2uoau4UwQsY
> 
> Make it fullscreen, then switch apps and come back to RVX.
> 
> You will find that it has remained in fullscreen mode.

Now , you have explained it in a much better way 🫡 
I hope anddea will be able to fix this issue.... 

( 👑 LEGEND INOTIA added this great patch for us Android users , which even Google can't do it yet 💀)

**Comment by MondayNitro** [comment]
> > > ReVanced extended settings > Fullscreen > Keep Landscape mode  ( This patch was added by @inotia00 - rex ,anddea , rufusin all rvx forks also have this :)
> > > ```
> > > 1710327802563.mp4
> > > ```
> > 
> > 
> > It only works when you press lock button when the video is playing in fullscreen. Or when the video is paused, and phone locks itself.
> > Read this convo fully for better understanding:
> > [inotia00/ReVanced_Extended#1920](https://github.com/inotia00/ReVanced_Extended/issues/1920)
> > Also, read that comment by nintendork07
> > Currently, it doesn't stay in fullscreen when you switch back & forth between apps.
> > But interestingly, portarit videos remain fullscreen no matter what you do (switch between apps all you want, it will still remain fullscreen).
> > You can try with this video:
> > https://youtu.be/2uoau4UwQsY
> > Make it fullscreen, then switch apps and come back to RVX.
> > You will find that it has remained in fullscreen mode.
> 
> Now , you have explained it in a much better way 🫡 I hope anddea will be able to fix this issue....
> 
> ( 👑 LEGEND INOTIA added this great patch for us Android users , which even Google can't do it yet 💀)

it was there in older yt versions, but google retards decided it was better to exit fullscreen when unlocking the phone

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225

**Comment by Aryan-Chauhan** [comment]
Stock YT v20.03.45 has this feature now.
