### ISSUE TITLE
suggestion: infinity for Reddit

### ISSUE THREAD

**Issue by TeaqariaWTF** [anddea/revanced-patches#230]
### Application

Other

### Suggestion description

Can you add patch support for infinity for reddit?

https://github.com/Docile-Alligator/Infinity-For-Reddit

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Sam101011** [comment]
Main Revanced already has a patch for it, plus you can also use the [google collab script](https://www.reddit.com/r/Infinity_For_Reddit/comments/14c2v5x/build_your_own_apk_with_your_personal_api_key_in/)(which I prefer)

**Comment by anddea** [comment]
I see no reason, it's available in Revanced, there's nothing Extended to add.
