### ISSUE TITLE
bug: youtube app crashing with vertical videos

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [anddea/revanced-patches#231]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.12.41

### Bug description

There is a bug with vertical videos (not shorts) (im talking about regular videos recorded on vertical) on 19.12.xx, those videos, in this specifical version make the app crash, i don't know if it's a problem of the patches itself or of an unique youtube problem

### Error logs

```shell
Idk
```

### Solution

Patch with 19.11.xx

### Additional context

I discovered something, when your project was bumped to 19.11, it started being great to patch later versions, But there is a shady turn, That will not work anymore, cuz in google are devilish and they made the "hide shorts components" and the "hide handle", and "return youtube dislike" patches fail, (that on 19.12.xx on both anddea-RVX and ReX and any other variation you think).

So it would be even better a bump to 19.12.xx, also i don't know if it's a patches related problem or a problem with app itself, i mean with regular youtube app

### Device Environment

Android 12 one ui 5 1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
https://github.com/anddea/revanced-patches/issues/218#issuecomment-2028096380
