### ISSUE TITLE
question: where is "Hide settings preferences" option?

### ISSUE THREAD

**Issue by federicogith** [anddea/revanced-patches#232]
### Application

YouTube

### Question description

I searched the new option added on v2.223.0-dev.21 in settings but couldn't exactly find it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Not available yet.
