### ISSUE TITLE
suggestion: Should be Documentation for Using ReVanced Patches by Anddea

### ISSUE THREAD

**Issue by vishal273007** [anddea/revanced-patches#234]
### Application

YouTube

### Suggestion description

I can't find official Revanced cli documentation. I find inotia00's and YT-Advanced's cli documentaion a little not easy to understand. So I think there should be a ReVanced ReX documention it as well.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
They are all the same, why do we need that many duplicated docs?

https://github.com/ReVanced/revanced-cli/tree/main/docs 

If you're gonna use inotia00's cli, there you have additional `--rip-libs` option.
Some options are not mentioned like `--exclusive` by I'm not sure if anyone would wanna use it.
