### ISSUE TITLE
(dev) Wrong youtube notification icon in Xiaomi

### ISSUE THREAD

**Issue by speedlorenzo12** [anddea/revanced-patches#235]
### Type

Other

### Tools used

Revancify

### Application

19.11.38

### Bug description

I successfully installed the latest dev version with the icon patch set to revancify blue, however I noticed that the notifications show revancify red instead
(When I have a notification I will send a screenshot)

### Solution

Fix revancify red notification icon error

### Device Environment

Android 13 miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by speedlorenzo12** [comment]
I cleaned the chance now 
![Screenshot_2024-04-01-16-19-09-212_app.and1.android.youtube.jpg](https://github.com/anddea/revanced-patches/assets/111771663/f20ded61-c776-4d99-aba9-18433bbaea14)

**Comment by anddea** [comment]
I just checked toast notification on my side and it's blue. Probably it's cached in the storage for you. Try to reboot your device. Install with a different package name or clear the storage.
