### ISSUE TITLE
Remove notification shade media controls

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#239]
### Application

YouTube

### Question description

How can I stop the media controls showing in the notification shade? I used to have it shut off in regular revanced. Not sure how I did it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Long press on notification and open settings of it, depending on your android version you can hide all notifications or select specific types of notifications.

**Comment by MtndaleRedneck** [comment]
I had done that already. Didn't fix the issue. I don't want background playback on and don't want the media controls in the notification shade. Galaxy S22 ultra.

**Comment by anddea** [comment]
Background playback can be turned off in YouTube Settings > Background. Notifications should be hidden if you turned them off. You can also check YouTube Settings > Notifications. But I always use System's Notification Settings.

**Comment by MtndaleRedneck** [comment]
Very strange. Checked all those already and I'm still getting the notification.
