### ISSUE TITLE
Why removed patch for disabling only ambient mode for player?

### ISSUE THREAD

**Issue by rsaurav12** [anddea/revanced-patches#242]
### Application

YouTube

### Question description

Why you removed patch for disabling ambient mode only in player? 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
All paches are there, default setting could be changed. You can change it back.
