### ISSUE TITLE
feat: pls add patch for disabling ambient mode only from player

### ISSUE THREAD

**Issue by rsaurav12** [anddea/revanced-patches#243]
### Application

YouTube

### Feature description

Pls add patch for disabling ambient mode only from player separately to keep ambient mode in bottom player enabled.
![Screenshot_2024-04-02-01-55-03-455_anddea youtube](https://github.com/anddea/revanced-patches/assets/53332518/ffd11600-891d-4c05-838f-f003362403d6)

### Motivation

It looks cool in bottom player but not in full screen 
![Screenshot_2024-04-02-01-57-02-494_anddea youtube](https://github.com/anddea/revanced-patches/assets/53332518/5dba800e-89e2-4113-bf1a-afe216b68a6b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
Seems like "Disable Ambient mode from full screen" toggle isn't working 👀 ( I've just tested it )

**Comment by anddea** [comment]
Go to Settings > Extended > Misc > Disable ambient mode, then go to Extended > Fullscrenn > Disable ambient mode in fullscreen.

**Comment by rsaurav12** [comment]
Thank you 🙏
