### ISSUE TITLE
bug: (Youtube) Categories Bar And Lateral Menu Not Showing on secondary Google Account

### ISSUE THREAD

**Issue by malaguer** [anddea/revanced-patches#244]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

RVX Manager 1.18.1
Anddea patcher and integrations sources
YouTube tested from 19.05.36 to 19.11.38
MicroG 0.3.1.3.240913 (from ReVanced) 

### Bug description

I'm new to using the anddea's repository, which I think is incredible, so maybe it is me who is doing something wrong. Although I have read and read all documentation and followed the steps once and another with the same result. 

When I patch the apk I find no errors. When I start the patched ReVanced Extended app it works fine and I can customize all the patches to my liking. 

But I'm using two different Google accounts. The main one works flawlessly, but my secondary account (with same settings) doesn't show neither the "categories bar" nor the lateral menu. 

I am using it on a Samsung Tablet, so my scenario is in Tablet Layout (don't know if this is important). 

I have to mention that restarting the app a random number of times makes it work, but 9 times out of 10 it fails showing those elements in the interface.

MAIN ACCOUNT:

![Screenshot_20240401_223956_YouTube](https://github.com/anddea/revanced-patches/assets/6715879/1f301ffa-8dce-42c1-a5b7-0603a821158c)

VS SECONDARY ACCOUNT:

![Screenshot_20240401_222948_YouTube](https://github.com/anddea/revanced-patches/assets/6715879/b27c8e96-267c-4a42-8232-591ac6d053fc)

Any idea what could be the cause? 

### Additional context

I've just realized it also happens in unpatched app but this is happening since I've migrated from standard ReVanced to anddea's Extended version... So I've must caused it somehow.

If the unpatched version is also affected, does it mean is a server side problem?

### Device Environment

Android 14
One UI 6.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by gigachaand** [comment]
Servers side problem.. plz report it to Google they will fix it👍

**Comment by anddea** [comment]
It's a YouTube thing. Categories go away itself after a few seconds, and if you swipe down they come back.

**Comment by malaguer** [comment]
> It's a YouTube thing. Categories go away itself after a few seconds, and if you swipe down they come back.

No, it's not. That behavior you mention shows on the phone. But on Tablet the bar is always on top (in feed tab at least).

> Servers side problem.. plz report it to Google they will fix it👍

That seems to be the case. After two days with the issue, today it seems to be working correctly in both accounts. I didn't change anything. 🤷🏻

Thank you both for answering. And congrats for the patches development. It's so good. 😃
