### ISSUE TITLE
Live Chat 

### ISSUE THREAD

**Issue by sultanmonsur** [anddea/revanced-patches#245]
### Application

YouTube

### Feature description

Please add patch to hide live chat. Live chat is boring to watch.
![Screenshot_2024-04-02-02-36-36-79_0635f5993b1f7a268b0ea09a0649cdab](https://github.com/anddea/revanced-patches/assets/61897416/a3b79105-6b37-4395-a286-ebcf44bbf851)

### Motivation

By implementing this, you will be able to watch live on a clean screen.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
What about Extended > General > Hide auto player popup panels? Or did you mean something different?

**Comment by sultanmonsur** [comment]
> সম্প্রসারিত > সাধারণ > অটো প্লেয়ার পপআপ প্যানেল লুকান সম্পর্কে কি? নাকি আপনি অন্য কিছু বোঝাতে চেয়েছিলেন?
> 
> সম্পাদনা: কোনো উত্তর না আসায় বন্ধ করা হচ্ছে।

The settings you say are unable to hide it.This is not what these settings are for.

**Comment by anddea** [comment]
What is it then? Any example link?

**Comment by sultanmonsur** [comment]
https://www.youtube.com/live/IpiiDH_fdfQ

![Uploading IMG_20240407_133817.jpg…]()

**Comment by anddea** [comment]
I don't see any live chat there. I use default settings from these patches. Is it popping up automatically for you? Try to reset to default settings or clean reinstall the app just to test it , export your settings before you do that.

**Comment by sultanmonsur** [comment]
![IMG_20240407_133817](https://github.com/anddea/revanced-patches/assets/61897416/37ce18e9-a216-4833-9228-9690a78aa4bf)

**Comment by sultanmonsur** [comment]
Okay

**Comment by anddea** [comment]
Where do you get that? Shorts? Feed?

**Comment by sultanmonsur** [comment]
Feed

**Comment by anddea** [comment]
Latest release now has the option to hide live chat text messages, although it's not hiding chat input and polls. It has to be implemented in another way to hide all of that.
