### ISSUE TITLE
bug: Revancify settings character limit.

### ISSUE THREAD

**Issue by ac-tu** [anddea/revanced-patches#247]
### Type

Error while patching

### Tools used

Revancify

### Application

Revancify as of 02.04.2024 (DD/MM/YYYY)

### Bug description

When reading the patch settings for "Tuck away preferences" it can't fit all it's default options in, hitting some form of character limit.
![Screenshot_20240402-015157_Termux](https://github.com/anddea/revanced-patches/assets/76844190/a2691711-8468-46a0-8df1-47acc2a8055b)

Leaving it cut off as "Try ex-"

### Error logs

```shell
N/A
```

### Solution

I'd suggest treating this patch like the edit account menu button. Placing the default list in there and letting users add their own that way. Instead just asking to restart the app instead of entirely patching.
![Screenshot_20240402-015356_YouTube RVX](https://github.com/anddea/revanced-patches/assets/76844190/c767cafe-5b58-4978-a2ed-cae3c432e4da)

### Device Environment

Android 14, Termux Monet as recommended by revancify.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It's not possible to make it inside Extended preferences yet, because litho filter doesn't see Settings elements. That's why I made it this way. Open request in Revancify repo, so they can fix the character limit.

**Comment by ac-tu** [comment]
Hopefully the above pull request gets merged and not just stuck in limbo, I appreciate your response either way and let's hope this gets fixed!
