### ISSUE TITLE
bug: Fullscreen button and chapters over seekbar are hidden

### ISSUE THREAD

**Issue by joelmzj** [anddea/revanced-patches#249]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 19.11.38
patches v2.223.0
integrations v0.150.0

### Bug description

The fullscreen button is hidden and chapters over seekbar are gone.

![photo_2024-04-01_18-52-44](https://github.com/anddea/revanced-patches/assets/79762041/b15a7cf3-05bc-439c-b984-2a62e7e53b11)

### Device Environment

Tested on different devices with different Android versions.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by odkate** [comment]
> The fullscreen button is hidden and chapters
🙄
Do not apply patches `Hide fullscreen button` `Hide player chapters`

**Comment by Armagedon13** [comment]
Sry to ping this but look @anddea :
![Screenshot_20240402-060549](https://github.com/anddea/revanced-patches/assets/12619078/f3a804f4-ae0f-4272-9b42-242ab8516196)
And look the yt:
![Screenshot_20240402-061614](https://github.com/anddea/revanced-patches/assets/12619078/04404223-72a3-42f6-95c8-e703baf500f2)
I try to find a option to change this in options but nothing change

**Comment by anddea** [comment]
In the first screenshot you didn't select it with spacebar.

**Comment by Armagedon13** [comment]
But there are unselected, so they not apply in the patches

**Comment by anddea** [comment]
Are you talking about chapters and fullscreen? Fullscreen is there, chapters are not shown because there are no chapters for this video.

**Comment by Armagedon13** [comment]
Chapters and related videos down Fullscreen are not showed

**Comment by anddea** [comment]
It means there are no chapters for this video. 

For related videos go to Settings > Extended > Fullscreen, and disable `Hide quick actions container`.
