### ISSUE TITLE
feat (YT Music) : add Custom Branding Heading patch.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#25]
### Application

YouTube Music

### Feature description

Similar to RVX YT, I'm requesting to implement Custom Branding Heading patch for YT Music also.
![Screenshot_2024-03-14-06-39-26-87_d5ca8c38f86219f8d8dafdf022bf2e3b.jpg](https://github.com/anddea/revanced-patches/assets/91815107/637477ac-e9e7-4b24-9400-2e3740973df7)

![ResizedImage_2024-03-14_06-40-37_1559.jpg](https://github.com/anddea/revanced-patches/assets/91815107/0f8ed241-f682-4bb6-802d-d59262c442f1)

### Motivation

This feature should be implemented because RVX already provides the same for YT. So, what's the reason for not getting the same benefits on YT Music? Since both apps are coming from the same company, uses same accounts & many users use both these apps on their phones, it makes sense to provide them a uniform app header design.

Explicit use case? Please keep the same mentality that one kept while writing the code for YT app custom branding heading / header.

Benefits? Same benefits that one gets while using custom branding heading on YT RVX.

Importance? Same as YT RVX.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
https://github.com/anddea/revanced-patches/assets/109387456/59379e38-1f6e-4b70-97fb-17375b22f767

I agree this patch will be good , but there are some complications...

We need to create these extra files like I showed in the above video.

Now, There are only revancify blue & red icons available with custom branding icon for YTM but they doesn't have header files like AFN icons ( coz @decipher3114 didn't add them )

This patch is totally dependent on some who created the custom branding icon for YTM !!

**Comment by selfmusing** [comment]
> What's the difference with this one #20?

It's the same thing :⁠-⁠D

**Comment by Aryan-Chauhan** [comment]
> What's the difference with this one https://github.com/anddea/revanced-patches/issues/20?

Actually, I've requested for "Custom Branding Heading patch". Sorry for the misunderstanding, I've edited the issue now.

RVX YT also has it, where we can use a custom PNG as the heading on top left corner.

**Comment by Aryan-Chauhan** [comment]
> > What's the difference with this one https://github.com/anddea/revanced-patches/issues/20?
> 
> Actually, I've requested for "Custom Branding Heading patch". Sorry for the misunderstanding, I've edited the issue now.
> 
> RVX YT also has it, where we can use a custom PNG as the heading on top left corner (we have to provide path to folder containing those PNGs).

That's the patch I'm requesting for YT Music / RVX Music.

**Comment by Aryan-Chauhan** [comment]
> > What's the difference with this one #20?
> 
> It's the same thing :⁠-⁠D  ( close this issue )

Actually, both requests are different things.

This is the more advanced version, where the user can use whatever custom PNG they want as the heading / header.

Check my above comment & read the edited issue please.

**Comment by selfmusing** [comment]
> > > What's the difference with this one #20?
> > 
> > 
> > It's the same thing :⁠-⁠D  ( close this issue )
> 
> Actually, both requests are different things.
> 
> This is the more advanced version, where the user can use whatever custom PNG they want as the heading / header.
> 
> Check my above comment & read the edited issue please.

can you share how many custom branding header files you've built yet for YTM ????? (

**Comment by Aryan-Chauhan** [comment]
> > > > What's the difference with this one #20?
> > > 
> > > 
> > > It's the same thing :⁠-⁠D  ( close this issue )
> > 
> > Actually, both requests are different things.
> > 
> > This is the more advanced version, where the user can use whatever custom PNG they want as the heading / header.
> > 
> > Check my above comment & read the edited issue please.
> 
> can you share how many custom branding header files you've built yet for YTM ????? 

I've built zero as of yet, but I have access to all paid/free icon packs on Play Store, so I will make those files & share on Telegram.

**Comment by selfmusing** [comment]
> > > > > What's the difference with this one #20?
> > > > 
> > > > 
> > > > It's the same thing :⁠-⁠D  ( close this issue )
> > > 
> > > 
> > > Actually, both requests are different things.
> > > This is the more advanced version, where the user can use whatever custom PNG they want as the heading / header.
> > > Check my above comment & read the edited issue please.
> > 
> > 
> > can you share how many custom branding header files you've built yet for YTM ?????
> 
> I've built zero as of yet, but I have access to all paid/free icon packs on Play Store, so I will make those files & share on Telegram.

Thanks 😁❤️

**Comment by anddea** [comment]
I don't think that anyone would use this feature, creating that many folders and files for different DPIs, so it'll be worthless. You can always extend existing `Custom branding icon` patch and add support for custom headers like it's done for launcher icon and open Pull Request here, I'll gladly accept that.

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT Music feature requests in this single issue:

#226
