### ISSUE TITLE
bug: HDR Videos disabling not working

### ISSUE THREAD

**Issue by Anurag69** [anddea/revanced-patches#250]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.11.38

### Bug description

 The higher video quality not available. Even after disabling hdr I am getting hdr video quality. YouTube patched using latest anddea patches. Device is Iqoo neo 7 Pro
![Screenshot_20240402_160037](https://github.com/anddea/revanced-patches/assets/30232586/367300e2-b0d9-4751-a394-59ef8b4482fc)
![Screenshot_20240402_160447](https://github.com/anddea/revanced-patches/assets/30232586/b3e932f4-97a8-4c04-86e7-ca4940dfac37)
![Screenshot_20240402_160455](https://github.com/anddea/revanced-patches/assets/30232586/b041d6b4-7d23-422e-a076-ca746eef5d66)

### Device Environment

Iqoo Neo 7 Pro  | Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
Disablw HDR Video toggle isn't working anymore on the latest versions of YouTube , I think you can use vp9 codec toggle to get rid of this HDR .

**Comment by Anurag69** [comment]
I am using recommended version - 19.11.38, Is this version also not supported for disabling HDR. Is there any other YouTube version that supports disabling hdr. Or any other method to fix this because in HDR my videos starts dropping frames in even 1080p. While in previous dev patch it was working without the need of enabling vp9 codex

**Comment by selfmusing** [comment]
> I am using recommended version - 19.11.38, Is this version also not supported for disabling HDR. Is there any other YouTube version that supports disabling hdr. Or any other method to fix this because in HDR my videos starts dropping frames in even 1080p. While in previous dev patch it was working without the need of enabling vp9 codex

USE ANY VERSION LOWER THAN 19.09.XX

[Checkout This]{https://github.com/ReVanced/revanced-patches/pull/2863}

**Comment by Anurag69** [comment]
Thanks for the info. I will try the 19.09.xx. But I don't know what went wrong previously I was using YT 19.11.38 using anddea v223 dev 14 patch and it was working perfectly fine

**Comment by anddea** [comment]
HDR autobrightness is a different patch. Either patch wasn't applied, or maybe there are new server-side features by google.

**Comment by Anurag69** [comment]
Hi @anddea, as I checked the patch was applied successfully and i tried the previous V223dec14 patched YT app it's also giving the same issue HDR is always showing even if the HDR is disabled. Maybe it's some server side changes.
Can you try from your end , to reproduce - Disable the HDR option then open the Costa Rica video shown in screenshot and let me know if it's same for you as well?

**Comment by anddea** [comment]
I cannot reproduce this issue. If anyone else can reproduce it, let us know. 

Maybe try to clean install, especially if it worked for you before. Is there anything that you changed so this happened? Maybe you changed sources back and forth and then it started? Or anything else?

**Comment by Anurag69** [comment]
Tried clean install, nothing changed in selected patches

**Comment by Anurag69** [comment]
As i checked now the HDR option is only showing for Costa Rica video shown in screenshot. Maybe this is video / user specific bug.

**Comment by anddea** [comment]
Can you disable `Disable HDR video` to check id other videos really have HDR.

I don't have HDR for Costa Rica video. 

Close the issue, if disable HDR works for you.

**Comment by Anurag69** [comment]
Tried disabling the HDR , as you can see the other videos does have HDR
![Screenshot_20240403_031622](https://github.com/anddea/revanced-patches/assets/30232586/2e9e8f76-5df4-46a4-9c1e-873426601bba)
![Screenshot_20240403_031533](https://github.com/anddea/revanced-patches/assets/30232586/4e86ccfa-312a-4142-b26d-976ff2e8c4ad)
![Screenshot_20240403_031512](https://github.com/anddea/revanced-patches/assets/30232586/3248c624-d686-4c42-a71e-e7e8402929c2)
![Screenshot_20240403_031456](https://github.com/anddea/revanced-patches/assets/30232586/668bb327-cd98-4c2f-bca8-08f1ec2b4757)

**Comment by Anurag69** [comment]
After enabling the disable HDR only the costa Rica video shows the HDR option as u can see in SS
![Screenshot_20240403_031836](https://github.com/anddea/revanced-patches/assets/30232586/2066fce2-9244-4616-9e01-157b67b9e82d)
![Screenshot_20240403_031823](https://github.com/anddea/revanced-patches/assets/30232586/4c1eee2b-a02a-43f4-b5c8-b468bb81019c)
![Screenshot_20240403_031813](https://github.com/anddea/revanced-patches/assets/30232586/d139bdab-1158-418b-91a1-48fc9e9692eb)
![Screenshot_20240403_031802](https://github.com/anddea/revanced-patches/assets/30232586/0438d532-38d6-4a2a-83b8-0dc927900699)

**Comment by Anurag69** [comment]
Closing as it got fixed automatically by maybe some server side changes on YouTube app
