### ISSUE TITLE
bug: When Using Wifi, Yt shorts is suttering. But audio still continues

### ISSUE THREAD

**Issue by relugnemkog** [anddea/revanced-patches#253]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.09.37

### Bug description

When Using Wifi, Yt shorts is suttering. But audio still continues. Also tried on stock 19.09.37 version. It still suttering. But last version of Stock YouTube has no problem with that.

### Device Environment

Android 13, Miui 14, Xiaomi Redmi 9T

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
What if you patch 19.11?

**Comment by anddea** [comment]
Did you set default quality for WiFi? It's a known bug for some users (which I cannot reproduce) if you set anything but auto.

**Comment by relugnemkog** [comment]
Sorry guys, i think its my phone fault. Likewise, Instagram reels is stuttering. Also, stock youtube has same issue.
