### ISSUE TITLE
No Youtube Notifications After Installing New GSM Core 

### ISSUE THREAD

**Issue by Tronak007** [anddea/revanced-patches#254]
I'm New Here So Don't Know Correct Way To Fix This Problem So Please Anyone Can Guide Me Through It

I'm Not Receiving Any Notification From Youtube After Updating To This New GSM Core, While Uninstalled Vanced MicroG

I Have Allowed All Permissions And Allowed App To Run In Background, I Have Unrestricted The Battry Optimization Also But No Luck For Me

Using YouTube ReVanced(Non Root)
By anddea, Build It With Revancify,

Youtube Version 19.11.38
With Latest Patches And Intigrations

Can Anyone Help Me To Solve This Problem, Thanks In Advanced

![Screenshot_20240402-190159.png](https://github.com/anddea/revanced-patches/assets/106589892/a7b6c0d8-9f1f-4df7-ab4a-c13de10181b6)

![Screenshot_20240402-190218.png](https://github.com/anddea/revanced-patches/assets/106589892/4cec755d-1fce-4e32-84d5-2d58012e3270)

![Screenshot_20240402-190221.png](https://github.com/anddea/revanced-patches/assets/106589892/5a3dc71f-4bcb-42bb-9617-3c34604d5271)

![Screenshot_20240402-190204.png](https://github.com/anddea/revanced-patches/assets/106589892/bcc9a32f-f7f5-4c36-9746-11f5e4bf6000)

**Comment by anddea** [comment]
Check this duplicate. 

https://github.com/anddea/revanced-patches/issues/227
