### ISSUE TITLE
feat: Download videos from notification list 3 dots menu

### ISSUE THREAD

**Issue by NikunjKhangwal** [anddea/revanced-patches#255]
### Application

YouTube

### Feature description

If possible please implement so we can download notified videos for offline viewing from 3 dots menu just like we can do in home feed.
![IMG_20240402_195737](https://github.com/anddea/revanced-patches/assets/99175083/ce161ac4-12c1-4e80-9f70-95da1a08242e)

### Motivation

I watch most of the vidoes offline because i have a very bad connection so online can buffer at any point. But playing every video one by one to download them is bit of a hassle. Having the ability to download it straight from notification will be much easier just like the other feeds.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Just wondering why don't you download it from the subscriptions tab, it's almost the same as notifications.

**Comment by NikunjKhangwal** [comment]
I have the tab disabled.
1. I've subscribed to hundreds of channels but only follow notification from like a dozen of them.
2. Subscription tab includes live videos as well
3. I prefer the list style layout for notifications
