### ISSUE TITLE
suggestion: "Force" type patches should be off by default

### ISSUE THREAD

**Issue by blacktornadog7** [anddea/revanced-patches#256]
### Application

YouTube, YouTube Music

### Suggestion description

All "Force" type patches or unreversible patches (e.g "Add splash animation" "Shorts overlay buttons" "Tuck away preferences") should be off (excluded) by default.

And all "Adds an option" type patches should be on (included) by default (or off temporarily until they're fixed if they cause a crash or a bug).

This makes more sense, since you have the option to choose to apply any patch after the fact or not.
It also makes it easier for people who generate their apk's automatically (by including all default patches by default) to enjoy new features or disable them if they don't like them which not possible with "force" patches.

The perfect solution for this is that every patch should be the "Adds an option" type but I don't know if this is harder or even possible with some patches.

btw thank you so much for continuing RVX, adding new features and all the hard work...

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Give me reasons why turning them on by default is a bad idea and I will consider. 

A lot of people hate default shorts buttons, myself included, I see no point disabling that patch by default. The same thing goes for cluttered settings. 

I can disable add splash animation but does it even change anything?
