### ISSUE TITLE
feat: Icons and Splash screen settings

### ISSUE THREAD

**Issue by blacktornadog7** [anddea/revanced-patches#257]
### Application

YouTube, YouTube Music

### Feature description

This is basically like two patches in one:
1. Add the option for the user to choose between just a [simple splash icon,](https://imgur.com/a/j565Z18) an [animated splash screen](https://imgur.com/a/dtLaOYP) 
or [both](https://imgur.com/n3WABBg) (this is what we have now).
2. Add all branding options (icons and splash screens, default and custom ones) to be configurable by the user to pick and choose whatever ones they like from ReVanced Extended settings (i.e after patching).
[Like how reddit allows premium users to change the app icon.](https://imgur.com/a/4kNKhpf)

### Motivation

more customizability 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Reopen this in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues)
