### ISSUE TITLE
question: "Tuck away preferences" 

### ISSUE THREAD

**Issue by hphp22f** [anddea/revanced-patches#258]
### Application

YouTube

### Question description

I can't find its setting, where is this setting.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
you need to provide a list of settings to hide in the stock YouTube app, via patch option.

**Comment by swarnenduu** [comment]
> you need to provide a list of settings to hide in the stock YouTube app, via patch option.

Hi, I'm sorry but I can't find any option to do so in the patch options. I'm using Revancify to patch.
