### ISSUE TITLE
question: Hello bro what is the password for the keystore?

### ISSUE THREAD

**Issue by Parsa307** [anddea/revanced-patches#259]
### Application

YouTube

### Question description

I want the keystore password so i can change the icon and sign with same signatures

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Keystore is created when you patch. Not sure what is the password there. 

Try this one maybe
https://github.com/ReVanced/revanced-manager/blob/c209c32613700281b784b656766b6c04ca5b8c69/lib/services/manager_api.dart#L45
