### ISSUE TITLE
feat (YT Music) : Ability to hide "Episodes for Later".

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#26]
### Application

YouTube Music

### Feature description

Kindly add the ability to hide "Episodes for Later" in Library.
![304052488-b3f08e28-80a0-4656-a7fb-ac577a026b00](https://github.com/anddea/revanced-patches/assets/91815107/fb9e57b2-9550-40e5-b181-673f5fc517f9)

### Motivation

Many people only use the RVX Music app for listening to music & never listen to podcasts. So, it will provide a better design for them.

If it's not too time-consuming, kindly look into it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT Music feature requests in this single issue:

#226

**Comment by anddea** [comment]
Since inotia accepts feature requests, it's better to ask him to implement all YT Music features.
