### ISSUE TITLE
feat: Disable the AV1 codec

### ISSUE THREAD

**Issue by DanGLES3** [anddea/revanced-patches#267]
### Application

YouTube

### Feature description

Seems with the march Play System update Google might have accidentally enabled the AV1 codec on all/some devices (regardless of hardware support) thus causing significant battery drain on devices without hardware AV1 decoding, i had to workaround with root by stripping out the AV1 codec from the update

If possible could a feature be implemented to force disable the AV1 codec to workaround this issue? The affected app is Youtube and likely Youtube Music as well (haven't tested the latter)

### Motivation

The use of the AV1 codec on unsupported devices causes huge strain on the CPU and thus significant battery drain, without an workaround/fix affected users will notice their devices heating up and running slower due to the overhead of decoding AV1 video

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )

Isn't this working?? 👀

**Comment by DanGLES3** [comment]
> YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> 
> Isn't this working?? 👀
> 
> ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> 
> YT Music v6.46.52 still hasn't affected.

Not at all, at least not for me

**Comment by selfmusing** [comment]
> > YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> > Isn't this working?? 👀
> > ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> > YT Music v6.46.52 still hasn't affected.
> 
> Not at all, at least not for me, that's why I had to resort to a root workaround

Strange 🤔 , I'm still getting vp9 codec tho on both YT & YT music .

You can also try installing armv7 build & then try to spoof the codec to vp9 from miscellaneous settings ( Google don't include libgav1JNI.so file in armv7 libs , which is responsible for av1 codec )

**Comment by DanGLES3** [comment]
> > > YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> > > Isn't this working?? 👀
> > > ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> > > YT Music v6.46.52 still hasn't affected.
> > 
> > 
> > Not at all, at least not for me, that's why I had to resort to a root workaround
> 
> Strange 🤔 , I'm still getting vp9 codec tho on both YT & YT music .
> 
> You can also try installing armv7 build & then try to spoof the codec to vp9 from miscellaneous settings ( Google don't include libgav1JNI.so file in armv7 libs , which is responsible for av1 codec )

I've already seen 2 other users in the Revanced subreddit with this issue, seems to be the result of some A/B testing, also i'm not with my device rn to test it, but when i tried forcefully disabling/removing the libgav1JNI, playback remained in AV1

Iirc that's because Youtube was using the built in software AV1 decoder that they push with their apex/play system updates (noticed because the swcodec process was spiking in CPU usage) if it was using solely Youtube's built in lib the load should be solely on Youtube no? 

With root i worked around the issue by undeclaring the av1 driver from the media_codecs.xml file in the media.swcodec apex library

**Comment by DanGLES3** [comment]
> > > YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> > > Isn't this working?? 👀
> > > ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> > > YT Music v6.46.52 still hasn't affected.
> > 
> > 
> > Not at all, at least not for me, that's why I had to resort to a root workaround
> 
> Strange 🤔 , I'm still getting vp9 codec tho on both YT & YT music .
> 
> You can also try installing armv7 build & then try to spoof the codec to vp9 from miscellaneous settings ( Google don't include libgav1JNI.so file in armv7 libs , which is responsible for av1 codec )

Btw the issue affects browsers as well, even when watching Youtube on the browser it was still using AV1

**Comment by Anurag69** [comment]
> With root i worked around the issue by undeclaring the AV1 codec from the media_codecs.xml file in the media.swcodec apex library
Do you know how to fix this for no root users?

**Comment by DanGLES3** [comment]
> > With root i worked around the issue by undeclaring the AV1 codec from the media_codecs.xml file in the media.swcodec apex library <
> 
> Do you know how to fix this for no root users?

Unfortunately no, tried everything I could on my end before resorted to root 

Even much older versions of Revanced (and even the official YouTube app) were defaulting to AV1

**Comment by Anurag69** [comment]
Sad life of no root users 😔

**Comment by DanGLES3** [comment]
> Sad life of no root users 😔

But tbh it's a YouTube issue, not a Revanced one, we should be spamming this to YouTube's support as well as it's their problem, not ours

**Comment by DanGLES3** [comment]
> > Sad life of no root users 😔
> 
> Haven't tested but go to the desktop YouTube website, tap your account icon, settings, playback and performance and try switching to prefer AV1 for SD, according to that option it'll switch to VP9 for high resolution content

**Comment by Anurag69** [comment]
Tried it somehow fix for some videos like for Costa Rica 4k hdr Video. First it plays video in hdr mode with avc1 codec for around 15-20 sec then it switched to VP9 codec

**Comment by NCLnclNCL** [comment]
> > > > YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> > > > Isn't this working?? 👀
> > > > ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> > > > YT Music v6.46.52 still hasn't affected.
> > > 
> > > 
> > > Not at all, at least not for me, that's why I had to resort to a root workaround
> > 
> > 
> > Strange 🤔 , I'm still getting vp9 codec tho on both YT & YT music .
> > You can also try installing armv7 build & then try to spoof the codec to vp9 from miscellaneous settings ( Google don't include libgav1JNI.so file in armv7 libs , which is responsible for av1 codec )
> 
> I've already seen 2 other users in the Revanced subreddit with this issue, seems to be the result of some A/B testing, also i'm not with my device rn to test it, but when i tried forcefully disabling/removing the libgav1JNI of Youtube, playback remained in AV1
> 
> Iirc that's because Youtube was using the built in software AV1 decoder that they push with their apex/play system updates (noticed because the swcodec process was spiking in CPU usage) if it was using Youtube's built in lib the CPU load should be solely on Youtube no? (at least that's the case when i use software decoding on VLC)
> 
> With root i worked around the issue by undeclaring the AV1 codec from the media_codecs.xml file in the media.swcodec apex library

Can you explain more clearly what to do, and how to check the codec on youtube android, I only see it on TV and computer

**Comment by DanGLES3** [comment]
> > > > > YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> > > > > Isn't this working?? 👀
> > > > > ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> > > > > YT Music v6.46.52 still hasn't affected.
> > > > 
> > > > 
> > > > Not at all, at least not for me, that's why I had to resort to a root workaround
> > > 
> > > 
> > > Strange 🤔 , I'm still getting vp9 codec tho on both YT & YT music .
> > > You can also try installing armv7 build & then try to spoof the codec to vp9 from miscellaneous settings ( Google don't include libgav1JNI.so file in armv7 libs , which is responsible for av1 codec )
> > 
> > 
> > I've already seen 2 other users in the Revanced subreddit with this issue, seems to be the result of some A/B testing, also i'm not with my device rn to test it, but when i tried forcefully disabling/removing the libgav1JNI of Youtube, playback remained in AV1
> > Iirc that's because Youtube was using the built in software AV1 decoder that they push with their apex/play system updates (noticed because the swcodec process was spiking in CPU usage) if it was using Youtube's built in lib the CPU load should be solely on Youtube no? (at least that's the case when i use software decoding on VLC)
> > With root i worked around the issue by undeclaring the AV1 codec from the media_codecs.xml file in the media.swcodec apex library
> 
> Can you explain more clearly what to do, and how to check the codec on youtube android, I only see it on TV and computer

To check you enable stats for nerds in the general settings, then on a video tap the gear icon and stats for nerds 

As for what I did to fix with root, its a bit convoluted as it requires a root method that can mount the Apex partition (might be a Kitsune Magisk only thing, I'm not sure) I could make a module for it I suppose

**Comment by selfmusing** [comment]
> > > > > > YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> > > > > > Isn't this working?? 👀
> > > > > > ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> > > > > > YT Music v6.46.52 still hasn't affected.
> > > > > 
> > > > > 
> > > > > Not at all, at least not for me, that's why I had to resort to a root workaround
> > > > 
> > > > 
> > > > Strange 🤔 , I'm still getting vp9 codec tho on both YT & YT music .
> > > > You can also try installing armv7 build & then try to spoof the codec to vp9 from miscellaneous settings ( Google don't include libgav1JNI.so file in armv7 libs , which is responsible for av1 codec )
> > > 
> > > 
> > > I've already seen 2 other users in the Revanced subreddit with this issue, seems to be the result of some A/B testing, also i'm not with my device rn to test it, but when i tried forcefully disabling/removing the libgav1JNI of Youtube, playback remained in AV1
> > > Iirc that's because Youtube was using the built in software AV1 decoder that they push with their apex/play system updates (noticed because the swcodec process was spiking in CPU usage) if it was using Youtube's built in lib the CPU load should be solely on Youtube no? (at least that's the case when i use software decoding on VLC)
> > > With root i worked around the issue by undeclaring the AV1 codec from the media_codecs.xml file in the media.swcodec apex library
> > 
> > 
> > Can you explain more clearly what to do, and how to check the codec on youtube android, I only see it on TV and computer
> 
> To check you enable stats for nerds in the general settings, then on a video tap the gear icon and stats for nerds
> 
> As for what I did to fix with root, its a bit convoluted as it requires a root method that can mount the Apex partition (might be a Kitsune Magisk only thing, I'm not sure) I could make a module for it I suppose

👀 Spoiler: In the next RVX Patch PDATE , inotia also added a toggle to reject software AV1 codec response 🫡

**Comment by DanGLES3** [comment]
> > > > > > > YouTube settings > ReVanced Extended > Miscellaneous > Change video codec setting ( you can either change it to vp9 or HDR )
> > > > > > > Isn't this working?? 👀
> > > > > > > ![Screenshot_20240405-013159_YouTube_Music](https://private-user-images.githubusercontent.com/109387456/319757204-a3b211c7-7541-488e-b5b6-081cfaca2f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjIxOTQsIm5iZiI6MTcxMjI2MTg5NCwicGF0aCI6Ii8xMDkzODc0NTYvMzE5NzU3MjA0LWEzYjIxMWM3LTc1NDEtNDg4ZS1iNWI2LTA4MWNmYWNhMmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMDE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc4YjE0ODJkMDIwMzg2ZjhjMGI2MDMyNmVkYTEyNjU2MjA2MWEzMzIwNTE4ZjVmZjJkY2FmZmI2YTFjYTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChPmV4CpSYpkGa_mUoskmczwE1_D8GiZjkQxUPzf5ss)
> > > > > > > YT Music v6.46.52 still hasn't affected.
> > > > > > 
> > > > > > 
> > > > > > Not at all, at least not for me, that's why I had to resort to a root workaround
> > > > > 
> > > > > 
> > > > > Strange 🤔 , I'm still getting vp9 codec tho on both YT & YT music .
> > > > > You can also try installing armv7 build & then try to spoof the codec to vp9 from miscellaneous settings ( Google don't include libgav1JNI.so file in armv7 libs , which is responsible for av1 codec )
> > > > 
> > > > 
> > > > I've already seen 2 other users in the Revanced subreddit with this issue, seems to be the result of some A/B testing, also i'm not with my device rn to test it, but when i tried forcefully disabling/removing the libgav1JNI of Youtube, playback remained in AV1
> > > > Iirc that's because Youtube was using the built in software AV1 decoder that they push with their apex/play system updates (noticed because the swcodec process was spiking in CPU usage) if it was using Youtube's built in lib the CPU load should be solely on Youtube no? (at least that's the case when i use software decoding on VLC)
> > > > With root i worked around the issue by undeclaring the AV1 codec from the media_codecs.xml file in the media.swcodec apex library
> > > 
> > > 
> > > Can you explain more clearly what to do, and how to check the codec on youtube android, I only see it on TV and computer
> > 
> > 
> > To check you enable stats for nerds in the general settings, then on a video tap the gear icon and stats for nerds
> > As for what I did to fix with root, its a bit convoluted as it requires a root method that can mount the Apex partition (might be a Kitsune Magisk only thing, I'm not sure) I could make a module for it I suppose
> 
> i will wait for module, I just checked, there is a small percentage of videos that are avc1, the majority are still vp9

If videos are still AVC1 and VP9 then you don't really have this issue, the issue is AV1

**Comment by Francesco146** [comment]
fixed in rvx
