### ISSUE TITLE
New type of ads can't be hidden

### ISSUE THREAD

**Issue by nullll1** [anddea/revanced-patches#269]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.11.43

### Bug description

1open youtube 
2check home feed

![Screenshot_20240403-172204](https://github.com/anddea/revanced-patches/assets/102777708/13aa8f91-ca1a-4c8c-ab9d-5c41a03b6c6b)

### Additional context

I know 19.11.43 is not supported but even if I rolled back to supported version 19.11.38, the issue still exists

### Device Environment

android 14, pixel 5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
Btw these are not ads , this is youtube playables which they earlier added only for premium users..
Now they also a/b testing it on non-premium accounts 🤓


https://github.com/anddea/revanced-patches/assets/109387456/ef5fd076-2831-435d-a207-88c5f98c5f83
