### ISSUE TITLE
bug: YT crashes while playing Shorts after few time

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#272]
### Type

Other

### Tools used

rvx-builder

### Application

YT 19.11.38

### Bug description

I think that it is a bug. Whenever we play Shorts for 4-5 mins, it crashes automatically. But while playing videos, it won't. It is a bug so check it in the code. 

I'll add proof in a while.

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Clean-install v19.05.36 with latest patches & integrations. Maybe your phone has some problem with new YT app versions.

BTW, you have no benefit using v19.11.38 because it doesn't have one single new thing compared to v19.05.36. Only the number looks bigger.

If you use v19.05.36, you will miss out NOTHING.

**Comment by anddea** [comment]
> BTW, you have no benefit using v19.11.38 because it doesn't have one single new thing compared to v19.05.36. Only the number looks bigger.

In fact, I saw the opposite, someone mentioned crashes in an older version and the latest supported fixed it for that person. Not sure if it's related to versions.

I can't reproduce this issue, if you can, grab logs and attach them here.

**Comment by Francesco146** [comment]
not reproducible on my part

**Comment by Vipin2003** [comment]
This issue is already mentioned in revanced. Check this:
https://github.com/ReVanced/revanced-patches/issues/2966

**Comment by anddea** [comment]
Still can't reproduce it. 

Did you set default video quality? There's a close bug for some people with shorts that caused by this setting. 

I need logs or maybe if you can try to experiment with settings, maybe disabling one of them will solve the problem.

**Comment by Francesco146** [comment]
should be fixed in RVX

**Comment by Vipin2003** [comment]
> Still can't reproduce it.
> 
> Did you set default video quality? There's a close bug for some people with shorts that caused by this setting.
> 
> I need logs or maybe if you can try to experiment with settings, maybe disabling one of them will solve the problem.

I already solved it but forgot to close it. It is due to Microg Disable Optimization. As I'm IQOO user, Vivo provides two ways (compulsory) to disable optimization for apps. And I forgot to do that with the 2nd method.
