### ISSUE TITLE
question: What do these switches hide in the Shorts?

### ISSUE THREAD

**Issue by odkate** [anddea/revanced-patches#274]
### Application

YouTube

### Question description

![2024_04_04_22 29 46](https://github.com/anddea/revanced-patches/assets/90364108/7ae5b80e-ca5c-4ea4-b0cf-d467a459b959)

Please provide screenshots of what should be hidden

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
![IMG_20240405_020415_088](https://github.com/anddea/revanced-patches/assets/109387456/88f6d07d-db6e-4a60-a002-72b98ed3ad21)

The last three toggles aren't working even on the last recommended version (v19.11.38) .

**Comment by odkate** [comment]
> toggles aren't working

I also don't see any changes from these switches, which is why I asked this question 🤔

**Comment by AbakNacchan** [comment]
Yeah, and the problem might escalated in 19.12.xx and up. Should see the problem in 19.13 of even 19.14 that impacted YT shorts.

**Comment by selfmusing** [comment]
> Yeah, and the problem might escalated in 19.12.xx and up. Should see the problem in 19.13 of even 19.14 that impacted YT shorts.

🥸Bruh!! these are not even supported versions...

I've also tried some older versions than v19.11.38 , but it seems like google changes something via a/b tests .

**Comment by anddea** [comment]
I'm not sure, I just merged Rex and he copied it from original ReVanced. Never had time to test it. Maybe it got merged in the wrong way, can you check if it doesn't do anything in rex patches too?

**Comment by odkate** [comment]
> Rex

I don't see any difference there either, it's the same with and without switches

**Comment by Aryan-Chauhan** [comment]
Not working on v19.05.36

**Comment by n1cKz1** [comment]
These settings do work. 
Video title: It hides the title of the video
The rest are not present on every video so I can't really provide a screenshot right now but they do work

**Comment by odkate** [comment]
> Video title: It hides the title of the video

provide a screenshot of how it hides the video title

**Comment by n1cKz1** [comment]
Uuh so something is wrong with this patch after all. Hiding video title doesn't work, and for some reason sound metadata labels and full video link labels are always hidden even if the switches are off.

This is what each of them hides (this screenshot is from official ReVanced patches, so just copy the changes from there and they will work fine)
![Screenshot_2024-04-05-20-51-01-468-edit_app revanced android youtube](https://github.com/anddea/revanced-patches/assets/107653639/a966c52e-989a-4d47-836d-cdca0fa9fcea)

**Comment by odkate** [comment]
> sound metadata labels and full video link labels are always hidden even if the switches are off

For me, `Sound metadata label` and `Video link` do not show even on patches of version 2.220.9a1, although there are no switches to hide them at all

**Comment by anddea** [comment]
It should be fixed in the latest dev. I also added notice that enabling hide info panels will hide components that some new options hide. Now, it's just more selective, what exactly do you want to hide or hide all of them at once.

**Comment by odkate** [comment]
> fixed

It works, but it turns out that there is an overlay of patches

![Screenshot_20240406-235744](https://github.com/anddea/revanced-patches/assets/90364108/a40eb3b6-cba4-4c1c-8324-c341b317d15d)

**Comment by odkate** [comment]
> latest dev

If "Spoof app version" is enabled, "Hide Shorts video title" does not work
