### ISSUE TITLE
feat (YT) : Allow the user to keep same type of Swipe Control on both side of the screen.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#275]
### Application

YouTube

### Feature description

Currently, we can use "Brightness Gesture" on the left side of the screen & "Volume Gesture" on the right side of the screen.

So, I'm requesting for implementation of two possibilities (1st can't be used when 2nd is enabled and vice-versa):

1. An option to use Volume Gesture on both left side and right side.

2. An option to use Brightness Gesture on both left side and right side.

Thank you.

### Motivation

There are people who only use one type of Swipe Control (either Volume or Brightness), so it's a logical move to provide them the ability to use 100% of the screen to change values of either Volume or Brightness.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225

**Comment by anddea** [comment]
It's not that hard but it'll be unintuitive for most people. Ask this one in intoia's repo, if he implments it, I'll merge it.

**Comment by Aryan-Chauhan** [comment]
I asked in inotia00's repo but he didn't accept it.

It may be unintuitive for some, and convenient for others.
