### ISSUE TITLE
question:  which microG or GSM core should i use? 

### ISSUE THREAD

**Issue by abdarker** [anddea/revanced-patches#276]
### Application

YouTube

### Question description

actual gsmcore is huge after installation and there's no option to hide app from launcher like previous microG. previous microG takes 20mb and now gsm core takes 200mb+ after installation and no option to hide app from launcher. do you have any dedicated gsmcore?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Either use the GmsCore from "ReVanced/GmsCore repo" or "YT-Advanced/GmsCore repo"

**Comment by anddea** [comment]
There is no recommendations, use whatever suits you the best. You can try those mentioned by Aryan-Chauhan, also you can use the one by rufusin.
