### ISSUE TITLE
feat(YouTube - Alternative thumbnails): Selectively enable for home / subscription / search

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#278]
### Application

YouTube

### Feature description

feat(YouTube - Alternative thumbnails): Selectively enable for home / subscription / search

![thumbnails](https://github.com/anddea/revanced-patches/assets/163995091/8420573c-5284-4703-b426-be177dd9c48d)

https://github.com/ReVanced/revanced-patches/commit/8549e1ba58ad1e1608f5e3ceacd31eeb94578949

### Motivation

:)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I actually had it stashed locally, but then I thought who might need it, so never pushed it. I'll try to add it in the next release.

**Comment by zerozero0022** [comment]
<string name="revanced_alt_thumbnail_home_title">Home tab</string>
<string name="revanced_alt_thumbnail_subscription_title">Subscription tab</string>
<string name="revanced_alt_thumbnail_library_title">\'You\' tab</string>
<string name="revanced_alt_thumbnail_player_title">Player playlists, recommendations</string>
<string name="revanced_alt_thumbnail_search_title">Search results</string>
<string name="revanced_alt_thumbnail_options_entry_1">Original thumbnails</string>
<string name="revanced_alt_thumbnail_options_entry_2">DeArrow &amp; Original thumbnails</string>
<string name="revanced_alt_thumbnail_options_entry_3">DeArrow &amp; Still captures</string>
<string name="revanced_alt_thumbnail_options_entry_4">Still captures</string>
<string name="revanced_alt_thumbnail_dearrow_about_title">DeArrow</string>
<string name="revanced_alt_thumbnail_dearrow_about_summary">"DeArrow provides crowd-sourced thumbnails for YouTube videos. These thumbnails are often more relevant than those provided by YouTube. If enabled, video URLs will be sent to the API server and no other data is sent. If a video does not have DeArrow thumbnails, then the original or still captures are shown.

Tap here to learn more about DeArrow."</string>

<string name="revanced_hide_shorts_shelf_home_title">Hide Shorts in home feed</string>
<string name="revanced_hide_shorts_shelf_home_summary_on">Shorts shelf in home feed are hidden</string>
<string name="revanced_hide_shorts_shelf_home_summary_off">Shorts shelf in home feed are shown</string>
<string name="revanced_hide_shorts_shelf_subscriptions_title">Hide Shorts in subscription feed</string>
<string name="revanced_hide_shorts_shelf_subscriptions_summary_on">Shorts shelf in subscription feed are hidden</string>
<string name="revanced_hide_shorts_shelf_subscriptions_summary_off">Shorts shelf in subscription feed are shown</string>
<string name="revanced_hide_shorts_shelf_search_title">Hide Shorts in search results</string>
<string name="revanced_hide_shorts_shelf_search_summary_on">Shorts shelf in search results are hidden</string>
<string name="revanced_hide_shorts_shelf_search_summary_off">Shorts shelf in search results are shown</string>
