### ISSUE TITLE
feat (YT) : Directly open RVX Settings when tapped on Settings icon.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#28]
### Application

YouTube

### Feature description

In the top right corner of You tab, there is a Settings icon. So, I'm requesting for a patch that directly opens RVX Settings when you tap on it. If implemented, the following obstructions can be avoided:

General
Account
Data saving
Auto-play
Video quality preferences
Background and downloads
Watch on TV
Manage all history
Your data in YouTube
Privacy
Try experimental new features
Purchases and memberships
Billing and payments
Notifications
Connected apps
Live chat
Captions
Accessibility
About
![306376839-22339829-1047-45d5-aba3-a59c9100aeb4](https://github.com/anddea/revanced-patches/assets/91815107/e4f2642b-dbd0-47d4-8155-2b7647678ae0)

### Motivation

As described in Feature Description section, 19 obstructions/redundant texts can be avoided.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
Laziness at its peak 🫡🫡🫡

> ### Application
> YouTube
> 
> ### Feature description
> In the top right corner of You tab, there is a Settings icon. So, I'm requesting for a patch that directly opens RVX Settings when you tap on it. If implemented, the following obstructions can be avoided:
> 
> General Account Data saving Auto-play Video quality preferences Background and downloads Watch on TV Manage all history Your data in YouTube Privacy Try experimental new features Purchases and memberships Billing and payments Notifications Connected apps Live chat Captions Accessibility About ![306376839-22339829-1047-45d5-aba3-a59c9100aeb4](https://private-user-images.githubusercontent.com/91815107/312142633-e4f2642b-dbd0-47d4-8155-2b7647678ae0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjcxOTEsIm5iZiI6MTcxMDMyNjg5MSwicGF0aCI6Ii85MTgxNTEwNy8zMTIxNDI2MzMtZTRmMjY0MmItZGJkMC00N2Q0LTgxNTUtMmI3NjQ3Njc4YWUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwNDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOTc4OTUxMTg5MTQxNjc3ZmQ1ODdhMDU4OGFmOTkzOGJjZWEwNTgxZDM4ZDM2MzdmY2RlYzAyZTM5NDAwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I1VgH2tPH8KMuWuEB-OYE7XYRA0UE3BE_EXJWS7bF2I)
> 
> ### Motivation
> As described in Feature Description section, 19 obstructions/redundant texts can be avoided.
> 
> ### Acknowledgements
> * [x]  This issue is not a duplicate of an existing feature request.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  I have written the title and contents in English.

Tell me you're lazy without telling me you're lazy 🦥🌝

**Comment by Aryan-Chauhan** [comment]
> Laziness at its peak 🫡🫡🫡
> 
> > ### Application
> > YouTube
> > 
> > ### Feature description
> > In the top right corner of You tab, there is a Settings icon. So, I'm requesting for a patch that directly opens RVX Settings when you tap on it. If implemented, the following obstructions can be avoided:
> > 
> > General Account Data saving Auto-play Video quality preferences Background and downloads Watch on TV Manage all history Your data in YouTube Privacy Try experimental new features Purchases and memberships Billing and payments Notifications Connected apps Live chat Captions Accessibility About ![306376839-22339829-1047-45d5-aba3-a59c9100aeb4](https://private-user-images.githubusercontent.com/91815107/312142633-e4f2642b-dbd0-47d4-8155-2b7647678ae0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjcxOTEsIm5iZiI6MTcxMDMyNjg5MSwicGF0aCI6Ii85MTgxNTEwNy8zMTIxNDI2MzMtZTRmMjY0MmItZGJkMC00N2Q0LTgxNTUtMmI3NjQ3Njc4YWUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEwNDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOTc4OTUxMTg5MTQxNjc3ZmQ1ODdhMDU4OGFmOTkzOGJjZWEwNTgxZDM4ZDM2MzdmY2RlYzAyZTM5NDAwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I1VgH2tPH8KMuWuEB-OYE7XYRA0UE3BE_EXJWS7bF2I)
> > 
> > ### Motivation
> > As described in Feature Description section, 19 obstructions/redundant texts can be avoided.
> > 
> > ### Acknowledgements
> > * [x]  This issue is not a duplicate of an existing feature request.
> > * [x]  I have chosen an appropriate title.
> > * [x]  All requested information has been provided properly.
> > * [x]  I have written the title and contents in English.
> 
> Tell me you're lazy without telling me you're lazy 🦥🌝

Bro, 19 obstructions can be avoided/hidden away with this feature.

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225

**Comment by Francesco146** [comment]
@anddea i got an idea. don't know if it's doable but I'll say it. instead of searching through the smali code for the remaining settings for the `Tuck away settings` patch, we could concentrate the effort for this patch, and invert the position of the settings that the user want to see.

something like this:
1. Old method:
   * YT Settings gear:
       * Setting1
       * Setting2
       * ...
       * RVX settings 
           * RVXSetting1
           * RVXSetting2
           * ...

2. New method:
   * YT Settings gear == RVX settings:
       * Setting1
       * Setting2
       * ...
       * Puppet settings (the new RVX settings
           * RVXSetting1
           * RVXSetting2
           * ...
(i write `SettingN` the setting related to the stock YouTube)

the whole idea it's just jumping to a new menu of settings from the gear icon. This new menu has the YouTube' stock settings and the existing (old) RVX settings. not sure if i explained myself

**Comment by anddea** [comment]
Currently, it's a resource patch, not a bytecode patch, so no smali, it just edits the xml. Doing it with smali could be better probably. I don't have enough time to go through smali, but I do it from time to time.

**Comment by Aryan-Chauhan** [comment]
@anddea , I agree with @Francesco146 .

When "Account" & "Your data in YouTube" will be hidden, we will only be left with "ReVanced Extended" in the Settings list.
This will increase one step for opening RVX Settings & also, that empty page won't look good.

So, it's a better idea to "hook" the gear icon to directly open RVX Settings.

That will have 2 benefits:

1. No need to figure out how to hide "Account" & "Your data in YouTube"

2. Empty looking page with only one option "ReVanced Extended" will be avoided.

**Comment by Aryan-Chauhan** [comment]
> @anddea , I agree with @Francesco146 .
> 
> If "Account" & "Your data in YouTube" will be hidden, we will only be left with "ReVanced Extended" in the Settings list.
> This will increase one step for opening RVX Settings & also, that empty page won't look good.
> 
> So, it's a better idea to "hook" the gear icon to directly open RVX Settings.
> 
> That will have 2 benefits:
> 
> 1. No need to figure out how to hide "Account" & "Your data in YouTube"
> 
> 2. Empty looking page with only one option "ReVanced Extended" will be avoided.
> 
> Also, I have a question: 
> 
> Earlier, SB & RYD used to be in the page where YT stock settings are, but now they are moved inside RVX Settings because I requested for that (thanks!).
> 
> So, isn't it possible to "bring out" Ads, Player, Bottom Player, Seekbar, Shorts, Miscellaneous, etc to the stock YT Settings page? Or will that be a mess?

**Comment by Aryan-Chauhan** [comment]
This feature is now available in inotia00's RVX.
