### ISSUE TITLE
question: How do I tuck away "Parent settings" in the YouTube settings?

### ISSUE THREAD

**Issue by ChesterXXX** [anddea/revanced-patches#282]
### Application

YouTube

### Question description

I am successfully patching YouTube 19.11.38. For the "Tuck away preferences" patch I am able to get rid of almost all the redundant settings. I understand that settings like `General`, `Account` and `Your data in YouTube` cannot be hidden for now. But I am also unable to hide `Parent settings`. My current patch option is 

> Parent settings, Data saving, Autoplay, Video quality preferences, Watch on TV, Manage all history, Your data in YouTube, Billing & payments, Privacy, Try experimental new features, Purchases and memberships, Notifications, Captions, Connected apps, Live chat, Accessibility, About

I have tested on two accounts, one of which has YouTube premium. The `Parent settings` option only appears in the [premium account](https://github.com/anddea/revanced-patches/assets/4339171/158b8f53-2e6c-414e-ad60-be8dd64a25ec), but it does not appear in the [non-premium account](https://github.com/anddea/revanced-patches/assets/4339171/d9f0e4f6-a7e0-4f4b-9e4e-c68fd53a8d2c).

Looking at the [code](https://github.com/anddea/revanced-patches/blob/c48719b36d7799bd04da3cdfe67298fcb908a554/src/main/kotlin/app/revanced/patches/youtube/layout/settings/HideSettingsPrefsPatch.kt#L30C1-L52C6), it seems to me (with my very basic understanding of kotlin) that `Parent settings` is not even considered in the map that converts the text to actual ID. If this is intentional, I would understand as this is a very minor issue. Cheers!

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Yes, it is not added as an option. I just thought that if someone uses parent controls, they most likely won't want to hide this preference. I'll add it if possible. 

You can hide General settings.

**Comment by anddea** [comment]
It should hide parent settings too. Verify it and let me know.
