### ISSUE TITLE
question:  Change forward/backword seconds

### ISSUE THREAD

**Issue by benc2010** [anddea/revanced-patches#285]
### Application

YouTube

### Question description

Where is the "Double-tap to seek"?  I can't find in general.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by odkate** [comment]
> Double-tap to seek

This is configured just before patching, then there is no way to change it in the settings

**Comment by odkate** [comment]
> can't find in general

You need to look in the general settings of YouTube itself, not in the general settings of revanced

**Comment by benc2010** [comment]
I need to check first. Maybe something is wrong, my youtube missing the 'general' settings. Thank you for helping.

**Comment by anddea** [comment]
If you included General in `Tuck away preferences` then it's the reason why it's missing. Either exclude it or disable the patch itself.
