### ISSUE TITLE
bypass age restriction

### ISSUE THREAD

**Issue by speedlorenzo12** [anddea/revanced-patches#287]
### Application

YouTube

### Feature description

I'm aware of the hide age restriction setting (I think almost no one uses it because it's not very useful) at this point do the bypass like tubular with a warning notification

### Motivation

it is much more useful than hiding the age restriction notification and you don't have to go to another app to bypass the restrictions 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Ask this in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues).

**Comment by speedlorenzo12** [comment]
I cant do a feature request for YouTube

**Comment by anddea** [comment]
Request for YT Music, if it's the same, he will add it for YT as well.

**Comment by speedlorenzo12** [comment]
![Screenshot_2024-06-14-15-36-33-063_com.microsoft.emmx.png](https://github.com/anddea/revanced-patches/assets/111771663/cf76f949-652e-4651-8f96-06f9cdec7800)

**Comment by anddea** [comment]
> Request for YT Music

YT Music has this option as well. I don't think this feature is possible at this point anyway. Otherwise, it would be implemented already.
