### ISSUE TITLE
Bug (YouTube): Custom Heading not working

### ISSUE THREAD

**Issue by ayushTNM** [anddea/revanced-patches#289]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 19.11.38 patches 2.224.0 dev. 2

### Bug description

Including the custom branding heading patch does not set a custom heading. It most likely gets replaced by heading in custom app icon patch ( I am using mmt)

### Error logs

```shell
None
```

### Solution

Potential solution could be to add the custom branding icon unrelated settings (e.g. splash screen, heading) as settings for respective patches (e.g. mmt option for add splash screen patch and mmt option for custom branding heading patch)

### Device Environment

Android 14, pixel 7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you check in the latest dev, I renamed patch to custom wordmark header.
