### ISSUE TITLE
feat (YT) : Ability to hide back button in Shorts.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#29]
### Application

YouTube

### Feature description

Kindly add the ability to hide the back button in Shorts. It is located on top-left corner of shorts.

### Motivation

Earlier it was hide-able & provided a fully clean look. So, it should be brought back.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
![Screenshot_20240313-161417_YT-RE𝕏_🦖](https://github.com/anddea/revanced-patches/assets/109387456/67f4dc35-d195-47ec-998d-58ee874c1567)


I don't know how but it's already hidden on my shorts .
I'm using 19.09.x with anddea patches...
IG google already removed it 🤔🤔

**Comment by selfmusing** [comment]
> ### Application
> YouTube
> 
> ### Feature description
> Kindly add the ability to hide the back button in Shorts. It is located on top-left corner of shorts.
> 
> ### Motivation
> Earlier it was hide-able & provided a fully clean look. So, it should be brought back.
> 
> ### Acknowledgements
> * [x]  This issue is not a duplicate of an existing feature request.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  I have written the title and contents in English.

![Screenshot_20240313-161554_YouTube](https://github.com/anddea/revanced-patches/assets/109387456/047947b8-2762-45c8-91e1-22a0901711fb)


This is stock YouTube, it clears that google already removed back button from shorts :D in newer updates!!

**Comment by Aryan-Chauhan** [comment]
> ![Screenshot_20240313-161417_YT-RE𝕏_🦖](https://github.com/anddea/revanced-patches/assets/109387456/67f4dc35-d195-47ec-998d-58ee874c1567)
> 
> 
> I don't know how but it's already hidden on my shorts .
> I'm using 19.09.x with anddea patches...
> IG google already removed it 🤔🤔

Ohhh!

Actually I'm using v18.49.37 with latest anddea patches.

Will try & report I'm getting the desired results.

**Comment by selfmusing** [comment]
> > ![Screenshot_20240313-161417_YT-RE𝕏_🦖](https://private-user-images.githubusercontent.com/109387456/312420750-67f4dc35-d195-47ec-998d-58ee874c1567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzAzNjksIm5iZiI6MTcxMDMzMDA2OSwicGF0aCI6Ii8xMDkzODc0NTYvMzEyNDIwNzUwLTY3ZjRkYzM1LWQxOTUtNDdlYy05OThkLTU4ZWU4NzRjMTU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMTQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDczNTE3ODE2ZWJmODJjZmI1NGUzZDBiMDRkMWFlYWNkZDg4ZjE4MjQ2MDM2OGU4OGIzNTgxZjI0YTk1ODcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.towLCOpQExsHFKhX2BO8RKPiwseEE56kMzTU1hA71GI)
> > I don't know how but it's already hidden on my shorts .
> > I'm using 19.09.x with anddea patches...
> > IG google already removed it 🤔🤔
> 
> Ohhh!
> 
> Actually I'm using v18.49.37 with latest anddea patches.
> 
> Will try & report if I'm getting the desired results.

![Screenshot_20240313-171148_YT-RE𝕏_🦖](https://github.com/anddea/revanced-patches/assets/109387456/2bf090a7-830b-4179-b8fd-0939ac55cf62)

Inotia added this inform note ,because there was no way to hide that button earlier ...

I think now it is possible by comparing what google removed in the newer updates to get rid of that button 🤔🤔

**Comment by MondayNitro** [comment]
inotia removed the ability to hide back button because it caused the top toolbar to glitch/disappear and then the user had to restart youtube to get it back

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225

**Comment by Aryan-Chauhan** [comment]
This feature is now available in inotia00's RVX.
