### ISSUE TITLE
bug: youtube crashing

### ISSUE THREAD

**Issue by Cloudytfw1** [anddea/revanced-patches#297]
### Type

Error at runtime

### Tools used

Revancify

### Application

19.11.38

### Bug description

Youtube will crash after a few minutes
1. Launch youtube
2. Browse for a few minutes
3. Crash

https://drive.google.com/file/d/1HAiJi75ogP-TswTjNT2xblxqebnHZ9Qi/view?usp=drivesdk

### Error logs

```shell
Full logs:

https://drive.google.com/file/d/1Gb16mGthMHpL2maKxbRopLZIlMKJxGGW/view?usp=drivesdk
```

### Device Environment

Android version: 13
Os: funtouch
Model: y22s

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Cloudytfw1** [comment]
Its much more frequent now

**Comment by Cloudytfw1** [comment]
Its much more frequent now

**Comment by Cloudytfw1** [comment]
Its pretty much unusable now i tried reinstalling and patching it again but it got worse

**Comment by Cloudytfw1** [comment]
Im gonna switch to revanced and try it

**Comment by anddea** [comment]
Try deleting Revancify folder and reinstalling it. What patches version do you use? Does ReVanced work for you?

**Comment by Cloudytfw1** [comment]
Hi, I already reinstalled ReVanced and patched YouTube again, but it's gotten worse. How can I check which patch version I used? ReVanced works much better overall, but it still crashes occasionally. I've given it permission to run without battery optimization, which improved things, but it still has those crashes from time to time.

**Comment by anddea** [comment]
Try older version of YouTube. 

And I said to remove and reinstall Revancify (the patching tool), not YouTube. If you face crashes on both Revanced and RVX, then most likely it has to do something with some old files in Revancify folder.

Also don't forget to reboot your device when you face crashes, sometimes it helps.

**Comment by Cloudytfw1** [comment]
Ah, no, my mistake! I meant ReVancify. I already reinstalled it, but it doesn't work. I've also tried downgrading to YouTube version 19.09.xx and below, but it's still crashing.

**Comment by anddea** [comment]
Do you experience the same problem with ReVanced Manager? Test it and let me know.

**Comment by Cloudytfw1** [comment]
I think it's fixed

**Comment by Cloudytfw1** [comment]
I think battery optimization was the cause

**Comment by Anurag69** [comment]
> I think battery optimization was the cause

You fixed the issue by disabling the battery optimisation for Yt or microg?

**Comment by Cloudytfw1** [comment]
I fixed the issue by disabling battery optimisation for yt
