### ISSUE TITLE
Notification options 

### ISSUE THREAD

**Issue by yurirosas** [anddea/revanced-patches#303]
### Application

YouTube

### Question description

In the last update the settings have undergone changes in their design and structure, I noticed that the option to configure notifications is gone. Has it been moved?

I'm on the latest pre release: 2.224.0.dev2

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
They are removed by `Tuck away preferences` patch, you can modify it and select what you you want to hide. In dev2, Notifications option was brought back, but your options.json saved previous state where the patch hides Notifications too.
