### ISSUE TITLE
question & suggestion: deleted string

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#305]
### Application

YouTube

### Question description

If I patch with a jar containing xml with a deleted (non-existent) string, won't I get an error during patching?

I know it's annoying, but if there is a deleted string, could you please type it at the bottom of the updated-strings.xml?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Jar is compiled with relevant strings, so there should be no error, unless you mean something specific. 

If you use new strings file with old patches source then there will be error, but I see no use case how can that happen.

**Comment by anddea** [comment]
Why do you need deleted strings? 

In the latest release there's a commit that deleted some strings They are deleted automatically for all language folders at once by the python script in this repo, for some reason it totally rearranged Korean strings.xml, for other languages it just deleted only exact strings without moving anything. Not sure why it happened. Please check if previous strings have been corrupted.

**Comment by zerozero0022** [comment]
When a patch containing an incomplete Korean translation[new strings(non-existentstring) file & old patches source] was updated on RVX GitHub in the past(When I Wasn't a RVX Crowdin Proofreader), I replaced only XML in the Jar file and patched it using the computer, but I remember an error at that time.

It doesn't matter if there's no problem.
Thank you for your answer.

**Comment by anddea** [comment]
If you replace host XML file in a jar file there might be an error. But it's not the host strings.xnl, it's a language strings.xml, so if strings are missing or deleted there should be no problem because it'll just use original strings from host file. Unless there's something with formatting in language strings, there should be no errors.
