### ISSUE TITLE
bug(youtube/ryd): Dislikes may not be visible when using non English language if compact like button is enabled

### ISSUE THREAD

**Issue by n1cKz1** [anddea/revanced-patches#306]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube

### Bug description

Same issue as this: https://github.com/ReVanced/revanced-patches/issues/2962

### Solution

https://github.com/ReVanced/revanced-integrations/pull/603/commits/eeaeb49f2a562d2690dae184153c303a5b1c4368

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Added that solution in the latest dev release, test it and let me know.

**Comment by n1cKz1** [comment]
Works, thanks
