### ISSUE TITLE
feat(YouTube - Hide Shorts components): Hide Shop, Location and Save sound to playlist buttons

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#307]
### Application

YouTube

### Feature description

https://github.com/ReVanced/revanced-patches/commit/5210ac431c191987264865bf8e789ea9f3fdd360

• Location Button

![Screenshot_20240413-073010_YouTube~01](https://github.com/anddea/revanced-patches/assets/163995091/ddd7d32b-eb0b-47a3-8204-d0a24dd245d9)

• Save sound to playlist button
(Playlist name: Sounds from Shorts)
(Right button in the bottom image)

![Screenshot_20240413-073027_YouTube~01](https://github.com/anddea/revanced-patches/assets/163995091/c1cbff36-5e26-43a0-bb2f-ac5627a1a9af)

• Shop button - Displayed in the same place as the location button.

### Motivation

:)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Added in the latest dev release, test it and let me know.

**Comment by zerozero0022** [comment]
Not working.

The source on the ReVanced GitHub seems to be just "add switches". (not source for operation)

**Comment by zerozero0022** [comment]
+
When "Hide Shorts shelf in home feed" is enabled,  following shelves are also hidden.
• Hide Shorts shelf in related video
• Hide Shorts section in description (Shorts remixing this video)

**Comment by anddea** [comment]
What do you mean hidden in revanced app? 

These new options are A/B tests, not everyone can see them now, me included. But if you see any of those buttons you can test.

**Comment by zerozero0022** [comment]
A few hours ago it worked in revanced but now it doesn't work in both, my account seems to have been A/B tested, I've requested that revanced feature in your app and I'm sorry I can't test your app now.

**Comment by anddea** [comment]
I see, probably I should move it under "experimental" subsection or create new "A/B test" subsection.
