### ISSUE TITLE
suggestion: Exclude 'Hide voice search button' from the default patch options

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#310]
### Application

YouTube

### Suggestion description

I know that 'Enable song search' is not available if I patch RVX including 'Hide voice search button'.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you post this idea here

https://github.com/anddea/revanced-patches/discussions/308
