### ISSUE TITLE
Resampler for Youtube/Music

### ISSUE THREAD

**Issue by Gl17chV** [anddea/revanced-patches#313]
### Application

YouTube Music

### Feature description

- YouTube
- YouTube Music

A patch to modify the pitch, just like NewPipe.

### Motivation

Recently, I’ve been experiencing diplacusis, and it’s becoming torture to watch videos and especially listen to music. Unfortunately, there isn’t an Android app that globally modifies audio pitch. Since YouTube is the platform I use the most, it would be a blessing to have this feature for those of us who suffer from this or for those who simply want more control over the audio

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This feature is complex to implement for such project as ReVanced as it takes a lot of effort, so no one use it at the end. NewPipe is a separate app, in ReVanced there's a big layer of reverse engineering. You can reopen this issue in inotia's repo for YouTube Music. But I guess no one will be able or will want to implement it.
