### ISSUE TITLE
bug: Hide notifications button doesn't work

### ISSUE THREAD

**Issue by fredrik1102** [anddea/revanced-patches#314]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube 19.11.38

### Bug description

Settings > ReVanced Extended > Navigation > Hide notifications button > ON

Hide notifications button doesn't work in v2.224.0-**dev.3** and v2.224.0-**dev.4**
It worked fine in v2.224.0-**dev.2** but not in the two newer versions dev.3 and dev.4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Should work now with the latest dev release.
