### ISSUE TITLE
feat(YouTube): Bump support version 19.12.41 - 19.13.37

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#315]
### Application

YouTube

### Feature description

https://github.com/rufusin/revanced-patches/commit/278b5b4a8e9a5ed6237bdbdf075a016284c32324

### Motivation

:)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
consider closing this, now the support is being brought up to v19.14.43
