### ISSUE TITLE
bug(youtube/hide-suggestions-shelf): match official ReVanced code

### ISSUE THREAD

**Issue by n1cKz1** [anddea/revanced-patches#317]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube

### Bug description

Now that official ReVanced implemented a proper way to hide the suggestions shelves (or horizontal shelves as they call it there), there's no need for workarounds like BrowseID or issues like playlist shelves being hidden.

### Solution

All commits related to this:

https://github.com/ReVanced/revanced-patches/commit/9ae0650c0005d882299996aa442410bab4261395

https://github.com/ReVanced/revanced-integrations/commit/fedace02fd5c443ef37dcf77253438b041f4c3f9

https://github.com/ReVanced/revanced-integrations/commit/c5d38a7e0791ebb8fe59397fff959cc94e0a7aed

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Thank you for sharing it. 

They removed hideBreakingNews() function, but it is used (or was used) for tablet and old versions. Not sure if it's still relevant but I kept that for now.

I cannot see suggestions shelves whether this feature is turned on or not, can you test latest dev and let me know if it works properly.

**Comment by n1cKz1** [comment]
Seems to work yes. Also could you remove it from experimental settings section? It also doesn't require app restart anymore since it hides litho components

**Comment by anddea** [comment]
Sure, will do that.

**Comment by n1cKz1** [comment]
Could you also add `horizontal_tile_shelf.eml` to the Suggestion Shelf filters? It's kind of a new component that is part of the suggestions shelf

**Comment by anddea** [comment]
> Could you also add `horizontal_tile_shelf.eml` to the Suggestion Shelf filters? It's kind of a new component that is part of the suggestions shelf

Done.
