### ISSUE TITLE
bug: seekbar thumbnail not showing in live videos 

### ISSUE THREAD

**Issue by Mhmodhaha** [anddea/revanced-patches#318]
### Type

Error at runtime

### Application

V19.11

### Bug description

The seekbar thumbnail isn't showing in live videos that are currently live but it  appears normally on the same video after the live ends 

### Error logs
Nothing
_No response_

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This is the behavior of the original YouTube. So it's not a ReVanced or RVX bug.

**Comment by Mhmodhaha** [comment]
> This is the behavior of the original YouTube. So it's not a ReVanced or RVX bug.

Oh i didn't know that sorry for bothering you 🫡
