### ISSUE TITLE
question: next patch is stable version?

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#319]
### Application

YouTube

### Question description

I can't ask you privately because I don't know your messenger ID, so I ask you on GitHub.

Is next patch a stable version?
I know the translation files were replaced about 16 hours ago.
I haven't uploaded the Korean translation to GitHub yet.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I want to release this week. But not sure how it will go. Do you face any issues, crashes?

**Comment by anddea** [comment]
Okay, will do that.

**Comment by anddea** [comment]
I added new options, test it and let me know if it works fine.
