### ISSUE TITLE
suggestion: "Premium Header"

### ISSUE THREAD

**Issue by hphp22f** [anddea/revanced-patches#32]
### Application

YouTube

### Suggestion description

I am useing CLI,, how to add "Premium Header"

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
Include "header switch" patch
