### ISSUE TITLE
feat: Shorts Hide subscribe button 

### ISSUE THREAD

**Issue by hphp22f** [anddea/revanced-patches#320]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v: 19.11.38

### Bug description

Hide subscriptions button is enable ,but it's not working
![Screenshot_2024-04-16-16-34-36-787_com google android youtube](https://github.com/anddea/revanced-patches/assets/151181919/a5096ccb-f38e-4e67-911f-d80579122b12)

### Device Environment

Android 12 MIUI 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Subscriptions button appears on top, this is not subscriptions button, it's a subscribe button.

**Comment by anddea** [comment]
Actually subscribe button was included in `Hide subscriptions button` before, I only noticed it today in code. It didn't work because it's inside new element now. I added new separated patch hide Subscribe button and Paused overlay buttons.

**Comment by hphp22f** [comment]
### okay dear

**Comment by anddea** [comment]
There's no "Hide subscriptions button" anymore, instead there are 2 options in settings now: Hide subscribe button and Hide paused overlay buttons (Subscriptions and Live)
