### ISSUE TITLE
bug: hide subscriptions button

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#325]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube    v19.11.38
patch     　2.224.0-dev.６

### Bug description

`hide subscriptions button` is enabled, the live and subscribe buttons will also be hidden.

![Screenshot_2024-04-17-10-22-17-809_anddea youtube](https://github.com/anddea/revanced-patches/assets/91464996/676d6161-41ce-43b1-a98c-7d4c8aa5512a)

### Device Environment

android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by n1cKz1** [comment]
Might as well just rename the setting to "hide paused overlay buttons". Separating them is not recommended as iirc the litho component strings of these buttons get updated fairly often so they would break regularly

**Comment by odkate** [comment]
> subscriptions

🙄 https://github.com/anddea/revanced-patches/issues/320#issuecomment-2059118382

**Comment by anddea** [comment]
I separated Subscribe and Pause overlay buttons in the latest release.
