### ISSUE TITLE
question: What strings have been removed in the new version?

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#331]
### Application

YouTube

### Question description

What strings have been removed in the new version?

revanced_hide_suggestions_shelf_method_title
revanced_hide_suggestions_shelf_method_summary_on
revanced_hide_suggestions_shelf_method_summary_off

and...

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by zerozero0022** [comment]
+ Another question:

<string name="">"... \' \' ..."</string>

If I use this, will you get a compile error?

**Comment by zerozero0022** [comment]
• Except for player components(related video, playlist, suggested video to play next) and search results, thumbnails that you have entered through the tab may appear as set thumbnails [e.g. feeds, playlists (no bottom player), channel video thumbnails ...]

I want to put this in, but I don't know where to put it. Should I not?

**Comment by Francesco146** [comment]
should be fixed with the latest patch

**Comment by zerozero0022** [comment]
> should be fixed with the latest patch

I'm translating and modifying Korean with an xml file (dev.1 file) downloaded to my phone, but I don't know which strings were removed in the latest version.

**Comment by zerozero0022** [comment]
> > < string name="" >"... \ ' \ ' ..."< /string >
> 
> You don't have to escape apostrophes inside double quotes.

okay, thanks

**Comment by anddea** [comment]
You don't have to worry about that, I can delete those strings later in an automated way. But it would be better if you just updated from latest dev. Because that automated string rearranged the whole filee and next time will be the same if you change it back.
