### ISSUE TITLE
suggestion: More Coustom Branding Icon YouTube

### ISSUE THREAD

**Issue by gigachaand** [anddea/revanced-patches#334]
### Application

YouTube

### Suggestion description

I want to see more Coustom Branding Icon..
I know we can added Coustom Branding Icon through patch option but there is little bit problem in there...
Splash screen and monochrome icon becoming YouTube default....

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
consider renaming this issue with: "Apply Custom Branding Icon to splash screen". what do you mean with "monochrome icon"?

**Comment by gigachaand** [comment]
@Francesco146 
![images](https://github.com/anddea/revanced-patches/assets/96541364/cfc141a5-ca1a-49c6-b7db-ee4787408e61)

**Comment by anddea** [comment]
In order to add any new branding icons, a specific folder with [these files](https://github.com/anddea/revanced-patches/tree/dev/src/main/resources/youtube/branding/afn_blue) must be provided.
