### ISSUE TITLE
bug(youtube/shorts): hide paid promotion banner doesn't work (a/b test)

### ISSUE THREAD

**Issue by n1cKz1** [anddea/revanced-patches#338]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube (general)

### Bug description

There's an a/b test going around with a new type of paid promotion banner (litho)

![Screenshot_2024-04-18-14-23-03-128-edit_anddea youtube](https://github.com/anddea/revanced-patches/assets/107653639/4c271e77-f353-453a-bc9d-87fa4aa3ffe8)

### Solution

Litho component name is `reel_player_disclosure.eml`

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Fixed.
