### ISSUE TITLE
bug(youtube/spoof-app-version): Remove broken versions

### ISSUE THREAD

**Issue by NicKz101** [anddea/revanced-patches#339]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube (general)

### Bug description

Versions 16.08.35 and 17.08.35 no longer work server-side. They should be removed. But instead of 17.08.35, 17.33.42 can be used for old UI layout, that version still works for now

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Done
