### ISSUE TITLE
feat: (YT) Remove YouTube Stock Settings

### ISSUE THREAD

**Issue by Francesco146** [anddea/revanced-patches#34]
### Application

YouTube

### Feature description

Remove this stock settings from the settings page (can't do that by a toggle, i get it. but a patch during compile time as I do that with ApkTool):
* Your data in YouTube
* Try experimental new features
* Purchases and memberships
* Billing & payments
* etc...

![Screenshot_20240312_192850_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/a3e78dad-d51c-4615-80bc-ce7f1abba3c7)
![Screenshot_20240312_192853_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/ddf18204-46a4-4b15-9572-0d6159d1d4d1)

### Motivation

Provides cleaner look to YouTube. Debloat the settings page.

Might work good along side to #28. also, might be a reasonable alternative to the extremist #22 .

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
which xml do you edit with apktoolm to remove those settings?

**Comment by Aryan-Chauhan** [comment]
Bro, meaning of " extremist #22 " ?

**Comment by selfmusing** [comment]
💀 That day isn't far when you guys will ask for a patch to remove YouTube from YouTube app 😭

**Comment by Francesco146** [comment]
> 💀 That day isn't far when you guys will ask for a patch to remove YouTube from YouTube app 😭

the ghostly [null] App :)

**Comment by Aryan-Chauhan** [comment]
> > Bro, meaning of " extremist #22 " ?
> 
> don't take this as an offence, but that issue is trying to get right of *all* settings, that contains pretty useful tabs, not considering that even ReVanced's settings their self need those to work (e.g. the autoplay one). ReVanced is not handling all of these settings, for example:
> * General
> * Background
> * Notifications
> * ...
> 
> And it's good as it is, removing them is quite '_extremist_', and would remove functionality to the final product. something in between would be preferable in my opinion

Actually, I didn't ask for hiding all settings.

I asked for the "possibility" of hiding all of them "one-by-one". Just like "Hide Account Menu" feature where you have to type what you want to hide.

Similarly, if someone don't want to hide General, Autoplay, About, etc, then they simply won't type them.

**Comment by Francesco146** [comment]
> I asked for the "possibility" of hiding all of them "one-by-one". Just like "Hide Account Menu" feature where you have to type what you want to hide.

my bad, that's not what I understood from your issue. just straight up think about how this patch can possibly be implemented. Then if that's what you meant, I'm agreeing with you.

> Similarly, if someone don't want to hide General, Autoplay, About, etc, then they simply won't type them in the proposed "Hide Settings Menu Components" feature.

I'm fairly sure the goal you want to achieve is not possible with a Runtime patch, it should work with a compile time patch with some options in the json format.

**Comment by anddea** [comment]
Added in the latest dev.
