### ISSUE TITLE
question: keyword filter

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#340]
### Application

YouTube

### Question description

I'm also working on the official ReVanced Korean translation, and it says "Videos in the home tab are filtered by keywords"... I'm not sure if it's a tab or a feed.

Is your source different from ReVanced's?

• Feed - Filters only feed videos
• Tab - Filters feed videos, player videos (related videos, playlists videos, next play videos...), channel profile videos, etc. (Excluded search results and comment sections)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It does the same as original ReVanced, maybe different strings.

**Comment by zerozero0022** [comment]
Original ReVanced 
[YouTube - Spoof device dimensions: Warn about potential performance issues]

https://github.com/ReVanced/revanced-patches/commit/9d6f305b7c923e62b89581d221fedbe1e3f81835

https://github.com/ReVanced/revanced-integrations/commit/786ac9d2b71886964454fcb748e656d1beed1964

Device dimensions spoofed\n\nHigher video qualities might be unlocked but you may experience video playback stuttering, worse battery life, and unknown side effects

**Comment by zerozero0022** [comment]
it can hide channel profile video on home feed by keyword.

**Comment by anddea** [comment]
I don't think so, although if it detects channel profile videos as selected tab for which this option is enabled, maybe it can hide it.

**Comment by zerozero0022** [comment]
Fullscreen ads are hidden\n\nThis feature is only available for older devices

This String is the String that was replaced in the original ReVanced Crowdin.
