### ISSUE TITLE
Trending Search still showing

### ISSUE THREAD

**Issue by quik-dusk** [anddea/revanced-patches#342]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v19.11.38

### Bug description

Trending searches on pressing search bar showing, even after selecting the respective patch.

![Screenshot_2024-04-15-22-21-10-315_anddea youtube](https://github.com/anddea/revanced-patches/assets/86847643/f805658d-7409-4af7-9376-e6ac7e21aa4c)
![Screenshot_2024-04-19-10-33-36-662_com termux-edit](https://github.com/anddea/revanced-patches/assets/86847643/fe1d3cac-3ba3-4907-a597-e2194bc30194)
![Screenshot_2024-04-19-10-34-29-612_anddea youtube-edit](https://github.com/anddea/revanced-patches/assets/86847643/dcc4b019-75ee-4161-a83a-94efa5cdccc0)

### Device Environment

HyperOS 1.0.7.0.UNLINXM on Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Is your watch history off?

Because they also came back for me when I had 0 videos in watch history.

Now, I added 1 video to watch history & disabled it again. Now, it is fixed.

I only get search recommendations when I type something.

Do above things after clean-installing latest patches RVX, then inform us.

**Comment by quik-dusk** [comment]
Yes, I do have my watch as well as search history turned off.

**Comment by Aryan-Chauhan** [comment]
> Yes, I do have my watch as well as search history turned off.

So, fixed or not?

**Comment by quik-dusk** [comment]
Yes I fixed, but I don't like to keep my search and watch history turned on.

**Comment by Aryan-Chauhan** [comment]
> Yes it fixed, but I don't like to keep my search and watch history turned on. 

I never said you have to keep your search & watch history on. You just have to keep 1 video in your watch history, then you can disable watch history.

You did not read my last comment properly.

**Comment by quik-dusk** [comment]
My bad, let me try that again.

**Comment by quik-dusk** [comment]
> > Yes it fixed, but I don't like to keep my search and watch history turned on.
> 
> I never said you have to keep your search & watch history on. You just have to keep 1 video in your watch history, then you can disable watch history.
> 
> You did not read my last comment properly.

Yeah it works that way, but then again my home feed starts showing videos which I don't want for distractions, so I had to delete even that 1 video from history as well. I request if it's possible to remove trending searches even without keeping a single video in history.

**Comment by quik-dusk** [comment]
> > > > Yes it fixed, but I don't like to keep my search and watch history turned on.
> > > 
> > > 
> > > I never said you have to keep your search & watch history on. You just have to keep 1 video in your watch history, then you can disable watch history.
> > > You did not read my last comment properly.
> > 
> > 
> > Yeah it works that way, but then again my home feed starts showing videos which I don't want for distractions, so I had to delete even that 1 video from history as well.
> > I request if it's possible to remove trending searches even without keeping a single video in history.
> 
> If you don't want videos on your home page, just hide Home Tab by going into Settings/Navigation/Hide Home Tab

Yeah I know that, but once you're in any tab, be it library or notification, etc, once you press back after being at the default tab, the home Tab comes again. Try that.

**Comment by Aryan-Chauhan** [comment]
> > > > > Yes it fixed, but I don't like to keep my search and watch history turned on.
> > > > 
> > > > 
> > > > I never said you have to keep your search & watch history on. You just have to keep 1 video in your watch history, then you can disable watch history.
> > > > You did not read my last comment properly.
> > > 
> > > 
> > > Yeah it works that way, but then again my home feed starts showing videos which I don't want for distractions, so I had to delete even that 1 video from history as well.
> > > I request if it's possible to remove trending searches even without keeping a single video in history.
> > 
> > If you don't want videos on your home page, just hide Home Tab by going into Settings/Navigation/Hide Home Tab
> 
> Yeah I know that very well and have hidden that, but once you're in any tab, be it library or notification, etc, once you press back after being at the default tab, the home Tab comes again. Try that.
> 
> It just hides the home Tab not the video on it. The only way to remove it is to delete any videos in history, as it's basically the recommendations based on your history.

Yes, I've noticed that as well.

But it's not a problem for me because I don't have a habit of navigating everywhere by pressing the back button.

I just click on whatever tab I want to go to.

**Comment by Aryan-Chauhan** [comment]
@anddea Hello.

New bug report:

"Hide Trending Searches" doesn't work when watch history has zero videos.

At least, one video should be in watch history for "Hide Trending Searches" to work.

If possible, please fix it.

Currently, I'm using a workaround, putting one video in watch history, then disabling it.

**Comment by quik-dusk** [comment]
> > > > > > Yes it fixed, but I don't like to keep my search and watch history turned on.
> > > > > 
> > > > > 
> > > > > I never said you have to keep your search & watch history on. You just have to keep 1 video in your watch history, then you can disable watch history.
> > > > > You did not read my last comment properly.
> > > > 
> > > > 
> > > > Yeah it works that way, but then again my home feed starts showing videos which I don't want for distractions, so I had to delete even that 1 video from history as well.
> > > > I request if it's possible to remove trending searches even without keeping a single video in history.
> > > 
> > > 
> > > If you don't want videos on your home page, just hide Home Tab by going into Settings/Navigation/Hide Home Tab
> > 
> > 
> > Yeah I know that very well and have hidden that, but once you're in any tab, be it library or notification, etc, once you press back after being at the default tab, the home Tab comes again. Try that.
> > It just hides the home Tab not the video on it. The only way to remove it is to delete any videos in history, as it's basically the recommendations based on your history.
> 
> Yes, I've noticed that as well.
> 
> But it's not a problem for me because I don't have a habit of navigating everywhere by pressing the back button.
> 
> I just click on whatever tab I want to go to.

It's not a question of habit bro. It's a natural way of closing an app. You press back button to close an app and the last tab happens to be the home Tab no matter which tab you're on our which one is set to default.

**Comment by Francesco146** [comment]
the issue shall remain open since it's reproducible and it's not how it's supposed to behave. 

OT but: those giant reply trees are really concerning xD. you don't actually need to quote the whole comment just to reply a sentence 😁

**Comment by quik-dusk** [comment]
Really the thread looks hilarious 😂 this you can say a habit of mine - a bad one indeed I developed from replying in YouTube comments.
