### ISSUE TITLE
suggestion:  Adds Custom Branding Header

### ISSUE THREAD

**Issue by CheesePancake** [anddea/revanced-patches#343]
### Application

YouTube

### Suggestion description

I'd love to see custom header on youtube as well, as for the text just "Premium" or "youtube" is fine, so it will match YTM

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
YouTube has custom header, it's included to all custom branding icons except for Revancify icons.
