### ISSUE TITLE
bug: Default video quality is only compatible with version up to19.09.37

### ISSUE THREAD

**Issue by fredrik1102** [anddea/revanced-patches#347]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube 19.11.38 + dev.10

### Bug description

Using your dev.10 version and YouTube 19.11.38 **with** --force gives error like this issue here: [https://github.com/anddea/revanced-patches/issues/346](https://github.com/anddea/revanced-patches/issues/346)

And **without** --force : WARNING: Default video quality is incompatible with version 19.11.38. This patch is only compatible with version 18.48.39, 18.49.37, 19.01.34, 19.02.39, 19.03.36, 19.04.38, 19.05.36, 19.06.39, 19.07.40, 19.08.36, 19.09.37

Any particular reason for "Default video quality" not to support YouTube 19.11.38 ?

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
How do you get that error and I don't? I just didn't add compatibility for 19.11 but it should be compatible.
