### ISSUE TITLE
bug: The issue of not exiting when you click the YouTube Premium subscription button. 

### ISSUE THREAD

**Issue by zebra8228** [anddea/revanced-patches#348]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.11.38, Patch 2.224.0 dev.8~

### Bug description

The problem is that after running the ReVanced Extended app, you do not exit when you press the sign-up button as shown in the video. (The ReVanced Extended app in the video is in Korean and the video quality has been lowered so it is very broken. Sorry) 

https://github.com/anddea/revanced-patches/assets/166817342/f26a33e8-38ad-4716-a6a6-8b8fcd6e0016

### Device Environment

Android 14, One UI 6.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I guess it comes from original YouTube, when you click external in-app links it does this. Did you check this in stock YouTube app?

**Comment by zebra8228** [comment]
> I guess it comes from original YouTube, when you click external in-app links it does this. Did you check this in stock YouTube app?

I checked and there is no problem.

**Comment by Francesco146** [comment]
although i can reproduce the issue, i can suggest two workarounds:
1. click in the bottom navigation bar to exit this loop page
2. remove completely that button by entering the exact text (`Get YouTube Premium` in your language) in:


* Settings 
  * ReVanced Extended 
    * General 
      * Edit account menu filter


like this:
![Screenshot_20240423_000639_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/754a5d0d-0f0e-4060-8173-49c3a37c50de)

**Comment by Francesco146** [comment]
this issue is reproducible even in RVX

**Comment by anddea** [comment]
Report to intoia instead.
