### ISSUE TITLE
Any Tutorial On How To Use Your ReVanced Patches 

### ISSUE THREAD

**Issue by Tronak007** [anddea/revanced-patches#35]
I Don't Know How To Use This ReVanced - Patches To Patch Youtube,

Can You Provide Any Tutorial On How To Build YT ReVanced With Your Patches On Android

**Comment by Francesco146** [comment]
there's plenty of documentation already in the Telegram groups. have you searched there?

**Comment by Tronak007** [comment]
> there's plenty of documentation already in the Telegram groups. have you searched there?

No I Didn't Searched On Telegram, Can You Provide Any Link,

**Comment by Tronak007** [comment]
> First download RVX Manager from inotia00's GitHub repo, and install it.
> 
> Then go to Settings, then Sources, change patches organization & integrations organization to "anddea", hit OK, then restart the app.
> 
> But, personally I prefer patching with ReVancify (another tool to patch apps).

Thank You For The Help,

**Comment by Francesco146** [comment]
> > there's plenty of documentation already in the Telegram groups. have you searched there?
> 
> No I Didn't Searched On Telegram, Can You Provide Any Link,

https://t.me/revanced_extended_chat

consider closing this issue if you solved your problem :)

**Comment by Tronak007** [comment]
> > > there's plenty of documentation already in the Telegram groups. have you searched there?
> > 
> > No I Didn't Searched On Telegram, Can You Provide Any Link,
> 
> https://t.me/revanced_extended_chat
> 
> consider closing this issue if you solved your problem :)

Yeah Sure I'm Closing This Issue And Thanks For The Help
