### ISSUE TITLE
feat: Ability to change package triggering `Listen with YouTube Music` option

### ISSUE THREAD

**Issue by Rairof** [anddea/revanced-patches#350]
### Application

YouTube

### Feature description

This patch should add the ability of you to change or add package into YouTube `Listen with YouTube Music` option.
![Screenshot_20240422-061100](https://github.com/anddea/revanced-patches/assets/107706560/d7056a6f-d8ec-4ee6-9e87-a77d9aa35b60)

### Motivation

It's useful as the option's default action is that you are directed to google store YouTube Music page when you already got modded YouTube Music installed. This patch solves this inconvenience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It's already available in Settings > Extended > Flyout menu > Edit feed flyoit filter, type the full text of the item.

**Comment by Rairof** [comment]
https://github.com/anddea/revanced-patches/issues/350#issuecomment-2068207686
I'm sorry but what am I supposed to type there?

**Comment by anddea** [comment]
Oh, I thought you wanna hide it. Sorry for misreading/misunderstanding.

**Comment by Rairof** [comment]
https://github.com/anddea/revanced-patches/issues/350#issuecomment-2070705445
It's a bit different from that post. I am asking for being able to configure what YouTube music app is opened when you click on `Listen with YouTube Music` button rather than just open RVX YouTube music. It gives us the option to open whatever ytm app we have when we got multiple ones installed.

**Comment by anddea** [comment]
Request this feature in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues). He does not accept feature requests for YT, but maybe he'll do it one day.
