### ISSUE TITLE
bug: (YT) Padding over video title in fullscreen mode

### ISSUE THREAD

**Issue by Francesco146** [anddea/revanced-patches#353]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v19.14.43

### Bug description

Since version v19.05.36 i noticed a padding over the video title, when entering fullscreen mode. When i was on version v19.05.36 i often cleaned the app's data and sometimes it worked; But now no method is able to solve this.

Here's the images:

> Broken one, RVX on latest dev patches (v2.224.0_dev12-v0.151.0_dev10)
![Screenshot_20240422_213630_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/f18b4b7d-80c3-4098-9ad5-9c0a87f325bf)

> Official YouTube v19.15.36
![Screenshot_20240422_214530_YouTube](https://github.com/anddea/revanced-patches/assets/49027005/f146d91e-2374-4e52-95cb-320941eab940)

### Error logs

```shell
None
```

### Solution

No solution.

### Additional context
None

### Device Environment

Android 14

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I patched multiple versions and I have no this issue in any of them. What could be the reason?

**Comment by Francesco146** [comment]
> I patched multiple versions and I have no this issue in any of them. What could be the reason?

given that in the past it was resolved with a total cleaning of the data, i believe it's A/B testing. not sure how to investigate any further. I tried turning on and off all the stuff related to fullscreen but nothing is happening. 

the only clue i have is that it's related to my notifications top bar of my phone. the fact that the hitbox of the title in fullscreen has a padding at the top exactly equal to the size of my notification bar made me think about this. I'll share this screenshot too:

![Screenshot_20240422_232733_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/332a1790-8ea5-4c1b-b9ef-da3e7569f9ec)

my phone cuts the screenshot so it cuts off the notification bar, but it's there, and it's height is the same as the red part in this issue's description.

**Comment by ILoveOpenSourceApplications** [comment]
Enable tablet mode causes a similar issue. Do you have it turned on?

**Comment by ILoveOpenSourceApplications** [comment]
You can see it [here](https://github.com/ReVanced/revanced-patches/issues/2180) & [here](https://github.com/YT-Advanced/ReX-patches/issues/146).

**Comment by Francesco146** [comment]
> Enable tablet mode causes a similar issue. Do you have it turned on?

i do! i can confirm that that caused my issue. thanks for providing the related issues! who could have guessed that would cause this problem! thank you, at least now i know what is it due to.

**Comment by Francesco146** [comment]
should i close this as duplicate of those issues @anddea ? I'm concerned that those two issues haven't been considered much recently though

**Comment by anddea** [comment]
As you want, I'll take a look later what can be done to fix this issue.

**Comment by Rairof** [comment]
> I patched multiple versions and I have no this issue in any of them. What could be the reason?

Try enabling tablet mode and check. I'm pretty sure it's tablet mode causing this issue @anddea

**Comment by Francesco146** [comment]
fixed in RVX
