### ISSUE TITLE
feat(YouTube - Shorts): Add Playback Speed button for Shorts

### ISSUE THREAD

**Issue by VrtxDesign** [anddea/revanced-patches#355]
### Application

YouTube

### Feature description

The Playback speed for Shorts can be adjusted by modifying default playback speed but it's is not possible to adjust playback speed of shorts manually without changing default playback speed for all.

### Motivation

Some shorts are incredibly slow yet still valuable to watch, while for those who are quick, their speed should be faster.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
dup of https://github.com/anddea/revanced-patches/issues/763
