### ISSUE TITLE
feat: Whitelist ADs option for some specific channels which we want to support 

### ISSUE THREAD

**Issue by TheLegendaryPhoenix08** [anddea/revanced-patches#356]
### Application

YouTube

### Feature description

Add option to Whitelist ads for specific channels with Keywords as well in the Whitelist Settings, as it would be a great way to support some legible content creators.

### Motivation

.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Request it in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues)
