### ISSUE TITLE
feat: Make the Snack Bar Dark for Dark Mode Users.

### ISSUE THREAD

**Issue by TheLegendaryPhoenix08** [anddea/revanced-patches#357]
### Application

YouTube

### Feature description

Currently, the Snack Bar is white for Dark Mode Users, in a very old release of ReX, it was dark, PFA :

Current :

![image](https://github.com/anddea/revanced-patches/assets/69076256/4d4c4b69-2057-4639-99b7-b566747f4e24)

Should Be in Future :
![image](https://github.com/anddea/revanced-patches/assets/69076256/9979aa31-89cc-4972-9036-dcdab3e36e90)

### Motivation

Because it will take a Eon for YouTube to do so

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Gud one.

**Comment by anddea** [comment]
I didn't add primary color though, because it gets mixed and not visible. Instead I use a little lighter color for snackbar.

**Comment by Vipin2003** [comment]
![Screenshot_20240507_213743](https://github.com/anddea/revanced-patches/assets/93650504/80631ad2-052b-48d5-b131-7ec9e6bfdcf6)

Now the Snackbar looks cool, after additional patches. Thamks anddea
