### ISSUE TITLE
question: Regarding New Visual Preferences Icons

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#358]
### Application

YouTube

### Question description

With the new visual preferences icons feature: selectable icons for Extended preference, how to set it on CLI or GitHub-based ReVanced builder that using `config.toml` file?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
They all have options.json file, there you will find ExtendedIcon key which by default has "Extension", but you can change it to "Gear", "ReVanced", "ReVanced Colored", or "Custom branding icon".

**Comment by AbakNacchan** [comment]
> They all have options.json file, there you will find ExtendedIcon key which by default has "Extension", but you can change it to "Gear", "ReVanced", "ReVanced Colored", or "Custom branding icon".

Do I need to add 'Custom Branding Icon' on `comfig.toml` file?

**Comment by anddea** [comment]
I'm not familiar with config.toml, can you send contents of it?

**Comment by AbakNacchan** [comment]
> I'm not familiar with config.toml, can you send contents of it?

It's just like this. The json file also configured too, I choose gear icon but it seems nothing happened.

```
[YouTube]
app-name = "YouTube"
build-mode = "both"
included-patches = "'Add splash animation' 'MaterialYou' 'Remove player controls background' 'Enable slide to seek'"
excluded-patches = "'Custom branding name YouTube' 'Announcements' 'Enable debugging' 'Change player flyout panel toggles'"
version = "19.14.43"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"
```

**Comment by anddea** [comment]
No, it's not the file to edit patch options. There should be options.json or revanced-options.json. I'll check builder later and will let you know.

**Comment by anddea** [comment]
I checked, there's an `options.json` file in the same directory where builder is located, there you can find and edit this key `ExtendedIcon`
