### ISSUE TITLE
bug: Space padding in chatbox on live chat in Livestreams

### ISSUE THREAD

**Issue by Rairof** [anddea/revanced-patches#360]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.14.43

### Bug description

Space existing besides chatbox in love chat during livestreams.

![Screenshot_20240424-105148](https://github.com/anddea/revanced-patches/assets/107706560/c0a8571d-73af-4f9d-b84c-0c161ae3827a)

### Error logs

```shell
N/A
```

### Solution

Let the chatbox occupy the space when not typing and send icon when typing

### Additional context

N/A

### Device Environment

Android 14, Project Elixir 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can't reproduce this, any steps, screen record?

**Comment by Rairof** [comment]
I can't seem to reproduce this issue anymore, I'll reopen this issue if I encounter it again with screen record next time. For now I'm closing this

**Comment by anddea** [comment]
> I can't seem to reproduce this issue anymore, I'll reopen this issue if I encounter it again with screen record next time. For now I'm closing this

Maybe it was old UI before app restart, some elements show empty space instead of removing it for old UI (e.g. hiding flyout menus' elements leave empty space for old UI).
