### ISSUE TITLE
bug (YT) : Make "Double-tap to seek preferences" an importable & exportable setting.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#361]
### Application

YouTube

### Feature description

Hi. Please make "Double-tap to seek preferences" an importable & exportable setting, so that user doesn't have to set it up again when they do a clean installation.

![Screenshot_2024-04-19-21-17-05-64_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/b3fb7c11-fcd6-4b54-ba82-c9e847a835ef)

### Motivation

It is a RVX-specific setting, so it's logical to make it a part of exported settings file/text. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AbakNacchan** [comment]
Why don't ask for `Backup Settings` like thee whole settings of RVX feature instead?

**Comment by Aryan-Chauhan** [comment]
> Why don't ask for `Backup Settings` like thee whole settings of RVX feature instead?

That's what I asked for, sir.

Just the choice of words was different.

**Comment by anddea** [comment]
This is an internal setting, very different from RVX settings, not sure how to inject it. Your best chance to reopen in inotia's repo, he doesn't accept feature requests though.
