### ISSUE TITLE
suggestion: change how "hide collapse button patch" is implemented

### ISSUE THREAD

**Issue by MondayNitro** [anddea/revanced-patches#363]
### Application

YouTube

### Suggestion description

the current `hide collapse button patch` leaves a space before the video title which makes the video title look misaligned. a better way is to hide collapse button by editing layout xml which does not have such issue.

using custom filter (current patch)

![Screenshot 2024-04-24 145501](https://github.com/anddea/revanced-patches/assets/87489540/03e97c9f-58e4-4025-9032-ba995dc2152b)

using layout xml (proposed patch)

![Screenshot 2024-04-24 145611](https://github.com/anddea/revanced-patches/assets/87489540/95da0459-7131-4019-a4ec-1ae7e04b0b82)

**the following changes need to be made in res/layout/youtube_controls_layout.xml (highlighted in orange)**

![Screenshot (9)](https://github.com/anddea/revanced-patches/assets/87489540/52f81214-983a-40dd-8769-af8ec7fbb7ac)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
I'll try make a pr for this, maybe this afternoon

**Comment by Francesco146** [comment]
nevermide i spent 4 hours trying to set up the debugger for testing the integrations. i can't do anything if i can't test my code

**Comment by anddea** [comment]
Test the latest release and let us know if you face any issues.
