### ISSUE TITLE
feat: Add an option to hide "Live chat replay" button in full screen.

### ISSUE THREAD

**Issue by Pikasatupu75** [anddea/revanced-patches#364]
### Application

YouTube

### Feature description

A toggle in full screen section to hide this button completely.

### Motivation

It is the button in bottom right corner after you close the live chat in fullscreen. I thought it is annoying and it would be good to be able to hide it.
![20240424_131134](https://github.com/anddea/revanced-patches/assets/126986435/95f2b4e3-1f4d-4c8a-acd3-a9a0b3870c6d)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
can you send the video link, for reference?

**Comment by Pikasatupu75** [comment]
Sure: https://www.youtube.com/live/CT8emTanWeA

**Comment by Francesco146** [comment]
> Sure: https://www.youtube.com/live/CT8emTanWeA

insert this in the Custom Filter:

`carousel_header$Live chat replay`

**Comment by Pikasatupu75** [comment]
> insert this in your Custom Filters:
> 
> `carousel_header$Live chat replay`

It doesn't seem to work.

**Comment by Francesco146** [comment]
> It doesn't seem to work.

was worth giving it a shot, i suggested you that because my build isn't showing that button and i remembered inserting that filter for a reason. sorry!

**Comment by Pikasatupu75** [comment]
Welp, thanks for trying anyways.

**Comment by anddea** [comment]
I cannot see this button. How do you get it?

**Comment by Pikasatupu75** [comment]
https://github.com/anddea/revanced-patches/assets/126986435/2c42e250-4f52-4a31-8d36-96448688cfb8

Here is a video of it.

**Comment by Francesco146** [comment]
i can reproduce the error. however here's what i found:
1. you need to disable the: `Hide live chat button` in Fullscreen section 
2. you need to disable the `Hide luve chat messages` in Shorts section (another issue with this)

**Comment by anddea** [comment]
The second one hides live chat everywhere actually, just like timed reactions.

**Comment by Francesco146** [comment]
> The second one hides live chat everywhere actually, just like timed reactions.

got it, the only issue with that is actually its description and setting location is quite misleading i guess. 

Anyhow, have you been able to reproduce that button?

**Comment by anddea** [comment]
> Anyhow, have you been able to reproduce that button?

Yes. 

If you add `live_chat_ep_entrypoint` to custom filter, this should be hidden. Should I add switch for it to the settings?

**Comment by Francesco146** [comment]
> Should I add switch for it to the settings?

the way i see it, it might as well be activated when the toggle `Hide live chat messages` is enabled.

**Comment by anddea** [comment]
What if someone wants to see live chat messages but doesn't want to see this button ruining video experience, because you can open live chat with quick actions button

**Comment by Francesco146** [comment]
> What if someone wants to see live chat messages but doesn't want to see this button ruining video experience, because you can open live chat with quick actions button.

that's spot on. a new setting in the Player section? 

> Can you verify that this filter works for you?

i can confirm that it's working!

**Comment by Pikasatupu75** [comment]
> What if someone wants to see live chat messages but doesn't want to see this button ruining video experience, because you can open live chat with quick actions button.

That is exactly what I wanted.

**Comment by anddea** [comment]
> a new setting in the Player section?

Or Fullscreen is better? I'll add it after stable release (which I wanted to release now), because if I add now, I'll have to wait for translations for new strings.

**Comment by Francesco146** [comment]
> Or Fullscreen is better? 

yeah, fullscreen is better indeed. quite borderline but both works for me. :)

**Comment by anddea** [comment]
> `Hide live chat messages` in Shorts section (another issue with this)

I moved it to General settings. 

Also, moved description components to bottom player. Although, I think it should be in Player. Because you can open description in fullcreen mode as well. What do you think?

**Comment by Francesco146** [comment]
> What do you think?

description can be opened in both ways. there's no right answer. have you thought about creating a new setting category named for these?

**Comment by Pikasatupu75** [comment]
> description can be opened in both ways

Then maybe it is best if they stay in general?

**Comment by Francesco146** [comment]
> Then maybe it is best if they stay in general?

the thing is, General is already clogged with multiple settings, and adding more and more won't help

**Comment by Pikasatupu75** [comment]
We can move some of the general settings to navigation. Lots of space there.

**Comment by Francesco146** [comment]
@anddea Player section seems appropriate on a second glance.

**Comment by Pikasatupu75** [comment]
Player section is fine by me too.

**Comment by anddea** [comment]
I just checked, original ReVanced also has this in Player section. I can minimize sections by creating subsections (like `Keyword filter` inside `General`), but it'll be an additional tap to open these settings.

**Comment by Francesco146** [comment]
meh, I don't see the need for a subsection

**Comment by Pikasatupu75** [comment]
If i think hard about it, the Player section seems like for buttons or actions that can be done in player in both vertical and horizontal mode. 

Fullscreen section is for only vertical mode buttons or actions. 

Since description can't be opened in player in vertical mode. They would not fit in Player settings section. 

In vertical mode they would fit in bottom player section. In horizontal mode they would fit in full screen section. 

But since the Player section is for things that can be done in both vertical and horizontal mode, it seems like the best fit for these settings. Even thought it is not in player in vertical mode. 

It doesn't make total sense. But it makes some sense I hope.

**Comment by Pikasatupu75** [comment]
The reason I said bottom player section before is because description seems related or important to comments. And comments are in bottom player section.

**Comment by Pikasatupu75** [comment]
Also, comments can technically be opened in both vertical and horizontal mode. 

Comments can only be opened in bottom player in vertical mode. 

Comments can only be opened in player in horizontal mode. 

So, they can't be opened in player in vertical mode. But can be opened in player horizontal mode. 

That is the same as description. In the same circumstances the comments are in bottom player section. So, it makes sense for description to be in bottom player with comments too.

**Comment by Francesco146** [comment]
or move the comments too in the player section. what ReVanced do with these settings?

**Comment by anddea** [comment]
Added this option with quick action buttons, although, it's not quick action button, it's kinda related. 

@Francesco146, I also added the option to hide comment button in shorts if it's disabled. Just because '0 comments" doesn't show any number of comments in buffer, the comment button will be hidden with both 0 comments and disabled button, just like you wanted from the beginning.

**Comment by Francesco146** [comment]
I saw it, thank you very much! It will help me understand how to work with the integrations module! :)

**Comment by sultanmonsur** [comment]
Where is the "hide live chat massage"??
![Screenshot_2024-05-02-09-15-40-33_0635f5993b1f7a268b0ea09a0649cdab](https://github.com/anddea/revanced-patches/assets/61897416/bf34cfde-4d81-46e0-a47b-b15686fab6ac)

**Comment by anddea** [comment]
It's in General now, because it hides live chat messages for both Shorts and normal videos.
