### ISSUE TITLE
suggestion: Split the info_panel (String) into two things

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#367]
### Application

YouTube

### Suggestion description

Split the info_panel into two things?

• revanced_hide_info_panel_... (General)
• revanced_hide_shorts_info_panel_... (Shorts)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Done.
