### ISSUE TITLE
bug: Another Padding Issue

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#369]
### Type

Other

### Tools used

CLI

### Application

YouTube 19.14.43

### Bug description

The seek ar on the full-screen portrait mode is on the edge of the bottom of the screen. 
![Screenshot_20240425_131226_YouTube](https://github.com/anddea/revanced-patches/assets/153147835/41e10d18-3545-40f6-8a04-69f0cfe89310)

### Solution

Add padding back? 

### Device Environment

Android 14, OneUI 6.0, Samsung Galaxy Tab A7 Lite. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
can't reproduce. is it happening in all videos?

**Comment by AbakNacchan** [comment]
> can't reproduce. is it happening in all videos?

Yes. Bumped to 19.16.xx the problem persists.

**Comment by Francesco146** [comment]
should be fixed in RVX
