### ISSUE TITLE
suggestion: add korean translation string.xml

### ISSUE THREAD

**Issue by ZeroZero0011** [anddea/revanced-patches#37]
### Application

YouTube

### Suggestion description

translations/ko-rKR

add this file.

https://mega.nz/file/8W9xGABC#ltW7gTFMv0wwWOw7wWVoV-e2uYtRoe5dJ1j10rZUlkE

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
There are some missing strings, if you'd like to know. 

<details>
<summary>Missing strings</summary>

Missing strings were collected by an automated script.
```xml
<string name="revanced_hide_player_button_background_summary_off">Player buttons background is shown.</string>
<string name="revanced_hide_player_button_background_summary_on">Player buttons background is hidden.</string>
<string name="revanced_hide_player_button_background_title">Hide player buttons background</string>
<string name="revanced_spoof_failure_connection_status_code" formatted="false">"Spoof storyboard not available: "</string>
<string name="revanced_spoof_failure_connection_timeout">Spoof storyboard temporarily not available (API timed out).</string>
<string name="revanced_spoof_failure_generic">"Spoof storyboard temporarily not available: "</string>
```
</details>

**Comment by ZeroZero0011** [comment]
* New *
     <string name="revanced_change_start_page_entry_browse">채널 탐색</string>
    <string name="revanced_change_start_page_entry_default">기본</string>
    <string name="revanced_change_start_page_entry_explore">탐색</string>
    <string name="revanced_change_start_page_entry_gaming">게임</string>
    <string name="revanced_change_start_page_entry_history">기록</string>
    <string name="revanced_change_start_page_entry_library">나 (보관함)</string>
    <string name="revanced_change_start_page_entry_liked_videos">좋아요 표시한 동영상</string>
    <string name="revanced_change_start_page_entry_live">실시간</string>
    <string name="revanced_change_start_page_entry_movies">영화</string>
    <string name="revanced_change_start_page_entry_music">음악</string>
    <string name="revanced_change_start_page_entry_search">검색</string>
    <string name="revanced_change_start_page_entry_shorts">Shorts</string>
    <string name="revanced_change_start_page_entry_sports">스포츠</string>
    <string name="revanced_change_start_page_entry_subscriptions">구독</string>
    <string name="revanced_change_start_page_entry_trending">인기 급상승</string>
    <string name="revanced_change_start_page_entry_watch_later">나중에 볼 동영상</string>
   <string name="revanced_override_premium_header_summary_off">기본 헤더</string>
    <string name="revanced_override_premium_header_summary_on">프리미엄 헤더</string>
    <string name="revanced_override_premium_header_title">헤더 변경하기</string>
    <string name="revanced_keyword_invalid_length" formatted="false">키워드 길이가 너무 짧습니다 (최소 %s 이상이어야 합니다): %s.</string>
    <string name="revanced_keyword_filter_strings_summary">필터링할 키워드 및 구문을 줄바꿈으로 구분하여 설정합니다.\n\n대문자가 포함된 영어 키워드는 대소문자를 구분하여 입력해야 합니다 (예: iPhone, TikTok, LeBlanc).</string>
    <string name="revanced_keyword_filter_strings_title">키워드 필터 편집하기</string>
    <string name="revanced_keyword_filter_summary_off">키워드 필터를 비활성화합니다.</string>
    <string name="revanced_keyword_filter_summary_on">키워드 필터를 활성화합니다.</string>
    <string name="revanced_keyword_filter_summary">키워드 필터를 사용하여 피드 및 검색 결과 동영상을 숨깁니다.</string>
    <string name="revanced_keyword_filter_title">키워드 필터 활성화하기</string>

* In ReX Korean Strings.xml, my retranslated String *
    <string name="revanced_enable_song_search_summary_on">노래 검색을 활성화합니다.\n\n\'Hide voice search button\' 패치가 포함된 앱에서는 이 기능을 사용할 수 없습니다.</string>
    <string name="revanced_disable_landscape_mode_summary_off">전체 화면 버튼을 눌러서 전체 화면 세로 모드로 전환할 수 없습니다.</string>
    <string name="revanced_disable_landscape_mode_summary_on">전체 화면 버튼을 눌러서 전체 화면 세로 모드로 전환할 수 있습니다.</string>
    <string name="revanced_disable_landscape_mode_title">전체 화면 세로 모드 전환하기</string>

**Comment by anddea** [comment]
I've updated to your new translation. It'll be in the next release. But I said there are other missing strings in dropdown "Missing strings", that I sent you in my previous message. I'll send again without dropdown. You can translate them and send me here. 

```xml
<string name="revanced_hide_player_button_background_summary_off">Player buttons background is shown.</string>
<string name="revanced_hide_player_button_background_summary_on">Player buttons background is hidden.</string>
<string name="revanced_hide_player_button_background_title">Hide player buttons background</string>
<string name="revanced_spoof_failure_connection_status_code" formatted="false">"Spoof storyboard not available: "</string>
<string name="revanced_spoof_failure_connection_timeout">Spoof storyboard temporarily not available (API timed out).</string>
<string name="revanced_spoof_failure_generic">"Spoof storyboard temporarily not available: "</string>
```

**Comment by ZeroZero0011** [comment]
https://mega.nz/file/Rac21DDC#cQhnLKoO4vDaOr4Ta4gop9kcr_4dRUHSTq_Dfwpn6tE

**Comment by anddea** [comment]
Seems good

**Comment by anddea** [comment]
Added in the [latest release](https://github.com/anddea/revanced-patches/releases/tag/v2.221.0.2). Check if it's fine.
