### ISSUE TITLE
bug: (Youtube) - Tablet Miniplayer broken controls.

### ISSUE THREAD

**Issue by Cast0r-999** [anddea/revanced-patches#371]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.16.38; patches 2.224.0 stable; GmsCore from official Revanced Github v0.3.1.4.240913 (ver. for Xiaomi) 

### Bug description

1. Enable Tablet miniplayer, restart app.
2. Open any video and minimize it.
- You can't pause or control video, buttons are invisible and disabled.
![Screenshot_2024-04-25-20-43-03-418_anddea youtube](https://github.com/anddea/revanced-patches/assets/162354008/9cdffd6f-d0d9-4e29-8554-55446f7f093b)

### Device Environment

Android 10, MIUI 12.0.1 Global Stable, official, non-root. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by sultanmonsur** [comment]
Same problem with me.
We need fix it's very fast.

**Comment by anddea** [comment]
Stick with older eversion 19.11 for now. New versions will always have this compromise, especially latest YouTube updates have a lot of changes in their code. So it's more likely even if it works now, tomorrow or a week later you will get A/B that will break everything.

**Comment by Francesco146** [comment]
> Stick with older eversion 19.11 for now. New versions will always have this compromise, especially latest YouTube updates have a lot of changes in their code. So it's more likely even if it works now, tomorrow or a week later you will get A/B that will break everything.

since v19.16.38 is the latest stable YouTube release, wouldn't it be better to keep an older version in stable releases (in this example 2.224.0), and attempt to port patches to the latest versions in dev releases?

**Comment by anddea** [comment]
I can't edit supported versions for released patches, only create new release and drop support. There is already a fix for tablet miniplayer, just wait a little.

**Comment by Cast0r-999** [comment]
Downgrading and reinstalling is exhausting (non-root device). Just fix this bug on v16, everything else seems fine (used 2 days).
