### ISSUE TITLE
bug: (Youtube) [Cosmetic] Nullify empty space between hidden buttons under the video player. 

### ISSUE THREAD

**Issue by Cast0r-999** [anddea/revanced-patches#372]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Any version. Current is: Youtube 19.16.38; patches 2.224.0 stable; GmsCore from official Revanced Github v0.3.1.4.240913 (ver. for Xiaomi) 

### Bug description

If you hide some buttons under the video player, replaced empty space looks wide and ugly. Can you make space beetween hidden & unhidden buttons balanced, equal?
                                     Example 1:
![Screenshot_2024-04-25-20-58-20-101_anddea youtube_1](https://github.com/anddea/revanced-patches/assets/162354008/dd64818d-658e-43d5-9efb-ebd8700121d3)
                                     Example 2:
![Screenshot_2024-04-25-20-59-31-817_anddea youtube_1](https://github.com/anddea/revanced-patches/assets/162354008/4b27758c-b86c-4f29-b7c9-d9fc3e6a5a61)

### Device Environment

Android 10, MIUI 12.0.1 Global Stable, official, non-root.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by nintendork07** [comment]
not necessarily about the spacing, but this option doesn't seem to work on the latest dev patch (v2.225.0-dev.11). remix, thanks and report are still showing up even though the option is selected to hide them.

**Comment by Francesco146** [comment]
if it's doable, it will be at compile time only

**Comment by anddea** [comment]
Yes, I already mentioned in another similar issue, it is not possible with current litho filter, otherwise it would be fixed already.
