### ISSUE TITLE
bug(YouTube): turning off RYD for shorts disables it for normal videos too

### ISSUE THREAD

**Issue by shreyjain1998** [anddea/revanced-patches#376]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 19.16.38

### Bug description

If I turn off the toggle `Show dislikes on Shorts`, dislikes counter disappears from normal videos too.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
i'll quote the patch description:
> Limitations: Dislikes may not appear in certain situations.

this behaviour you are encountering is happening in all videos?

**Comment by shreyjain1998** [comment]
Yes, this is happening for all videos. This issue is not there in official ReVanced though.

**Comment by anddea** [comment]
Should be fixed in the latest release.

**Comment by shreyjain1998** [comment]
Yes it is fixed. Thank you!
