### ISSUE TITLE
Change name of the RVX/REX settings

### ISSUE THREAD

**Issue by speedlorenzo12** [anddea/revanced-patches#377]
### Application

YouTube

### Feature description

Add a patch option for [title] named custom setting name in case of revancify for change the settings title from revanced extended to and another title

### Motivation

it makes the settings more customizable and the creators don't have to change the title every time since the users will do it

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
could you make some example? are you referring to changing the settings like "General", "Ads", Alternative thumbnails",...?

**Comment by speedlorenzo12** [comment]
Change only revanced extended title
![Screenshot_2024-04-27-09-43-29-790_app.and.android.youtube-edit.jpg](https://github.com/anddea/revanced-patches/assets/111771663/9dc2252c-7cfc-4924-a0dd-add9a7da6840)

**Comment by Francesco146** [comment]
i'll try making a PR for this feature

**Comment by Francesco146** [comment]
done! you may close this now. if you encounter a bug let us know :)
