### ISSUE TITLE
bug: Isn't detecting MicroG

### ISSUE THREAD

**Issue by ac-tu** [anddea/revanced-patches#38]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Any YouTube Version 

### Bug description

When opening YouTube, it can't detect MicroG

The MicroG I use is [here](https://github.com/WSTxda/MicroG-RE), I don't know where the issue comes from, but this version works for revanced and extended, apologies if the issue comes from that MicroG instead of the patch used.

Step 1. Use the MicroG stated above
Step 2. Patch with MicroG support
Step 3. Open patched app, only to have it instantly crash

### Device Environment

Poco F3, CRDroid 14, non rolt installation of the YouTube app

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Does this MicroG you mentioned worked before?

There was no changes to MicroG patch in YouTube and YT Music. Try to troubleshoot, is it MicroG or RVX Manager, maybe clear storage and cache of those apps.

**Comment by ac-tu** [comment]
This MicroG worked on Revanced and Revanced Extended, I'm unsure if it only reveals itself to those apps, the app patches correctly, it just explodes as it can't find MicroG,

Perhaps it's a issue of package names, as it seemingly looks for that! Sorry for not having tons of information.
![Screenshot_20240313-200009_MicroG](https://github.com/anddea/revanced-patches/assets/76844190/5503069e-6d7f-43d3-9aba-042133f6959d)

When I just have this version of YouTube installed, it doesn't show the ReVanced Extended box as detected.

**Comment by ac-tu** [comment]
> try this microg : https://github.com/inotia00/vancedmicrog/releases

After testing, oddly enough still seems to crash on opening, no clue why. App just instantly crashes on launch still.

**Comment by ac-tu** [comment]
Nevermind, I didn't triple check what manager I was using! So sorry for that.

Solved by just using RVX Manager!
