### ISSUE TITLE
bug: Hide player buttons background

### ISSUE THREAD

**Issue by CobalTitan** [anddea/revanced-patches#380]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.15.36 and above.
![Screenshot_20240426_100515_RVX Manager](https://github.com/anddea/revanced-patches/assets/60859375/2e2ac7b2-0f70-4f93-9648-b6055964ec92)
![Screenshot_20240426_100423_Samsung Internet](https://github.com/anddea/revanced-patches/assets/60859375/2668fea6-8d2e-4da7-9823-7322eedbb3f6)

### Bug description

Patch Hide player buttons background not supported to v19.15.36 and above.  But it says that the version is supported.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It should work, just didn't update info. Will update later.

**Comment by CobalTitan** [comment]
Okay I'm going to remove require suggested app version limit and compose.
Everything went well during compilation.
Thanks
