### ISSUE TITLE
bug: Skip preloaded buffer does not work

### ISSUE THREAD

**Issue by Dimedro11** [anddea/revanced-patches#382]
### Type

Other

### Tools used

Revancify

### Application

19.16.38

### Bug description

Skipping the preloaded buffer does not work in the latest versions.
![Screenshot_20240426_185533_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/78a59126-08b3-4e6f-adf5-8ce3dd537c76)
![Screenshot_20240426_185523_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/9f8b8d4f-e985-48c7-a715-848bce1a7acb)
![Screenshot_20240426_185513_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/8901ab7c-e3a3-4e61-8f5f-475820b943f1)
![Screenshot_20240426_185459_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/4b5c6943-c6f2-46b0-9fb3-fabdb94c18f3)
![Screenshot_20240426_185452_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/8124676b-997f-4fd2-84f3-b7a7a515f913)
![Screenshot_20240426_185442_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/9d66f6b4-2796-4948-8ecc-6642ea1f7e21)
![Screenshot_20240426_185437_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/44d3b4f7-11e3-4b4b-8cf8-3bbc691863a6)
![Screenshot_20240426_185426_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/a92b770f-a9e2-4ecd-9253-9bfcad200930)
![Screenshot_20240426_185418_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/36131a8f-34c9-497b-ac56-56a8a00d317a)
![Screenshot_20240426_185409_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/39da4806-bcfd-4d8d-85fe-163b29544ded)
![Screenshot_20240426_185348_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/c51f4e33-8c3e-408b-a47d-bbdc46f74c98)
![Screenshot_20240426_185339_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/5fdc90aa-9afa-42a0-afdb-dca0f3856602)
![Screenshot_20240426_185333_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/b211247e-7922-412c-9129-0e073987b15b)
![Screenshot_20240426_185327_YouTube](https://github.com/anddea/revanced-patches/assets/111146046/fbafa8aa-851e-4254-999d-0df184f9fffb)

### Device Environment

Samsung s23u
One Ui 6.1
Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by jdjta** [comment]
Same for me, the preload buffer is no longer working after updating to 19.16.38. I used the latest anddea patches (2.224.1-dev 1). I reinstalled the app, rebooted my devices, force stopped the app multiple times but it still starts at 360p/480p and switches after a few seconds.

![Screenshot_20240426_210638_YouTube](https://github.com/anddea/revanced-patches/assets/50163840/f3938b13-aa0a-438d-affa-d85b1db6ee48)

**Comment by anddea** [comment]
Fixed in the latest release. But it's an experimental feature.

**Comment by jdjta** [comment]
Kind of fixed in 2.224.1-dev3 but not completely. 2160p is my default setting on my tablet as shown above. Watching a 1080p video (without 1440p or 2160p as an option) and watching a second video after the first one which has these higher quality options still first starts playing at lower quality before 'gearing up'  to the highest quality available.

**Comment by anddea** [comment]
I'll think of possible improvement. But this kind of a behavior was before too. Was it different for you?

**Comment by jdjta** [comment]
> I'll think of possible improvement. But this kind of a behavior was before too. Was it different for you?

Alright, I was under the impression it was different in earlier releases where it selected the highest possible quality (up to the selected default playback quality) but I might be wrong here. 

Sorry to bother you and thank you kindly for all the dedication to give us the best experience possible 🙏.
