### ISSUE TITLE
bug: Youtube Music Hook Download Button does not work

### ISSUE THREAD

**Issue by Uryaaa** [anddea/revanced-patches#384]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube Music 6.48.53

### Bug description

1. Enable hook download button
2. Configure External Download Package to any 3rd party downloader app (i use com.junkfood.seal)
3. Restart YTM
4. Try to download any song
5. See downloader does not open

### Error logs

```shell
-
```

### Solution

-

### Additional context

-

### Device Environment

Samsung A20, Android 11

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
> ### Type
> Other
> 
> ### Tools used
> RVX Manager
> 
> ### Application
> Youtube Music 6.48.53
> 
> ### Bug description
> 1. Enable hook download button
> 2. Configure External Download Package to any 3rd party downloader app (i use com.junkfood.seal)
> 3. Restart YTM
> 4. Try to download any song
> 5. See downloader does not open
> 
> ### Error logs
> ```shell
> -
> ```
> 
> ### Solution
> 
> ### Additional context
> 
> ### Device Environment
> Samsung A20, Android 11
> 
> ### Acknowledgements
> * [x]  This issue does not reproduce on unpatched YouTube or YT Music.
> * [x]  This issue is not a duplicate of an existing bug report.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  I have written the title and contents in English.


https://github.com/anddea/revanced-patches/assets/109387456/12e8b3b3-3808-4e33-8085-3e1af6848cec

**Comment by Vipin2003** [comment]
But it is working fine here...

**Comment by Vipin2003** [comment]
But it is working fine here

**Comment by Uryaaa** [comment]
> But it is working fine here

Hmm that is weird, it dosen't work on mine, can i see your ytm rvx config and version?

**Comment by Uryaaa** [comment]
I try to re-patch on older version 
(I use `YouTube Music 6.41.58`) and it work as expected, i'll leave this issue open until someone can confirm if ot actually a bug related to new version of YTM or anddea decide to close it.

**Comment by YT-Advanced** [comment]
Google switched Action Button to Litho, so both RYD and Hook Download Button will no longer working

**Comment by Uryaaa** [comment]
I see, thanks for the answer.

**Comment by selfmusing** [comment]
> Google switched Action Button to Litho, so both RYD and Hook Download Button will no longer working Related issues: #302

IDK How but both buttons are working fine for me even on v6.50.xx

**Comment by Vipin2003** [comment]
> > Google switched Action Button to Litho, so both RYD and Hook Download Button will no longer working Related issues: #302
> 
> IDK How but both buttons are working fine for me even on v6.50.xx

Same here too

**Comment by YT-Advanced** [comment]
> > Google switched Action Button to Litho, so both RYD and Hook Download Button will no longer working Related issues: #302
> 
> IDK How but both buttons are working fine for me even on v6.50.xx

Nah, it is A/B Testing bruh

**Comment by selfmusing** [comment]
> > > Google switched Action Button to Litho, so both RYD and Hook Download Button will no longer working Related issues: #302
> > 
> > 
> > IDK How but both buttons are working fine for me even on v6.50.xx
> 
> Nah, it is A/B Testing bruh

Yeah , now correct 😁.
