### ISSUE TITLE
bug: "You may also like" shows in search 

### ISSUE THREAD

**Issue by rsaurav12** [anddea/revanced-patches#385]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.38
Revanced patches 2.224.0
Revanced integration 0.151.0

### Bug description

"You may also like" still shows in search even if i enable  "hide video with gray description" , "hide gray description" and "hide gray separator" in general settings

![Screenshot_2024-04-27-00-04-36-236_anddea youtube](https://github.com/anddea/revanced-patches/assets/53332518/ac345595-5355-4297-80e1-087ce2be99e3)
![Screenshot_2024-04-27-00-38-14-471_anddea youtube](https://github.com/anddea/revanced-patches/assets/53332518/3ba55ea4-40d6-4874-9135-bb441e1b6317)
![Screenshot_2024-04-27-00-39-27-719_anddea youtube](https://github.com/anddea/revanced-patches/assets/53332518/1e584d98-79c3-4d19-87b0-17daab5cabf2)

### Device Environment

Android 12, Miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
should be fixed in RVX

**Comment by rsaurav12** [comment]
> should be fixed in RVX

Will anddea fix this in this patch?

**Comment by Francesco146** [comment]
> Will anddea fix this in this patch?

already did, do you still get this?
