### ISSUE TITLE
feat (YT Music) : Add support for "Enable Color Match Player" for new versions of YT Music.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#39]
### Application

YouTube Music

### Feature description

I know this patch is deprecated since YouTube Music v6.34.51 but the current minimised player just looks really dull/ugly with only AMOLED dark mode. Maybe it's possible for you to somehow make this patch work again through different methods or means. I would really love to see this patch working again in later versions as it gives the player more vibrance and colour & I and others really love it.
![Screenshot_2024-03-13-18-59-28-65_50ecd26a21c2c56ce608de5e94733463](https://github.com/anddea/revanced-patches/assets/91815107/e3f75aea-0077-4abf-8831-bb24eeb85f4d)

### Motivation

I & many others loved this patch.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
> ### Application
> YouTube Music
> 
> ### Feature description
> I know this patch is deprecated since YouTube Music v6.34.51 but the current minimised player just looks really dull/ugly with only AMOLED dark mode. Maybe it's possible for you to somehow make this patch work again through different methods or means. I would really love to see this patch working again in later versions as it gives the player more vibrance and colour & I and others really love it. ![Screenshot_2024-03-13-18-59-28-65_50ecd26a21c2c56ce608de5e94733463](https://private-user-images.githubusercontent.com/91815107/312474852-e3f75aea-0077-4abf-8831-bb24eeb85f4d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTc2MzQsIm5iZiI6MTcxMDM1NzMzNCwicGF0aCI6Ii85MTgxNTEwNy8zMTI0NzQ4NTItZTNmNzVhZWEtMDA3Ny00YWJmLTg4MzEtYmIyNGVlYjg1ZjRkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE5MTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZmVkOTNjZDhhYWU5NTRkYjBjNGY5MWNlY2I2NWU4YWIwMGVhOGJjYmIwN2U2N2E5MmNmOGFmNjA3ODI1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KIvQFIXIhLEup9AqrG6yX7sWV_h1iUEMXZrxETR9OPM)
> 
> ### Motivation
> I & many others loved this patch.
> 
> ### Acknowledgements
> * [x]  This issue is not a duplicate of an existing feature request.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  I have written the title and contents in English.

It's sad but google now killing ytm patches in newer updates after v6.29.xx : https://github.com/inotia00/ReVanced_Extended/issues/1933#issue-2094650762

They even completely removed the resources for old style miniplayer in 6.42.xx 🥲 & much more patches are broken in 6.43.xx ... 
( I hope some of them patches like change start page, custom playback speed, hide action bar component, sponsorblock, spoof app version are still can be fixed )

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT Music feature requests in this single issue:

#226
