### ISSUE TITLE
feat: Volume steps adjustment 

### ISSUE THREAD

**Issue by selfmusing** [anddea/revanced-patches#390]
### Application

YouTube

### Feature description

Is there a way to force volume buttons to work the same amount as they do by default in android : from 1-20, (not from 0 to 150) even in yt Fullscreen and volume gesture is enabled .

- when i'm not in Fullscreen mode, volume button has 20-25 steps from empty to full (like for other apps sound)

- when I enter fullscreen in yt, i have 150 steps from empty to full (like volume gesture)

My request is to keep button volume like for other apps (from 0 to 25) even in yt fullsceen and gesture enabled or add a specific setting to adjust the volume steps in swipe settings .

https://github.com/anddea/revanced-patches/assets/109387456/a204fe16-f89a-4d6d-a454-9a8c614effeb

[ Btw , I opened this feature request on behalf of someone else ]

### Motivation

It will help the users who get higher volume steps when they play any video in full screen after enabling volume swipe gesture.

💀 0-25 volume steps by default  is much better than having 0-150 steps .

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I think it's system related on your side, adjust steps in your system. I have 15 steps by default as my system.

**Comment by selfmusing** [comment]
> I think it's system related on your side, adjust steps in your system. I have 15 steps by default as my system.

Btw I don't have this issue , a user reported this on telegram...
He has 15 vol. steps by default , but no idea why he get 150 steps while using swipe volume gesture 💀in full screen.

**Comment by anddea** [comment]
Maybe it's related to his ROM. He could've selected 15 steps for calls and 150 for media. 

I'll close it but feel free to continue this discussion.

**Comment by irishFaraon** [comment]
(it's me who mentioned this issue and requested for help)
It's not related to ROM, since i don't face this on any other app other than yt rvx. Btw i've already mentioned volume steps count is the same in volume gesture (0-150) as i showed in the screen record.
My second proof, i've installed yt rvx in 3 other phones of my family members, and, the same issue.
Or maybe it's related to MIUI/hyperOs not my specific ROM (the other phones i've tried are all in MIUI)

Uploading Screenrecorder-2024-04-30-21-27-16-882.mp4…

**Comment by selfmusing** [comment]
@anddea can you check what's wrong 🤔?

**Comment by anddea** [comment]
Original ReVanced repo has related issue and it's device specific for how volume swipe is working. Probably it needs rewriting. I'll check when I have time, not sure when.

**Comment by irishFaraon** [comment]
Thanks a lot Mr Anddea, i think that detach volume button and volume gesture will solve the problem (use android volume for buttons, instead of build in volume changer of the app when buttons are clicked)

**Comment by anddea** [comment]
If you disable swipe gestures for volume it will detach and will use system UI volume panel instead. 

Settings > Extended > Swipe controls > Enable volume gesture (turn off).

**Comment by irishFaraon** [comment]
I knew that, but I prefer to keep both if it's possible 
* Volume gesture by swiping 
* Default system volume for buttons

**Comment by irishFaraon** [comment]
> Reopen this issue in inotia's repo too.

How to do it please 🙏🏻🙏🏻

**Comment by anddea** [comment]
> How to do it please

https://github.com/inotia00/ReVanced_Extended/issues/new/choose
