### ISSUE TITLE
feat(YT): Re-adding the curved design option for OverlayButtonIcon in option.json

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#391]
### Application

YouTube

### Feature description

Try to restore the Curved Design of OverlayButtons which is dropped by Inotia earlier, like custom splash screen. Like currently we have stock and outline icons.
https://github.com/inotia00/ReVanced_Extended/issues/968#issue-1698363114

### Motivation

It will return back the Curved cool design of overlay buttons, which looks more beautiful than stock.
Personally, I like them most.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you provide example images?

**Comment by Vipin2003** [comment]
> Can you provide example images?

Umm....I'll try to add the images soon.

**Comment by Vipin2003** [comment]
I've got the magisk module of the old version of vanced extended which have those icons. Can you check it if you can.
https://uploadnow.io/f/SQNTkqY

**Comment by anddea** [comment]
I don't use magisk. Screenshot will be enough.

**Comment by Vipin2003** [comment]
> I don't use magisk. Screenshot will be enough.

I only found 1 screenshot yet...Hope this will help you to understand that. At that time, it is enabled from option.toml with the key "overlay icons" with value "old" and "new"
![IMG_20240428_231301_144](https://github.com/anddea/revanced-patches/assets/93650504/716796ea-268c-4a7a-8e3d-7a0f650002a1)

**Comment by Vipin2003** [comment]
It is implemented here too previously...
![Screenshot_20240428_231743](https://github.com/anddea/revanced-patches/assets/93650504/a9d4b808-deda-4172-8fb5-5a6e8e786334)
Will try for more SS for better understanding.

**Comment by anddea** [comment]
I'll try to reproduce those icons when I have time. Do you remember what was the last version that had those icons?

**Comment by Vipin2003** [comment]
It is 17.35.35....I only remember that version only, as I found bug in that version that time.

**Comment by Vipin2003** [comment]
> I'll try to reproduce those icons when I have time. Do you remember what was the last version that had those icons?

I think it will be hard for you as You will need root. Becoz there is currently no non-root apk available for vanced xtended. Try once if you got success in finding non-root apk. Best of luck for that.

**Comment by selfmusing** [comment]
> I'll try to reproduce those icons when I have time. Do you remember what was the last version that had those icons?

![Screenshot_20240429-010622_MT Manager](https://github.com/anddea/revanced-patches/assets/109387456/43500bfe-32a6-4225-af65-381b248a50cc)

@Vipin2003

**Comment by selfmusing** [comment]
> I'll try to reproduce those icons when I have time. Do you remember what was the last version that had those icons?

https://github.com/inotia00/revanced-patches/commit/bb331e5c3a4ad0a9e9156f9487759b6fc8aa30a8

**Comment by Vipin2003** [comment]
> I'll try to reproduce those icons when I have time. Do you remember what was the last version that had those icons?

Have you got any updates regarding this?

**Comment by anddea** [comment]
> Have you got any updates regarding this?

I'll add them soon. There's no need to recreate them, they're fine as is, maybe will refine them and I'll also add missing icons.

**Comment by Vipin2003** [comment]
> > Have you got any updates regarding this?
> 
> I'll add them soon. There's no need to recreate them, they're fine as is, maybe will refine them and I'll also add missing icons.

Great News...Finally, we will be having them.
