### ISSUE TITLE
question: YT Music Supported Ver?

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#392]
### Application

YouTube Music

### Question description

What's the latest version of YT Music that supported by this RVX patch?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It's better to use older version, before 6.42, because a lot of things are changed and will break with A/B tests. Although, most of the patches are still working for the latest version.
