### ISSUE TITLE
bug: YouTube crashes when opened with latest patch

### ISSUE THREAD

**Issue by BAXSD** [anddea/revanced-patches#394]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.38

### Bug description

After patching is done and installed successfully opening YouTube app it crashes. I never make it into the YouTube app. I read on Reddit that someone tested to uncheck "Return YouTube Dislike" and got it to work. I tested that but opening YouTube would only last for a couple of seconds before it crashes again. Have tested with other YouTube versions too but it crashes too. It is something with the latest patch that might cause this. I dont know. Anyone else experiencing the same? How to fix this?

I have tested to reinstall GMSCore, ReVanced Manager and YouTube from scratch but did not help either.

Anddea, Please address this issue and fix this. I would really appreciate it. Im not the only one that having this issue. Thanks in advance :)

### Device Environment

Android 14

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by tyw7** [comment]
![Screenshot_20240428_163428_ReVanced Manager](https://github.com/anddea/revanced-patches/assets/14168657/a5ff6467-b00e-47ea-934d-f03056b3a6e2)

Hi.  These are the patches I used and so far it's not crashing. 

I was the Redditor that reported the crashing here: https://www.reddit.com/r/revancedextended/comments/1cf4pan/one_of_the_patches_keep_crashing/

I have been stung by random patches causing crashes, so I have only opted to patches I will use, keeping the patch number low.

**Comment by anddea** [comment]
Download logcat app, capture and share crash error (search YouTube in the logcat app logs and when you see red, copy and share it here).

**Comment by tyw7** [comment]
YouTube doesn't appear in it, though.

To help you diagnose, I am going to attach the APK too.  To others, DO NOT trust random Revanced patched APKs.

APK (expires in 7 days): https://we.tl/t-WJCd296DVL
[Log_2024-04-28_18-01-22.txt](https://github.com/anddea/revanced-patches/files/15142923/Log_2024-04-28_18-01-22.txt)

**Comment by tyw7** [comment]
> > Download logcat app, capture and share crash error (search YouTube in the logcat app logs and when you see red, copy and share it here).
> 
> Thanks for the quick respond. I have never came across "logcat" app or even know what it is. Could you please add a link where I can download it? I searched on Google Play Store and there some options. Dont know exactly which one to download? It must be free.

I used https://play.google.com/store/apps/details?id=scd.lcex&hl=en_US

Maybe attach your Patched app to help @anddea diagnose it on their end.

Also, what patches are you using?

**Comment by anddea** [comment]
I use all patches and can't reproduce it. 

https://play.google.com/store/apps/details?id=com.dp.logcatapp

**Comment by tyw7** [comment]
> I use all patches and can't reproduce it.
> 
> https://play.google.com/store/apps/details?id=com.dp.logcatapp
> 
> I think any logcat will do. Just start it before you open YT.

I don't see YouTube in the logs though.  To help you, I have attached the apk.  And the Core I'm using is https://github.com/ReVanced/GmsCore/releases

**Comment by anddea** [comment]
What is the package name of your YouTube app?

What patch version do you use?

**Comment by tyw7** [comment]
> What is the package name of your YouTube app?
> 
> What patch version do you use?

See https://github.com/anddea/revanced-patches/issues/394#issuecomment-2081558745

Using the APK from https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-16-38-release/youtube-19-16-38-android-apk-download/

**Comment by anddea** [comment]
Update to latest dev patches 2.224.1-dev-5. you use dev integrations that is incompatible with stable patches.

**Comment by tyw7** [comment]
> Update to latest dev patches 2.224.1-dev-5. you use dev integrations that is incompatible with stable patches.

Unfortunately Revanced Manager can't exclude dev integrations, at least I can't find within the options.

**Comment by tyw7** [comment]
This is the changelog of the patch used, according to the Revanced manager.  This may help to recognize which patch it belongs to:
![Screenshot_20240428_191852_ReVanced Manager](https://github.com/anddea/revanced-patches/assets/14168657/8419c5f7-314c-4244-bf69-a52a8e79c242)

**Comment by tyw7** [comment]
> Update to latest dev patches 2.224.1-dev-5. you use dev integrations that is incompatible with stable patches.

Can you push Dev 5 to stable so I can see if I can fetch it?

**Comment by tyw7** [comment]
> > > > Download logcat app, capture and share crash error (search YouTube in the logcat app logs and when you see red, copy and share it here).
> > > 
> > > 
> > > Thanks for the quick respond. I have never came across "logcat" app or even know what it is. Could you please add a link where I can download it? I searched on Google Play Store and there some options. Dont know exactly which one to download? It must be free.
> > 
> > 
> > I used https://play.google.com/store/apps/details?id=scd.lcex&hl=en_US
> > Maybe attach your Patched app to help @anddea diagnose it on their end?
> > Also, what patches are you using?
> 
> How do you use that app Logcat Extreme? I press record the open Youtube then back to Logcat and stop recording but I cant find anything related to Youtube in the log. What am I doing wrong. Do I need root?

I don't know either.  I, too, don't see anything related to YouTube in the log.  That's why I uploaded the patched APK as well so @anddea can dissect it themselves.

**Comment by anddea** [comment]
Use RVX Manager. It should be a bug of Manager that it it shows dev integrations for stable patches. 

https://github.com/inotia00/revanced-manager/releases

**Comment by tyw7** [comment]
> Use RVX Manager. It should be a bug of Manager that it it shows dev integrations for stable patches.
> 
> https://github.com/inotia00/revanced-manager/releases

"Bug" reported: https://github.com/ReVanced/revanced-manager/issues/1887

**Comment by tyw7** [comment]
@anddea Inotia's patch is pulling in Dev5 though.

**Comment by tyw7** [comment]
> > @anddea Inotia's patch is pulling in Dev5 though.
> > ![Screenshot_20240428_195619_ReVanced Extended](https://private-user-images.githubusercontent.com/14168657/326286960-935c8cec-850c-4bd8-ac7c-e458012fa2c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzEwMzAsIm5iZiI6MTcxNDMzMDczMCwicGF0aCI6Ii8xNDE2ODY1Ny8zMjYyODY5NjAtOTM1YzhjZWMtODUwYy00YmQ4LWFjN2MtZTQ1ODAxMmZhMmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE4NTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzNmZjdlYmVkNDNmZTRhNTA2MzI1MjQ0YmNhZjI4MTY4YzU4OGNlN2VlNDE1NjliMGEzNTgyOTEzNGMwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qOqVJwRD2jw22utAoR_8-FVOnhl1HH_fBMJLieqgUU0)
> 
> It dont crash now when I used RVX Manager. Should I not use RVX Manager? What the downside using Dev patches?

No idea. I thought that patches with the word "dev" in front aren't ready for prime time ie dev build vs stable build but Anddea might be using a different naming scheme.

**Comment by anddea** [comment]
Dev is mostly stable too, but it's better to test dev and if something's broken then fix it until it goes stable.

Currently, the problem is that you wanted to use stable where patches are stable actually but integrations are not which causes crash as they are incompatible. 

Yes, change sources to anddea to use these patches and integrations.

**Comment by tyw7** [comment]
> Dev is mostly stable too, but it's better to test dev and if something's broken then fix it until it goes stable.
> 
> Currently, the problem is that you wanted to use stable where patches are stable actually but integrations are not which causes crash as they are incompatible.
> 
> Yes, change sources to anddea to use these patches and integrations.

Can you try to diagnose the problem with Revanced Manager and maybe post a detailed diagnosis so the devs of that app can fix it?

Even Inotia's manager is pulling in a dev build for both patches and integrations.

**Comment by selfmusing** [comment]
What's the exact issue you guys are facing now?

**Comment by tyw7** [comment]
Apparently, both Inotia's and Revanced Manager pull in the dev version of the integrations.  Inotia Manager pulls in the dev patches as well, but the Revanced Manager only pulls in the stable patches.

And @anddea says the crash could be caused by a mismatch between stable patches and dev integration.  Inotia's version kinda fixes this by using both dev patches and dev integration, but don't think this is the intended behavior.

**Comment by selfmusing** [comment]
> Apparently, both Inotia's and Revanced Manager pull in the dev version of the integrations. Inotia Manager pulls in the dev patches as well, but the Revanced Manager only pulls in the stable patches.
> 
> And @anddea says the crash could be caused by a mismatch between stable patches and dev integration. Inotia's version kinda fixes this by using both dev patches and dev integration, but don't think this is the intended behavior.

Try this fork of rvx manager : https://github.com/Francesco146/revanced-manager

It even has a toggle to enable or disable pre-release patches .

![IMG_20240429_012949_596](https://github.com/anddea/revanced-patches/assets/109387456/e4f0b811-bc6b-4d93-816e-b231415948c7)

**Comment by selfmusing** [comment]
> Dev is mostly stable too, but it's better to test dev and if something's broken then fix it until it goes stable.
> 
> Currently, the problem is that you wanted to use stable where patches are stable actually but integrations are not which causes crash as they are incompatible.
> 
> Yes, change sources to anddea to use these patches and integrations.

Btw , I've tried the latest dev patches.
YT doesn't crash for me anymore with append timestamp.
But it's crashing for some users to whom i gave the same patched.apk for testing.

💀 Unfortunately , I haven't got any logs from any of them ...

**Comment by anddea** [comment]
> but don't think this is the intended behavior.

For RVX Manager it's intended behavior. Dev releases were enabled there always. 

> But it's crashing for some users to whom i gave the same patched.apk for testing.

Maybe they have to clear their cache and data.

**Comment by anddea** [comment]
Just to notify you, the bug of the Manager is fixed now.

**Comment by tyw7** [comment]
Even without a new version neijg pushed?

**Comment by anddea** [comment]
You need to use the latest dev release of ReVanced Manager.

https://github.com/ReVanced/revanced-manager/releases/tag/v1.21.0-dev.2

And everything after it should work as well.

**Comment by selfmusing** [comment]
> > Apparently, both Inotia's and Revanced Manager pull in the dev version of the integrations. Inotia Manager pulls in the dev patches as well, but the Revanced Manager only pulls in the stable patches.
> > And @anddea says the crash could be caused by a mismatch between stable patches and dev integration. Inotia's version kinda fixes this by using both dev patches and dev integration, but don't think this is the intended behavior.
> 
> Try this fork of rvx manager : https://github.com/Francesco146/revanced-manager
> 
> It even has a toggle to enable or disable pre-release patches .
> 
> ![IMG_20240429_012949_596](https://private-user-images.githubusercontent.com/109387456/326290280-e4f0b811-bc6b-4d93-816e-b231415948c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDQwODEsIm5iZiI6MTcxNDQwMzc4MSwicGF0aCI6Ii8xMDkzODc0NTYvMzI2MjkwMjgwLWU0ZjBiODExLWJjNmItNGQ5My04MTZlLWIyMzE0MTU5NDhjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNTE2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjczNjRhNTA4MjI4YTlmODUwYzU4Y2EyYmVmMmQ4MTBkNjYxMzRmNGFiYTg3NWQzMGYxNTc4YTgzNWQ4NTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eMsdoreholInIEpp12-erA1wBEvWV18QN4p6QvkhRRY)

have you tried this @BAXSD ?
