### ISSUE TITLE
question:  How to use other icon options for "Revanced Extended" settings

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#395]
### Application

YouTube

### Question description

![Screenshot_2024_0428_233723](https://github.com/anddea/revanced-patches/assets/93650504/ab3ad47b-4d23-4383-9dcd-da20821e0339)

How to use other icons specified in this...there is always a extension icon while patching with stock icon and name.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
If you use Manager just open "Settings" patch and there will be dropdown menu.

**Comment by Vipin2003** [comment]
> If you use Manager just open "Settings" patch and there will be dropdown menu.

And what about rvx builder and revancify?

**Comment by anddea** [comment]
Yes, just write one of the mentioned options that is specified in changelog in parentheses (Extension, Gear...). Additionally there's also "ReVanced Colored" option.

**Comment by Vipin2003** [comment]
![Screenshot_2024_0429_135057](https://github.com/anddea/revanced-patches/assets/93650504/a8067e33-cf19-463a-9a9d-5a2977f2fe6c)

Now tell me what to write in PatchName, Key and Value for that.

**Comment by anddea** [comment]
It's not the option for Extended icon in Settings. Delete or rename old option file so it can generate new one.

**Comment by Vipin2003** [comment]
> It's not the option for Extended icon in Settings. Delete or rename old option file so it can generate new one.
> 
> On your screenshot, it shows YT Music, but the `Visual preferences icons` patch is available only for YouTube.

It's just for asking....How can I delete the options file....Do I have to clean install the rvx-builder?

**Comment by anddea** [comment]
There should be options.json file that you have to delete, reinstalling rvx-builder without deleting everything related to it won't help you.

**Comment by Vipin2003** [comment]
> There should be options.json file that you have to delete, reinstalling rvx-builder without deleting everything related to it won't help you.

No issues rn...As I reinstalled complete termux. After which it shows all the options including this too. Thanks for the idea
