### ISSUE TITLE
bug: Both `fullscreen button` and `chapters in player bottom UI container` are visible when settings are imported

### ISSUE THREAD

**Issue by Kuddus73** [anddea/revanced-patches#4]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Patches v2.220.8a3

### Bug description

If you import the settings, the full screen button and the chapters in player bottom UI container aren't hidden any more.

### Solution

**Add toggles for both options in settings.**

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you provide more details? Like what settings are you importing? Or any other useful information? Because I can't reproduce this issue.
