### ISSUE TITLE
bug (YT) : Slight misalignment between overlay button & time stamp.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#40]
### Type

Cosmetic

### Tools used

Revancify

### Application

v19.09.37

### Bug description

![1710339703603](https://github.com/anddea/revanced-patches/assets/91815107/062ab542-0e54-4250-9c0a-6f337320aff0)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
They are intentionally vertically aligned to the bottom. One of the reasons is chapter-buttons overlap that people encountered previously.

**Comment by Aryan-Chauhan** [comment]
> They are intentionally vertically aligned to the bottom. One of the reasons is chapter-buttons overlap that people encountered previously.

Please see this. The "time stamp + Quality" unit should be just a tad bit up.
![Screenshot_2024-03-13-20-28-14-51_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/anddea/revanced-patches/assets/91815107/d00ae730-8ce7-4de4-a6f3-26eefa8456e1)

**Comment by anddea** [comment]
Will move 1 dip up in the next release. Not sure when though.

**Comment by Aryan-Chauhan** [comment]
> Will move 1 dip up in the next release. 

Thank you!

**Comment by Aryan-Chauhan** [comment]
> Will move 1 dip up in the next release.

Hi, sorry for sending a notification on a closed issue, but can you solve this bug in next release?

**Comment by anddea** [comment]
It's already moved up 1dip in previous releases.

**Comment by Aryan-Chauhan** [comment]
> It's already moved up 1dip in previous releases. 

I think 1 dip more is required.
Video link: https://youtu.be/vB2m1uRF30c
![Screenshot_2024-03-22-13-37-26-46_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/anddea/revanced-patches/assets/91815107/c8dc9025-666a-4e26-b864-44d6bf86321e)

**Comment by anddea** [comment]
1dip is not that big, please test yourself every padding and open Pull Request with your changes.

**Comment by Aryan-Chauhan** [comment]
> 1dip is not that big, please test yourself every padding and open Pull Request with your changes. 

Can you explain to me in brief how to do that?

**Comment by anddea** [comment]
You have to build patches yourself for that. Don't worry, I'll test it myself when I have time.

**Comment by anddea** [comment]
@Aryan-Chauhan, I increased padding for 1 more dip.

**Comment by Aryan-Chauhan** [comment]
> @Aryan-Chauhan, I increased padding for 1 more dip.

Thank you.
