### ISSUE TITLE
bug: Voice search button does not appear

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#403]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.38
patch      2.225.0-dev.1

### Bug description

The voice search button in the upper right corner does not appear.

All settings in the applied Patch and revanced are defaults.

### Device Environment

android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can't reproduce, make sure you excluded `Hide voice search button` patch (it's included by default, react here to change defaults https://github.com/anddea/revanced-patches/discussions/308#discussioncomment-9106492), if you clean installed then restart the app so it loads the new interface.
