### ISSUE TITLE
question: what is comments button disabled or with label "0"?

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#404]
### Application

YouTube

### Question description

It's hard to translate without knowing what it is.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by odkate** [comment]
disabled comments
![Screenshot_20240430-093637](https://github.com/anddea/revanced-patches/assets/90364108/d811c43d-c4fe-46ab-bf48-31af6440a2af)
with label \"0\"
![Screenshot_20240430-093723](https://github.com/anddea/revanced-patches/assets/90364108/0a159021-4b4f-46a3-8963-74eea16e6e79)

**Comment by zerozero0022** [comment]
thanks
