### ISSUE TITLE
bug: Append Time Stamp Information displayed incorrectly on Arabic interface

### ISSUE THREAD

**Issue by iBasim** [anddea/revanced-patches#405]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 19.16.38

### Bug description

When the device's primary language is Arabic, Time Stamp Information (Video quality or playback speed), information displayed interlaced

Revanced Extended>SeekBar>Append Time Stamp Information(Enabled)

![Screenshot_20240430_090845_anddea youtube_edit_60426309565778](https://github.com/anddea/revanced-patches/assets/57762287/239b16cc-ac02-4aaf-a4ad-8ece617d18f6)
![Screenshot_20240430_090806_anddea youtube_edit_60442458384525](https://github.com/anddea/revanced-patches/assets/57762287/c2b77597-2095-4c4f-8d43-9f6a189ad37d)

The problem did not exist with inotia00 Patches

### Device Environment

on tow mobile
Huawei P30 Android 10
Samsung Galaxy S24 Ultra Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
When did it change? Patches version?

**Comment by iBasim** [comment]
Thank You!
I have been using it for about a month, and the problem has been present since the first version I used. Unfortunately, I do not know its version number.

**Comment by anddea** [comment]
It should be fixed now. Test it and let me know.

**Comment by iBasim** [comment]
Confirm it has been fixed, thank you very much

**Comment by anddea** [comment]
Btw, selfmusing reported this issue but lately I have troubles with time.
