### ISSUE TITLE
feat(YouTube - Disable landscape mode): Restore old landscape layout of Shorts

### ISSUE THREAD

**Issue by odkate** [anddea/revanced-patches#408]
### Application

YouTube

### Feature description

On YouTube version 18.25.40 and lower, the landscape layout of Shorts looks normal:
![Screenshot_20240430-162826](https://github.com/anddea/revanced-patches/assets/90364108/e469c479-f7e1-4099-a67b-3f27d42c49fe)
In newer versions, the layout is stretched and cropped:
![Screenshot_20240430-160458](https://github.com/anddea/revanced-patches/assets/90364108/3a3817c5-ac63-498b-9a65-79687c06eb08)

### Motivation

It's convenient to watch Shorts in landscape mode when you can't use the device in portrait mode

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by odkate** [comment]
> Shorts

To make the video normal full screen in Shorts, press the search button🔍 and the back button🔙

**Comment by Francesco146** [comment]
> To make the video normal full screen in Shorts, press the search button🔍 and the back button🔙

it might not showing up in my device. 

the navigation bar is also part of the problem:


https://github.com/anddea/revanced-patches/assets/49027005/ae6f53d2-8315-44d9-a380-03d43224339a

**Comment by odkate** [comment]
> not showing up in my device.

Turn on in the shorts settings


> navigation bar is also part of the problem

This is a bug in the hide_shorts_player_navigation_bar patch, but it has an experimental flag, so no one wants to fix it

**Comment by Francesco146** [comment]
worth noting that this behavior has been fixed in newer versions on yt

**Comment by odkate** [comment]
> newer versions on yt

What's the version number?

**Comment by Francesco146** [comment]
i tested the latest supported one

**Comment by odkate** [comment]
> latest supported

I tried YouTube v19.21.40, the image is still stretched and cropped

**Comment by Francesco146** [comment]
must be still in testing, now I'm unable to play Shorts in landscape mode
