### ISSUE TITLE
New YTmusic version support

### ISSUE THREAD

**Issue by Xisrr1** [anddea/revanced-patches#411]
Some patches are broken on 6.50.x

**Comment by selfmusing** [comment]
> Some patches are broken on 6.50.x

can you share patchlog or screenshot of patch screen ?

**Comment by Xisrr1** [comment]
> > Some patches are broken on 6.50.x
> 
> can you share patchlog or screenshot of patch screen ? (actually I have not tried this version , so I am just curious what's broken)
> 

Only _Enable zen mode_ and _Enable color match player_ have failed for me.

**Comment by selfmusing** [comment]
> > > Some patches are broken on 6.50.x
> > 
> > 
> > can you share patchlog or screenshot of patch screen ? (actually I have not tried this version , so I am just curious what's broken)
> 
> Only _Enable zen mode_ and _Enable color match player_ have failed for me.

BRUHHH!! 
![Screenshot 2024-05-01 213202](https://github.com/anddea/revanced-patches/assets/109387456/7d09b50c-93e3-4dc2-a5ea-bff04ff9be84)
![Screenshot 2024-05-01 213147](https://github.com/anddea/revanced-patches/assets/109387456/9f03a106-d9e7-406a-8d8f-1356505cfe15)

**Comment by Xisrr1** [comment]
Oh. There is another problem, I label is not hidden on player buttons.

**Comment by selfmusing** [comment]
> Oh. There is another problem, label is not hidden on player buttons.

screenshot?

**Comment by Xisrr1** [comment]
> > Oh. There is another problem, label is not hidden on player buttons.
> 
> screenshot?
> 

I restarted the app and now it's hidden... I guess you can patch.
