### ISSUE TITLE
Reddit app not opening any links or notifications it's supposed to.

### ISSUE THREAD

**Issue by Mesazane** [anddea/revanced-patches#417]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Reddit 2024.17.0

### Bug description

Opening reddit links doesn't lead to the app(even though I already toggled it on in the default apps settings). Also, tapping any reddit notifications just lead you to the homepage for some reason.

### Device Environment

Android 13, One UI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Unfortunately, I couldn't reproduce this issue. It works as expected for me.

**Comment by anddea** [comment]
Check the latest release, if you still face this issue.
