### ISSUE TITLE
bug: ReVanced Extended stopped working

### ISSUE THREAD

**Issue by RoonMoonlight** [anddea/revanced-patches#418]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.05.36 and above

### Bug description

When I play any of videos, there is infinity buffering loop and does not play at all. It happens regardless of which YouTube versions to patch. I'm using the default patch options. Additionally this one might be related with this issue: https://github.com/ReVanced/revanced-patches/issues/3113

### Device Environment

Android 14 / One UI 6

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Sergio0Eazzy** [comment]
I have the same problem.
Version 19.16.38.

**Comment by NickDeBeenSAE** [comment]
Same issue with myself.

This app just crashes.

**Comment by NickDeBeenSAE** [comment]
My version is 19.0.43

**Comment by Francesco146** [comment]
it's a YouTube server side issue. currently all versions of ReVanced are affected, but not all users.

**Comment by Alistair1231** [comment]
> it's a YouTube server side issue. currently all versions of ReVanced are affected, but not all users.

Seems like it may  not be. Osumatrix from Revanced is investigating it now apparently. Also, anecdotal evidence from me (with YT Premium in case that matters somehow), this only happens in revanced, in anddea revanced extended or normal revanced. As soon as I go into the real yt app it works fine.

https://github.com/ReVanced/revanced-discussions/discussions/1037#discussioncomment-9307345

**Comment by Cast0r-999** [comment]
> > it's a YouTube server side issue. currently all versions of ReVanced are affected, but not all users.
> 
> Seems like it may not be. Osumatrix from Revanced is investigating it now apparently. Also, anecdotal evidence from me (with YT Premium in case that matters somehow), this only happens in revanced, in anddea revanced extended or normal revanced. As soon as I go into the real yt app it works fine.
> 
> [ReVanced/revanced-discussions#1037 (comment)](https://github.com/ReVanced/revanced-discussions/discussions/1037#discussioncomment-9307345)

Of course it works in official app, because Google try to block Youtube mods. This is 5 wave of blocking modified apps. Seems repetitive, every end of a month. Maybe at the end of 2024 they get bored... 😂

**Comment by RoonMoonlight** [comment]
Hey guys, so there seems to be temporary workaround for YouTube not playing any videos. Seems there is issue related to SafetyNet in YouTube and it needs to be disabled. Unfortunately this workaround requires re-login so keep that in mind.

> WARNING: Before reinstalling, make sure you download the backup file by exporting on ReVanced Settings before proceeding.

1. Reinstall or reset the microG that you installed from YT-Advanced and anddea patched YouTube app.
2. Open the YT-Advanced MicroG settings and go to `Google SafetyNet`.
3. Disable `Allow device attestation` and go back.
4. Click on `Google Accounts`, `Add account` and login with your Google Account.
5. Open YouTube and import your settings data, play any of videos.

Please note that this is unofficial, temporary workaround and it is not guaranteed to be working.

**Comment by odkate** [comment]
> working

After these manipulations, only Shorts started working

**Comment by RoonMoonlight** [comment]
> After these manipulations, only Shorts started working

Yeah this method only works for some people unfortunately, and does not work for everyone (I tried this method as well and only little bit worked)

**Comment by Android-PowerUser** [comment]
NewPipe v0.25.2 still works without logging in. Maybe Google wants to kill accounts soon because it is legally difficult to take action against these patches.

**Comment by anddea** [comment]
> NewPipe 

NewPipe is an alternative client, but ReVanced is a modification of the official YouTube app. You won't notice these problems if you install root version of ReVanced. It has to do with signature and currently it's the problem of GmsCore. Probably it can be fixed with patches somehow as well, but currently we have to investigate it. For example, before we had spoof player parameters (which was inspired by the code of NewPipe), ReVanced's YouTube didn't work for weeks and even months for some people. 

When I say ReVanced, I also refer to RVX.

**Comment by alpha-adil** [comment]
Facing same issue, please fix asap 🥺

**Comment by Android-PowerUser** [comment]
How do you get the root version?

**Comment by Android-PowerUser** [comment]
I have root

**Comment by Vertuhai** [comment]
It takes a long time for me to load a video, it can work for about 5 minutes and then freeze on endless loading.
Which is very upsetting.

**Comment by alpha-adil** [comment]
Guysss any solutionn... ?

**Comment by Francesco146** [comment]
fixed in RVX, using test client or newpipe data stream
