### ISSUE TITLE
suggestion: Update Italian translations (string.xml)

### ISSUE THREAD

**Issue by Kuddus73** [anddea/revanced-patches#42]
### Application

YouTube

### Suggestion description

Added translations to missing strings:
[strings.xml](https://mega.nz/file/cHIynLzZ#BWeiRTwWEqTvkB7EwK0SzY-f4MVzNXsVhdczf0-3Cvs)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Missing strings:

```xml
<string name="revanced_change_start_page_entry_browse">Browse channels</string>
<string name="revanced_change_start_page_entry_gaming">Gaming</string>
<string name="revanced_change_start_page_entry_live">Live</string>
<string name="revanced_change_start_page_entry_movies">Movies</string>
<string name="revanced_change_start_page_entry_music">Music</string>
<string name="revanced_change_start_page_entry_sports">Sports</string>
<string name="revanced_change_start_page_entry_watch_later">Watch later</string>
<string name="revanced_keyword_invalid_length" formatted="false">Invalid keyword length (must be at least %s characters): %s.</string>
<string name="revanced_keyword_filter_strings_summary">Configure keywords and phrases to hide, separated by new lines

Words with uppercase letters in the middle must be entered with the casing (ie: iPhone, TikTok, LeBlanc).</string>
<string name="revanced_keyword_filter_strings_title">Edit keyword filter</string>
<string name="revanced_keyword_filter_summary_off">Keyword filter is disabled.</string>
<string name="revanced_keyword_filter_summary_on">Keyword filter is enabled.</string>
<string name="revanced_keyword_filter_summary">Hides feed and search result videos using keyword filters.</string>
<string name="revanced_keyword_filter_title">Enable keyword filter</string>
```

If you want, you can open Pull Request with your updates and I will merge it.

**Comment by ZeroZero0011** [comment]
you're not thinking about crowdin, are you?

**Comment by anddea** [comment]
> not thinking about crowdin

Not really. I wish someone could do this for me. Also, maybe weblate or something, I know that weblate can be integrated with Github to automatically create Pull requests, although I've never used it.

**Comment by Kuddus73** [comment]
> If you want, you can open Pull Request with your updates and I will merge it.

Dunno how to do PRs, but updated the translations of the missing strings:
[strings.xml](https://mega.nz/file/4WJDlZqQ#EAWuLSzdcNeOLhC-_krYhH1gGvqMfSjvHDm9Gavtq-Q)

**Comment by Kuddus73** [comment]
> If you want, you can open Pull Request with your updates and I will merge it.

Dunno how to do PRs, but translated the new missing strings:
[strings.xml](https://mega.nz/file/4WJDlZqQ#EAWuLSzdcNeOLhC-_krYhH1gGvqMfSjvHDm9Gavtq-Q)

**Comment by ZeroZero0011** [comment]
1. Download Eng Xml & your language XML
2. Found the newly updated text in ReX anddea ver app
3. Found the line containing it in the Eng XML, copied it
4. Paste the line into your language XML file
5. Translate newly updated text and save
6. Update Edited XML files in your cloud drive and share the file with your developer.

Your Language XML
Eng XML
- https://github.com/anddea/revanced-patches/blob/main-rex/src/main/resources/youtube/settings/host/values/strings.xml

Your Language XML
- https://github.com/anddea/revanced-patches/tree/main-rex/src/main/resources/youtube/translations/...

**Comment by Kuddus73** [comment]
> but translated the new missing strings: [strings.xml](https://mega.nz/file/4WJDlZqQ#EAWuLSzdcNeOLhC-_krYhH1gGvqMfSjvHDm9Gavtq-Q)
> 
> Let me know if there's any other missing string.

@anddea is it fine?

**Comment by anddea** [comment]
Everything is fine, there are strings that were edited earlier (with better clarification), check them also, if you wanna edit 'em in your translation.

```xml
<string name="revanced_hide_gray_description_summary_off">"Gray description is shown.
• From your Watch Later playlist.
• People also watched this video.
• Channel viewers also watch this channel, etc."</string>
<string name="revanced_hide_gray_description_summary_on">"Gray description is hidden.
• From your Watch Later playlist.
• People also watched this video.
• Channel viewers also watch this channel, etc."</string>

<string name="revanced_append_time_stamp_information_type_summary_off">Append playback speed. Tap and hold on timestamp to change the type while playing the video.</string>
<string name="revanced_append_time_stamp_information_type_summary_on">Append video quality. Tap and hold on timestamp to change the type while playing the video.</string>
```

@ZeroZero0011 if you want, you can update them too.

**Comment by ZeroZero0011** [comment]
• From your Watch Later playlist.
• People also watched this video.
• Channel viewers also watch this channel, etc.

What do these three lines have to do with the grey description? I don't understand.

**Comment by anddea** [comment]
> What do these three lines have to do with the grey description? I don't understand.

I don't think anyone knows what does that "gray description" even mean.

So, this is a clarification, maybe you can come up with a better name and description.

https://github.com/inotia00/ReVanced_Extended/issues/455.

**Comment by ZeroZero0011** [comment]
The translation related to timestamps has been added to the Korean translation for a while now, so I'll update it after the next update after checking the 3 gray descriptions.
