### ISSUE TITLE
bug: Headers of Channel Home tab sections are missing because of hiding Shorts

### ISSUE THREAD

**Issue by Spaceshiprace** [anddea/revanced-patches#426]
### Application

YouTube

### Question description

I need help, How can i fix that
![Screenshot_2024-05-05-23-15-18-992_org mozilla firefox_1_1](https://github.com/anddea/revanced-patches/assets/156727749/0b54fde6-5e67-40c0-bea7-4d1d44c31be2)
![Screenshot_2024-05-05-23-17-11-582_anddea youtube_1_1](https://github.com/anddea/revanced-patches/assets/156727749/f2f42a24-5963-403f-bdc2-b099cdbc0558)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by zerozero0022** [comment]
When Shorts Shelf is hidden, that label is also hidden.
It's a bug.

**Comment by anddea** [comment]
Tbh, I couldn't understand what's wrong? More explanation maybe? Is it something that should be fixed?

**Comment by zerozero0022** [comment]
enable 'Hide Shorts in home feed'
-> If you enter your channel profile from Home tab, you'll see that label is gone.

enable 'Hide Shorts in subscriptions feed'
-> If you enter your channel profile from subscription tab, you'll see that label is gone.

enable 'Hide Shorts in search results'
-> If you enter your channel profile from search results, you'll see that label is gone.

**Comment by zerozero0022** [comment]
enable 'Hide Shorts in home feed'
-> The label on channel profile from Home tab is disappeared.

enable 'Hide Shorts in subscriptions feed'
-> The label on channel profile from subscription tab is disappeared.

enable 'Hide Shorts in search results'
-> The label on channel profile from search results is disappeared.

**Comment by anddea** [comment]
This should be fixed now with the latest integrations update. Let me know if you face any issues.
