### ISSUE TITLE
bug: Video Buffering 

### ISSUE THREAD

**Issue by himanshusaini26** [anddea/revanced-patches#427]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

v19.16.38

### Bug description

When I _try to play any video or short it shows loading for infinity time_. When I enabled spoof player parameter it shows this content is not available on YouTube ! 

### Device Environment

Android 14, Evolution-X

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by odkate** [comment]
> * This issue is not a duplicate of an existing bug report.

https://github.com/anddea/revanced-patches/issues/418
🙄🤨

**Comment by Francesco146** [comment]
duplicate of #418. this issue should be closed
