### ISSUE TITLE
question: What is "Force Snackbar Theme" do?

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#429]
### Application

YouTube

### Question description

Recently u have added this patch...But I didn't understand what this patch does. And what does the "Backgroud Color" "corner radius" in that patch. Can u explain with some SS.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
https://github.com/anddea/revanced-patches/issues/357

It just changes the background color, stroke color and corner radius.

**Comment by Vipin2003** [comment]
Now I got it...Thamks
