### ISSUE TITLE
bug (YT) : Community Posts aren't hiding in Subscriptions Feed & Related Videos Feed.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#43]
### Type

Cosmetic

### Tools used

Revancify

### Application

YT v19.09.37

### Bug description

Some additional information that might be insightful:

• It is happening 6 out of 10 times.

• If Community Posts are appearing in subscriptions feed & then you refresh the feed, they disappear.

• If Community Posts are appearing in related videos feed & then you close the video and then re-open it, they disappear.

• While scrolling subscriptions feed, I encounter those posts, then I ignore them & scroll away. Now, when I scroll up to find them, I realize that they've hidden themselves automatically. I don't know how useful this point is, but this is happening everyday.

• I've seen community posts appear in Feeds, then they hide/close/collapse themselves right before my eyes. When I encounter them, I keep them on screen for 2-3 seconds & they hide/close/collapse themselves right before my eyes.

• All above points were happening in @YT-Advanced patches as well.
![Screenshot_2024-03-14-07-21-19-37_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/118ec826-f795-4c98-8d2f-8cadfc8bee46)

### Error logs

```shell
No logs.
```

### Solution

Hide Community Posts in Home Feed, Subscriptions Feed & Related Videos Feed should work as before.

### Additional context

Given in Bug Description section.

### Device Environment

Realme 7 Pro
Android 12
Skin name: Realme UI 3.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
https://github.com/YT-Advanced/ReX-integrations/releases/tag/v0.146.2

**Comment by anddea** [comment]
It is implemented in the [latest integrations](https://github.com/anddea/revanced-integrations/releases/tag/v0.147.1) as you already know.

**Comment by Aryan-Chauhan** [comment]
> It is implemented in the [latest integrations](https://github.com/anddea/revanced-integrations/releases/tag/v0.147.1) as you already know.

Yes, the first reaction was mine.

Thanks for the quick fix.

**Comment by smed79** [comment]
Community posts in subscriptions feed are not hidden for me using the patch [2.224.0](https://github.com/anddea/revanced-patches/compare/v2.223.0...v2.224.0) (2024-04-25)

YouTube v19.16.38
Android 14

- e.g. https://github.com/anddea/revanced-patches/assets/1873139/d269aa68-2532-4073-9b9f-e32a595df3ff

- settings https://github.com/anddea/revanced-patches/assets/1873139/e4c009a8-6076-4ba1-be47-9e6a70b73058
