### ISSUE TITLE
Patching Failed 

### ISSUE THREAD

**Issue by sultanmonsur** [anddea/revanced-patches#430]
### Application

YouTube

### Question description

[patch_log.txt](https://github.com/anddea/revanced-patches/files/15221729/patch_log.txt)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Same here.

**Comment by anddea** [comment]
What patching tools did y'all use? I know it's failing in the Manager for now, works with CLI.

**Comment by sultanmonsur** [comment]
I am using revancify (noon-root)

**Comment by racnes** [comment]
[patch_log.txt](https://github.com/anddea/revanced-patches/files/15225123/patch_log.txt)
same, latest dev patches with revancify fails, tried few minutes ago twice (revancify -r'ed and same).

**Comment by anddea** [comment]
It's failing because of patcher incompatibility, I'll fix it soon when I have time. I could just delete the latest dev release, but the same way you can also use previous release or stable.

**Comment by Francesco146** [comment]
you can solve this by:
* using the official [ReVanced Manager](https://github.com/ReVanced/revanced-manager) -- only stable releases
* using my sort-of-fork [ReVanced Manager](https://github.com/Francesco146/revanced-manager) -- supports dev and stable releases
* revancify [as soon as the main dev merge my PR](https://github.com/decipher3114/Revancify/pull/81)

**Comment by sultanmonsur** [comment]
Latest released dev not working with revancify.
I am trying recommend version.
It's failed.

**Comment by Francesco146** [comment]
> Latest released dev not working with revancify. I am trying recommend version. It's failed.

read what i wrote. it still need to merge my pr :(

**Comment by sultanmonsur** [comment]
I do not know why the shift to RV?
I used RVX and it didn't seem friendly to me.
Now you are suggesting an RV that I have never used.

**Comment by Vipin2003** [comment]
Yup..it fails. Even in Builder too. Complete error is :

```
[builder] INFO: Loading patches
[builder] INFO: Decoding app manifest
[builder] INFO: Excluding Change player flyout panel toggles
[builder] INFO: Excluding Force hide player chapters
[builder] INFO: Excluding Hide player buttons background
[builder] INFO: Excluding Force hide fullscreen button
[builder] INFO: Excluding Force hide collapse button
[builder] INFO: Excluding Force disable Shorts dim
[builder] INFO: Excluding Spoof player parameters
[builder] INFO: Excluding Hide animated button background
[builder] INFO: Excluding Hide double tap to like animations
[builder] INFO: Excluding Custom branding icon YouTube
[builder] INFO: Excluding Custom branding name YouTube
[builder] INFO: Excluding Force snackbar theme
[builder] INFO: Excluding Custom package name
[builder] INFO: Setting patch options
[builder] INFO: Merging integrations
[builder] INFO: Deleting existing resource cache directory
[builder] INFO: Decoding resources
[builder] INFO: Executing patches
[builder] Exception in thread "main"
[builder] java.lang.NoSuchMethodError: 'java.io.File app.revanced.patcher.data.ResourceContext.get(java.lang.String, boolean)' at app.revanced.patches.youtube.layout.splashanimation.AddSplashAnimationPatch.execute(AddSplashAnimationPatch.kt:65) at app.revanced.patches.youtube.layout.splashanimation.AddSplashAnimationPatch.execute(AddSplashAnimationPatch.kt:12) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
[builder] at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

**Comment by bober757** [comment]
In rvx-builder you can use 'ReVanced' organization for revanced-cli

**Comment by Vipin2003** [comment]
> In rvx-builder you can use 'ReVanced' organization for revanced-cli

Any difference in inotia's revanced cli and normal revanced cli

**Comment by Vipin2003** [comment]
Let's just wait for @inotia00 to update the builder.

**Comment by Francesco146** [comment]
> Let's just wait for @inotia00 to update the builder.

the builder works fine if you set CLI source to `ReVanced` and not `inotia00`

**Comment by anddea** [comment]
For now, I reverted back compatibility with RVX CLI as well.

**Comment by Francesco146** [comment]
when all the patching tools have corrected their CLI source, we can re-apply the thing

**Comment by arghya339** [comment]
> you can solve this by:
> * using my sort-of-fork [ReVanced Manager](https://github.com/Francesco146/revanced-manager) -- supports dev and stable releases

Sir, your ReVanced Manager broke keystore regenerate, import & export functionalities
Please fix, it's important for people who don't have 'core patch' ls patch module basically noon rooted users, Your RVX Manager repo don't allow to bug report, this why i'm wrote here, sorry for that. Best Regards.

**Comment by AbakNacchan** [comment]
If you're using CLI, I suggest you to use from j-hc instead.

**Comment by sultanmonsur** [comment]
How to use cli?
Anyone guide me?

**Comment by anddea** [comment]
> How to use cli

Manager and Revancify use it anyway, you don't have to use it manually if you're fine with them.

**Comment by Vipin2003** [comment]
> The only useful feature of RVX (cli and manager) (probably) is riplibs, other than that it's the same as far as it can be, because newer CLI and manager obviously fixed a lot of bugs and added new features, so it should be better.
> 
> As I said, it fails because of patcher incompatibility. Inotia should come back soon and will update everything, so it should be compatible then.
> 
> Sorry for this inconvenience but what should we expect from dev branch, right?
> 
> Either we revert back to old codebase for patches or wait for patching tools to be updated.
> 
> Also, you can use the Manager by Francesco for now.

Now inotia00 updated the rvx-builder and soon updating manager. So, we can shift to new codebase in stable release of patches

**Comment by Francesco146** [comment]
yes, inotia00 merged my pre-releases feature. I've archived my repo

**Comment by Vipin2003** [comment]
mmm... Like inotia has been returned and releasing patches in 2-3 days, are you going to keep your patches alive or going to archive it till inotia's again discontinuation announcement.? Or going to merge inotia's patches with yours.?

**Comment by Francesco146** [comment]
@anddea have to decide that. in my opinion it makes more sense to keep this project alive indefinitely. new patches that will be in the inotia00 repo will be put in this repo. patches that are already in this repo will remain here. inotia00 can at any time merge the missing parts into its repo.

**Comment by anddea** [comment]
I'll merge it at least for myself. But if he merges all patches from this repo there will be no reason for other people to come here anymore.

**Comment by AbakNacchan** [comment]
> I'll merge it at least for myself. But if he merges all patches from this repo there will be no reason for other people to come here anymore.

I guess he'$not merging any repo from here, and I'll stay with your repo instead.

**Comment by Vipin2003** [comment]
Ya...I think so. For merged, inotia need PR
