### ISSUE TITLE
bug: RVX can't find YouTube

### ISSUE THREAD

**Issue by Android-PowerUser** [anddea/revanced-patches#431]
### Type

Error while patching

### Tools used

RVX Manager and Revanced Manager

### Application

Current

### Bug description

It says no app found. But I have the original YouTube app installed and have RVX Manager and Revanced manager tried out.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Android-PowerUser** [comment]
was a bug in Android, sorry.

**Comment by zerozero0022** [comment]
If the status of ReVanced Manager and Patches in the ReVanced Manager dashboard is "Loading...", the ReVanced API is unavailable because the number of ReVanced API connections has been exceeded.

Please try again in an hour or so.
