### ISSUE TITLE
feat(YouTube - Spoof player parameters): Spoof player parameters  of the sponsored video

### ISSUE THREAD

**Issue by odkate** [anddea/revanced-patches#441]
### Application

YouTube

### Feature description

I found that the sponsored videos are
![Screenshot_20240509-012229](https://github.com/anddea/revanced-patches/assets/90364108/50f87ea1-0462-4e22-a99b-2c35782343e9)
not buffering and
![Screenshot_20240509-012245](https://github.com/anddea/revanced-patches/assets/90364108/40f7d4ba-8af8-407a-9b4a-34a49cdcdc36)
play normally until the end
![Screenshot_20240509-012525](https://github.com/anddea/revanced-patches/assets/90364108/dc1edcf0-4b17-4ade-b3fd-00fbf9fff3fd)

Therefore, Spoof the player parameters of regular videos to player parameters of sponsored videos

### Motivation

I think this way you can solve the Issue of video buffering

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
it might be resolved in RVX, by the introduction of test client and newpipe stream data

**Comment by anddea** [comment]
Spoof player parameters is deprecated now.
