### ISSUE TITLE
question:  Normal Talk

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#442]
### Application

YouTube

### Question description

As of now, inotia didn't merged too many patches from this repo and also he removed too many patches from his repo too. I don't think that inotia will merge most of the patches from here. Let's see as he is working and releasing some dev patches. You can merge some fixes and features he introduced like new tablet mini player, toggle fix, etc here.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I was planning to do that. But some changes may impact other features not to work anymore.

**Comment by Vipin2003** [comment]
I think that inotia will never going to merge some of your patches he removed in past...like Kije custom branding splash screen, Old overlay icons, etc. Bcoz also in past, he didn't do this. That's why.
