### ISSUE TITLE
feat: Option to hide Song/Video picker in the player (YTM)

### ISSUE THREAD

**Issue by bean-factory** [anddea/revanced-patches#444]
### Application

YouTube Music

### Feature description

Add option to hide the song/video switcher at the top of the player in the YouTube Music app. I think it may already be possible to do this through a custom filter but i was not able to find any discussion in this direction.

![Screenshot_20240510_113025_YouTube Music (Medium)](https://github.com/anddea/revanced-patches/assets/76696071/6ebcd0f9-9d9d-4b85-aa73-224bf7a4e0ae)
### Motivation

A lot of songs dont even have music video to go with them so the picker is pretty much useless and just clutters up the ui without providing any real functionality.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Can you also request this on inotia00's repository, since he currently accepts feature requests for RVX YT Music?

https://github.com/inotia00/ReVanced_Extended

**Comment by bean-factory** [comment]
Done
