### ISSUE TITLE
bug: Download stuck when loading all resources for YouTube patch.

### ISSUE THREAD

**Issue by Vertuhai** [anddea/revanced-patches#447]
### Type

Error while patching

### Tools used

rvx-builder

### Application

![2024-05-10 16_37_24-Downloading dependencies](https://github.com/anddea/revanced-patches/assets/136680660/078aa911-aa5a-49d5-a288-f084c1154820)
I sat like that 20 times and tried to load resources, but I couldn’t.
It starts loading and the process freezes either at the beginning or in the middle, or does not even start at all.

### Bug description

When downloading resources, it simply does not download.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Maybe GitHub rate limited you. But that should go away after some time. Try to change your sources in settings. Maybe reinstall builder. Or you can download resources manually.
