### ISSUE TITLE
suggestion: Opening PR in inotia's repo.

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#448]
### Application

YouTube

### Suggestion description

After a little talk with inotia, he is agreed to merge your patches but he said to open PR's for them. Ahh..I don't want to give you a trauma but, can you open pull requests for the introduced features there...Just mention all the features in one single PR, if it is possible. Here is the talk: https://github.com/inotia00/ReVanced_Extended/issues/1986#issue-2289862472
If I know how to work with PR, then definitely I'll do that, and let you disturb. But....

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by odkate** [comment]
> merge

inotia changed a lot the keys of strings, will have to rewrite a lot
🤔

**Comment by Vipin2003** [comment]
> > merge
> 
> inotia changed a lot the keys of strings, will have to rewrite a lot 🤔

Isn't there any way like you just create a new branch and some little change and then just put all features in a single PR? Change like a letter change in readme file.
You just have to create a single PR mentioning all the required Patches. Or I'll convince him to take them from issues. If he agrees then, I'll create them in issues.

**Comment by anddea** [comment]
Maybe when I have time. Too busy right now. Code should be adjusted to new refactored code, it is not hard but time consuming.

**Comment by Vipin2003** [comment]
Thanks brotherr... Try to go for it when you are free
