### ISSUE TITLE
bug: Ads still appear in youtube shorts

### ISSUE THREAD

**Issue by JakobHunterek** [anddea/revanced-patches#45]
### Type

Other

### Tools used

Revancify

### Application

Youtube 19.09.37

### Bug description

Ads still show up when viewing Youtube shorts even with all patch options enabled to Hide

### Additional context

Patches youtube using recommended patches in Revancify
Plus Material You
Minus Swipe Controls

### Device Environment

Android 14 OneUI 6.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ZeroZero0011** [comment]
turn off "Navigation - Switch create with notifications button".

**Comment by JakobHunterek** [comment]
It is off by default (create on bottom, notifi ation on top)

**Comment by JakobHunterek** [comment]
Okay, it worked. Thanks
