### ISSUE TITLE
feat(YouTube - Shorts): Play Shorts in Normal Video Player

### ISSUE THREAD

**Issue by Omega944** [anddea/revanced-patches#450]
### Application

YouTube

### Feature description

Add an option to play shorts using the same player as normal videos.

### Motivation

In a web browser, it is possible to force shorts to play like normal videos by editing the url, replacing the /shorts/ part by /watch?v= (This can be automated with the following userscript: https://greasyfork.org/es/scripts/439993-youtube-shorts-redirect )
I find the default video player interface more comfortable to use. As far as I know there is no way to do something like this currently.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AykhanUV** [comment]
Youtube vanced had that feature it was great

**Comment by YT-Advanced** [comment]
> Youtube vanced had that feature it was great

huh, what where when, how

**Comment by AykhanUV** [comment]
When you watch shorts then go to history you can view it like normal video

**Comment by Francesco146** [comment]
dup of https://github.com/anddea/revanced-patches/issues/763
