### ISSUE TITLE
question (YT) : What is the meaning of all options in `Force Snackbar Theme` patch?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#453]
CornerRadius is obvious, so no need to clarify.

What does "BackgroundColor" do? And, inside it, what is the meaning of `?ytChipBackground` and `?ytBaseBackground` ? And, what kind of custom value can I put in it?

What does "StrokeColor" do? And, inside it, what is the meaning of `None` , `Inverted` and `Accent` ? And, what kind of custom value can I put in it?

**Comment by anddea** [comment]
You can put any hex color there. 

Chip background color will use background color used for chips a little lighter than Base. 

Base is just the theme color used everywhere in the app. 

Both of them will match theme you select in the app, but if you put hex color it will use the same color for both light and dark themes. 

Stroke is just a stroke color, if you select Base background it will blend with the background, so stroke color will highlight the snackbar. Inverted use the inverted theme of the theme you use, light stroke for dark theme and vice versa. Accent is an accent color.
