### ISSUE TITLE
v2.225.0-dev10 does not support v18.49.37

### ISSUE THREAD

**Issue by kyan5221** [anddea/revanced-patches#456]
### Application

YouTube

### Question description

old v2.225.0-dev9 supports v18.49.37 but dev10 does not.
when I select v18.49.37. rvx manager shows all patch options have warnings of version compatible.
please check it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It's because there are few (kinda major) versions are used as compatible, but it should patch. If you have no error when patching, you're good to go. I can add more version but that's just on paper, and in reality they work for more intermediate versions.

**Comment by kyan5221** [comment]
ok no need to add version number thank you..
