### ISSUE TITLE
question: about Japanese translation

### ISSUE THREAD

**Issue by riolove1** [anddea/revanced-patches#458]
### Application

YouTube

### Question description

Hello! 
I'm rio, the one who sent the pull request. (I've talked to you before under the account "rio0723fck", but for some reason that account can't fork any repositories.) 
I'm working on a translation with akir45. I just sent a pull request, would you approve it? And could you remove the unnecessary strings?
Thank you.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by riolove1** [comment]
And do you have plans to open a project like crowdin in the future?

**Comment by anddea** [comment]
Hi. I will merge your translation but I suggest you to contribute translations on inotia's crowdin from now on. As it's going to be main source for translation except for unique strings.

> I've talked to you before

When and where?

**Comment by riolove1** [comment]
RVX #446 
[anddea](https://github.com/anddea) announced in [Announcements](https://github.com/anddea/revanced-patches/discussions/categories/announcements)
![Screenshot_20240514-204730464](https://github.com/anddea/revanced-patches/assets/169620657/2bf1b39f-d475-4cf5-9498-e808a3f4e41a)

**Comment by anddea** [comment]
Now I remember.

**Comment by riolove1** [comment]
> I will remove unused strings later.

Thank you. I'll be waiting.
