### ISSUE TITLE
bug: incorrect dislikes count on shorts

### ISSUE THREAD

**Issue by Berlinkk** [anddea/revanced-patches#459]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

Dislikes count on shorts shows incorrect number, however when I click on dislike button it shows correct number. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Open this issue in inotia's repo.

**Comment by Berlinkk** [comment]
Inotia's patches don't have this issue, this is specific to your patches

**Comment by anddea** [comment]
What version of inotia patches and integrations do you use? I just checked his patches and it has the same issue.

**Comment by Berlinkk** [comment]
Latest dev patches v4.8.0-dev.5 and integrations v1.9.0-dev.4

**Comment by anddea** [comment]
I see, I'll fix it later then. Thank you for your report.

**Comment by Berlinkk** [comment]
Thanks for your prompt response

**Comment by anddea** [comment]
Should be fixed, verify that.

**Comment by Berlinkk** [comment]
Yes, it is fixed. Thanks.
