### ISSUE TITLE
suggestion: Change the repo issue labels to work with the issue templates

### ISSUE THREAD

**Issue by KobeW50** [anddea/revanced-patches#46]
### Application

Other

### Suggestion description

In the [issue templates](https://github.com/anddea/revanced-patches/tree/main-rex/.github%2FISSUE_TEMPLATE), they automatically label issues for ypu when the available issues in the repository match with the first line in the issue forms.

Please check the issue forms and change them or the labels so that issues are automatically labeled in the future

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Added labels so it should work as intended for new issues.
