### ISSUE TITLE
bug(YouTube): shorts shelf hidden in home feed even though settings turned off

### ISSUE THREAD

**Issue by shreyjain1998** [anddea/revanced-patches#460]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

I have turned off `Hide shorts self` and even all it's sub settings but the shorts shelf is not visible only in the home feed.

![Screenshot_2024-05-14-20-44-52-735_anddea youtube-edit](https://github.com/anddea/revanced-patches/assets/107779107/0ec208ed-14bd-4baf-b318-f8091222717d)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Sometimes it happens, I'm not sure what's the reason, I guess it's based on the account, but it's a YouTube thing. I verified just now, it shows for me.
