### ISSUE TITLE
bug: Hide remix button is not working 

### ISSUE THREAD

**Issue by rsaurav12** [anddea/revanced-patches#468]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.38
Patches 2.224.0
Integration 0.151.0

### Bug description

Button player > Button container > hide remox button enable 

After enabling remix button is still showing 
![Screenshot_2024-05-15-16-15-40-444_anddea youtube](https://github.com/anddea/revanced-patches/assets/53332518/12e16445-bd94-402a-b79e-b7c934a34bbe)
![Screenshot_2024-05-15-16-15-49-596_anddea youtube](https://github.com/anddea/revanced-patches/assets/53332518/ad160f7b-bec5-4b6f-8c22-e1d8f45a8a0c)

### Device Environment

Android 12
Miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by rsaurav12** [comment]
> A/B testing. could you share the logs?

Sorry but i didn't patch debugging settings

**Comment by Francesco146** [comment]
i was able to reproduce the issue, the latest dev release solved this
