### ISSUE TITLE
feat (YT) : Overlay Button that opens up Captions Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#47]
### Application

YouTube

### Feature description

Please add an overlay button that, when clicked, opens up Captions Menu.
![Screenshot_2024-03-15-08-11-30-72_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/5f3640af-1f08-4135-b609-aa7b3a97405a)

### Motivation

• Captions Menu has equal importance to that of Playback Speed Menu, but only the latter has a dedicated overlay button (as of yet).

• It will save steps/taps for opening Captions Menu. Saving steps/taps was also the motivation behind Playback Speed Overlay Button, so Captions Menu should also get equal treatment.

• If implemented, large number of people will use it, just like they use Playback Speed Overlay Button.

• I've personally seen multiple positive comments on how convenient Playback Speed Overlay Button is, and the proposed button is also a convenient & practical one. So, that's why it should be implemented. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Creating that many Overlay buttons takes a lot of space which is going to be user unfriendly. 

Go to Settings > ReVanced > Player > Hide captions button (turn off that option). Captions button will appear at the top right corner of the player. You can tap to show/hide captions, and tap and hold to open the language selection menu.

**Comment by Aryan-Chauhan** [comment]
> Creating that many Overlay buttons takes a lot of space which is going to be user unfriendly. 
> 
> Go to Settings > ReVanced > Player > Hide captions button (turn off that option). Captions button will appear at the top right corner of the player. You can tap to show/hide captions, and tap and hold to open the language selection menu.

6 overlay buttons can easily be occupied on my Samsung Galaxy M31 (default font size, default screen zoom, default minimum width/smallest width). I'm going to use these 6:

1. Playback Speed (available)
2. Download (available)
3. Captions ( #47 )
4. Quality ( #49 )
5. Share ( #50 )
6. Save To Playlist ( #51 )

I genuinely believe that 5 or 6 overlay buttons will be user friendly, & users can enable/disable these buttons according to their preference.

Also, the reason for not using the default captions button in video player is, because it doesn't look symmetrical with reference to collapse button. 

So, please re-open this issue for the following reason:

_Users have the autonomy of enabling/disabling overlay buttons according to their preference and adding a Captions Overlay Button merely provides them a new choice, hence this request shouldn't be considered a user-unfriendly one._

**Comment by MondayNitro** [comment]
> > Creating that many Overlay buttons takes a lot of space which is going to be user unfriendly.
> > Go to Settings > ReVanced > Player > Hide captions button (turn off that option). Captions button will appear at the top right corner of the player. You can tap to show/hide captions, and tap and hold to open the language selection menu.
> 
> 6 overlay buttons can easily be occupied on my Samsung Galaxy M31 (default font size, default screen zoom, default minimum width/smallest width). I'm going to use these 6:
> 
> 1. Playback Speed (available)
> 2. Download (available)
> 3. Captions ( [feat (YT) : Overlay Button that opens up Captions Menu. #47](https://github.com/anddea/revanced-patches/issues/47) )
> 4. Quality ( [feat (YT) : Overlay Button that opens up Quality Menu. #49](https://github.com/anddea/revanced-patches/issues/49) )
> 5. Share ( [feat (YT) : Overlay Button that opens up Android's Native Share Menu. #50](https://github.com/anddea/revanced-patches/issues/50) )
> 6. Save To Playlist ( [feat (YT) : Overlay Button that opens up Save To Playlist Menu. #51](https://github.com/anddea/revanced-patches/issues/51) )
> 
> I genuinely believe that 5 or 6 overlay buttons will be user friendly, and even if they aren't, users can just enable/disable these buttons according to their preference.
> 
> Also, the reason for not using the default captions button in video player is, because it doesn't look symmetrical with reference to collapse button.
> 
> So, please re-open this issue for the following reason:
> 
> _Users have the autonomy of enabling/disabling overlay buttons according to their preference and adding a Captions Overlay Button merely provides them a new choice, hence this request shouldn't be considered a user-unfriendly one._

wdym by "doesnt look symmetrical"

**Comment by Aryan-Chauhan** [comment]
> > > Creating that many Overlay buttons takes a lot of space which is going to be user unfriendly.
> > > Go to Settings > ReVanced > Player > Hide captions button (turn off that option). Captions button will appear at the top right corner of the player. You can tap to show/hide captions, and tap and hold to open the language selection menu.
> > 
> > 6 overlay buttons can easily be occupied on my Samsung Galaxy M31 (default font size, default screen zoom, default minimum width/smallest width). I'm going to use these 6:
> > 
> > 1. Playback Speed (available)
> > 2. Download (available)
> > 3. Captions ( [feat (YT) : Overlay Button that opens up Captions Menu. #47](https://github.com/anddea/revanced-patches/issues/47) )
> > 4. Quality ( [feat (YT) : Overlay Button that opens up Quality Menu. #49](https://github.com/anddea/revanced-patches/issues/49) )
> > 5. Share ( [feat (YT) : Overlay Button that opens up Android's Native Share Menu. #50](https://github.com/anddea/revanced-patches/issues/50) )
> > 6. Save To Playlist ( [feat (YT) : Overlay Button that opens up Save To Playlist Menu. #51](https://github.com/anddea/revanced-patches/issues/51) )
> > 
> > I genuinely believe that 5 or 6 overlay buttons will be user friendly, and even if they aren't, users can just enable/disable these buttons according to their preference.
> > 
> > Also, the reason for not using the default captions button in video player is, because it doesn't look symmetrical with reference to collapse button.
> > 
> > So, please re-open this issue for the following reason:
> > 
> > _Users have the autonomy of enabling/disabling overlay buttons according to their preference and adding a Captions Overlay Button merely provides them a new choice, hence this request shouldn't be considered a user-unfriendly one._
> 
> wdym by "doesnt look symmetrical"

I meant this.

Even if you ignore that point, rest of the points still stands. It was anyways the weakest reason/argument of them all.

**Comment by MondayNitro** [comment]
you mean stroke thickness of the captions button? i submitted a request for the same

**Comment by Aryan-Chauhan** [comment]
> you mean stroke thickness of the captions button? i submitted a request for the same

Nope. I simply meant that there should be 1 button on the top-left corner & 1 button on the top-right corner.

Although unrelated, #56 is a reasonable request.

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225
