### ISSUE TITLE
Bug in Action Button 

### ISSUE THREAD

**Issue by MoniBlackouts** [anddea/revanced-patches#472]
### Type

Other

### Tools used

Revancify

### Application

Youtube 19.16.38

### Bug description

Share, Remix, Thanks, Report buttons are not hiding. But If I enable "Hide like and dislike buttons" then all other buttons hiding ..Other than that NO.

### Device Environment

Android 12, OneUI 4.1
 Rooted official firmware

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Are you using latest dev patches? Do you face the same issue on inotia's repo?

**Comment by akir45** [comment]
I am facing the same problem.
The inotia repo works.　Fixed by this inotia00/revanced-integrations@504c852 commit.
YouTube v19.16.39
patch v2.225.0-dev.3

**Comment by anddea** [comment]
I pushed integrations release now, check again

**Comment by MoniBlackouts** [comment]
> I pushed integrations release now, check again

Appreciated mate.. Now it's working fine. The bug is solved
