### ISSUE TITLE
bug: YouTube and YouTube Music are crashing

### ISSUE THREAD

**Issue by hibonox705** [anddea/revanced-patches#473]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 19.16.39 and YouTube Music 6.51.52

### Bug description

I just recently fetch the latest patches and tried to patch the latest recommended version using the following patches : 

![jZK63lvW](https://github.com/anddea/revanced-patches/assets/116116660/f1cc02f9-5e01-49a1-8876-cac15bfa8e7d)
![39Ze8zfX](https://github.com/anddea/revanced-patches/assets/116116660/b87058c7-fa9f-486c-a470-f8ff7d887c83)

YouTube crash/close after launching a video and it start buffering. As for YouTube Music it's crashing right away when launching the app

### Error logs

```shell
Don't know if this count or can help but my phone generated the following after the crash of YouTube Music : https://paste.crdroid.net/jVZo5O
```

### Additional context

Launched Revancify, fetch the latest patches (pre release included), and tried what i described above 

### Device Environment

Android 14 running the rom Matrixx 10.4.3 on Xiaomi 11 Lite 5G NE (Lisa)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Clear Revancify. I cannot reproduce this issue.

**Comment by hibonox705** [comment]
> Clear Revancify. I cannot reproduce this issue.

Just did and it still crashes, and I'm not the only one that have the issue

**Comment by anddea** [comment]
I pushed integrations release now, check again

**Comment by hibonox705** [comment]
> I pushed integrations release now, check again

Just tested it and it no longer crash. Thanks for the quick fix 👍
