### ISSUE TITLE
question: How To Generate options.json File? 

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#475]
### Application

YouTube

### Question description

Is the any method or app that can be used to generate `options.json` file or it must be configured manually?

[options.json](https://github.com/anddea/revanced-patches/files/15339228/options.json) 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It is auto generated when you start patching.
