### ISSUE TITLE
feat: status bar

### ISSUE THREAD

**Issue by Nalmor1** [anddea/revanced-patches#477]
### Application

YouTube

### Feature description

Hello, is it possible to make a full screen that hides the status bar?

### Motivation

Full screen 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This is based on your system settings, allow Fullscreen mode for the app, you have to find that for your device and OS.

**Comment by Nalmor1** [comment]
Thanks
