### ISSUE TITLE
question:main screen

### ISSUE THREAD

**Issue by Nalmor1** [anddea/revanced-patches#478]
### Application

YouTube

### Question description

hello, is it possible to add a function that hides on the main screen
![Screenshot_20240516-110809_YouTube (1)](https://github.com/anddea/revanced-patches/assets/169981296/cb68e4fa-032a-43b9-b96a-713af530a9bd)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
There's no option to hide that element. And no custom filter can be applied, because it either hides the whole video or nothing.
