### ISSUE TITLE
Tablet mini player.

### ISSUE THREAD

**Issue by Hell0Earth** [anddea/revanced-patches#479]
### Application

YouTube

### Feature description

Always show channel name on modern tablet mini player. For now we only can see it when moden tablet mini player is on and one video is minimized, if you change device theme or you minimise and open YouTube app, channel name will appear.

![Screenshot_2024-05-17-01-23-43-224_com google android youtube](https://github.com/anddea/revanced-patches/assets/93066706/214f1878-3efd-4a12-b80b-7c80aa9ab4c3)

![Screenshot_2024-05-17-01-43-19-621_com google android youtube](https://github.com/anddea/revanced-patches/assets/93066706/e54affa2-575a-4ae2-863d-eaf32c9f25da)

### Motivation

Looks useful when watching videos from unknown channels.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Seems more like a bug. Open bug report in inotia's repo.

**Comment by Hell0Earth** [comment]
> Seems more like a bug. Open bug report in inotia's repo. 

But can be a feature on your fork 🗿

**Comment by anddea** [comment]
But it's not a feature, this feature already exists, it's just buggy. I guess it's a YouTube test feature, and just because it's a test feature, it's buggy now, and YouTube will fix it itself, but it's just a guess as I had no chance to look to this setting yet.

**Comment by Hell0Earth** [comment]
> But it's not a feature, this feature already exists, it's just buggy. I guess it's a YouTube test feature, and just because it's a test feature, it's buggy now, and YouTube will fix it itself, but it's just a guess as I had no chance to look to this setting yet. 

Oh okay I will close it.
