### ISSUE TITLE
Custom tablet mini player size.

### ISSUE THREAD

**Issue by Hell0Earth** [anddea/revanced-patches#480]
### Application

YouTube

### Feature description

An option to select tablet mini player size. For example on give us the chance to set a custom dpi value for size.

### Motivation

On new patches tablet mini player is very small.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I don't think it's a good idea, I always want mini player to be small, otherwise why would I even minimize it. It seems fine as it is right now for me.
