### ISSUE TITLE
feat: Additional flyout feed actions in notification tab

### ISSUE THREAD

**Issue by CodeF53** [anddea/revanced-patches#483]
### Application

YouTube

### Feature description

In every context except for the notification tab (bell icon), you have the option to save videos to watch later / add to queue.
This would simply add those missing options to the flyout menu of videos in the notification tab. 

### Motivation

I almost never want to immediately watch a video I see in notification tab, I would like the ability to just save them to watch later / add to queue.
The subscription feed would work, but it's full of stuff I don't care about (I would unsub but the channels have some stuff I care about).

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Use subscriptions tab instead that has all those options in flyout menu. Too complex and pointless to impelemtn it.

**Comment by CodeF53** [comment]
Please read the second sentence of motivation

**Comment by anddea** [comment]
Please read the second sentence of my comment. Too much effort for one out of thousands to use this one feature. I don't know any people who use notifications instead of subscriptions tab which is more functional and easier to use. You can customize subscriptions tab however you want.
