### ISSUE TITLE
bug: Bug

### ISSUE THREAD

**Issue by Nalmor1** [anddea/revanced-patches#484]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39 
![Screenshot_20240517-121645_YouTube_1](https://github.com/anddea/revanced-patches/assets/169981296/d39c24db-431b-4951-a01f-5c5e3f3c7411)

### Bug description

I don't think it should be like that. 
like and dislike buttons on top of the title

### Device Environment

Asus ZenFone 9. 13 Android 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Seems like YouTube's design issue, can you reproduce it in the original YouTube?

**Comment by Nalmor1** [comment]
yes, same for the original
![Screenshot_20240517-123439_YouTube](https://github.com/anddea/revanced-patches/assets/169981296/c463b753-0638-465d-9036-a65d04ec8ff4)

**Comment by anddea** [comment]
Is it the latest version? Report the bug to YouTube then.

**Comment by Nalmor1** [comment]
19.07.39

**Comment by anddea** [comment]
Test the latest original YouTube and if it persists, then report in Help & feedback inside YouTube. This bug is related to languages with long texts, it looks as expected for English without any misalignments.

**Comment by Nalmor1** [comment]
Thank you,ok
