### ISSUE TITLE
bug (YouTube): Can't build YouTube with AFN Red Icon

### ISSUE THREAD

**Issue by IgorTHh1337** [anddea/revanced-patches#485]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube v.19.16.39

### Bug description

YouTube's patching fails when you trying to set AFN Red Icon.
![Screenshot_20240517_162252_Termux](https://github.com/anddea/revanced-patches/assets/134911638/cd174885-53a3-45d8-865f-50a5d813f085)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by IgorTHh1337** [comment]
Also tested building with Inotia00's CLI and getting the same error in the same place.
![изображение](https://github.com/anddea/revanced-patches/assets/134911638/23358d1c-cdb8-4f86-8b02-229d7c8ce516)
Here's the log of cmd
[log.txt](https://github.com/anddea/revanced-patches/files/15353960/log.txt)

**Comment by AbakNacchan** [comment]
AFN blue too.

**Comment by anddea** [comment]
Should be fixed now, test it and let me know.
