### ISSUE TITLE
bug: "Spoof device dimensions" doesn't work properly

### ISSUE THREAD

**Issue by joelmzj** [anddea/revanced-patches#487]
### Type

Error at runtime

### Tools used

Revancify

### Application

Device: Samsung Galaxy S8+
Android version: (Stock) Android 9
Version: YT 19.16.39
Patches version: 2.25.0-dev.15
Integrations version: 0.152-dev.9

![Screenshot_20240517-131816_ YouTube](https://github.com/anddea/revanced-patches/assets/79762041/574fb5a1-3d65-42b7-84ed-84be43aee207)

![Screenshot_20240517-131831_ YouTube](https://github.com/anddea/revanced-patches/assets/79762041/1cebceb0-530c-4f0a-bdbb-c4b398fa1ed6)

Higher resolutions never show. Max video resolution is 720p for every video.

I've tried with another devices:

______________________________

Device: Samsung Galaxy Note 10+
Android version: (ported stock rom from Galaxy S21 Ultra) Android 13
Version: YT 19.16.39
Patches version: 2.25.0-dev.15
Integrations version: 0.152-dev.9

![IMG_20240517_144825_783](https://github.com/anddea/revanced-patches/assets/79762041/cad3e54c-073e-4f15-8f53-e9207ddd90f7)

______________________________

Device: Samsung Galaxy A02
Android version: (Stock) Android 11
Version: YT 19.16.39
Patches version: 2.25.0-dev.15
Integrations version: 0.152-dev.9

(This result was unexpected because the device is cheap and has a Mediatek CPU.)

![IMG_20240517_145011_646](https://github.com/anddea/revanced-patches/assets/79762041/077c55a0-5916-43b3-ad71-9bbaceab6ead)

______________________________

Even made tests on my tablet:

Device: Samsung Galaxy Tab A (8.0", 2019)
Android version: (Stock) Android 11
Version: YT 19.16.39
Patches version: 2.25.0-dev.15
Integrations version: 0.152-dev.9

![IMG_20240517_150106_590](https://github.com/anddea/revanced-patches/assets/79762041/293862c0-bcb4-49fd-bcd1-5abd5a686a5d)

### Bug description

It's probably a bug or issue related to Android version, but not sure.

### Solution

I've noticed that this specific patch supports YT 19.16.38 and lower versions.

I also tried with YT 19.16.38 but was the same.

As said, it's probably a bug related to Android version or this specific patch need to be updated.

![Screenshot_20240517-141808_Firefox Nightly](https://github.com/anddea/revanced-patches/assets/79762041/af25469d-7943-43ec-bbae-89e031791a46)

### Device Environment

Android 9, Android 11 and Android 14.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you reproduce this issue with inotia's patches?

**Comment by joelmzj** [comment]
> Can you reproduce this issue with inotia's patches?

Sorry for UHD video quality (you know GitHub upload limitations). Lol.

Same behaviour. :(

https://github.com/anddea/revanced-patches/assets/79762041/1ef7f4d2-2ebe-4fbf-8ed4-1e22b3f72256

Test made on:

Device: Samsung Galaxy S8+
Android version: (Stock) Android 9
Version: YT 19.16.39
Inotia00 patches version: v4.8.0-dev.6
Inotia00 integrations version: v1.9.0-dev.5

Based on this tests it's probably an issue related to Android version and device information. It's probably necessary spoof device rather than dimensions.

I also noticed on my other mentioned devices that it's not necessary for me to enable "Spoof format stream data" or "Spoof device dimensions". I can play videos at least on 1080p but with no buffer issues.

This issue it's just present on this specific device. 

I need to clear that (obviously) I'm using non-root method.

**Comment by anddea** [comment]
Open bug report in inotia's repo, maybe he can reproduce this issue. For me spoof device dimensions never worked actually, so it could be device related.

**Comment by joelmzj** [comment]
Think the same. Thanks for your amazing support. :)

**Comment by joelmzj** [comment]
@anddea can't create a bug report on inotia00's repo. It's allowed just create pull requests. :(

**Comment by anddea** [comment]
https://github.com/inotia00/ReVanced_Extended/issues

**Comment by NichirinSword** [comment]
> Open bug report in inotia's repo, maybe he can reproduce this issue. For me spoof device dimensions never worked actually, so it could be device related.

Hi, I am using Galaxy J7 Pro (arm7) running on android 9 (One UI 1.1) in which device dimension spoof don't work. Either on or off, I am only stream upto 1080p which my device natively supports. But in my another device, Realme 9 Pro, it works as intended. There's also a issue like if the videos is in 60fps then enabling device dimension spoof limits the streaming upto 720p after playing 10-15 sec in 4k or 1440p. But this issue doesn’t occur if videos not in 60fps.

**Comment by anddea** [comment]
Report in inotia's repo.
