### ISSUE TITLE
feat (YT) : Overlay Button that opens up Quality Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#49]
### Application

YouTube

### Feature description

Please add an overlay button that, when clicked, opens up Quality Menu.
![Screenshot_2024-03-15-08-27-14-60_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/e51232e1-3afe-49c4-98c3-d69a8f5298d8)

### Motivation

• Quality Menu has equal importance to that of Playback Speed Menu, but only the latter has a dedicated overlay button (as of yet).

• It will save steps/taps for opening Quality Menu. Saving steps/taps was also the motivation behind Playback Speed Overlay Button, so Quality Menu should also get equal treatment.

• If implemented, large number of people will use it, just like they use Playback Speed Overlay Button.

• I've personally seen multiple positive comments on how convenient Playback Speed Overlay Button is, and the proposed button is also a convenient & practical one. So, that's why it should be implemented.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Hey, can you merge/combine all your `Overlay buttons` requests into one issue and close the others? It's hard to track all issues this way. You can also do the same with other issues you opened too. You can just perfectly format them in one issue.

**Comment by Aryan-Chauhan** [comment]
> Can you merge/combine all your `Overlay buttons` requests into one issue and close the others? It's hard to track all issues this way. You can do the same with other issues you opened too. You can just perfectly format them in one issue.

I will do that today.

But in that one issue, do I have to give link to my other issues or write everything again?

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225
