### ISSUE TITLE
question (YT & YT Music) : If I only want English (India) as my language, are these patch options preferences correct?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#490]
Just wanted to know if I'm using these patch options correctly or not.
![Screenshot_2024-05-18-14-26-39-66_91a936403af6fae783b1a226bd5fdf5c.jpg](https://github.com/anddea/revanced-patches/assets/91815107/7b5bb004-bd8e-4cb4-94b1-054101a37750)

Second question: Now, my compiled APK's size is lower, but still these are showing in the app. Is this how it is supposed to be?
![Screenshot_2024-05-18-14-33-23-50_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/anddea/revanced-patches/assets/91815107/89a08690-65bd-4170-b571-02fc2bce69fa)

**Comment by Aryan-Chauhan** [comment]
Now, my compiled APK's size is lower, but still these are showing in the app. Is this how it is supposed to be?
![Screenshot_2024-05-18-14-33-23-50_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/anddea/revanced-patches/assets/91815107/89a08690-65bd-4170-b571-02fc2bce69fa)

**Comment by anddea** [comment]
Yes, everything is correct. It just removes translation files but not interface entries for these translations.

**Comment by Aryan-Chauhan** [comment]
Thanks!

And what is the difference between "en" and "en-rIN" ?

**Comment by anddea** [comment]
All `en` languages have a few changed strings but mostly they're the same. Even if you remove all en, English wil be present because it's default language. So to be clear, for default English you can just keep it empty.
