### ISSUE TITLE
bug: Hide "Share", "Thanks", "Report", "Remix" button does not work

### ISSUE THREAD

**Issue by BAXSD** [anddea/revanced-patches#493]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.38
Patches 2.224.0

### Bug description

When turning these options off they still show.

1. "Share" button always shows when turned off.
2. "Report" button always shows when turned off.
3. "Thanks" button shows sometimes depending on videos when turned off.
4. "Remix" button shows sometimes depending on videos when turned off.

### Device Environment

Android 14/ OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
> Patches 2.224.0

Update to the latest dev, it's stable too.
