### ISSUE TITLE
bug: Video resolution bug 

### ISSUE THREAD

**Issue by GKid94** [anddea/revanced-patches#496]
### Type

Error at runtime

### Tools used

CLI

### Application

![Screenshot_2024-05-19-15-09-22-061_com revanced net revancedmanager](https://github.com/anddea/revanced-patches/assets/18757054/7f7a2444-a985-4d29-a707-d85232d1bed6)

### Bug description

Video resolution doesn't change with auto quality 
![Screenshot_2024-05-19-14-57-23-164_anddea youtube](https://github.com/anddea/revanced-patches/assets/18757054/650a1d35-04a1-4271-ac94-0f2974206455)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I don't think it's the problem with ReVanced, YouTube itself sometimes is very slow to update quality. I cannot reproduc it as Auto works just fine for me. Maybe you have connection issues and YouTube decides that it's the most optimized quality for you. Also, depends on how much you double tap to seek and what video speed do you use. 

You can always force the quality.

**Comment by Aryan-Chauhan** [comment]
@GKid94 , I think you shouldn't open issues here, because you don't use the official patching tools.

Go ask for support on the fake website where you downloaded that fake ReVanced Manager from.

**Comment by Aryan-Chauhan** [comment]
> > @GKid94 , I think you shouldn't open issues here, because you don't use the official patching tools.
> > 
> > Go ask for support on the fake website where you downloaded that fake ReVanced Manager from.
> 
> It's the same version as here https://revanced.net/

The website you linked is a fake website.
