### ISSUE TITLE
bug:  bell

### ISSUE THREAD

**Issue by Nalmor1** [anddea/revanced-patches#497]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39  anddea 225 dev 17 

### Bug description

the bell does not appear, exactly.  which answers (Personalized ) the remaining bells are there.
![Screenshot_20240520-011201_YouTube_1](https://github.com/anddea/revanced-patches/assets/169981296/e802eca5-1c94-4447-8d3b-b3afaef19c53)

### Device Environment

Asus ZenFone 9 Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I cannot reproduce this issue. Did you use custom filters? Or maybe some setting you changed caused this behavior? You don't have RYD?

**Comment by Nalmor1** [comment]
I use your patches, nothing else, it seems to me that the bell disappeared after I reinstalled different versions several times.  I checked on the original YouTube, it disappeared there too :(

**Comment by anddea** [comment]
If it's on original YouTube too, then it's something on YouTube's side again, maybe new tests by them.

**Comment by Nalmor1** [comment]
ok, and the last question, please tell me whether it’s worth upgrading to newer versions or can you safely sit on versions 18..

**Comment by anddea** [comment]
You can use 18.xx too. They are supported by patches.
