### ISSUE TITLE
suggestion: increase time ordered playlist button size a bit

### ISSUE THREAD

**Issue by MondayNitro** [anddea/revanced-patches#5]
### Application

YouTube

### Suggestion description

the time ordered playlist button is a bit smaller compared to other overlay buttons. it would be great if you could increase its size a bit.
![photo_6291554067444513712_x](https://github.com/anddea/revanced-patches/assets/87489540/a9fa9772-2a93-4cca-ba34-f76054871911)

i think the triangle in the button design is a bit outside the main icon, if you feel the same you can shift it inward (like the one below)
![Screenshot_8-3-2024_41258_icon-icons com](https://github.com/anddea/revanced-patches/assets/87489540/651e96cb-d8b4-4277-9446-321d5f90bb34)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This icon is taken from the official Google Material Icons. What you said doesn't look any better, it looks a little squashed. 
The playlist button is actually not small, it is slightly misaligned. And in the perspective, it seems smaller than it really is. The fullscreen button is odd though, not my latest one.

<details>
<summary>Screenshot</summary>

![demo](https://github.com/anddea/revanced-patches/assets/70171475/f60acbd0-2b5c-42ab-ac00-915f2c2686f4)
</details>

**Comment by Francesco146** [comment]
> This icon is taken from the official Google Material Icons. What you said doesn't look any better, it looks a little squashed. The playlist button is actually not small, it is slightly misaligned. And in the perspective, it seems smaller than it really is. The fullscreen button is odd though, not my latest one.
> Screenshot
> 
> ![demo](https://private-user-images.githubusercontent.com/70171475/311356361-f60acbd0-2b5c-42ab-ac00-915f2c2686f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjg5MzgsIm5iZiI6MTcxMDI2ODYzOCwicGF0aCI6Ii83MDE3MTQ3NS8zMTEzNTYzNjEtZjYwYWNiZDAtMmI1Yy00MmFiLWFjMDAtOTE1ZjJjMjY4NmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE4MzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMzgwZGYyOTRlYmM1MmQ2YjM0YzYyNGNlYmEzZjIwNDE0YmMzMDAzZTcwMGUwZTlmZDI0ZTJiM2YzZTVjYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITbd_Uf1izJ20B4YzyrS1C0TkNjgoLXfGKr66G-Ig1U)

it appears that the icon is aligned in the bottom line, but it has an upper empty border, that makes it seem that it isn't aligned. might try with an icon like this:
![311059341-651e96cb-d8b4-4277-9446-321d5f90bb34](https://github.com/anddea/revanced-patches/assets/49027005/5d410c08-1842-4c6c-a4e2-cd9cbf4fe8f6)

**Comment by MondayNitro** [comment]
> This icon is taken from the official Google Material Icons. What you said doesn't look any better, it looks a little squashed. The playlist button is actually not small, it is slightly misaligned. And in the perspective, it seems smaller than it really is. The fullscreen button is odd though, not my latest one.
> 
> Screenshot

what francesco said is right, you can zoom the image below to see that some empty space is left on top of playlist overlay buttom, you can utilise that space to increase its size by 5-10%, it will also make the overlay button look better aligned

![Screenshot_20240317-165932_Trebuchet](https://github.com/anddea/revanced-patches/assets/87489540/1fed50dc-4158-4b78-93c8-46bee5d672fb)

**Comment by anddea** [comment]
DId you check my screenshot, I added modified button there, still no comments on that, is it any good?

**Comment by MondayNitro** [comment]
> DId you check my screenshot, I added modified button there, still no comments on that, is it any good?

both are good, but im not talking about shifting arrow inwards, but about this

![Screenshot_20240317-165932_Trebuchet2](https://github.com/anddea/revanced-patches/assets/87489540/72b02b60-f893-44f1-873c-04a6a53d4874)

the size of the playlist button can be increased to fill the upper empty space

**Comment by MondayNitro** [comment]
regarding your modified button, i think arrow can be shifted a little bit inwards but not too much

**Comment by anddea** [comment]
I made changes in the latest dev, is it any better now?

**Comment by Francesco146** [comment]
> I made changes in the latest dev, is it any better now?

I've checked and i think the fix did it. thank you!
