### ISSUE TITLE
feat (YT) : Overlay Button that opens up Android's Native Share Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#50]
### Application

YouTube

### Feature description

Please add an overlay button that, when clicked, opens up Android's Native Share Menu.
![Screenshot_2024-03-15-07-46-07-16_c31b32364ce19ca8fcd150a417ecce58](https://github.com/anddea/revanced-patches/assets/91815107/bb38eca3-26fa-494c-852f-cdb6315e7bf3)

### Motivation

• Android's Native Share Menu has equal importance to that of Playback Speed Menu, but only the latter has a dedicated overlay button (as of yet).

• It will save steps/taps for opening Android's Native Share Menu. Saving steps/taps was also the motivation behind Playback Speed Overlay Button, so Android's Native Share Menu should also get equal treatment.
![1710472210920](https://github.com/anddea/revanced-patches/assets/91815107/38a687ab-dd10-41da-9774-89cb188cb13f)

• If implemented, large number of people will use it, just like they use Playback Speed Overlay Button.

• I've personally seen multiple positive comments on how convenient Playback Speed Overlay Button is, and the proposed button is also a convenient & practical one. So, that's why it should be implemented.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
I think add a patch to force open native share menu is better

**Comment by Aryan-Chauhan** [comment]
> I think add a patch to force open native share menu is better

I don't use Button Containers because they are cosmetically buggy (they have inconsistent padding/spacing):

https://github.com/ReVanced/revanced-patches/issues/62

https://github.com/inotia00/ReVanced_Extended/issues/17

https://github.com/inotia00/ReVanced_Extended/issues/89

https://github.com/inotia00/ReVanced_Extended/issues/451

https://github.com/inotia00/ReVanced_Extended/issues/674

https://github.com/inotia00/ReVanced_Extended/issues/1754

I use my app like this:
![Screenshot_2024-03-17-08-43-18-88_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/anddea/revanced-patches/assets/91815107/2ed84044-2f18-4e30-aba0-64c1f83b734d)

**Comment by anddea** [comment]
This padding between the buttons is caused by the way the litho filter hides the elements, in the case of this "button container" it hides only the button, but there are 2 parent elements of this button that have this padding. Solution: either rewrite the button filtering in a different way, or add some kind of a parental deletion to litho, which will cause problems with other elements. Because the litho filter hides a lot of things: ads, buttons, custom, new keyword filter, etc, and all of that works fine except for the button container.

**Comment by Aryan-Chauhan** [comment]
> This padding between the buttons is caused by the way the litho filter hides the elements, in the case of this "button container" it hides only the button, but there are 2 parent elements of this button that have this padding. Solution: either rewrite the button filtering in a different way, or add some kind of a parental deletion to litho, which will cause problems with other elements. Because the litho filter hides a lot of things: ads, buttons, custom, new keyword filter, etc, and all of that works fine except for the button container. 

Yes, that's why I requested for a Share Overlay Button instead of "Hook Share Button" that Alireza was talking about.

I always want to keep Button Containers hidden.

**Comment by Aryan-Chauhan** [comment]
Not exactly, but kinda similar:

https://github.com/ReVanced/revanced-patches/issues/1896

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225

**Comment by Francesco146** [comment]
this one is doable, I'll write them down for when I have time
