### ISSUE TITLE
bug(YT) : "Restore Old Seekbar Thumbnails" doesn't work in 19.17.41

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#500]
### Type

Other

### Tools used

rvx-builder

### Application

Same as above

### Bug description

![Screenshot_20240521_011008](https://github.com/anddea/revanced-patches/assets/93650504/388c775a-6de5-4d11-b727-8641371f0266)

And also bump the version to 18 or 19.

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
19.16 is the latest supported for this patch, so I'm going to close it now, it's not an error, it's a warning.

**Comment by Vipin2003** [comment]
And when you are going to bump the version.?

**Comment by anddea** [comment]
Don't know yet. There's nothing new in new YT versions, why bump it?
