### ISSUE TITLE
bug: Videos keep buffering

### ISSUE THREAD

**Issue by GKid94** [anddea/revanced-patches#509]
### Type

Error at runtime

### Tools used

CLI

### Application

![Screenshot_2024-05-22-22-02-23-770_com revanced net revancedmanager](https://github.com/anddea/revanced-patches/assets/18757054/c00ee998-7121-4260-b225-3e8044c3e52e)

### Bug description

Videos often won't load and keep buffering 
![Screenshot_2024-05-22-21-53-41-074_anddea youtube](https://github.com/anddea/revanced-patches/assets/18757054/c2ffd22d-e07c-40bb-9f1a-dd996fa9a60d)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by exciar** [comment]
same issue I used the spoof format stream data but that makes the video buffer for at least 10 seconds before loading


running on Evolution X 9.0 vayu (android 14)

**Comment by Felting** [comment]
Don't use revanced.net revanced, it's fake. Build it yourself instead.

**Comment by GKid94** [comment]
> Don't use revanced.net revanced, it's fake. Build it yourself instead.

It's better than official launcher honestly, the official one doesn't even detect and update the apps

**Comment by selfmusing** [comment]
lmao 🤣 revanced.net user spotted

**Comment by GKid94** [comment]
> > > Don't use revanced.net revanced, it's fake. Build it yourself instead.
> > 
> > 
> > It's better than official launcher honestly, the official one doesn't even detect and update the apps
> 
> Rvx manager detects when there is new patches, you just need to download the YouTube apk. The version from revanced.net may be misconfigured, outdated or malicious.

My Xiaomi antivirus said the app was safe

**Comment by exciar** [comment]
> > > > Don't use revanced.net revanced, it's fake. Build it yourself instead.
> > > 
> > > 
> > > It's better than official launcher honestly, the official one doesn't even detect and update the apps
> > 
> > 
> > Rvx manager detects when there is new patches, you just need to download the YouTube apk. The version from revanced.net may be misconfigured, outdated or malicious.
> 
> My Xiaomi antivirus said the app was safe

the Xiaomi antivirus you are talking about is just an adware to ship you ads

**Comment by GKid94** [comment]
> > > > > Don't use revanced.net revanced, it's fake. Build it yourself instead.
> > > > 
> > > > 
> > > > It's better than official launcher honestly, the official one doesn't even detect and update the apps
> > > 
> > > 
> > > Rvx manager detects when there is new patches, you just need to download the YouTube apk. The version from revanced.net may be misconfigured, outdated or malicious.
> > 
> > 
> > My Xiaomi antivirus said the app was safe
> 
> the Xiaomi antivirus you are talking about is just an adware to ship you ads

It showed me the official YouTube Revanced as virus

**Comment by GKid94** [comment]
Still not fixed
![Screenshot_2024-06-22-12-46-52-095_anddea youtube](https://github.com/anddea/revanced-patches/assets/18757054/25ebb505-e5f3-4277-97b6-afb237afaba1)
![Screenshot_2024-06-22-12-49-20-089_com miui securitycenter](https://github.com/anddea/revanced-patches/assets/18757054/77879f1c-bda0-4799-995c-75c46957f6b5)

**Comment by GKid94** [comment]
> > Still not fixed
> 
> Enable `Spoof client`. No one else reported this issue. Search what's wrong on your side.

It's enabled by default

**Comment by GKid94** [comment]
https://xdaforums.com/t/youtube-videos-stuck-in-loading-after-miui-14-update.4609969/

**Comment by anddea** [comment]
If you face these issues on inotia's RVX as well, report bugs there. I cannot reproduce it on my side.
