### ISSUE TITLE
Disable media control playback notification

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#510]
### Application

YouTube

### Feature description

I get a media control playback notification in my notification shade when I'm watching a video. I'm not sure how to disable it. I used to have it disabled on an old inotia00 build of YouTube but I can't figure out how to disable it now.

### Motivation

It's annoying and pointless to have that notification.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MtndaleRedneck** [comment]
I have Lock Screen Media Controls disabled yet I keep seeing the notification.

**Comment by anddea** [comment]
Lock screen will only in lock screen, when you lock your phone. If you want to hide when phone is unlocked then there should be another option.

**Comment by MtndaleRedneck** [comment]
I'm not seeing any option for it

**Comment by anddea** [comment]
Then it's not possible. You can dismiss it with a swipe but it will still appear under tiles. It also depends on Android OS and ROM.
