### ISSUE TITLE
Speed resets to default

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#512]
### Type

Error while patching

### Tools used

RVX Manager

### Application

V19.05.36

### Bug description

I have a default YouTube speed set and the option to remember my video speed shut off. I want it to default to a speed although on a per video basis I might switch it. I have background playback shut off. If I switch the per video speed, minimize it, then reenter YouTube and continue the video it reverts to my default video speed.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I cannot reproduce it, it works fine for me. Did you enable remember playback speed? If it's not turned on it's expected behavior, if you minimize and come back, even with soft refresh It can reset speed.

**Comment by MtndaleRedneck** [comment]
You're missing what I mean. I disabled remember playback speed. I don't want it remembering from video to video. I have my default speed set to 2.25x. But for some videos I'll slow it down, say to 1.5x. Then in middle of the video I'll switch apps, then continue the video. It'll continue at the default 2.25x instead of the 1.5x it was at when I switched apps. Switched, not closed.

**Comment by anddea** [comment]
Maybe system mismanaged the RAM and app got freed and once it got freed, it just resets to default. 

I tested on my devices and it's not reset unless I spend some time in different apps that frees YouTube.

**Comment by MtndaleRedneck** [comment]
🤷‍♂️ I'm on a s22 Ultra. It's instantly switching after only seconds minimized. It doesn't close the open video. Only reset the speed to default.

**Comment by anddea** [comment]
I'm not sure what could cause this. Maybe clean install it. It does not reset for me for hours (remember speed disabled).
