### ISSUE TITLE
Add option to hide buttons by pressing and holding it

### ISSUE THREAD

**Issue by mysticmac3** [anddea/revanced-patches#513]
### Application

YouTube

### Feature description

I appreciate your hardwork,If possible can you add an option where we can press and hold a specific button and hide it instead of going all the way back to revanced extended settings and finding and hiding it

### Motivation

This option would be great for users are confused about revanced extended settings and also it would help users to make it easy to hide unwanted buttons on the go instead of going back to recvanced extended settings, Example-Lets say i am watching a video and i want to hide remix button in the buttons container i can just press and hold remix button and hide instead of pausing the video and going back to revanced extended settings to hide the same ,Its a request and this feature would be cool,if possible please apply it

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Until this feature is implemented, do you plan on familiarizing yourself with the settings?

**Comment by mysticmac3** [comment]
> Until this feature is implemented, do you plan on familiarizing yourself with the settings?

I am familiar with the settings and fully aware, this is just an idea and a feature request in general,if implemented it would be cool if not i still appreciate the developers hardwork

**Comment by anddea** [comment]
I don't think it will be intuitive, some buttons have actiona assigned on them already, like save button on long press will open playlists list to choose where you want it to be saved. Or captions button that will open list of available languages on long press.

**Comment by Aryan-Chauhan** [comment]
> > Until this feature is implemented, do you plan on familiarizing yourself with the settings?
> 
> I am familiar with the settings and fully aware, this is just an idea and a feature request in general,if implemented it would be cool if not i still appreciate the developers hardwork , also i didn't mention anywhere that i am confused with the settings

After reading the issue, I just got the vibe that you are a lazy user not ready to explore the settings, but now it is clear that you are not a lazy user, but an aware user. So, thanks for clarifying.

**Comment by mysticmac3** [comment]
> I don't think it will be intuitive, some buttons have actiona assigned to them already, like save button on long press will open playlists list to choose where you want it to be saved. Or captions button that will open list of available languages on long press. 
> 
> There's a search bar in settings, it's a lot easier to navigate now. 

Thanks for responding,it was just an idea but now i know the limitations of it, thanks for clarification,as always i appreciate your hard work, thank you

**Comment by mysticmac3** [comment]
> > > Until this feature is implemented, do you plan on familiarizing yourself with the settings?
> > 
> > I am familiar with the settings and fully aware, this is just an idea and a feature request in general,if implemented it would be cool if not i still appreciate the developers hardwork , also i didn't mention anywhere that i am confused with the settings
> 
> After reading the issue, I just got the vibe that you are a lazy user not ready to explore the settings, but now it is clear that you are not a lazy user, but an aware user. So, thanks for clarifying.
Lol an average lazy user wouldn't go as far as to creating a GitHub issue they would just simply post somewhere asking for it,It was just an idea but now i know the limitations as anddea mentioned, Thanks mate cheers 👍

**Comment by mysticmac3** [comment]
@anddea since you have responded to the issue shall i close the issue from my side?

**Comment by anddea** [comment]
It's fine, I'll close it myself.
