### ISSUE TITLE
feat: stable volume 

### ISSUE THREAD

**Issue by r-i-s-u** [anddea/revanced-patches#515]
### Application

YouTube

### Feature description 

(https://github.com/anddea/revanced-patches/assets/114793497/f9f6ebc5-7991-46ff-94e8-549f1c7d478c)
Why is the stable volume option not opening in music videos? 

### Motivation

![IMG_20240524_140935](https://github.com/anddea/revanced-patches/assets/114793497/9dc699b4-3bf4-473c-9b43-f946764ee5d7)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
It's the same even of official YouTube app , it only works on some specific videos & sometimes the toggle stays disabled even after enabling it.

**Comment by anddea** [comment]
As original YouTube has the same behavior, I'm closing this issue.
