### ISSUE TITLE
feat: Hide the blue dot badge in channel avatar section in Youtube app.

### ISSUE THREAD

**Issue by smed79** [anddea/revanced-patches#517]
### Application

YouTube

### Feature description

Hide the blue dot badge in channel avatar section in Youtube app.

https://github.com/anddea/revanced-patches/assets/1873139/c3fbf627-444a-4948-b874-731e1b709521

### Motivation

The notification badge is annoying and distracting, to make it disappear you have to browse all the contents uploaded to the channel even these you have already hide for your self as shorts or community posts.

This is a feature request to add  a switch to toggle off the blue dot badge notification.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by smed79** [comment]
Previous request at ➞  https://github.com/YT-Advanced/ReX-patches/issues/182

**Comment by anddea** [comment]
I don't think this one needs an additional setting, and I'm not sure where to add this setting even if created. 
Instead, add `status_dot.eml` to custom filter.

**Comment by smed79** [comment]
> add `status_dot.eml` to custom filter.

Thanks for the tip.

**Comment by smed79** [comment]
@anddea Could you please provide a custom filter to hide the same element in 'tablet layout'. 

Thanks in advance.

**Comment by anddea** [comment]
Unfortunately, I don't have any tablets, but you can find this filter if you enable debug logging and buffer debugging. Then, grab the logs using logcat. You can even find logcat apps on Google Play. If you decide to grab the logs, it's better to restart the app and freshly open the subscriptions tab. After that, you can stop the logcat capture and search for similar words or go through all the captured logs.

**Comment by smed79** [comment]
> I don't have any tablets right now

By 'tablet layout' i mean enable it in rvx settings.
General > Experimental Flags > Tablet ([screenshot](https://github.com/user-attachments/assets/abdd3c7a-a8d3-463e-adec-c7142f834384)).

> you can find this filter [...] search for similar words...

I already try that but i could not find the right filter.

here the logcat > [logcat_10-26-2024_17-45-35.txt](https://github.com/user-attachments/files/17531388/logcat_10-26-2024_17-45-35.txt)

**Comment by anddea** [comment]
I don't see any related content for that. It should be inside the subscriptions_channel_bar element, but there is no such element at all. When I switch to tablet layout, it doesn't show this subscriptions carousel at all. And if there is no new subscriptions element, there should not be this blue dot as well.

**Comment by smed79** [comment]
When I switch to tablet layout It appears as in the below ➞  [screenshot](https://github.com/user-attachments/assets/2494e743-32c3-4703-9035-85ffd991982a). 

The blue status dot 🔵 that hover the channel avatar shows up for me all the time. To make it disappear you must watch all the content of the channels videos, shorts, community posts... This is impossible, especially when you have dozens of subscriptions and i can not view some contents that i hade by default because it does not intereste me like community posts, live, upcoming and shorts.

@inotia00 Any help is welcome.
