### ISSUE TITLE
question: How do I get the newer versions

### ISSUE THREAD

**Issue by samve000** [anddea/revanced-patches#518]
### Application

YouTube

### Question description

Hi, I'm pretty new to this so I'm still figuring some stuff out, I downloaded the latest patches.json and used the correct data sources. But I don't see any newer version than 19.05.36.

![Screenshot_2024-05-25-20-04-50-64_b2982762ac851fa27deabc856cd0808c](https://github.com/anddea/revanced-patches/assets/12258003/7fc3dcfb-f61a-4421-bed4-a7b5b7d0feb4)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Enable pre-releases in the latest RVX Manager. You can patch up to 19.16 even if shows 19.05.
