### ISSUE TITLE
Creating PR in inotia patches about searching Revanced settings 

### ISSUE THREAD

**Issue by Mohammed1520** [anddea/revanced-patches#519]
### Application

YouTube

### Suggestion description

Please can you integrate the search ability in inotia patches too
Thank you in advance 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I open pull requests one by one and when I have time I'll open for this feature as well. 

What's so different between inotia and anddea, that you want it to see there and not to use it here?
