### ISSUE TITLE
What's the setting for disabling full screen gesture by scrolling down the description

### ISSUE THREAD

**Issue by harsharora08** [anddea/revanced-patches#521]
### Application

YouTube

### Question description

![Screenshot_20240527_001754_YouTube](https://github.com/anddea/revanced-patches/assets/41362690/5cdf5cec-b9a2-4c93-b805-96203349e2c4)
Swiping down on description opens it in weird full-screen. What's the setting to disable this? Can't seem to find it.

Thanks in advance.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Swipe controls > Enable watch panel gestures. There's a search bar now.
