### ISSUE TITLE
suggestion: update playback speed overlay button icon

### ISSUE THREAD

**Issue by MondayNitro** [anddea/revanced-patches#522]
### Application

YouTube

### Suggestion description

please update overlay button icon for playback speed to match the official one used in yt.

![Screenshot_27-5-2024_12831_github com](https://github.com/anddea/revanced-patches/assets/87489540/9fe99332-c7bd-48bc-b2ac-f87886331331)

saw it in pr [here](https://github.com/ReVanced/revanced-patches/pull/3197)
this is also the icon used in youtube flyout menu

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Why? It seems less consistent. I was thinking about this icon, it is the first icon shown in Google meterial icons when searching for "speed", but decided it's inconsistent.
