### ISSUE TITLE
feat(YouTube - Live Chat): Hide Chat Summary

### ISSUE THREAD

**Issue by RoonMoonlight** [anddea/revanced-patches#523]
### Application

YouTube

### Feature description

(Due to inotia00 no longer accepting feature request I had to write in this issue section, would be appreciated if it is possible to be implemented.)

Surprisingly Google recently added new feature into the feature Chat Summary into live chat to keep up what is happening in the live chat, using Gemini AI. Unfortunately there doesn't seems to be option to turn it off and would be grateful if there is option to hide the Chat Summary feature in chat.

### Motivation

Same as hide related video thing, to reduce distraction and annoyances.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by RoonMoonlight** [comment]
Additional info: Not sure when this feature got added, seems it is A/B testing thing.

Example screenshot below:
![Screenshot_20240527_161249_YouTube RVX](https://github.com/anddea/revanced-patches/assets/25527589/4fe10499-2034-428b-b923-6a0e1a9c5a56)

**Comment by Francesco146** [comment]
this is A/B testing. i don't have this feature yet.

**Comment by RoonMoonlight** [comment]
> this is A/B testing. i don't have this feature yet. could you upload the logs with protobuffer content?

How do I do that?

**Comment by Francesco146** [comment]
1. include Debug logging 
2. enable debug logging in Miscellaneous (both the toggles)
3. connect the device on your PC and set up adb
4. reopen the app
6. grep the logs with:
```bash
adb logcat | grep --line-buffered "Extended" > log.txt
```
7. make render the component you want to log, in your case make sure that Chat Summary is shown
8. upload log.txt here

**Comment by RoonMoonlight** [comment]
Also please don't close the issue as some might be experiencing same issue right now

**Comment by Francesco146** [comment]
> P.S. Also if you are contributor please consider adding that info somewhere else such as wiki page so everyone should know how to make log output

sure, thanks for the tip





> Also please don't close this issue as some might be experiencing same issue right now

sure, don't worry

**Comment by RoonMoonlight** [comment]
> this is A/B testing. i don't have this feature yet. could you upload the logs with protobuffer content?

https://gist.github.com/RoonMoonlight/2821c54ec289453132902e7728a4d035
@Francesco146 Here you go (Had to remove above and below logs to keep it simple)

**Comment by Francesco146** [comment]
hey, i'm taking care of this issue, do you have a link to a stream that (consistently) shows you this pop-up?

**Comment by RoonMoonlight** [comment]
> hey, i'm taking care of this issue, do you have a link to a stream that (consistently) shows you this pop-up?

Umm sorry I am not sure which stream does show up but it seems to be happening to stream like thegameawards
