### ISSUE TITLE
bug: (YouTube) Splash screen isn't disabled

### ISSUE THREAD

**Issue by Francesco146** [anddea/revanced-patches#524]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v19.20.34

### Bug description

The splash screen at startup isn't hidden properly (sometimes it's shown for half a second, sometimes it's hidden from the start, sometimes it's not hidden at all).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Is it different from inotia? Because if it's present there, then bugs can be reported there.

**Comment by Francesco146** [comment]
> Is it different from inotia? Because if it's present there, then bugs can be reported there.

not sure, i'll test it and in case close this issue

**Comment by Francesco146** [comment]
issue was resolved in RVX in this commit: https://github.com/inotia00/revanced-patches/commit/bc0860bba7390dc3a98195775381edcd58d546d7
