### ISSUE TITLE
bug: Custom color in some random texts

### ISSUE THREAD

**Issue by Joshua64** [anddea/revanced-patches#527]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.20.34

### Bug description

I patched the latest pre release patch ver 2.225.0-dev.22 in rvx manager with everything in stock except for custom youtube name and icons and the theme colors, i set baby pink color #FFFFB7CE and some random texts gets pink like in the prints

![Screenshot_20240527_081645_RVX Manager](https://github.com/anddea/revanced-patches/assets/20147128/811acc2e-1c39-419e-b7ea-7ddad5b6f467)
![Screenshot_20240527_081814_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/9dfef8e1-3758-4922-837e-acf76871bf00)
![Screenshot_20240527_081913_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/ac4c9c08-7cab-4a4e-9e02-c61757e72a86)
![Screenshot_20240527_081923_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/7e449846-2a7b-4cdd-bf70-a961c205365b)

This affects nothing but this is one bug so i think that the best is to show this

### Device Environment

Samsung galaxy A12
Android 13 with latest updates
One UI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
If you face the same issue on inotia's patches report there for bugs.

**Comment by Joshua64** [comment]
Yes this issue happens with inotia's patches too
And there is more two issues that i forgot to mention

![Screenshot_20240527_104620_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/c4c36a63-20b0-47d8-adaf-6fc37e2acc1b)
![Screenshot_20240527_104641_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/648d0eb7-c563-494d-b3b7-71da6b6a72ab)

In Bright Mode, the custom color does not apply in notifications bar (I tested with #FFFFB7CE (baby pink) and #FFDEDEDE (very light gray i think) and does not matter the custom color, the notifications bar is allways white and when i selected light gray the notifications bar turned all white and was not possible to see the bat percent, the hour and the Wi-Fi, everything was with the same white color.

And even in the Bright Mode the custom color applys to some random texts that Washington supposed to be gray like the time stamps names and Chambers names

**Comment by anddea** [comment]
Open this issue in inotia's repo. He accepts bug reports, maybe this is an intentional behavior.
