### ISSUE TITLE
"The following content is not available on this app" error

### ISSUE THREAD

**Issue by stu2005** [anddea/revanced-patches#53]
### Type

Error at runtime

### Tools used

Revancify

### Application

**YouTube 19.09.37**
But Same issue occurs in all versions.

### Bug description

When logged in with [MicroG](https://github.com/WSTxda/MicroG-RE) the message "The following content is not available on this app" is displayed for all videos.  I also tried MicroG by other developers and had the same issue.
![Screenshot_20240315-164836](https://github.com/anddea/revanced-patches/assets/58098330/8fc6ac65-6c43-4343-b707-5a1ba1c17cb8)

[YouTube_v19.09.37_2024-03-15.txt](https://github.com/anddea/revanced-patches/files/14612666/YouTube_v19.09.37_2024-03-15.txt)

### Device Environment

Android13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by stu2005** [comment]
Sorry, Found the same issue
https://github.com/ReVanced/revanced-patches/issues/2878

**Comment by anddea** [comment]
> Sorry, Found the same issue

Can you check if you encounter this issue with this version of patches?

https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.220.7

**Comment by bwskin** [comment]
@anddea I built it (using revancify if that matters, checkes if patches version match) and issue persists

**Comment by stu2005** [comment]
> > Sorry, Found the same issue
> 
> Can you check if you encounter this issue with this version of patches?
> 
> https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.220.7

I tried it, but it doesn't improve.

**Comment by DVSVIDEO** [comment]
On 23 March, I received the same message. I had been using ReVanced for a year and hadn't touched anything.
Online newspapers reported that Google had told the Vanced developers to stop the project or they would be sued.
Google has changed something because previous original YouTube apps have had the same message. But the new versions work.
The latest version in the ReVanced manager is 19.04.37 for which there are patches. However, the original version of this one does not play anything either, it throws up the aforementioned message.
The new version is 19.11.43 and plays videos without error, but there are no Patches for it. 
I have tried all the ReVanced.apk's, uploaded them, but none of them play the videos after March 23rd...

**Comment by stu2005** [comment]
> On 23 March, I received the same message. I had been using ReVanced for a year and hadn't touched anything.
> Online newspapers reported that Google had told the Vanced developers to stop the project or they would be sued.
> Google has changed something because previous original YouTube apps have had the same message. But the new versions work.
> The latest version in the ReVanced manager is 19.04.37 for which there are patches. However, the original version of this one does not play anything either, it throws up the aforementioned message.
> The new version is 19.11.43 and plays videos without error, but there are no Patches for it. 
> I have tried all the ReVanced.apk's, uploaded them, but none of them play the videos after March 23rd...

The original ReVanced and YT-Advanced have released a patch and MicroG to fix this issue, but the YT-Advanced version still seems to have the problem.

**Comment by DVSVIDEO** [comment]
Can you provide kinks for the latest versions? I'm a bit confused between the many versions and releases.

**Comment by stu2005** [comment]
> Can you provide kinks for the latest versions? I'm a bit confused between the many versions and releases.

You're getting off topic. Let's not say anything more about it.

**Comment by Anatolia1990** [comment]
Здравствуйте Так есть решение что делать почему не работает? Будет ли работать?

**Comment by bwskin** [comment]
> Здравствуйте Так есть решение что делать почему не работает? Будет ли работать?

@Anatolia1990 This issue is fixed in newest release, update your patches (and/or revanced manager) and patch your app again

**Comment by Anatolia1990** [comment]
Tell me where to download the installed version, the latest version? I
can't find it on your website.

пт, 29 мар. 2024 г., 12:14 Norbert Bolanowski ***@***.***>:

**Comment by bwskin** [comment]
Revanced manager is [here](https://github.com/ReVanced/revanced-manager/releases/tag/v1.19.3). Just use it as normal.

**Comment by anddea** [comment]
@Anatolia1990, use [RVX Manager](https://github.com/inotia00/revanced-manager/releases) to patch with latest Dev, as it uses new GmsCore that should fix this issue. Or in Revancify turn on pre-release updates.
