### ISSUE TITLE
about youtube translations' question

### ISSUE THREAD

**Issue by re-zero001** [anddea/revanced-patches#530]
### Application

YouTube

### Question description

I have uploaded the Chinese Simplified translation to Crowdin,and inotia accept it now(v4.8.5).You added new settings from inotia,but you didn't update it's translation from Crowdin.So what do you want the translators to do, just upload translated strings to your repository when you add your own setings,and you just add new translated strings from Crowdin when you add new settings from inotia.Or we updated all translated strings to you?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
My latest patches came before inotia's latest, in the next release translations will be updated automatically. If you translated everything in crowdin, there's no need to do the same job twice. You can check if there are unique untranslated strings if they are not translated yet. They will be updated automatically as well. 

https://github.com/anddea/revanced-patches/blob/dev/src/main/resources/youtube/translations/zh-rCN/missing-strings.xml
