### ISSUE TITLE
App icon in launcher

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#531]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube Music 7.02.51

### Bug description

I choose MMT icon for YouTube Music in RVX Manager but in launcher the app has a default icon

### Additional context

![Screenshot_2024-05-27-21-08-57-083_com miui home-edit](https://github.com/anddea/revanced-patches/assets/61022739/04c1598f-a68c-4aee-8d4c-698e12a673ff)
![IMG_20240527_211033](https://github.com/anddea/revanced-patches/assets/61022739/17b3b5ea-0f1a-4b5d-92af-592883a650be)
![Screenshot_2024-05-27-21-11-34-417_app rvx manager flutter-edit](https://github.com/anddea/revanced-patches/assets/61022739/86e47951-ebef-4d50-a4e0-45ecdb4f69be)

### Device Environment

HyperOS 1.0.(Elite HyperOS Lite 24.5.13)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Maybe you use a set of custom icons, I patched to verify and cannot reproduce it, I see MMT icon.

**Comment by bozander** [comment]
I reapplied the icons and the problem disappeared.   Thanks for the quick response
@anddea
