### ISSUE TITLE
bug: sponsorblock upload new segment button doesnt work

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#532]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Yt 19.20.34

### Bug description

https://github.com/anddea/revanced-patches/assets/143447608/9b39d1f1-f038-4eeb-ad55-274da58be77e

### Additional context

It doesnt happens on inotia's patch

### Device Environment

Android 14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
fixed in RVX in this commit: https://github.com/inotia00/revanced-patches/commit/fb6f1c3acee7d62d85d19f871aa1df9a7835093d

after the latest merge should be all good

**Comment by Ahmey1400** [comment]
Should i close it

**Comment by Francesco146** [comment]
nope

**Comment by Ahmey1400** [comment]
Its fixed now at 2.225.0-dev.25
