### ISSUE TITLE
bug: The download button under the channel does not appear

### ISSUE THREAD

**Issue by StarsShine11904** [anddea/revanced-patches#535]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube v19.20.34

### Bug description

The switch option of the download button is displayed, but not displayed
![Screenshot_20240528_072629_YouTube](https://github.com/anddea/revanced-patches/assets/89504980/a1bf987c-296a-41e6-a1e8-69ae815f9482)
![Screenshot_20240528_073304_YouTube](https://github.com/anddea/revanced-patches/assets/89504980/22551e5a-4d53-43af-9088-a57152fce1dd)

### Device Environment

Samsung A33 5G
OneUI 6.0
Android 14
No Root

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It should be a YouTube issue, it happens sometimes and then it appears on its own. It's region dependent also. 

Do you have this button on inotia patches and original YouTube?
Log out and log back in, enable disable incognito, reinstall the app, maybe it will force the button to show up again.
