### ISSUE TITLE
suggestion: Hopefully patch support for the suggested video ending screen can be restored

### ISSUE THREAD

**Issue by StarsShine11904** [anddea/revanced-patches#537]
### Application

YouTube

### Suggestion description

I hope you can restore support for the patch for the suggested video end screen, because I'm used to turning off autoplay, but once I turn off the suggested video end screen, I can't use it anymore, which causes me trouble.
![Screenshot_20240528_092916_YouTube](https://github.com/anddea/revanced-patches/assets/89504980/dfda3869-9e50-427e-9602-8c187f7938b9)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
There's a toggle now

**Comment by anddea** [comment]
Autoplay is an internal setting. Previously, it was broken for years, when people enabled hiding endscreen overlay suggestions or whatever caused it, autoplay never worked, even if enabled. And when people tried to toggle this setting they were confused, that was what we call inconvenience and unintuitive UI. Currently, it is the best implementation that we came to for now. We cannot duplicate settings for each section, it will be even worse UX. 

You can open this issue in inotia's repo, maybe he'll make it better.
