### ISSUE TITLE
Automatic video resuming when device is turned off whit spoof client on

### ISSUE THREAD

**Issue by speedlorenzo12** [anddea/revanced-patches#538]
### Type

Other

### Tools used

Revancify

### Application

YouTube 19.20.34

### Bug description

When Spoof client is on when I turn off the device the video resuming And sometimes happen randomly
1 Watch a video
2 pause the video
3 turn off the device (sospension)
4 Watch if the video resuming

### Device Environment

Android 13 miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Please test it if it happens with inotia patches and then open bug report there.

**Comment by speedlorenzo12** [comment]
I'm now testing inotia
