### ISSUE TITLE
When will you release stable update?

### ISSUE THREAD

**Issue by driftywinds** [anddea/revanced-patches#539]
### Application

YouTube

### Question description

Due to only releasing pre-releases which are not compatible with ReVanced manager I am not able to make new builds. When do you plan to make a stable release?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
When it's ready to be released, I receive bug reports daily so cannot push it to stable. Maybe in 24 hours.

**Comment by driftywinds** [comment]
Thank you for replying!
