### ISSUE TITLE
feat (YT) : Swipe Controls that can change Playback Speed.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#54]
### Application

YouTube

### Feature description

Please add the swipe controls feature for playback speed, where swipe-up increases the speed & swipe-down decreases the speed.

### Motivation

• Playback Speed is an equally important parameter when compared to Volume & Brightness, so it should get equal treatment.

• It will save steps/taps for opening Playback Menu. Saving steps/taps was also the motivation behind Brightness & Volume Gesture, so Playback Speed should also get equal treatment.

• If implemented, large number of people will use it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
We already have hold to 2x video, isn't it ?

**Comment by Aryan-Chauhan** [comment]
> We already have hold to 2x video, isn't it ?

Yeah, but controlling playback speed by swiping would be much, much cooler.

**Comment by Aryan-Chauhan** [comment]
Closing this issue, because I listed all my YT feature requests in this single issue:

#225
