### ISSUE TITLE
What repository secrets have you configured exactly for semantic-release to work properly?

### ISSUE THREAD

**Issue by driftywinds** [anddea/revanced-patches#540]
### Application

Other

### Question description

I am trying to use GitHub Actions to make releases after forking your repo but semantic-releases always gives me an error code saying it doesn't have the permission to push to my repo. I wanted to know how I could fix the issue and it would be helpful if you could tell me what exact GitHub repo secrets do you use for semantic-release to work properly?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
[REPOSITORY_PUSH_ACCESS](https://github.com/settings/tokens/new?scopes=write:packages&description=REPOSITORY_PUSH_ACCESS)

Either remove GPG signing from release workflow and build.gradle, or use GPG on your computer and create GPG key (only 1 key), then just create these secrets
GPG_PRIVATE_KEY - private key generated by GPG
GPG_PASSPHRASE - passphrase for it
GPG_FINGERPRINT - the hash fingerprint for it

Secrets are provided in Settings tab for each repository.

**Comment by driftywinds** [comment]
Hey, thank you for replying!

I configured the secrets but semantic-release fails to release without an error code or anything I can go by: - https://github.com/driftywinds/revanced-patches/actions/runs/9267836878/job/25495136538

If you could please let me know what I'm doing wrong I'd be thankful!

**Comment by anddea** [comment]
Probably because it generates logs for all commits and it has error that cannot handle that many logs. Create release tag manually in your repo and assign it to the latest commit or choose any recent, so next time you push something, it will generate with no error.

**Comment by driftywinds** [comment]
> Probably because it generates logs for all commits and it has error that cannot handle that many logs. Your error is E2BIG which means "Argument list too long.". Check [error codes](https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html). Create release tag manually in your repo and assign it to the latest commit or choose any recent, so next time you push something, it will generate with no error. You can delete manually created empty release tag later, once your auto-release will be successful.

Thank you so much, that got it working!
