### ISSUE TITLE
question: Is the history broken with latest dev patches?

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [anddea/revanced-patches#545]
### Application

YouTube

### Question description

I'm currently using the latest dev patches and whenever I play a video, it won't get saved to the history.
I do have the application installed as root in case that's important.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
No, history works fine. Either your AdBlock or YouTube bug.

**Comment by anddea** [comment]
> Using brand account doesn't save history so maybe that's it?

Yes, could be. Only if spoof client to iOS is enabled.
