### ISSUE TITLE
suggestion: About search settings bar

### ISSUE THREAD

**Issue by sr-shishir** [anddea/revanced-patches#546]
### Application

YouTube

### Suggestion description

![20240529_005940](https://github.com/anddea/revanced-patches/assets/139035194/4c38e2a2-1f9b-47ad-baf4-658811d3b6b2)
Can you redesign the search settings bar like this rounded shape. It would be very cool & more professional 😊

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by speedlorenzo12** [comment]
At this point make the bar similar to that of YouTube but at the same size

**Comment by anddea** [comment]
That was in my plan, but I have not much time currently.

**Comment by sr-shishir** [comment]
> That was in my plan, but I have not much time currently.

Take your time but make this happen 😊

**Comment by Francesco146** [comment]
can be closed
