### ISSUE TITLE
About Default quality problem 

### ISSUE THREAD

**Issue by Mohammedibrahim15** [anddea/revanced-patches#548]
### Application

YouTube

### Question description

Hi anddea
Thanks for your great efforts
I want to know if this problem is solved in your recent patches or not

https://github.com/inotia00/ReVanced_Extended/issues/1959#issuecomment-2132153812

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Yes, I merged those changes by inotia a while ago.
