### ISSUE TITLE
question: anddea, do you have any interest in making the `Spoof client` patch compatible with Relay v11.0.19 ?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#549]
### Application

YouTube

### Question description

Just wanted to ask this.

Relevant issue on ReVanced repository:

https://github.com/ReVanced/revanced-patches/issues/2532

Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Not really. I hardly have time to make features for YouTube/Music. It's hard for one person to maintain that many apps, because everyday something gets broken.
