### ISSUE TITLE
Close the next, previous and pause/play buttons by tapping the screen

### ISSUE THREAD

**Issue by OctavXD** [anddea/revanced-patches#551]
### Application

YouTube

### Question description

So on YouTube if you have a video playing on fullscreen and you tap the screen once, the buttons for last video, next video and play/pause will appear, if you tap the screen once again, they will dissappear. Currently this option is not available for me and I don't know how to change it. The only way I can close those buttons is to click the x in the right up corner. Is there any way I could change some settings so the screen closes just by taping the screen somewhere empty?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Disable accessibility controls in Settings > Accessibility.
