### ISSUE TITLE
feat(YouTube): add ability to hide key concept

### ISSUE THREAD

**Issue by shreyjain1998** [anddea/revanced-patches#552]
### Application

YouTube

### Feature description

Would you please add an option to hide key concepts?

<details>
<summary>Screenshots</summary>

Video [link](https://youtu.be/zgdMhNnNuY0)
![Screenshot_2024-05-30-15-29-02-632_anddea youtube](https://github.com/anddea/revanced-patches/assets/107779107/b435b68d-9035-4c1f-9d19-6251ca76791e)
![Screenshot_2024-05-30-15-29-07-015_anddea youtube](https://github.com/anddea/revanced-patches/assets/107779107/998bd287-6fb1-4135-a962-e407e24d008d)
![Screenshot_2024-05-30-15-29-33-111_anddea youtube](https://github.com/anddea/revanced-patches/assets/107779107/6cab1437-8ab6-4c31-8590-88c54bea52d1)

</details>

### Solution
Custom filter: https://github.com/anddea/revanced-patches/issues/552#issuecomment-2143382489 and https://github.com/anddea/revanced-patches/issues/552#issuecomment-2158506975

### Motivation

Cleaner experience

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by odkate** [comment]
> Video [link](https://youtu.be/zgdMhNnNuY0)

For some reason, I don't have such a label on this video🤔

**Comment by Aryan-Chauhan** [comment]
You can enable `Hide Chapters Section`. That option can hide Key Concepts as well.

Side-effect: All chapters section will be hidden in description of all videos.

**Comment by Aryan-Chauhan** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2102

**Comment by ILoveOpenSourceApplications** [comment]
Add `^macro_markers_carousel$learning_concept` to custom filters if you want to hide only 'Key concepts' shelf and don't want to hide 'Chapters' shelf.

**Comment by ILoveOpenSourceApplications** [comment]
`Hide chapters section` and `Hide key concepts section` can now be separated. 
For chapters: `^macro_markers_carousel.eml$chapters_horizontal_shelf`
For key concepts: `^macro_markers_carousel$learning_concept`
```kotlin
06-10 19:05:21.008 13232 13232 D revanced: LithoFilterPatch: Searching ID: null Path: macro_markers_carousel.eml|d933604104a4a354|CellType|carousel_listener.eml|d56813604510a92b|ContainerType| BufferStrings: macro_markers_carousel_shelf_0Γ¥Öchapters_horizontal_shelfΓ¥Ö
06-10 19:05:21.076 13232  3204 D revanced: LithoFilterPatch: Searching ID: macro_markers_carousel.eml|d933604104a4a354 Path: macro_markers_carousel.eml|d933604104a4a354|CellType| BufferStrings: macro_markers_carousel.horizontal_shelf_slotsΓ¥Öhorizontal_shelf_slots.eml|9759d42c3246a45cΓ¥Ölearning_concept_macro_markers_carousel_shelf_0Γ¥Öcarousel_listener.eml|d56813604510a92bΓ¥Ö1718026477149505265Γ¥Ömacro_markers_carousel.eml|d933604104a4a354Γ¥Ö
```

**Comment by Francesco146** [comment]
can be close
