### ISSUE TITLE
Premium Header is not working 

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#553]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.20.34

### Bug description

https://github.com/anddea/revanced-patches/assets/61022739/3b9708df-b5e1-4932-8c47-d2df717f8065

### Additional context

![IMG_20240530_183533](https://github.com/anddea/revanced-patches/assets/61022739/78f8c812-8d90-4f77-9b17-cb2038ee2abc)

### Device Environment

Android 14 HyperOS 1.0 Elite HyperOS Lite 24.5 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Exclude `Force custom branding wordmark header` patch.
