### ISSUE TITLE
feat: Toggle to disable battery optimization popup at startup

### ISSUE THREAD

**Issue by hdd45** [anddea/revanced-patches#554]
### Application

YouTube

### Feature description

Please add a toggle to hide the new microG GMS core battery optimization popup at startup.
![image](https://github.com/anddea/revanced-patches/assets/51121709/f409d99a-a7b1-4f0f-bb9b-d5dba8fe4339)
For me It works seamlessly without doing so it's very annoying.

I understand it's necessary but It shouldn't popup every time I open the app.

### Motivation

I requested the same thing to [ReVanced devs](https://github.com/ReVanced/revanced-patches/issues/3213) but they denied adding this, so requesting from you I hope you'll understand. There are lots of options to hide even minute things in the app, adding this will not be a big deal for you. Thank You

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Sam101011** [comment]
Open the microG. Go to self-check. Scroll to the bottom and click the tick next to *battery optimisation ignored. Done

**Comment by Aryan-Chauhan** [comment]
> Open the microG. Go to self-check. Scroll to the bottom and click the tick next to *battery optimisation ignored. Done

He & I does not want to give GmsCore that permission. 

That's why the request to hide that popup banner.

**Comment by Aryan-Chauhan** [comment]
@hdd45 

Can you also request this on inotia00's repository?

https://github.com/inotia00/ReVanced_Extended/issues/

**Comment by Francesco146** [comment]
without this permission you could be logged out from your account

**Comment by anddea** [comment]
So is there an open issue in inotia's repo, because if he's willing to do it then I don't need to.

**Comment by anddea** [comment]
Open it there and if he's not going to do that, I'll take a look.

**Comment by rohankm** [comment]
Please add do not show button.. that popup is annoying

**Comment by anddea** [comment]
@rohankm this feature request was completed on June 5, 2024. The "Do not show" button is already available.

**Comment by rohankm** [comment]
> @rohankm this feature request was completed on June 5, 2024. The "Do not show" button is already available.

Whenever I open the app I see alert dialogue... It has only continue button

**Comment by anddea** [comment]
Sounds like you're using the wrong patches if you don't have that setting. Switch to `anddea`. Verify the source, version in your patching tool settings.
