### ISSUE TITLE
question: Overlay buttons only visible on xxhdpi devices?

### ISSUE THREAD

**Issue by TidalMist** [anddea/revanced-patches#555]
### Application

YouTube

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
No, all devices. It uses xxhdpi folder, but if no other folder is found it will use the only provided folder.
