### ISSUE TITLE
feat(YouTube - Related Video Overlay): Hide Mix Playlists in Related Videos Overlay

### ISSUE THREAD

**Issue by Pikasatupu75** [anddea/revanced-patches#556]
### Application

YouTube

### Feature description

I am requesting that when the "Hide mix playlists" option is activated in the feed options, that the mix playlists in related videos overlay are hidden as well. Since they are supposed to show the same list of videos.

Related videos overlay
![Screenshot_20240531-011422_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/126986435/f484ef42-aa48-4e41-82bb-777975997472)

Feed
![20240531_012859](https://github.com/anddea/revanced-patches/assets/126986435/30846b86-dee4-4f28-9c64-190ec8c46e0e)

Note: I am on version 2.225.0-dev.22. So I am sorry if this is a feature already in newer versions. Even though I checked the changelog.

### Motivation

It is just for the sake of consistency.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Pikasatupu75** [comment]
And here is the video link for reference: https://youtu.be/5RAUAVWrTPM

**Comment by anddea** [comment]
Reopen this issue as bug report in inotia's repo.

**Comment by Pikasatupu75** [comment]
Alright but how? There is no issues section in inotia's repo.
![20240531_112126](https://github.com/anddea/revanced-patches/assets/126986435/1c2d2666-f797-4605-a0f7-910d0bd4eca6)

**Comment by Pikasatupu75** [comment]
Inotia00 doesn't accept this as a bug.
https://github.com/inotia00/ReVanced_Extended/issues/2022

Maybe he will accept it as a feature request?

**Comment by anddea** [comment]
He will close it too then.

**Comment by Pikasatupu75** [comment]
Yes, it is already closed. https://github.com/inotia00/ReVanced_Extended/issues/2105

**Comment by imvoldemort** [comment]
What's the name of your fonts?

**Comment by Pikasatupu75** [comment]
It is [Livvic](https://fonts.google.com/specimen/Livvic)

**Comment by anddea** [comment]
Untli I have time to investigate a little deeper, if it's possible to hide at all, use custom filter:

```
related_watch_next$Mix
```

Replace "Mix" if it's different in your language.

The same way you can hide playlist by using "Playlist" instead of "Mix".

Also, to hide Mix playlists from feeds you can use 

```
video_with_context$Mix
```

This custom filter is a little better for performance than the one in the settings as it has to check less things. So to make this filter better, either we have to collect translations for "Mix" (like we made for patches filtering videos by views and auto-expanding descriptions), or use multiple exceptions as currently implemented for hiding Mix playlists, although this method is slightly more resource-intensive.

**Comment by Pikasatupu75** [comment]
Tested the custom filters, everything works as you have said. Only addition, `video_with_context$Mix` also hides videos with "Mix" in their name. So I think the current "Hide mix playlist" setting does a better job at hiding Mix playlists.

**Comment by anddea** [comment]
> `video_with_context$Mix` also hides videos with "Mix" in their name. So I think the current "Hide mix playlist" setting does a better job at hiding Mix playlists.

Yes, the option in settings is more reliable. 

What about this one

```
video_with_context$Mix -
```

**Comment by anddea** [comment]
Yes, if there is "Mix -" in the title, it will be hidden as well. My recommendations are different, so I don't see any videos with "Mix -" in the title.

**Comment by Pikasatupu75** [comment]
Me neither, it is just the only issue I could point out with `video_with_context$Mix -`. Other than that, it is perfectly good and works.
