### ISSUE TITLE
suggestion: Thanks Button

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#558]
### Application

YouTube

### Suggestion description

YouTube - Hide Shorts components: Hide 'Buy super thanks' button ([#3176](https://github.com/ReVanced/revanced-patches/issues/3176)) ([89c1548](https://github.com/ReVanced/revanced-patches/commit/89c154861c8b3afa665542e97ff201c3e84410b2))

Can you divide 'Hide Thanks button' into 'Hide Thanks Button (Action Button , Existed Setting), 'Hide Thanks Button (Comment Section, Existed Setting)', and 'Hide 'Buy Super Thanks'  Button' (Shorts Player, No Existed Setting, The button above the information (location, tagged product...))'?

It seems like I can hide 'buy super thanks' button by with one of the two existing settings.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Open this issue in inotia's repo.
