### ISSUE TITLE
suggestion: Add Config Custom Filter For Settings On Compiler/Patcher or Else

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#559]
### Application

YouTube

### Suggestion description

I mean, it kind of troublesome to type one by one the settings I wanna hide. So I guess it's better to add the config in the patcher, or config.json file if using ReVanced builder like mine or j-hc ones, or hide it by default.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I cannot understand your request. We already have options.json for patching tools (all of them) and import/export internal settings.
