### ISSUE TITLE
YouTube Music new releases

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#560]
### Application

YouTube Music

### Question description

I just built a new YouTube Music app and my New Releases notifications at the top of my screen seems to be gone. I clearly accidentally shut it off in the revanced settings. But I can't figure out which setting it was... Picture was from before. Any idea how to get that New Releases notifications back?

![Screenshot_20240527_232342_WhatsApp](https://github.com/anddea/revanced-patches/assets/117659952/0b6bb5a5-73d3-428d-90c5-2d8084f08832)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
New releases are not always at the top, it's behavior of YT Music itself. Reset your settings to default to check if it comes back.

**Comment by MtndaleRedneck** [comment]
By default it does come back. Which means I clearly shut it off by accident while stripping out all the fluff from the app. I just can't figure out which setting caused it...
