### ISSUE TITLE
Add Quality Dialog button

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#561]
### Application

YouTube

### Suggestion description

I love the Speed Dialog feature to allow you to quickly change speeds in full screen. Can we get the same for a Quality dialog button?

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You can tap on timestamp info quality and it will open menu to select quality.

**Comment by MtndaleRedneck** [comment]
Huh. Never realized that before. Thanks. Why does Quality take up the full screen while Speed doesn't? Any way to stop Quality taking up the full screen?

![Screenshot_20240531_105838_YouTube.jpg](https://github.com/anddea/revanced-patches/assets/117659952/af06e1da-0f53-4efc-8f6c-a09cc26a9bee)

![Screenshot_20240531_105832_YouTube.jpg](https://github.com/anddea/revanced-patches/assets/117659952/d751538b-0ca5-4163-b1f5-23c8f5bf89ef)

**Comment by anddea** [comment]
Because no one could find a better way to use bottom sheet menu. It tries to replicate bottom sheet, because YT uses it by default.

**Comment by MtndaleRedneck** [comment]
Don't really understand what you mean but you're basically saying that the full screen Quality is a known issue but there's no good way around it?

**Comment by anddea** [comment]
Yes, except it's not an issue, it's a feature. Custom written and purposely made like this.

**Comment by MtndaleRedneck** [comment]
It's not an 'issue', but it is annoying. Would be better if it didn't go full screen.

**Comment by anddea** [comment]
True. Maybe I'll take a look when I have time.
