### ISSUE TITLE
Revancify Yellow Icon

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#566]
### Application

YouTube

### Question description

In changeling of Revanced Patches 2.26.0-dev.3 mentioned that you add Revancify Yellow Icon
![IMG_20240601_181526](https://github.com/anddea/revanced-patches/assets/61022739/46dc0431-753b-4e45-a362-276475f6940d)
But i don't see this type of icon in Revanced Manager 
![Screenshot_2024-06-01-18-12-57-600_app rvx manager flutter-edit](https://github.com/anddea/revanced-patches/assets/61022739/edf378f2-9b26-4f9e-97de-b830841ffdc8)
I use Revanced Patches 2.26.0-dev.3
![Screenshot_2024-06-01-18-12-45-358_app rvx manager flutter-edit](https://github.com/anddea/revanced-patches/assets/61022739/ff2dd475-20c4-4d09-9d67-916f19c72503)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Someone didn't add it to patch options, you can type yourself "Revancify Yellow", "revancify_yellow" or whatever.

**Comment by bozander** [comment]
Fixed in Revanced Patches 2.226.0-dev.4 Thanks @anddea
