### ISSUE TITLE
bug(YT & YTM) - "Open GMSCore" button doesn't support forked GMSCore(s)

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#569]
### Type

Other

### Tools used

rvx-builder

### Application

Not Applicable

### Bug description

"Open GMSCore" doesn't support or open any of the forked GMSCore. It only support official from revanced. As we know that revanced GMSCore doesn't support hiding from launcher. Due to which many people like me use the rufusin GMSCore as he only added support for hide from launcher.

So, the option should open forked GMSCore(s) from ReX and rufusin too. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Does it happen in inotia's patches?

**Comment by Vipin2003** [comment]
> Does it happen in inotia's patches?

Yupp...It is also there too.

**Comment by anddea** [comment]
Open bug report there then, he accepts bug reports and fixes them when he has time.
