### ISSUE TITLE
bug: comment like button dont work via comment filtering on

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#570]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

19.20.34

### Bug description

When i open comment filtering this happens
![Screenshot_20240601_213336_RVX Youtube](https://github.com/anddea/revanced-patches/assets/143447608/95f7f7dd-5e2c-4025-b87d-fc32b7128e77)

### Solution

Turn off comment filtering or disable filtering "Like" word

### Device Environment

Android 14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You mean keyword filter for comments? What are your filters?

**Comment by Ahmey1400** [comment]
![Screenshot_20240602_004111_RVX Youtube](https://github.com/anddea/revanced-patches/assets/143447608/d8375cdc-c47c-4a26-b336-afd7cb09915d)

**Comment by anddea** [comment]
Yep, that's what I thought. The like button in comments has "like" in the description and/or drawable name, which is why it's being hidden.

@inotia00, please update the whitelist for keyword filtering too.

**Comment by Ahmey1400** [comment]
Should i close this issue or open it at inotia's repo

**Comment by anddea** [comment]
If you want. But I tagged him, so he'll see this anyway.

**Comment by anddea** [comment]
He said this

> if i disable "like" word it fixes itself

Although for me "like" hides the whole bar (like, dislike, comment and other buttons). If I type "like this", it hides like and dislike buttons keeping the number of likes. Just like in the screenshot. 

@Ahmey1400 can you share what exactly you typed there? Was it just "like"?

**Comment by Ahmey1400** [comment]
When I add "like" the whole buttons disappear such as like-dislike but when I add "like this comment" the like and dislike part disappears.

**Comment by Ahmey1400** [comment]
If I add "like this comment" it looks like this:

![Screenshot_20240603_181242_RVX Youtube](https://github.com/anddea/revanced-patches/assets/143447608/ea4954c4-5b05-47c2-ae5c-74f23d3aa870)

**Comment by Ahmey1400** [comment]
And if I add "like" word it look like that (whole comment stuff gone):

![Screenshot_20240603_181540_RVX Youtube](https://github.com/anddea/revanced-patches/assets/143447608/e73ac236-dbdf-4751-b104-6174e84567f4)

**Comment by Ahmey1400** [comment]
@anddea did you find any solution?

**Comment by Francesco146** [comment]
after the merge by RVX, does still happen in RVX?

**Comment by anddea** [comment]
There was no fix yet.

**Comment by anddea** [comment]
Fixed in the latest release, test it and let me know.
