### ISSUE TITLE
feat: Stretch the video on phones with a different aspect ratio to 16:9

### ISSUE THREAD

**Issue by ElmorenohWTF** [anddea/revanced-patches#571]
### Application

YouTube

### Feature description

To be able to take advantage of the full size of the screen, it seems to me a better solution than cutting content.

It will solve that you have to cut content when you want to take advantage of the entire screen of your device.

That there is a button, or a gesture, that allows you to stretch the video so that it fills the entire screen.

### Motivation

Because it would be very useful for people with a device that has a different aspect ratio than 16:9

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
There's a built-in features in YouTube Settings > General > Zoom to fill. But if you restart the app it'll reset, you can report to YouTube team this bug.
