### ISSUE TITLE
Additional external downloader options

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#572]
### Application

YouTube

### Question description

Not sure if you've ever heard of Listenbox (listenbox.app) but can you please add https://listenbox.app/later or https://play.google.com/store/apps/details?id=app.listenbox as an option for external downloader? Listenbox is a service that turns YouTube channels into rss podcast feeds.  https://listenbox.app/later (or the app which I linked that exists solely as a redirect to that web page) allows you to forward a YouTube link into your own personal rss podcast feed. It then gets added to your podcast app of choice. Very cool service. I'd just love to be able to use the download link as a redirect button to that app.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by meoyawn** [comment]
if Revanced is able to send `android.intent.action.SEND` with the video URL Listenbox app will be able to handle it.

If Revanced has a Share option, Listenbox app will appear in the share sheet

**Comment by anddea** [comment]
You can enter any downloader app package name in "External downloader package name" option.

**Comment by MtndaleRedneck** [comment]
@anddea Thanks!! That worked.
