### ISSUE TITLE
YouTube Music Voice Search question: 

### ISSUE THREAD

**Issue by sultanmonsur** [anddea/revanced-patches#573]
### Application

YouTube Music

### Question description

YT Music Voice Search Not Working Why?
![Screenshot_2024-06-02-21-49-29-90_e37d6c609c2adec833a8789adba3d4f2](https://github.com/anddea/revanced-patches/assets/61897416/9aa75fdd-ddff-4b7c-b3c6-36d5f9b1d884)
![Screenshot_2024-06-02-21-32-27-28_e37d6c609c2adec833a8789adba3d4f2](https://github.com/anddea/revanced-patches/assets/61897416/086ed14b-a9fc-4226-b1ef-8fd3662c0316)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It works just fine. Either it didn't recognize anything or you didn't give microphone permission.

**Comment by anddea** [comment]
It recognizes songs for me, so should be something on your side.
