### ISSUE TITLE
I'm getting no ad blocking

### ISSUE THREAD

**Issue by B2Pi** [anddea/revanced-patches#575]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 19.20.34

### Bug description

Ads are not being blocked at all. I've uninstalled all updates and repatched to reinstall to no avail

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Can you go to ReVancify folder in your internal storage, then open `patch_log.txt` in some text editor and paste everything in the patch log here in the form of a comment?

**Comment by B2Pi** [comment]
Please forgive the delay

INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Translations excluded 
INFO: Enable debug logging excluded 
INFO: Force hide player buttons background excluded 
INFO: MaterialYou excluded 
INFO: Theme excluded 
INFO: Hide double tap to like animations excluded 
INFO: Force custom branding wordmark header excluded 
INFO: Hide Shorts dimming excluded 
INFO: Hide ads excluded 
INFO: GmsCore support excluded 
INFO: Shorts components excluded 
INFO: Change Shorts repeat state excluded 
INFO: Disable resuming Shorts on startup excluded 
INFO: Hide feed components excluded 
INFO: Hide feed flyout menu excluded 
INFO: Ambient mode control excluded 
INFO: Player components excluded 
INFO: Change player flyout menu toggles excluded 
INFO: Hide player flyout menu excluded 
INFO: Fullscreen components excluded 
INFO: Hide action buttons excluded 
INFO: Hide comments components excluded 
INFO: Seekbar components excluded 
INFO: Hide player buttons excluded 
INFO: Description components excluded 
INFO: Force snackbar theme excluded 
INFO: Disable auto audio tracks excluded 
INFO: Navigation bar components excluded 
INFO: Disable splash animation excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Add splash animation succeeded 
INFO: Alternative thumbnails succeeded 
INFO: Change start page succeeded 
INFO: Custom branding icon YouTube succeeded 
INFO: Custom branding name YouTube succeeded 
INFO: Custom double tap length succeeded 
INFO: Custom package name succeeded 
INFO: Disable QUIC protocol succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable haptic feedback succeeded 
INFO: Enable external browser succeeded 
INFO: Enable gradient loading screen succeeded 
INFO: Enable minimized playback succeeded 
INFO: Enable open links directly succeeded 
INFO: Enable tablet mini player succeeded 
INFO: Hide animated button background succeeded 
INFO: Hide double tap overlay filter succeeded 
INFO: Hide layout components succeeded 
INFO: Layout switch succeeded 
INFO: Overlay buttons succeeded 
INFO: Remove viewer discretion dialog succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Sanitize sharing links succeeded 
INFO: Shorts overlay buttons succeeded 
INFO: SponsorBlock succeeded 
INFO: Spoof app version succeeded 
INFO: Spoof client succeeded 
INFO: Swipe controls succeeded 
INFO: Toolbar components succeeded 
INFO: Video playback succeeded 
INFO: Visual preferences icons succeeded 
INFO: Settings succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiling modified resources 
INFO: Ripping selected native libs 
INFO: Aligning APK 
INFO: Signing APK 
INFO: Saved to /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.20.34/base-RVX-anddea.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 



Rooted: true
Arch: arm64-v8a
App: YouTube v19.20.34
CLI: inotia00-cli-v4.6.1.jar
Patches: anddea-patches-v2.226.0-dev.4.jar
Integrations: anddea-integrations-v0.153.0-dev.1.apk
Patches argument: -i Add splash animation -i Alternative thumbnails -i Change start page -i Custom branding icon YouTube -i Custom branding name YouTube -i Custom double tap length -i Custom package name -i Disable QUIC protocol -i Disable auto captions -i Disable haptic feedback -i Enable external browser -i Enable gradient loading screen -i Enable minimized playback -i Enable open links directly -i Enable tablet mini player -i Hide animated button background -i Hide double tap overlay filter -i Hide layout components -i Layout switch -i Overlay buttons -i Remove viewer discretion dialog -i Return YouTube Dislike -i Sanitize sharing links -i Settings -i Shorts overlay buttons -i SponsorBlock -i Spoof app version -i Spoof client -i Swipe controls -i Toolbar components -i Video playback -i Visual preferences icons

**Comment by Aryan-Chauhan** [comment]
> INFO: Hide ads excluded 

Look here on the 11th line, you excluded `Hide ads` patch.

How will you get adblocking?

Please include it & repatch, then kindly close the issue.

**Comment by B2Pi** [comment]
I want born stupid. It took years of work... I have no idea how that happened. Thank you
