### ISSUE TITLE
suggestion: Kindly just stay to maintain the source 

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#577]
### Application

YouTube

### Suggestion description

Due to overly complex and complicated discussions here...

https://github.com/inotia00/revanced-patches/pull/55

I guess it's better to not to make a PR to inotia00. It's up to you though, but if some unique patch will be removed, we'll, it's a deal breaker. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I will continue. Maybe people will have to wait longer, if I have no time.
