### ISSUE TITLE
bug:(YT) - `Download` button in action bar not showing on many videos

### ISSUE THREAD

**Issue by Vipin2003** [anddea/revanced-patches#581]
### Type

Other

### Tools used

rvx-builder

### Application

Latest Supported

### Bug description

Download button is not showing on any of the videos. I tried it with around 20 videos, but it keeps hidden. I also checked my revanced x settings, everything looks fine there. Here are screenshot from RVX and Official of same video. 
![Screenshot_20240606_081732](https://github.com/anddea/revanced-patches/assets/93650504/169ed963-38e9-4fac-a260-86a1444ec3a1)
![Screenshot_20240606_081722](https://github.com/anddea/revanced-patches/assets/93650504/d49a0b10-2a0d-470d-9d87-44d18904fb95)

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
It is a new side effect of Client Spoof, I think

**Comment by Vipin2003** [comment]
> It is a new side effect of Client Spoof, I think

You are right...It only happens when client is spoofed
