### ISSUE TITLE
question: how can I change app icon option in RVX builder PC?

### ISSUE THREAD

**Issue by hdd45** [anddea/revanced-patches#582]
### Application

YouTube

### Question description

how can I change app icon patch, brand name options in RVX builder Windows ?

Under "Custom branding icon YouTube", It says "Changes the app icon to the icon specified in options.json"

Where can I locate this **options.json** file and how can I modify it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
`options.json` located in the same folder where your builder is. Just open it and find patch name there, there you can provide the name for custom branding icon.
