### ISSUE TITLE
Bug in fullscreen mode

### ISSUE THREAD

**Issue by Gubbbka** [anddea/revanced-patches#583]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.20.34

### Bug description

Cant disable video switching by swiping down and up in full screen mode. Swiping to exit fullscreen mode and swiping to other videos isnt work due this one. 

https://github.com/anddea/revanced-patches/assets/169579036/09c29795-f62e-4f21-b73a-e708b593a46e

### Solution

Repatch with v19.19.39 or lower

### Device Environment

Android 13. MIUI 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by Francesco146** [comment]
it happens even on RVX? if so you can file a bug report in its issue center

**Comment by anddea** [comment]
Maybe because of client spoof. Reopen this bug report in inotia's repo.
