### ISSUE TITLE
suggestion: splash animation for afn red&blue icons

### ISSUE THREAD

**Issue by MondayNitro** [anddea/revanced-patches#586]
### Application

YouTube

### Suggestion description

can you add these splash animations for afn red&blue icons? its a simple animation but it works

[splash-red.zip](https://github.com/user-attachments/files/15743057/splash-red.zip)

[splash-blue.zip](https://github.com/user-attachments/files/15743058/splash-blue.zip)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I'll check later, thank you.

**Comment by anddea** [comment]
If you want, you can create animations for other icons too, even simple animations look better.

**Comment by MondayNitro** [comment]
> If you want, you can create animations for other icons too, even simple animations look better.

svg files of the icons will be needed for that, making svg icons for afn was quite easy but revancify looks very difficult to me🥲

**Comment by anddea** [comment]
Yes, it's true, don't worry then, it's fine. But if you ever create new animations or improve animations for these, feel free to share. Thank you for your contribution. 

But if you wonder, they can be recreated with simple shapes, just in case you would want to try, there's a fairly simple web-based tool Boxy SVG (I think there was a repo for it) with good tutorials on YouTube. There's also a good open source professional software - Inkscape.

**Comment by anddea** [comment]
Btw, monochrome icon is an SVG icon actually, you just have to convert it or copy paste each pathData to SVG paths.

**Comment by MondayNitro** [comment]
thanks, it works but i cant create color gradient like in the icon

![vector](https://github.com/anddea/revanced-patches/assets/87489540/766ec9b4-a313-4c10-b5f7-12b35906ebf6)
 i think i should create monet themed splash for revancify icon, as there wont be gradient issue here

**Comment by MondayNitro** [comment]
this looks decent i think, now i will try make splash
![Untitled (1)](https://github.com/anddea/revanced-patches/assets/87489540/201e5e5d-0e3b-4954-9a29-ecae95ad2deb)

**Comment by Xisrr1** [comment]
@MondayNitro Hey, I am working on a splash animation for the Revancify icon too.

**Comment by MondayNitro** [comment]
> @MondayNitro Hey, I am working on a splash animation for the Revancify icon too.

are you able to put color gradient in splash animation(not in svg)

**Comment by Xisrr1** [comment]
> are you able to put color gradient in splash animation(not in svg)

I haven't tried yet.

Where did you get the high resolution revancify icon from?

**Comment by MondayNitro** [comment]
> > are you able to put color gradient in splash animation(not in svg)
> 
> I haven't tried yet.
> 
> Where did you get the high resolution revancify icon from?

from the monochrome icon

**Comment by Xisrr1** [comment]
> > > are you able to put color gradient in splash animation(not in svg)
> > 
> > I haven't tried yet.
> > 
> > Where did you get the high resolution revancify icon from?
> 
> from the monochrome icon

I tried, but I didn't get the same resolution. Do you mind sending me it as a file?

**Comment by MondayNitro** [comment]
> > > > are you able to put color gradient in splash animation(not in svg)
> > > 
> > > 
> > > I haven't tried yet.
> > > Where did you get the high resolution revancify icon from?
> > 
> > 
> > from the monochrome icon
> 
> I tried, but I didn't get the same resolution. Do you mind sending me it as a file?

the ones i pasted here are svg icons only

**Comment by Xisrr1** [comment]
I see

**Comment by Xisrr1** [comment]
@MondayNitro how did you get all 4 files for the splash animation?

**Comment by MondayNitro** [comment]
> @MondayNitro how did you get all 4 files for the splash animation?
> 
> And I'm not able to use a gradient color.

put animation xml in apk folder and compile. it will autocreate the 4 files
btw, which tool u ised to make animation?

**Comment by Xisrr1** [comment]
> put animation xml in apk folder and compile. it will autocreate the 4 files

What apk folder? Can you elaborate?

> btw, which tool u ised to make animation?

 I used Shape Shifter, what did you use and how did you export the animation?

**Comment by MondayNitro** [comment]
> > put animation xml in apk folder and compile. it will autocreate the 4 files
> 
> What apk folder? Can you elaborate?
> 
> > btw, which tool u ised to make animation?
> 
> I used Shape Shifter, what did you use and how did you export the animation?

put in res/drawable folder of the apk and compile, then decompile the apk to get the animation files. i used apktool jar for this

i also made on shapeshifter, the animations there are really basic. nothing like the youtube splash or mmt splash

**Comment by Xisrr1** [comment]
> put in res/drawable folder of the apk and compile, then decompile the apk to get the animation files. i used apktool jar for this

What's apktool jar? I'm using apktool m.

So I need to patch YouTube, decompile, put the animation, compile and then decompile? How am I supposed to find the animation files there? there are tons of other files.

And how did you know that you need to do that in order to get the files? 

Apologies for all the questions.
 
> i also made on shapeshifter, the animations there are really basic. nothing like the youtube splash or mmt splash

I managed to make a pretty decent animation, are you sure you did it correctly?

**Comment by anddea** [comment]
With Shape Shifter you can make any kind of animation, even like MMT. You just need more time to play with it. Any compiling app will do, Apktool M should do the job.

**Comment by Xisrr1** [comment]
> With Shape Shifter you can make any kind of animation, even MMT-like. You just need more time to play with it. Any compiling app will do, Apktool M should do the job. 

So there's no simpler way to get these files?

And what is apktool jar? I couldn't find any information online.

**Comment by MondayNitro** [comment]
> > With Shape Shifter you can make any kind of animation, even MMT-like. You just need more time to play with it. Any compiling app will do, Apktool M should do the job.
> 
> So there's no simpler way to get these files?
you can simply do it on stock yt apk, decompile->compile->decompile. should only take 5 min

also can you share here a preview of your animation, im on a11 rom so cant check myself

**Comment by Xisrr1** [comment]
> you can simply do it on stock yt apk, decompile->compile->decompile. should only take 5 min

On my phone it takes much longer

> also can you share here a preview of your animation, im on a11 rom so cant check myself

https://github.com/anddea/revanced-patches/assets/133952156/5364ca11-c9aa-4d43-b7b1-43dfb34d2b36

I can make it for the other Revancify icons if you want.

**Comment by MondayNitro** [comment]
> > you can simply do it on stock yt apk, decompile->compile->decompile. should only take 5 min
> 
> On my phone it takes much longer
> 
> > also can you share here a preview of your animation, im on a11 rom so cant check myself
> 
>  VID_20240620_203435_543.mp4 
> I can make it for the other Revancify icons if you want.

wow, its look great, you should make for red and blue too.
also, would you mind doing doing for afn also, mine was really bad. i will provide the svg if you agree

**Comment by Xisrr1** [comment]
> wow, its look great, you should make for red and blue too.

Yes.

> also, would you mind doing doing for afn also, mine was really bad. i will provide the svg if you agree

You can give me the SVG, but I cannot guarantee I will start working on it immediately.

**Comment by MondayNitro** [comment]
> You can give me the SVG, but I cannot guarantee I will start working on it immediately.

thanks, you can try making it at your leisure

![afn-blue](https://github.com/anddea/revanced-patches/assets/87489540/8029b552-a6e3-4394-840e-365c0e81a5c6)


![afn-red](https://github.com/anddea/revanced-patches/assets/87489540/678abf6f-dff4-4b58-a219-415da10d26c3)
