### ISSUE TITLE
bug: mmt animation doesnt work

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#590]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

19.20.35, patch version is: 2.226.0-dev.6

### Bug description

When I patch icon to mmt, special openning animation doesnt work

### Device Environment

Android 14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
can be closed
