### ISSUE TITLE
bug: Patch fails with custom brand icon option

### ISSUE THREAD

**Issue by Joshua64** [anddea/revanced-patches#591]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 19.20.35

### Bug description

Using the custom branding icon option with this settings 
![Screenshot_20240611_102229_RVX Manager](https://github.com/anddea/revanced-patches/assets/20147128/9ea341af-ba8a-49ee-823b-c153d2cf135c)

 The app fails to apply the patches 
![Screenshot_20240611_102441_RVX Manager](https://github.com/anddea/revanced-patches/assets/20147128/c2775517-58d7-4fb9-b8dc-7228bbaa77da)

### Device Environment

Galaxy a12
Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
can be closed
