### ISSUE TITLE
suggestion(YouTube - Custom Shorts action buttons): Make an actually outlined version of stock icons

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [anddea/revanced-patches#593]
### Application

YouTube

### Suggestion description

Currently the option outline doesn't use an actual outlined version of stock icon rather a slightly modified version. Using the already available assets from YouTube, including like,  dislike, comments & share, the only one requiring rework would be the remix button.

| Stock | Outline | Stock Outline |
|--------|--------|--------|
| ![Screenshot_20240611_195226_YouTube](https://github.com/anddea/revanced-patches/assets/117499019/1696885d-ce10-4197-b938-4a91c879839e) | ![Screenshot_20240611_195407_YouTube](https://github.com/anddea/revanced-patches/assets/117499019/b2b3cf96-0f5f-427f-af82-4eb30147a619) | ![A_black_image](https://github.com/anddea/revanced-patches/assets/117499019/e676866b-06ec-470b-afc7-993bcf5852bd) (I edited the icons from screenshots of YouTube and hence the weird icon layout) | 

As seen the the last column image, the stock outline remix button was taken from video action buttons. But the normal remix button can be seen in the first colum image. Whichever is fine in my opinion. Samples from YT Music can also be used for like, comments and share icons, if needed.

If outline is gonna be kept as is, maybe another option called stock outline could be added, which is a 1:1 replica of stock icons in an outline form.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you open PR? It would be better to stretch comment button though. Like it is right now for original bold icon or outline but flipped by X axis. You can grab vector images from prefs icons and convert them to PNG (for new YT) for each DPI and XML (for old YT).

**Comment by ILoveOpenSourceApplications** [comment]
I don't think I'm qualified enough for such a job. I'm barely understanding GitHub, and with zero knowledge in coding, I'll only make things worse. But I would appreciate if this got implemented.

**Comment by anddea** [comment]
I'll do that when I have enough time. I wanted to change them anyway but didn't have enough time. 

Btw, you don't need the code to update these icons, because the logic is already implemented, you just name each icon accordingly as they are right now and that's it.

**Comment by ILoveOpenSourceApplications** [comment]
Even if we have the icons don't they need to be resized and format changed and all?

**Comment by anddea** [comment]
Yes, they need to be resized for each screen DPI.

**Comment by ILoveOpenSourceApplications** [comment]
Yes, I saw that when I checked the directory and I was so confused with all the different folders for the different DPIs and stuff.

**Comment by MondayNitro** [comment]
> Yes, they need to be resized for each screen DPI.

i have the outline icons, ill upload zip here in sometime

**Comment by MondayNitro** [comment]
> I'll do that when I have enough time. I wanted to change them anyway but didn't have enough time.
> 
> Btw, you don't need the code to update these icons, because the logic is already implemented, you just name each icon accordingly as they are right now and that's it.

heres xhdpi and xxhdpi, someone please resize for other dpis
[outline.zip](https://github.com/user-attachments/files/15845858/outline.zip)

**Comment by anddea** [comment]
You can create only high quality images and then auto resize with ffmpeg for example, or similar tools. I was going to make it when I have more time. I have lossless quality images of these icons, so you don't have to worry.

**Comment by anddea** [comment]
I updated some icons, should look better now, what do you think?

**Comment by ILoveOpenSourceApplications** [comment]
Let me patch with dev release.

**Comment by ILoveOpenSourceApplications** [comment]
Yep, now the comments, share and remix match the official action buttons. The only thing which is slightly off is the tip of the thumb in like and dislike buttons icon. It's sharp in the current one, while the official one has a rounded tip.

**Comment by ILoveOpenSourceApplications** [comment]
Definitely looks better now for sure.
![Screenshot_20240626_201133_YouTube](https://github.com/anddea/revanced-patches/assets/117499019/acf29ca2-4a8d-4458-9792-6be3417667df)

**Comment by anddea** [comment]
Maybe I'll update like and dislike buttons one day, but not now. YouTube uses multiple types of these buttons.

**Comment by ILoveOpenSourceApplications** [comment]
Yeah, my main issue were with the entirely off looking share and remix buttons and now that they're changed it's looking much better. 

For more stock-ish outline icons (like 100%), the three icons that needs changing would be the like, dislike & comments button. They, for some reason, use a much squarer looking comments box icon than a rectangular looking icon(which imo, is better,) but again if we're going for a stock outline look, is slightly off.

<details><summary>Reference</summary>
<p>

![Screenshot_20240626_202034_YouTube Music](https://github.com/anddea/revanced-patches/assets/117499019/afd747d2-45de-4f94-a760-634ad13727e8)

But I'm happy with what it's now. There's always room for improvement in the future.

</p>
</details> 

Slightly off topic, but for this to be merged with inotia's repo, will he be able to merge it or will you have to open a PR there?

**Comment by anddea** [comment]
He'll ask to open PR anyway.

**Comment by ILoveOpenSourceApplications** [comment]
Will you be opening a PR then for this?

**Comment by anddea** [comment]
I'm going to, but not sure when.

**Comment by ILoveOpenSourceApplications** [comment]
Maybe, @MondayNitro can help with this small changes?
