### ISSUE TITLE
bug: 'hide disabled comments button' also disables comments button on normal shorts

### ISSUE THREAD

**Issue by sdsucks** [anddea/revanced-patches#594]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

Youtube-anddea-v19.20.35-patches_v2.226.0-dev.7

### Bug description

shorts - shorts player - action buttons - hide disabled comments button

turning on "hide disabled comments button" also disables comments button on normal shorts 

### Device Environment

android 13

one ui 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Turn off this option, seems like the litho filter is different for people from different regions or maybe for some other reasons. I cannot reproduce this issue. You're the first one to report this issue though. 

If you can grab logs and filter only "comment", send me here. Enable debug logging, including protobuf.
