### ISSUE TITLE
bug (YT) : Invalide keyword. Cannot use `VICE` as a filter

### ISSUE THREAD

**Issue by smed79** [anddea/revanced-patches#595]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.20.34
Patch v2.225.0 (2024-05-29)

### Bug description

Adding `VICE` as a keyword to my filters give me an error.
 
- [Screenshot / VICE keyword](https://github.com/anddea/revanced-patches/assets/1873139/4a6a42b8-a1af-492a-a4c3-e75226abd370).

### Additional context

My filter list has more than 250 lines in different languages, and I have never experienced any problem.

### Device Environment

Android 14.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Open bug reports in inotia's repo.

**Comment by anddea** [comment]
Fixed in the latest release, test it and let me know.

**Comment by smed79** [comment]
I tested with 

- YouTube 19.21.40
- ReVanced Patches 2.226.0-dev.11(2024-06-14)

The error message is gone but unexpected behavior has appeared !!

In the user channel, all or 99.99% of the content is hidden in the "videos page" if i add the keyword `VICE` (see screenshots).

No problem if i add `VICE News` for example.

Screenshots: 

- `https://i25.servimg.com/u/f25/11/94/21/24/0010.jpg`
- `https://i25.servimg.com/u/f25/11/94/21/24/0111.jpg`
- `https://i25.servimg.com/u/f25/11/94/21/24/0211.jpg`

My Settings: 

- https://pastebin.com/raw/ce9beXKi


Thank you.

**Comment by smed79** [comment]
I also noticed that the three dots to the right of the video title used to display the menu are hidden.

- `https://i25.servimg.com/u/f25/11/94/21/24/66611.jpg`

**Comment by anddea** [comment]
I see, I couldn't reproduce this issue, that's why I removed one whitelisted keyword. But I guess I have to revert back as it's whitelisted for good as you can see. At least for now if there's no better solution. 

https://github.com/anddea/revanced-integrations/blob/6104c34a46dc923b0d1d883748e59307066db467/app/src/main/java/app/revanced/integrations/youtube/patches/components/KeywordContentFilter.java#L78-L81

**Comment by smed79** [comment]
> I couldn't reproduce this issue.

I will try on another device to check if the issue come from my side.

Thank you for your help.
