### ISSUE TITLE
Shorts are not fully playing

### ISSUE THREAD

**Issue by lolouthefox** [anddea/revanced-patches#596]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

anddea.youtube v19.20.35

### Bug description

Shorts suddenly stop playback at 25% of their progress and then no shorts play at all.
I cannot send any video of the accident at this time.

### Device Environment

Android 14 (AP1A.240505.004) on Google Pixel 6a (aka stock Android version)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I cannot reproduce this issue. Check original YouTube if it has this issue for you and let me know.

**Comment by lolouthefox** [comment]
> I cannot reproduce this issue. Check original YouTube if it has this issue for you and let me know. 

Does not happen on original YouTube, it's really only happening on this version...
