### ISSUE TITLE
feat(Reddit): Remove 'Related Communities' section 

### ISSUE THREAD

**Issue by sliceanddice9** [anddea/revanced-patches#597]
### Application

Reddit

### Feature description

Remove the annoying 'Related Communities' ad that appears when scrolling within subreddits.

### Motivation

The 'Related Communities' appears in the 2024.17. 0 version of the Official Reddit App APK. It would be great to see this section removed. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by sliceanddice9** [comment]
![related communties](https://github.com/anddea/revanced-patches/assets/59092472/b19bf09e-ea62-4059-8bff-cc69439ee3c5)

**Comment by anddea** [comment]
Reopen this issue in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues)
