### ISSUE TITLE
Compact like/dislike

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#598]
### Application

YouTube Music

### Suggestion description

Can we get compact like/dislike buttons in the YouTube Music player? Want to see how many people have liked and disliked a song, but don't need it taking up so much space.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Request this in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues), he accepts requests for YT Music

**Comment by MtndaleRedneck** [comment]
You're just merging inotia00's code now? Trying to understand where your 2 separate repositories stand rn.

**Comment by anddea** [comment]
I have no enough time lately, so I do something but it's rare.
