### ISSUE TITLE
About making some patches with ON/OFF switch

### ISSUE THREAD

**Issue by Mohammed1520** [anddea/revanced-patches#6]
### Application

YouTube

### Question description

Hi . Please if it is possible can you make these patches with a switch in settings
Hide player button background
Hide chapters in player

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Added a toggle switch for `Hide player button background`.

**Comment by speedlorenzo12** [comment]
At this point make on/off switches for all patches

**Comment by Francesco146** [comment]
it can be fixed by refactoring from RVX
