### ISSUE TITLE
bug: YouTube app is laggy when scrolling

### ISSUE THREAD

**Issue by jojobozo** [anddea/revanced-patches#60]
### Type

Other

### Tools used

Revancify

### Application

YouTube v19.09.37

### Bug description

It's laggy when scrolling in the app, especially when scrolling in replies of comments

### Device Environment

Pixel 7 A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I can't see any lags on my devices. Do you experience the same behavior on stock YouTube app?

**Comment by Francesco146** [comment]
it's not the autoplay feature right?

**Comment by jojobozo** [comment]
> I can't see any lags on my devices. Do you experience the same behavior on stock YouTube app?

I'm not facing it on the stock app. I'm also using the rooted version so it's mounted on the stock app but I didn't face it on ReVanced.

**Comment by jojobozo** [comment]
> it's not the autoplay feature right?

It's disabled so I don't think so

**Comment by anddea** [comment]
> I'm not facing it on the stock app. I'm also using the rooted version so it's mounted on the stock app but I didn't face it on ReVanced.

Can you see any differences between apps? Maybe unhide all buttons in Bottom player? There actually should be no differences between ReVamced and Extended, related to scrolling comments or feed.

**Comment by jojobozo** [comment]
> > I'm not facing it on the stock app. I'm also using the rooted version so it's mounted on the stock app but I didn't face it on ReVanced.
> 
> Can you see any differences between apps? Maybe unhide all buttons in Bottom player? There actually should be no differences between ReVamced and Extended, related to scrolling comments or feed.

Yes I can see the difference, here's a video https://streamable.com/r45xys

**Comment by anddea** [comment]
I meant differences between interface that may cause any lags. Can you make comparison video with stock app?

**Comment by jojobozo** [comment]
> I meant differences between interface that may cause any lags. Can you make comparison video with stock app?

It's good now that I did a factory reset.
