### ISSUE TITLE
feat: (YTM) - Add patch option to hide buttons from "Samples" with background.

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#600]
### Application

YouTube Music

### Feature description

Like YT, there should be a option to hide buttons from "Samples" too. I know that many of the people don't use it (or may use it), it should be there. As icons are increasing too fast.

![Screenshot_20240614_205156](https://github.com/anddea/revanced-patches/assets/93650504/65b25b23-129c-4ad4-b6d5-406c867b4e08)

### Motivation

Will clean the YTM Samples and enhances the look.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Request YTM features in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues)

**Comment by vippium** [comment]
> [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues)

Are you just merging from inotia's repo from now??

**Comment by anddea** [comment]
I don't have enough time, so you'll get. better chance if you report there.

**Comment by Aryan-Chauhan** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1365
