### ISSUE TITLE
bug: (YT) - Old Splash animation is not working.

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#601]
### Type

Other

### Tools used

rvx-builder

### Application

19.16.39

### Bug description

Old splash animation doesn't exits anymore. It just a simple logo appears. Old splash animation is more feasible than having a simple logo only.

https://github.com/anddea/revanced-patches/assets/93650504/5fc796a2-23b0-4a9c-b8d3-c91e3159348e

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
DId you enable RestoreOldSplashAnimation?

**Comment by vippium** [comment]
> DId you enable RestoreOldSplashAnimation?

How and from where? Like I've included all patches. Is it different from patches or wot?

**Comment by Francesco146** [comment]
> How and from where🤔? Like I've included all patches. Is it different from patches or wot?

![Screenshot_20240614_181600_RVX Manager](https://github.com/anddea/revanced-patches/assets/49027005/b131aa69-1e60-42d3-84d6-296a795fac7f)

patch option in the custom branding icon patch

**Comment by vippium** [comment]
> > How and from where🤔? Like I've included all patches. Is it different from patches or wot?
> 
> ![Screenshot_20240614_181600_RVX Manager](https://private-user-images.githubusercontent.com/49027005/339835400-b131aa69-1e60-42d3-84d6-296a795fac7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODIxNzgsIm5iZiI6MTcxODM4MTg3OCwicGF0aCI6Ii80OTAyNzAwNS8zMzk4MzU0MDAtYjEzMWFhNjktMWU2MC00MmQzLTg0ZDYtMjk2YTc5NWZhYzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE2MTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZTZlMWI3MjUxYWQxMzcwZGI4YWJhOTJhODU1MjFlNDY3ZWU5NGU2ZGFmMDFiYzU0YWUwNjRjN2JmNzgxYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hSM3FUhgbaqrJqBRgXQgvDxDvAHhd2szAePkE_x_Ik)
> 
> patch option in the custom branding icon patch

And how to do it in rvx-builder? As I don't use manager.

**Comment by Francesco146** [comment]
i don't use the builder. search "Patch options" when patching

**Comment by vippium** [comment]
> i don't use the builder. search "Patch options" when patching

Already included all the patches...I think there is something in option.json which can trigger this

**Comment by Francesco146** [comment]
it's not a patch, it's a patch option
