### ISSUE TITLE
feat(YouTube - Change Start Page): Add New Entry (Courses, Playables)

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#603]
### Application

YouTube

### Feature description

Add New Entry (Courses, Playables)

### Motivation

.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Can you share links for Courses and Playables?

**Comment by zerozero0022** [comment]
https://m.youtube.com/channel/UCtFRv9O2AHqOZjjynzrv-xg

https://m.youtube.com/playables

**Comment by anddea** [comment]
Thank you, I'll add them later.

**Comment by zerozero0022** [comment]
thanks
