### ISSUE TITLE
question: Why latest patches on GitHub are in disorder?

### ISSUE THREAD

**Issue by joelmzj** [anddea/revanced-patches#604]
### Application

Other

### Question description

https://github.com/anddea/revanced-patches/assets/79762041/ae5417d5-69a2-4da3-9e74-ee54374f841f

I mean, at top are patches v2.226.0-dev.9 but below are v2.226.0-dev.11and below v2.226.0-dev.10.

It's a little weird. I always check latest updates and don't even realise there were 2 new patches today. 😅

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Probably has to do something with semantic versinailning, but not sure about that. Probably this kind of a question was already asked on GitHub community.
