### ISSUE TITLE
bug: "Enable black player background" doesn't work properly

### ISSUE THREAD

**Issue by joelmzj** [anddea/revanced-patches#605]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube Music 7.05.53

### Bug description

https://github.com/anddea/revanced-patches/assets/79762041/a12c1974-eed9-4634-bef9-00a36abb90aa

With very specific tracks the black background disappears. In this case when playing ["Stay with me" by Sam Smith](https://music.youtube.com/watch?v=7hkL4zDCKhs), but it happens with other tracks too. For example:

•["Infinity" by Jaymes Young](https://music.youtube.com/watch?v=WMK3JXG3Fx0)
•["Life is good" by Future](https://music.youtube.com/watch?v=6f8gDL-wPN8)

This is obviously related to album art colours.

### Device Environment

Patches version v2.226.0-dev.9

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Reopen this in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues)

**Comment by Aryan-Chauhan** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2119
