### ISSUE TITLE
bug: Patched Youtube by anddea is crashing after reboot

### ISSUE THREAD

**Issue by PH03N1X1000** [anddea/revanced-patches#607]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Application: YouTube
Version: 19.21.40
Revanced Patches: v2.226.0-dev.11

### Bug description

I Patch the recommended version of YouTube from RVX manager and then mount it as it is unable to install it over the existing YouTube installed on the device of the same version which i also cannot somehow fully uninstall regardless of what method i use (It has some error with signatures of revanced YouTube and existing installed YouTube), i have a rooted device so i uncheck the GMScore support and then patch the apk which now after reboot says YouTube is not responding and is not opening it happens after every reboot and i have to repatch and mount again.

### Device Environment

Android 11 OneUi 3.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This is most likely your patching tool problem, because when you use mount the patching tool has to create auto mount on reboot as well, otherwise on each reboot it will use original YouTube. Because this method just mounts RVX to original YouTube, it does not replace it like other root methods: system patching or module.

**Comment by PH03N1X1000** [comment]
So any way u could suggest to fix this issue ? 
Should i use another Patching tool ?
And how can i try other root methods which you mentioned above ?

**Comment by anddea** [comment]
You need to ask community on Reddit or Telegram who encountered this.
