### ISSUE TITLE
Swipe to expand miniplayer not working 

### ISSUE THREAD

**Issue by NichirinSword** [anddea/revanced-patches#609]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.21.40

### Bug description

After selecting modern miniplayer 1 and hide expand & close button, it supposed to expand using swipe up gesture but not working. Swipe down to close miniplayer working. 

### Device Environment

Android 14, RealmeUI 5.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by akir45** [comment]
this is not a bug

Google has changed Miniplayer behavior in YouTube 19.20.35+ so that videos can only be expanded using the expand button
(also reproduced on unpatched YouTube)

If you want the old behavior, roll back to YouTube 19.16.39
