### ISSUE TITLE
suggestion: update korean translation

### ISSUE THREAD

**Issue by ZeroZero0011** [anddea/revanced-patches#61]
### Application

YouTube

### Suggestion description

I'm not a developer, and I've never used GitHub properly, so... I don't know if my request was sent correctly.

The Korean translation file is this link.

https://mega.nz/file/wD9CFSKb#HPU5oywQW8tUvqljlO0eaQpKcpoGo3IJKoSM-IYFBok

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Kuddus73** [comment]
It's also happening for the Italian language.
For some reason after applying v2.221.0.3 patches, the missing strings are still in English (not translated).

Italian translations file:
[strings.xml](https://mega.nz/file/4WJDlZqQ#EAWuLSzdcNeOLhC-_krYhH1gGvqMfSjvHDm9Gavtq-Q)

**Comment by anddea** [comment]
Updated, will be in the next release.

@Kuddus73, which preference(s) was not applied? I checked a few new strings, they have been updated. Git doesn't see any difference, so your last `strings.xml` is already applied.

**Comment by Kuddus73** [comment]
@anddea as you can see none of the missing strings are translated.

https://github.com/anddea/revanced-patches/assets/127908708/ac67d26b-2b09-493c-8b4b-8bdc26d15aa0

Also, the version of Patches is shown wrong in Info, even though Integrations version is correct.

**Comment by anddea** [comment]
> Also, the version of Patches is shown wrong in Info, even though Integrations version is correct.

Probably that's the reason. For me, it updated all the strings and patches version is v2.221.0.3, as shown in the Misc > Patches info. Maybe it didn't update patches for you?

**Comment by Kuddus73** [comment]
> Maybe it (Manager, Revancify) didn't update patches for you?

Thought the same at first but it did update as it was showing v2.221.0.3 in the top right corner of the Manager.
I just uninstalled/reinstalled the Manager and repatched and now it's fine.
Cheers.
