### ISSUE TITLE
MMT Blue, MMT Green, MMT Yellow Icons

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#612]
### Application

YouTube

### Question description

In changelong of Revanced Patches 2.26.0-dev.12 mentioned that you add MMT Blue, MMT Green and MMT Yellow Icons
![IMG_20240617_141856](https://github.com/anddea/revanced-patches/assets/61022739/b7876a98-4a21-40fb-af00-c22b60a8fefd)
But i don't see these types of icons
 in Revanced Manager
![Screenshot_2024-06-17-14-14-13-908_app rvx manager flutter-edit](https://github.com/anddea/revanced-patches/assets/61022739/2b0f87b0-7ddb-45b9-88af-aea239db58ca)
I use Revanced Patches 2.26.0-dev.12
![Screenshot_2024-06-17-14-13-40-378_app rvx manager flutter-edit](https://github.com/anddea/revanced-patches/assets/61022739/6adf4d4f-921a-45ad-b6c1-3f485c936229)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Clear cache or data of the Manager
