### ISSUE TITLE
bug: Custom icon doesn't work in splash animation

### ISSUE THREAD

**Issue by Alxon4789** [anddea/revanced-patches#613]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube: v19.16.39
CLI: inotia00-cli-v4.6.1.jar
Patches: anddea-patches-v2.226.0-dev.12.jar

### Bug description

Despite the explicit use (and enabling) of a custom icon (as can see in the screenshots and video) all the time when launching the application shows the standard icon. I attach the patchlog and settings from Revancify
[patch_log.txt](https://github.com/user-attachments/files/15873585/patch_log.txt)

https://github.com/anddea/revanced-patches/assets/143010511/f9f1726c-925c-4e54-b4f8-2e9d7b2779c2

<img src="https://github.com/anddea/revanced-patches/assets/143010511/1654a518-77c0-456e-ac4a-3d0468acc49e" width=40% height=40%>

### Device Environment

Poco F4
Android 14
Paranoid Android Uvite Beta 4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Vanced Light doesn't have animated splash. You can disable RestoreOldSpalshAnimation and it will show static splash icon. Only MMT and AFN have splash animations for now.
