### ISSUE TITLE
bug: Unable to delete some setting in YouTube menu

### ISSUE THREAD

**Issue by Alxon4789** [anddea/revanced-patches#614]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube: v19.16.39
CLI: inotia00-cli-v4.6.1.jar
Patches: anddea-patches-v2.226.0-dev.12.jar

### Bug description

Using the filter for deleting YouTube settings, it is not possible to delete "Your data in Youtube" (in Polish is "Twoje dane w Youtube"), even though I clearly typed it next to the others. I tried different combinations of words (in my language, of course). I encountered that this error occurs only in the Polish language version. As evidence, I send screenshots and patchlog.
[patch_log.txt](https://github.com/user-attachments/files/15873816/patch_log.txt)
<img src="https://github.com/anddea/revanced-patches/assets/143010511/4b7dd474-d337-43b5-8fc8-8990df77caa7" width=50% height=50%><img src="https://github.com/anddea/revanced-patches/assets/143010511/b635a86c-7779-4305-b202-983f851db77b" width=50% height=50%>

### Device Environment

Poco F4
Android 14
Paranoid Android Uvite Beta 4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Report this in [intoia's repo](https://github.com/inotia00/ReVanced_Extended/issues) if you can reproduce it there, I think it's the same
