### ISSUE TITLE
suggestion: mmt blue at yt music

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#616]
### Application

YouTube Music

### Suggestion description

Can you add mmt blue to youtube music

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Will be added later if I have time.
