### ISSUE TITLE
suggestion: revancify splash animation

### ISSUE THREAD

**Issue by MondayNitro** [anddea/revanced-patches#617]
### Application

YouTube

### Suggestion description

here is the splash animation for revancify red, can you check if the frame is displayed properly or its too thick. if its displayed correctly ill edit it for blue & yellow icons too
since im in a11 rom, i cant check for myself

edit- these should display properly since they display correctly in svg
[blue.zip](https://github.com/user-attachments/files/15881628/blue.zip)
[red.zip](https://github.com/user-attachments/files/15881629/red.zip)
[yellow.zip](https://github.com/user-attachments/files/15881631/yellow.zip)
check once nonetheless

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Looks fine. Xisr will make animation for Revancify Yellow as he created it and already started playing with multiple animations, so I'll use your Blue and Red, and will wait for his Yellow.

**Comment by MondayNitro** [comment]
> Looks fine. Xisr will make animation for Revancify Yellow as he created it and already started playing with multiple animations, so I'll use your Blue and Red, and will wait for his Yellow.

i think it will be better to use their animation then, since its a better animation and also for the sake of consistency. they should just change color codes for red and blue

**Comment by anddea** [comment]
I think Xisr will create only for Yellow, but we'll see

**Comment by Xisrr1** [comment]
I am not sure yet, you put effort into this
