### ISSUE TITLE
feat: Timestamp Enhacements

### ISSUE THREAD

**Issue by nochlab1** [anddea/revanced-patches#618]
### Application

YouTube

### Feature description

Hi thanks so much for doing this its really helpful
1. i like your option of pressing timestamp to change video quality
was wondering if can have a option that holding down changes the timestamp to time left like in original and in order to change what pressing down does it has to be changed in settings
 2. the devices i use have big screens so was wondering if can add to see video speed and video quality at same time as i have enough space and only need pressing to change video quality as there is already a button to change video speed
 3. this is really a longshot but maybe a option to see video time left based on current speed so i don't have to do math:)
 Thanks!

### Motivation

adds functionally that i use and will be helpful on day to day

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
1. Holding down the timestamp changes the type of information: speed or quality. To revert to the original behavior, you need to turn off this timestamp info.

For 2 and 3, I really doubt if they're that important; they add more drawing on the screen and can impact performance. I've never known anyone who cares about the time left, especially when people can visually see the seekbar and remaining time. I saved it to my notes, but for now I'll close it.

**Comment by nochlab1** [comment]
Ok thanks
