### ISSUE TITLE
feat: mmt splash animation slower for phone

### ISSUE THREAD

**Issue by andylee516** [anddea/revanced-patches#619]
### Application

YouTube

### Feature description

for phone, mmt splash animation moves so quick that it doesn't show the outline color. Besides, tablet works fine. Can you fix this?

https://github.com/anddea/revanced-patches/assets/113352087/a03c8967-3e60-467d-bdfc-2ba1bace5d13

https://github.com/anddea/revanced-patches/assets/113352087/be82441d-da6e-4cbd-8f91-ad0edbba368e

### Motivation

it will be more nicer

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Probably you sped up animations in your system. It's not an animation problem.
