### ISSUE TITLE
bug: Chapter names missing from video player

### ISSUE THREAD

**Issue by darkvpier** [anddea/revanced-patches#62]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube: 19.09.37
revanced-patches: V2.221.0.3
revanced-integrations: V0.147.2

### Bug description

I'm experiencing an issue where the chapter names are not displaying within the video player on the YouTube app. This is happening on version 19.09.37 of the app.

Steps to Reproduce:

- Open the YouTube app and ensure you're on version 19.09.37 (check the app settings for version information).
- Play a video that has chapters.
- Observe that the chapter names are not visible within the video player interface.

### Device Environment

Android 14
Google pixel 6a

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
exclude the hide chapters patch

**Comment by darkvpier** [comment]
> exclude the hide chapters patch

It's excluded but still not showing the names.

**Comment by anddea** [comment]
I can't reproduce it. I did everything as you said. Check if you saved your patch selection, then check if the patch doesn't show up during patching process as succeeded. Make sure to clear old files left by Revancify.

**Comment by darkvpier** [comment]
Did that too..
This is patches I included:
includedPatches": [
      "Add splash animation",
      "Alternative thumbnails",
      "Ambient mode switch",
      "Append time stamps information",
      "Change start page",
      "Custom branding heading",
      "Custom branding icon YouTube",
      "Custom double tap length",
      "Custom playback speed",
      "Custom player overlay opacity",
      "Custom seekbar color",
      "Default playback speed",
      "Default video quality",
      "Disable HDR video",
      "Disable QUIC protocol",
      "Disable auto captions",
      "Disable haptic feedback",
      "Disable landscape mode",
      "Disable pip notification",
      "Disable rolling number animations",
      "Disable shorts on startup",
      "Disable speed overlay",
      "Enable bottom player gestures",
      "Enable compact controls overlay",
      "Enable debug logging",
      "Enable external browser",
      "Enable gradient loading screen",
      "Enable language switch",
      "Enable minimized playback",
      "Enable new splash animation",
      "Enable new thumbnail preview",
      "Enable open links directly",
      "Enable seekbar tapping",
      "Enable song search",
      "Enable tablet mini player",
      "Enable tablet navigation bar",
      "Enable wide search bar",
      "Force fullscreen",
      "Force opus codec",
      "Force video codec",
      "Hide auto player popup panels",
      "Hide autoplay button",
      "Hide autoplay preview",
      "Hide button container",
      "Hide captions button",
      "Hide cast button",
      "Hide category bar",
      "Hide channel avatar section",
      "Hide channel profile components",
      "Hide channel watermark",
      "Hide collapse button",
      "Hide comment component",
      "Hide crowdfunding box",
      "Hide description components",
      "Hide double tap overlay filter",
      "Hide end screen cards",
      "Hide end screen overlay",
      "Hide feed flyout panel",
      "Hide filmstrip overlay",
      "Hide floating microphone",
      "Hide fullscreen panels",
      "Hide general ads",
      "Hide handle",
      "Hide info cards",
      "Hide latest videos button",
      "Hide layout components",
      "Hide load more button",
      "Hide mix playlists",
      "Hide music button",
      "Hide navigation buttons",
      "Hide navigation label",
      "Hide seek message",
      "Hide shorts components",
      "Hide snack bar",
      "Hide suggested actions",
      "Hide suggested video overlay",
      "Hide suggestions shelf",
      "Hide time stamp",
      "Hide toolbar button",
      "Hide tooltip content",
      "Hide trending searches",
      "Hide video ads",
      "Keep landscape mode",
      "Layout switch",
      "MaterialYou",
      "MicroG support",
      "Overlay buttons",
      "Quick actions components",
      "Remove viewer discretion dialog",
      "Return YouTube Dislike",
      "Sanitize sharing links",
      "Settings",
      "Settings icons",
      "Shorts overlay buttons",
      "SponsorBlock",
      "Spoof app version",
      "Spoof device dimensions",
      "Spoof player parameters",
      "Swipe controls",
      "Theme",
      "Translations"
    ]
  }

And this is my settings:
"custom_playback_speeds": "0.25\n0.5\n0.75\n1.0\n1.25\n1.5\n1.75\n2.0\n2.25\n2.5\n3.0\n4.0\n5.0",
"disable_auto_captions": false,
"disable_haptic_feedback_chapters": false,
"disable_haptic_feedback_scrubbing": false,
"disable_haptic_feedback_seek": false,
"disable_haptic_feedback_seek_undo": false,
"disable_haptic_feedback_zoom": false,
"disable_hdr_video": false,
"disable_speed_overlay": false,
"disable_update_screen": false,
"enable_custom_seekbar_color": false,
"enable_new_thumbnail_preview": true,
"enable_opus_codec": false,
"enable_save_playback_speed": false,
"enable_save_video_quality": false,
"enable_swipe_brightness": false,
"enable_video_codec": false,
"hide_audio_track_button": false,
"hide_auto_player_popup_panels": false,
"hide_autoplay_button": false,
"hide_browse_store_button": false,
"hide_button_download": false,
"hide_button_share": false,
"hide_captions_button": false,
"hide_cast_button": false,
"hide_channel_profile_links": false,
"hide_channel_watermark": false,
"hide_chips_shelf": false,
"hide_community_posts_home": false,
"hide_community_posts_related_video": false,
"hide_community_posts_subscriptions": false,
"hide_end_screen_cards": false,
"hide_end_screen_overlay": false,
"hide_feed_flyout_panel": false,
"hide_feed_survey": false,
"hide_floating_microphone": false,
"hide_for_you_shelf": false,
"hide_gray_separator": false,
"hide_handle": false,
"hide_image_shelf": false,
"hide_info_cards": false,
"hide_info_panel": false,
"hide_latest_posts": false,
"hide_latest_videos_button": false,
"hide_mix_playlists": false,
"hide_movie_shelf": false,
"hide_navigation_label": false,
"hide_previous_next_button": false,
"hide_quick_actions": false,
"hide_shopping_links": false,
"hide_shorts_button": false,
"hide_shorts_player_info_panel": false,
"hide_store_tab": false,
"hide_suggested_video_overlay": false,
"hide_suggestions_shelf": false,
"hide_ticket_shelf": false,
"hide_trending_searches": false,
"keep_landscape_mode": false,
"overlay_button_copy_video_url": false,
"overlay_button_copy_video_url_timestamp": true,
"spoof_device_dimensions": true,
"spoof_player_parameter_in_feed": true,
"swipe_brightness_value": -1,
"switching_create_notification": false

**Comment by anddea** [comment]
Are you sure there are chapters in that specific video? Verify in other YouTube client or check if there are chapters under video description (if you didn't hide it in the settings).

**Comment by ArcherLegend** [comment]
I can confirm this bug too, the only difference is that I patched using RVX Manager from Inotia00.

The chapters do not show like the original reported said, I have double checked every setting to be the same of my ReX based installation on version 19.06.36 and chapters do not show.

Another thing that is missing is the fullscreen button.

**Comment by anddea** [comment]
Some patches are better without toggles as they have some performance issues like [this one](https://github.com/anddea/revanced-patches/issues/63) for example. It'll be as is, unless I or someone else can find a better way to capture needed fingerprint for hiding.

> Are you thinking of opening a new subreddit for your RevancedExtended patches or we can use the https://www.reddit.com/r/revancedextended/ made by Inotia00 to discuss your patches?

You're free to discuss there. I don't think it's necessary to create other subreddits.

**Comment by anddea** [comment]
Btw, it shouldn't make any difference what you use to patch, you just need to clear the storage and cache of these apps from time to time when you notice any problems. Because they cache old artifacts.
