### ISSUE TITLE
feat(YouTube - Shorts Components): change more button to playback speed button on shorts player toolbar

### ISSUE THREAD

**Issue by zerozero0022** [anddea/revanced-patches#620]
### Application

YouTube

### Feature description

change more (3dot) button to playback speed button on shorts player toolbar

Is this possible?

ex) change search and more buttons to forward and back buttons on shorts player toolbar in rvx for android 6-7
![Screenshot_20240618-160617_ReVanced Extended~01](https://github.com/anddea/revanced-patches/assets/163995091/4a04ec7d-1759-4888-afdc-2c1a0f8d433a)
i don't know the source for this.

### Motivation

.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Adding buttons for Shorts is problematic, but I have plans to look into possible ways
