### ISSUE TITLE
bug: custom made icon doesnt apply to header

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#622]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Yt music supported version

### Bug description

When i try to use my custom icon and turn on apply to header, it doesnt apply to header
![Screenshot_20240618_163702_RVX Music](https://github.com/anddea/revanced-patches/assets/143447608/cef47fd1-e2d9-4858-857a-628c2c35df86)

### Device Environment

Android 14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Custom icon cannot change header

**Comment by Ahmey1400** [comment]
What is this option stands for ?

![Screenshot_20240618_174853_RVX Manager](https://github.com/anddea/revanced-patches/assets/143447608/a7396f6c-0482-409d-862f-d3a0e03bc9d8)

**Comment by anddea** [comment]
It's only for applying internal icons. The path you provide only includes what is written in the description of that option. Only mipmap folders as you can see.

**Comment by Ahmey1400** [comment]
I understand it now thanks, btw please add mmt blue to yt music
