### ISSUE TITLE
bug: Youtube ambient mode isn't work perfectly.

### ISSUE THREAD

**Issue by laxmanroy52** [anddea/revanced-patches#626]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Youtube 19.21.40

### Bug description

When I try to enabling ambient mode in youtube revanced by anddea, it's not working perfectly. Please solve this issue?

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Not enough details to understand the issue. Ambient mode is a YouTube feature, if you don't have issues with disabling ambient mode, then it's not ReVanced issue. If you face the same issue with inotia patches, you have to open bug reports there.
