### ISSUE TITLE
bug: Custom Splash Animation Doesn't Work

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#627]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube v19.20.41
YouTube Music v7.05.53

### Bug description

I don't know what's wrong, but I do set custom splash animation to `mmt` and `mmt_blue` and there were some warning messages.

### Error logs

```shell
WARNING: Could not set option value for the Custom branding icon YouTube Music patch: Type java.lang.Boolean was expected but received type java.lang.String

WARNING: Could not set option value for the Custom branding icon YouTube patch: Type java.lang.Boolean was expected but received type java.lang.String
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Probably something's wrong with your options.json. Share your options.json.

**Comment by AbakNacchan** [comment]
> Probably something's wrong with your options.json. Share your options.json.

[options.json](https://github.com/user-attachments/files/15910277/options.json)

**Comment by anddea** [comment]
`ChangeSplashIcon` is a boolean option, use `true` or `false`.

**Comment by AbakNacchan** [comment]
> `ChangeSplashIcon` is a boolean option, use `true` or `false`.

Ah, I see. Thanks.
