### ISSUE TITLE
feat: (yt) bring back "FORCE HIDE PLAYER BUTTON BACKGROUND" patch

### ISSUE THREAD

**Issue by MondayNitro** [anddea/revanced-patches#63]
### Application

YouTube

### Feature description

the new implementation for hiding player button background, which has an on-off switch, makes the player overlay lag/glitch (which is the reason inotia removed it) read [here](https://github.com/inotia00/ReVanced_Extended/issues/1679)

https://github.com/anddea/revanced-patches/assets/87489540/2dbf3ef9-97c1-40c6-b7fd-50dec99bdb25

i understand that it lags for some users and doesnt for others, so the best way is to keep this patch and reintroduce **"force hide player button bacground"** patch as was the case with inotias patches earlier.

### Motivation

this will allow users for whom current implementation is bugged to be able to hide player button background.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Reverted back in the latest release.
