### ISSUE TITLE
Add an option to hide Live button on shorts player

### ISSUE THREAD

**Issue by NichirinSword** [anddea/revanced-patches#630]
### Application

YouTube

### Feature description

Option to hide Live button on shorts player

### Motivation

Most of the live videos in shorts sections are some prostitutes doing their videos which is disturbing. I think many people don't wanna see this kinds of videos even by mistakenly. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by zerozero0022** [comment]
Is that the upper left opaque button (subscribe, live, shopping)?

If that's right,, enable 'Hide Paused overlay button'.

(ReVanced Extended Setting - Shorts - Shorts Player)

**Comment by NichirinSword** [comment]
> Is that the upper left opaque button (subscribe, live, shopping)?
> 
> If that's right,, enable 'Hide Paused overlay button'.
> 
> (ReVanced Extended Setting - Shorts - Shorts Player)
> 
> ++ It doesn't seem to be possible to hide the Shorts Live Stream that appears when you swipe through the Shorts player.

Yes. That's the button. Hide Paused overlay button option works but it also hides subscription, shopping option. Isn’t it possible to hide only live button?

**Comment by anddea** [comment]
This is not possible at the moment, as filtering can change every day and thus cannot be maintained properly.
