### ISSUE TITLE
bug: `Change package name` doesn't work fine with your patches

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#631]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YT & YTM

### Bug description

`Custom Package Name` not work as indented. As you also know that your default and custom package name are same, so even renaming the package name in options.json doesn't change it. Builder doesn't distinguish b/w them and uses the default one even after changing. RVX (inotia's) does work well. 
Can you check at your side with builder. I know that builder is outdated and you don't even recommend it. But then also, check it. 
I won't switch to manager till it gets the apk downloading ability by itself and need not to download it manually. 

### Device Environment

A14 Funtouch OS 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Unfortunately, I cannot reproduce this issue. Can you record the whole process? Share what builder version exactly you used, send the link. I'm giving this issue one month to be open, if no one else agrees that this issue is present, I'm going to close it permanently.

**Comment by vippium** [comment]
> Unfortunately, I cannot reproduce this issue. Can you record the whole process? Share what builder version exactly you used, send the link. I'm giving this issue one month to be open, if no one else agrees that this issue is present, I'm going to close it permanently.

I'll share the full video of that...of around 10-15min. Or try to shorten the video

**Comment by anddea** [comment]
I don't understand, what's this default and custom? Send your `options.json`.

**Comment by vippium** [comment]
> I don't understand, what's this default and custom? Send your `options.json`.

I mean without including Custom Package Name (Default) and Including Custom Package Name (Custom).

**Comment by vippium** [comment]
Ohh...Now I can confirm that `Custom Package Name` is working fine till you use the default google's package name.
Like if I want to change the package name to my name, it will work. But if I want to replace the Playstore YTM using `Custom Package Name`, it won't.

**Comment by anddea** [comment]
You cannot use default package name if you don't use root method.

**Comment by vippium** [comment]
> You cannot use default package name if you don't use root method.

And what's your thought on my suggestion
> And one last suggestion is that try to change the default package name to (rvx.xyz or comment.rvx.xyz) instead of using (anddea.xyz) for both Default and Custom Package Name for removing any confusion like I got.

**Comment by anddea** [comment]
This will branch out further from inotia's repo and it will be harder to merge his changes.
