### ISSUE TITLE
bug: Background playback not working for vertical livestreams

### ISSUE THREAD

**Issue by u2716** [anddea/revanced-patches#633]
### Type

Other

### Tools used

CLI

### Application

all

### Bug description

Vertical streams are opened with the shorts player and that prevents background playback to work. Forcing them to open with the default player would solve the issue and would also make possible to change resolution. 

### Solution

Making the app open the stream with the link in this format `youtube.com/watch?v=videoid` or `youtu.be/videoid` , and not `youtube.com/live/videoid` like it normally does, should force the default player and make background playback/PiP work. Is it possible to make a patch to automate this?

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not an issue with anddea's patches

**Comment by anddea** [comment]
Reopen this issue in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues)
