### ISSUE TITLE
Unable to turn off "get youtube premium" Whith russian language

### ISSUE THREAD

**Issue by Gubbbka** [anddea/revanced-patches#634]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

19.21.40

### Bug description

Unable to turn off "get youtube premium" via filters whith russian language. Other buttons i can disable I think it caze YT prem wrote on english 
P.S: how put away that 3 lines which placed after every 2 buttons

![Screenshot_20240621_212921_YouTube](https://github.com/anddea/revanced-patches/assets/169579036/ddf9ab3c-13d6-4d36-923f-f8373dfcc2ab)
.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not an issue with anddea's patches as it occurs in RVX too

**Comment by anddea** [comment]
Report bug reports in [inotia's repo](https://github.com/inotia00/ReVanced_Extended/issues), if you can reproduce there
