### ISSUE TITLE
feat(YouTube - Description): Hide Shorts in Video Description

### ISSUE THREAD

**Issue by Francesco146** [anddea/revanced-patches#636]
### Application

YouTube

### Feature description

Restore the old patch that hides the Shorts section in video description.

### Motivation

cool.

I'll work on this in july, not sure if it's a/b testing, but here's a video that has Shorts in the description on my device:

https://youtu.be/v3JULO-C70U

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by zerozero0022** [comment]
Wasn't Shorts shelf in the video description automatically hidden when "hide Shorts shelf in home feed" is enabled?

**Comment by zerozero0022** [comment]
Shorts shelf in the video description automatically hidden when "hide Shorts shelf in home feed" is enabled?

I remember it working like that before and now.

**Comment by Francesco146** [comment]
at first yes, then it broke. anddea made a separate patch but when it merged all RVX's work it was deleted
