### ISSUE TITLE
feat(YouTube - Layout): Hide Premium Badge in Playlists

### ISSUE THREAD

**Issue by Francesco146** [anddea/revanced-patches#637]
### Application

YouTube

### Feature description

Add an option to hide the YouTube Premium tags/badge on playlists. Afaik these playlists works good even on free users, so it's like some advertisment.
<details>
 <summary>here's the screenshot</summary>

![Screenshot_20240621_221054_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/49027005/382bbc4e-494f-4351-a048-e087c2f21792)

</details>

### Motivation

will work on this in july 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
a better patch would be to hide playlists marked with premium, since these should only be playable after buying premium

**Comment by Francesco146** [comment]
However, I can see the videos in these playlists, is this something in A/B testing?
