### ISSUE TITLE
bug: Is this Shorts comment setting supposed to be like this?

### ISSUE THREAD

**Issue by BAXSD** [anddea/revanced-patches#638]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.21.40
Patch: 2.226.0-dev.11

### Bug description

Im not sure if this Shorts comments setting is working properly or if its a bug?

I have enabled Shorts comments button but when I turn on in Shorts settings **Hide disabled comments button** it stops showing Shorts comments button too even when Shorts comments button settings is turned on when playing Shorts. Should it not stop showing comments button in Shorts when the Shorts video has disabled the comment section and only show Shorts comments button when the comments section is available to comment?

### Device Environment

Android 14 OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Seems like it's A/B testing that I cannot reproduce on my side yet.

**Comment by Francesco146** [comment]
try repatching, anddea made some changes in the integrations that didn't trigger any dev releases here (which is correct)

**Comment by Francesco146** [comment]
great, this issue can be closed
