### ISSUE TITLE
feat(YouTube - Playlists) : Hide Recommended Playlists from Playlist

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#639]
### Application

YouTube

### Feature description

When you open a playlist from search results, then scroll all the way down, there is a `Recommended Playlists` section.

This feature request is to add the ability to hide it.

Playlist link: https://youtube.com/playlist?list=PLRv_c3P0AbXn22Mv7hEBfghkCH91sJhKt

![Screenshot_2024-06-18-09-15-37-51_a9acfd2263b6b7a65bf2540b0d9449ca](https://github.com/anddea/revanced-patches/assets/91815107/b058e863-60e6-43d5-89af-4cee8fa78c68)

### Motivation

They are just some random playlists recommended by YouTube. I'm seeing them very often & realized they are of no use to me.

So, ability to hide them would be appreciated.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
do you mind share the buffer logs?

**Comment by Aryan-Chauhan** [comment]
Sorry for late reply. 

I would've shared the buffer logs on the same day but my laptop was having hardware issues. It's getting new parts now.

Can someone else do it from the playlist link given above?

**Comment by RoonMoonlight** [comment]
@Aryan-Chauhan, this is not the logcat one but I have found the temporary workaround for this issue, tho this does not fix the issue entirely.

1. Open the RVX settings -> General category -> Custom filter
2. Enable the setting 'Enable custom filter'
3. Click on custom filter, type `compact_video`
4. Done.

**Be aware that this one has not been tested properly if this works well. Expect some breakage.**
