### ISSUE TITLE
question: How to update a string file

### ISSUE THREAD

**Issue by EnzoDpch33** [anddea/revanced-patches#64]
### Application

Other

### Question description

`Hello, I'd like to translate the application into French, but I don't know how to go about it. Should I contact you? 
`

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Go to your [language folder](https://github.com/anddea/revanced-patches/tree/main/src/main/resources/youtube/translations/fr-rFR) and send me translated missing and updated strings as text here.

**Comment by EnzoDpch33** [comment]
French translation : Missing strings

<string name="revanced_change_start_page_entry_browse">Chaînes</string>
<string name="revanced_change_start_page_entry_gaming">Jeux vidéo</string>
<string name="revanced_change_start_page_entry_live">Direct</string>
<string name="revanced_change_start_page_entry_movies">Films et séries TV</string>
<string name="revanced_change_start_page_entry_music">Musique</string>
<string name="revanced_change_start_page_entry_sports">Sport</string>
<string name="revanced_change_start_page_entry_watch_later">À regarderplustard</string>
<string name="revanced_keyword_invalid_length" formatted="false">Longueur du mot-clé invalide (doit comporter au moins %s caractères) : %s.</string>
<string name="revanced_keyword_filter_strings_summary">Configurez les mots-clés et les phrases à masquer, séparés par une nouvelle ligne.

Les mots avec des majuscules au milieu doivent être écrits avec des majuscules (par exemple, iPhone, TikTok, LeBlanc).</string>
<string name="revanced_keyword_filter_strings_title">Modifier le filtre à mot-clé</string>
<string name="revanced_keyword_filter_summary_off">Le filtre à mot-clé est désactivé. </string>
<string name="revanced_keyword_filter_summary_on">Le filtre àmot-clé est activé</string>
<string name="revanced_keyword_filter_summary">Masque les vidéos du flux et des résultats de recherche à l'aide du filtre à mot-clé.</string>
<string name="revanced_keyword_filter_title">Filtre à mot-clé</string>
<string name="revanced_hide_player_button_background_summary_off">L'arrière-plan des boutons du lecteur est affiché.</string>
<string name="revanced_hide_player_button_background_summary_on">L'arrière-plan des boutons du lecteur est affiché.</string>
<string name="revanced_hide_player_button_background_title">Arrière plan des boutons du lecteur</string>
<string name="revanced_override_premium_header_summary_off">En-tête : Par défaut</string>
<string name="revanced_override_premium_header_summary_on">En-tête : YouTube Premium</string>
<string name="revanced_override_premium_header_title">En-tête YouTube Premium</string>
<string name="revanced_spoof_failure_connection_status_code" formatted="false">"Falsification du storyboard indisponible :"</string>
<string name="revanced_spoof_failure_connection_timeout">Falsificationdu storyboard temporairement indisponible (API obsolète)</string>
<string name="revanced_spoof_failure_generic">"Falsificationdu storyboard temporairement indisponible : "</string>

Strings update  : 

  <string name="revanced_enable_bottom_player_gestures_summary_off">Le passage en plein écran en faisant glisser la zone inférieure du lecteur est désactivé.</string>
<string name="revanced_enable_bottom_player_gestures_summary_on">Le passage en plein écran en faisant glisser la zone inférieure du lecteur est activé.</string>
<string name="revanced_hide_button_live_chat_summary_off">Le bouton "Chat en direct" est affiché</string>
<string name="revanced_hide_button_live_chat_summary_on">Le bouton "Chat en direct" est masqué</string>
<string name="revanced_hide_button_live_chat_title">Bouton "Chat en direct"</string>
<string name="revanced_hide_floating_microphone_summary_off">Le bouton "Microphone flottant" est affiché</string>
<string name="revanced_hide_floating_microphone_summary_on">Le bouton "Microphone flottant" est masqué</string>
<string name="revanced_hide_floating_microphone_title">Bouton "Microphone flottant"</string>
<string name="revanced_hide_store_tab_title">Onglet "Parcourir"</string>
