### ISSUE TITLE
bug(YouTube Music - Visual preferences icons): v2.224.0-dev.7 error recurrence 

### ISSUE THREAD

**Issue by stainlf** [anddea/revanced-patches#640]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube Music v7.06.53-

### Bug description

Visual preferences icons were finally added to YouTube Music in v2.226.0-dev.3, but A patch error that occurred on YouTube in v2.224.0-dev.7 has recurred so far.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.4
Model: SM-S928N
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v7.06.53 (Suggested: 7.06.53)
Patches version: v2.226.0-dev.17
Patches added: Default
Patches removed: Custom package name, Amoled, Restore old style library shelf, Enable debug logging, Translations
Default patch options changed: Settings for YouTube Music [RVX settings menu name: RVX Settings], Visual preferences icons [Extended icon: custom_branding_icon]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: true
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 26 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~DOZGIsa51AWV9PqxZi7ghA==/app.rvx.manager.flutter-xmDoTpBEpyoRNeeouqhQzw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YULZCQ/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YULZCQ/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:484)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~DOZGIsa51AWV9PqxZi7ghA==/app.rvx.manager.flutter-xmDoTpBEpyoRNeeouqhQzw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YULZCQ/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YULZCQ/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
```

### Solution

It seems that the bug fix patch of v2.224.0-dev.8 should also be applied to YouTube Music. Thank you.

### Device Environment

Android 14

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
have you tried with other patching tools?

**Comment by AbakNacchan** [comment]
> have you tried with other patching tools?



> have you tried with other patching tools?

Got similar error on CLI too.

**Comment by stainlf** [comment]
Visual preferences icons patch have not yet been merged into YouTube Music in Inotia00 patch.

**Comment by Francesco146** [comment]
i see, some cherry picking went wrong

**Comment by AbakNacchan** [comment]
> i see, some cherry picking went wrong

I guess it's a `RVXSettingsMenuName` problem.

**Comment by AbakNacchan** [comment]
> nooo maybe this
> 
> ▶ Currently applied (v2.224.0-dev.7) [c47dc23](https://github.com/anddea/revanced-patches/commit/c47dc23e5dbc06534cfdc568d2edd23b62d3f7a6) At this patch there was the same error on YouTube.
> 
> ▶ Not yet applied (v2.224.0-dev.8) [a4b8466](https://github.com/anddea/revanced-patches/commit/a4b846684bc8b0c1f3746f8cf34e7112a3c4e212) This patch doesn't seem to have been applied to YouTube Music yet.

Visual Preferences Icon has no problem with that, but if you try to change RVX Settings name, the problem will occurs. It can be solved without adding custom settings name for a while - until there's a fix - both in YouTube and YouTube Music.
