### ISSUE TITLE
bug: ReVanced Settings Missing

### ISSUE THREAD

**Issue by MegaBigBossMan** [anddea/revanced-patches#641]
### Type

Other

### Tools used

Revancify

### Application

YouTube 19.23.40
v2.226.0-dev.16 patches

### Bug description

The Revanced Settings no longer appear in the app please see the attached screenshot. The patch for settings is enabled. I think it is just a bug with the newest dev patch.

![Screenshot_20240623_110221_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/97305321/5772c2a0-8ad1-4217-9ce4-7111c6900273)

### Error logs

```shell
No error log. Termux patched the application fine. It is an issue upon using the app.
```

### Solution

Hotfix to re-enable the settings. It probably is just a small oversight that can be fixed quickly. I just wanted to share.

### Additional context

Thank you for reading this report.

### Device Environment

Android 14, Samsung (US Variant) Note 20 Ultra

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Clear your `options.json` file. One option is changed now and some tools cannot update it automatically.

**Comment by MegaBigBossMan** [comment]
Hello, thank you for getting back to me so quickly.

Would you be able to briefly walk me through how to clear the options.json
file?

I utilize Revancify through Termux.

Thank you!

**Comment by MegaBigBossMan** [comment]
I believe it is this?

**Comment by MegaBigBossMan** [comment]
Issue resolved

Solution for Revancify (Termux)

#7 Delete Components
Then Select #3 Patch Options and confirm.
Then Repatching solves the issue.

Thank you.

**Comment by Dhyfer1** [comment]
> Issue resolved
> 
> Solution for Revancify (Termux)
> 
> #7 Delete Components
> Then Select #3 Patch Options and confirm.
> Then Repatching solves the issue.
> 
> Thank you.

![Screenshot_20240627-225045.jpg](https://github.com/anddea/revanced-patches/assets/50301201/f3cf09ca-a0f1-4b5a-9875-fd89ee83f201)

Option 7 is Delete Components, but you are wrong in option 3, it's not Patch Options as you said, it's Change source. I don't know where you got Patch Options from, I don't see it in any option.

**Comment by MegaBigBossMan** [comment]
You have to select number 7 and then once you do select number 3 to within
that menu.

Please see the attached 2 images to make it easier.

**Comment by MegaBigBossMan** [comment]
![Screenshot_20240628_000020_Termux](https://github.com/anddea/revanced-patches/assets/97305321/c7883603-710a-4ef5-98de-2fb177fa1f64)
![Screenshot_20240628_000030_Termux](https://github.com/anddea/revanced-patches/assets/97305321/7f8ff3ac-d42a-4cca-a1b0-ff7191657d2f)

**Comment by Dhyfer1** [comment]
Ah, now I understand you. You are right 👍

**Comment by MegaBigBossMan** [comment]
Happy to help!

**Comment by Dhyfer1** [comment]
Your comment is repeated 3 times xD Anyway, thanks for the clarification 👍
