### ISSUE TITLE
bug: (YT) - `Settings for YouTube` patch not working

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#644]
### Type

Error while patching

### Tools used

rvx-builder

### Application

Latest Recommended

### Bug description

Latest patch not able to apply `Settings for YouTube`  patch with latest Supported YT version.

![Screenshot_2024_0623_225933](https://github.com/anddea/revanced-patches/assets/93650504/681344a1-af8b-4ed4-a666-dbb2b92b2c7c)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by vippium** [comment]
Fixed or not?? 🤔 Can I patch it again

**Comment by anddea** [comment]
No, I closed it as a duplicate
