### ISSUE TITLE
feat(YouTube Music - Downloader): Hook Like Button for External Downloader

### ISSUE THREAD

**Issue by 93Pd9s8Jt** [anddea/revanced-patches#645]
### Application

YouTube Music

### Feature description

Essentially the title. This  would be almost identical to the current "hook download button" patch, except of course the like button will still need to actually like the song. The setting would probably be default-off, as I think the "hook download button" is.

As a bonus feature, this would support other sources of likes (the only one I can think of is the like button in the notification, but there may be others).

### Motivation

I assume its obvious why I'm suggesting this,  but: it's a pain to manually download each song you come across; it's probably a safe bet that if you like the song, you want to download it. Just a simple time saver.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
https://github.com/anddea/revanced-patches/issues/645#issue-2368885540
I'd wager, very few  would like videos solely for the purpose of the video to be downloaded for whatever reason. please reconsider this issue from hooking download feature from likes to playlists in general such that you may add all your videos in a single playlist and download the playlist through the download function.

**Comment by 93Pd9s8Jt** [comment]
> [#645 (comment)](https://github.com/anddea/revanced-patches/issues/645#issue-2368885540) I'd wager, very few would like videos solely for the purpose of the video to be downloaded for whatever reason. please reconsider this issue from hooking download feature from likes to playlists in general such that you may add all your videos in a single playlist and download the playlist through the download function.

No, the sole purpose of liking would not be to download it, but if you like it, you probably want to download it (and anyway it would be a default-off setting).
