### ISSUE TITLE
bug: Revanced options do not apear after the patch

### ISSUE THREAD

**Issue by Joshua64** [anddea/revanced-patches#646]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.23.40

### Bug description

I patched the app with the latest version with everything in stock and now i can not access the revanced options because the button is missing and i tried all the youtube options but revanced options do not apear 

![Screenshot_20240623_203604_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/d084e042-5427-4223-bf1d-0fa52f9e9f48)

![Screenshot_20240623_203547_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/869a1855-3ece-415b-b02f-df22c653d9f6)

### Device Environment

Galaxy A12
ANDROID 13
One Ui 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Clear `options.json` in your patching tool

**Comment by vippium** [comment]
Just add about clearing patch.json in announcement.

**Comment by anddea** [comment]
Added for the latest release
