### ISSUE TITLE
feat(YouTube - Navigation Buttons): Hide Red Bubble Notification

### ISSUE THREAD

**Issue by icynstant** [anddea/revanced-patches#650]
### Application

YouTube

### Feature description

![IMG_20240624_191557](https://github.com/anddea/revanced-patches/assets/127024748/85600953-c093-461c-ac25-ab08954527f3)

### Motivation

I subscribed to many channels and go to "subscriptions" only when I want, the red circle distracts me

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Parsa307** [comment]
That's not a big deal and is fine

**Comment by MondayNitro** [comment]
i think its these resources res/drawable/new_content_dot_background.xml & res/drawable/new_content_dot_background_cairo.xml, not sure though.
