### ISSUE TITLE
bug: YouTube Music background playback does not work

### ISSUE THREAD

**Issue by BAXSD** [anddea/revanced-patches#655]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube Music v7.06.53
Patch 2.226.0-dev.17

### Bug description

Background playback does not work in YouTube Music. Tried to play something then exit YouTube Music app (not closing). Then it stops playing in the background. Same thing with closed screen. Does anyone else having this issue?

Second. You cant toggle from Video to Audio. When trying this I get a message that I should "upgrade". With previously pacthes I did not have this issue. Is this normal behavior?

### Device Environment

Andorid 14 - OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
i need to select the patch. if you experience the issue even if the patch is selected, reopen this issue

**Comment by anddea** [comment]
Should be the issue of the Manager, I had this as well when switching sources for example, but when you press "Default" button in "Selected patches" list, this patch to remove restrictions is selected, so by default it's selected.
