### ISSUE TITLE
bug: coustom branding header doesn't apply in some places

### ISSUE THREAD

**Issue by gigachaand** [anddea/revanced-patches#658]
### Type

Other

### Tools used

Revancify

### Application

19.23.40
![IMG_20240627_072050](https://github.com/anddea/revanced-patches/assets/96541364/f9c77215-1bc6-4298-a197-048ab1991a26)
![IMG_20240627_071846](https://github.com/anddea/revanced-patches/assets/96541364/9c161479-e79c-4d34-9b5c-9db8903cfc92)

### Bug description

None

### Solution

None

### Additional context

None

### Device Environment

None

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
It's not a problem related to the unique things in this repo, open this in RVX issue center
