### ISSUE TITLE
question: how to apply my own custom header icon

### ISSUE THREAD

**Issue by AliBASE** [anddea/revanced-patches#660]
### Application

YouTube

### Question description

I'm working with cli on windows.I created custom header images with different dpi[hdpi-mdpi-xhdpi-xxhdpi-xxxhdpi], i enabled the "Custom branding icon YouTube" patch then edit the value of "CustomHeader" by providing the folder path in options.json, and i provided another folder path for the custom app icon, the custom app icon changed, but the custom header it didn't change.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Ahmey1400** [comment]
It doesnt support you can look this issue that i opened before https://github.com/anddea/revanced-patches/issues/622

**Comment by Francesco146** [comment]
you have to provide the whole header in order to change the icon, not only the icon image
