### ISSUE TITLE
bug: mini player/background playback doesn't work

### ISSUE THREAD

**Issue by Noth1ngLol** [anddea/revanced-patches#662]
### Type

Other

### Tools used

Revancify

### Application

19.24.40

### Bug description

1. Go to yt
2. Go to random vid
3. Then go to home

### Device Environment

Funtouch 14 global

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Noth1ngLol** [comment]
Also my english sucks

**Comment by Francesco146** [comment]
not an issue related to a unique feature of this repo, open this in the ReVanced Extended issue center
