### ISSUE TITLE
ci: Update README and patches.json with the latest supported versions

### ISSUE THREAD

**Issue by root-kernelhacker** [anddea/revanced-patches#664]
### Application

YouTube

### Feature description

Please indicate the supported YouTube version in the patch menu page json sample.

### Motivation

Please indicate the supported YouTube version in the patch menu page json sample.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by root-kernelhacker** [comment]
"name": "Alternative thumbnails",
    "description": "Adds options to replace video thumbnails using the DeArrow API or image captures from the video.",
    "compatiblePackages":[
      {
        "name": "com.google.android.youtube",
        "versions": [
          "18.29.38",
          "18.33.40",
          "18.38.44",
          "18.48.39",
          "19.05.36",
          "19.16.39" <------- no latest.

**Comment by Francesco146** [comment]
the gradle task that handles this is `generatePatchesFiles`, currently there's no easy way to automate this. i'll do that manually.

**Comment by Francesco146** [comment]
a managed to do that in the latest dev commit
