### ISSUE TITLE
bug(YouTube): App crashing after playing few videos 

### ISSUE THREAD

**Issue by shreyjain1998** [anddea/revanced-patches#665]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v19.23.40

### Bug description

App is crashing whenever I play more than couple of videos one after another from feed.
To reproduce - try to play feed videos and minimise it then play another one. For every 3rd and 4th video, application is crashing. I tested the same thing with latest RVX and ReVanced and it doesn't happen there.

Not sure how I can get the logs but please let me know if I can help. Thanks.

### Device Environment

Android 13, HyperOS 1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not an issue related to a unique feature of this repo, open this in the ReVanced Extended issue center

**Comment by shreyjain1998** [comment]
> not an issue related to a unique feature of this repo, open this in the ReVanced Extended issue center

But ReVanced extended or even ReVanced are not crashing if I play videos in same pattern.

**Comment by Francesco146** [comment]
very well, after i merge RVX changes I'll close this
