### ISSUE TITLE
feat(YouTube - DeArrow): Add alternative URL for blocked countries

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#667]
### Application

YouTube

### Feature description

Add the ability to include an alternative domain for images in the Revanced Extended settings.  In some countries (for example, Russia), the image domain yt3.ggpht.com is blocked.  As a result, channel icons and user avatars are not displayed in comments.  Detailed description of the function in the screenshot.
![photo_2024-06-28_08-41-12](https://github.com/anddea/revanced-patches/assets/61022739/943f048e-1ca4-44b8-8938-b3b90957f64c)

### Motivation

If this function is added to Revanced Extended, you will not have to use VPN and applications such as DPI Tunnel.  Unfortunately, now in Russia VPN services work very poorly.  The connection speed is very slow.  DPI Tunnel is also not stable.  Sometimes an application simply does not want to start a proxy connection.  Restarting the application doesn't help.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
can you translate what the screenshot says? i don't understand the request by only reading the description

**Comment by bozander** [comment]
> can you translate what the screenshot says? i don't understand the request by only reading the description

![Screenshot_2024-06-29-13-03-37-786_com google android googlequicksearchbox](https://github.com/anddea/revanced-patches/assets/61022739/755c2e38-29cf-4a95-9639-380c0325c2fb)

**Comment by Francesco146** [comment]
thank you, i'll add this
