### ISSUE TITLE
bug(YouTube - Custom Branding Icon): `Revancify Yellow` icon in settings is not working

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#669]
### Type

Other

### Tools used

Revancify

### Application

YouTube 19.23.40

### Bug description

In revancify i set settings icon to custom branding icon now when i go to settings icon is bugged
![IMG_20240629_234023](https://github.com/anddea/revanced-patches/assets/172329144/17211016-43df-49b1-a208-f3350f6945f3)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
does it happen for all the icons?

of yes, open this bug in the RVX issue center.

**Comment by anddea** [comment]
It should be only for Revancify Yellow, I didn't add that icon for settinga unlike other icons. I guess I'll fix it, when I'm free.

**Comment by AykhanUV** [comment]
In revancify you go to edit patch options

> just a query, can anyone tell me where can I find all the values of the options to explore in options.json file.

**Comment by AbakNacchan** [comment]
> actually I build on pc, there are no dropdowns to show all possible values have to manually change them. If possible can anyone list all these values.

Use RVX Manager to check.
