### ISSUE TITLE
bug: Outline with circle icons do not apply properly

### ISSUE THREAD

**Issue by imvoldemort** [anddea/revanced-patches#671]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.23.40

### Bug description

Outline with circle icons do not apply on ads in shorts. Short ads appear with outline icons rather. It's not appealing!
![IMG_20240630_151941](https://github.com/anddea/revanced-patches/assets/159900453/a562d0f7-8cf1-4ac3-8372-e2a598e60f39)
![Screenshot_2024-06-30-15-19-52-060_anddea youtube](https://github.com/anddea/revanced-patches/assets/159900453/0dde5231-8684-499b-b146-f9504d2bd154)

### Device Environment

Android 10, MIUI 12.5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
shorts ads are not detected as regular shorts. not planned
