### ISSUE TITLE
Enable Cairo splash animation

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#674]
### Application

YouTube Music

### Question description

Why patch "Enable Cairo splash animation" not supported for Youtube Music 7.07.51?
When you try to select this patch, it gives an error (see screenshot)
![IMG_20240701_152948](https://github.com/anddea/revanced-patches/assets/61022739/c1f97ae1-5216-4d85-994d-517014e79bf2)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Disable `Require suggested app version`. 7.06+ is supported.
