### ISSUE TITLE
bug: Use UTF-8 bytes for character counts for filtering videos

### ISSUE THREAD

**Issue by probablytukars** [anddea/revanced-patches#680]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube Version: v19.23.40
ReVanced Patches: 2.227.0-dev.2
ReVanced Integrations: 0.153.0

### Bug description

When filtering videos by keyword (Revanced Extended -> Feed -> Video Filter -> Keywords to hide), entering a word "less than 3 characters" causes an error that keyword filters should be 3 characters or more. For latin alphabets, this is not a bad restriction, however for non-latin alphabets this causes issues, where valid words are not accepted as keywords, despite them being words.

### Solution

This can be fixed by counting the number of UTF-8 bytes of keywords rather than the current approach which counts the "visible" character. For example, the word "직캠" (meaning "fancam") is technically 2 characters, but it represents a whole word, and has a UTF-8 byte count of 6 bytes (see https://mothereff.in/byte-counter#%EC%A7%81%EC%BA%A0), compare that to a latin word like "an" which has a UTF-8 byte count of 2 bytes (see https://mothereff.in/byte-counter#an). By checking the number of UTF-8 bytes instead of "characters" it would mean that those of us searching with non-latin alphabets would be able to use valid words in our languages.

Here is a function below which gets the number of UTF-8 bytes of a string:
```kt
fun getUtf8BytesLength(input: String): Int {
    return input.toByteArray(Charsets.UTF_8).size
}
```

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Report this issue [here](https://github.com/inotia00/ReVanced_Extended/issues) for bugs. It will be automatically reflected here. 

This restriction exists because some people might use 2-letter words, which could result in filtering out everything. However, besides that, I don't see any reason for this restriction at all. Perhaps the solution would be to simply remove it. Using bytes is also not ideal, as some languages may require 2 bytes for a single letter (e.g., Greek, Cyrillic, Coptic, Armenian, Hebrew, Arabic, etc.), and these letters do not necessarily constitute entire words; they are just individual letters.

**Comment by probablytukars** [comment]
Is the pattern `/(?:^|\s)(word)(?:$|\s)` not being used to find instances of keywords? If you had the key word "an" then the string "and something" wouldn't be removed but the string "an something" would be blocked. The 3 character minimum restriction seems arbitrary and can lead to alot of otherwise completely valid keywords being rejected for no good reason other than there existing some arbitrary lower limit on what the keyword must be.

**Comment by anddea** [comment]
No, it just checks if protobuf array contains the keyword as is, it can be a full word or just part of the word, no regex is used. Your solution might be used as an option "Match full word", although not sure if anyone would use it.

**Comment by anddea** [comment]
I removed minimum length check and added an option for full word matching, so you can test it and let me know if you face any issues.

**Comment by zerozero0022** [comment]
On: Filtering keyword with matching whole
( Ice Cream - "Ice Cream" )

Off: Filtering keyword with matching parts
( Ice Cream - "Ice" "Cream" )

Is this right?

**Comment by probablytukars** [comment]
In response to a message sent on the email chain:

> On: Filtering keyword with matching whole
> ( Ice Cream - "Ice Cream" )
> 
> Off: Filtering keyword with matching parts
> ( Ice Cream - "Ice" "Cream" )
> 
> Is this right?

I think it should work like this:

Examples:

    "Run somewhere"
    "Running somewhere"
    "He is running somewhere"
    "He has gone for a run"
    "He has gone for a run somewhere"
    "Run"
    "He is running"
    "He has outrun them all"
    "He will be outrunning them all"


With these examples, toggle off (match keyword anywhere) - would match against all strings since they all contain the word "run" - a note - it should convert the string and keyword to lowercase before matching to match all potentially different capitalizations of the word.

With these examples, toggle on (match keyword exactly) - it would match 1, 4, 5, 6 since they all contain the exact word "run" - they either start with a space or are at the start of the string, and they either end with a space or are at the end of the string - how the regex was set up to match.

If you recall back to the regex - `/.*(?:^|\s)(word)(?:$|\s).*/i` (/i = ignore capitalization, I added .* at start and beginning to help match any characters...)  then you would do a substitution in place of `word` (obviously don't use word in the matching string set up), just make sure to clean the string so that it matches against the literal strings. For example, if for some reason it contains the backslash, it should make sure to insert it in the regex such that it checks for the literal backslash character.


Consider the following kotlin example:

```kt
fun doesKeywordMatch(keyword: String, title: String, matchExactly: Boolean): Boolean {
    if (!matchExactly) {
        return title.contains(keyword, ignoreCase = true)
    }
   
    val escaped = Regex.escape(keyword);
    val regex = Regex(""".*(?:^|\s)($escaped)(?:$|\s).*""", RegexOption.IGNORE_CASE)
    return regex.matches(title)
}

fun main() {
    val titles = arrayOf(
        "Run somewhere",
    "Running somewhere",
    "He is running somewhere",
    "He has gone for a run",
    "He has gone for a run somewhere",
    "Run",
    "He is running",
    "He has outrun them all",
    "He will be outrunning them all"
    );
   
    val keyword = "Run";
   
    for ((index, title) in titles.withIndex()) {
        val matchesToggleOff = doesKeywordMatch(keyword, title, false);
        val matchesToggleOn = doesKeywordMatch(keyword, title, true);
       
        print("${index+1}. \"$title\" matches \"$keyword\"?: $matchesToggleOff | $matchesToggleOn\n");
    }
}
```

This will showcase the behaviour with the toggle on.

**Comment by zerozero0022** [comment]
I got it wrong, so I deleted what I wrote. I guess an e-mail was sent to you about it.

**Comment by anddea** [comment]
**Match full word toggled off:** If you provide "car", it will hide everything containing "car": cars, care, careful, caring, cargo, cartoon, etc.

**With toggled on:** It will match only "car" and nothing else.

**Obviously, it will consider multiple words. If you provide "taking car" with toggle off, it will match:** taking car to repair, taking care of my family, etc. **With toggle on, it will match only the first example.**

**Comment by zerozero0022** [comment]
It seems to filter keywords that are blank before and after.

But if it's the first digit in the sentence, it doesn't seem to be a filter.
(For example, I want to filter "He" in "He is running somewhere", but it doesn't filter because the front of "He" is not blank)

**Comment by anddea** [comment]
Yep, that can be true. Since buffer array has some data before and after every text occurrence. Seems like it should be removed after all as it works only if provided filter is in the middle of a text. That probably can be achieved without regex though. I just don't have enough time to experiment.

**Comment by anddea** [comment]
I added @probablytukars's idea to wrap it in word boundaries using `\b` and mentioned as a co-author. It seems to work for me. Test it and let me know.

**Comment by zerozero0022** [comment]
I think it's the same as deactivating that function and activating it.

**Comment by anddea** [comment]
It shouldn't work the same with 'on' and 'off'. For example, if you have 'taking car' and 'taking care', and filter 'car' with `match full word` off, it will filter out both examples. If you turn 'on', it will only filter out the first one.

I tested it with your example, and it worked the same. I searched for '치킨먹방', and if I filter '치킨' with `match full word` on, it won't hide anything. But if I disable `match full word`, it will hide everything.

**Comment by zerozero0022** [comment]
I understand.

I can't search for filtering keywords.
If I search for other keywords, the search will exclude the filtering keywords. [Compound keywords (Something+Filtering keyword+Something) are not excluded].

**Comment by anddea** [comment]
Sorry, I think I didn't understand. If you filter "taking care" it won't filter out "care taking", as it searches for exact order, including spaces and any symbols with both on and off. The only difference is that it will match exact full word if that option is turned on, "taking car" will not hide "taking cars", or "cars taking".

**Comment by probablytukars** [comment]
Maybe "match phrase exactly" would be better wording than "match word exactly"?

If you wanted to filter out "taking care" and "care taking" you would probably have to add both "care" and "taking" as individual words if that is what you want, or have to add both orders to the keywords blocking list.
