### ISSUE TITLE
bug: YouTube/Settings icon

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#681]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 19.23.40
Lastest patches

### Bug description

I choose mmt blue in custom branding icon patch but in settings it has thw default mmt logo
![IMG_20240703_020008](https://github.com/anddea/revanced-patches/assets/172329144/681b1d68-da62-4fb8-90f7-6d83d31711af)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AykhanUV** [comment]
You forgot yt music

**Comment by anddea** [comment]
Added for YT Music as well, let me know if I missed something.
