### ISSUE TITLE
question: why the notification bar have the same color as the lightheme?

### ISSUE THREAD

**Issue by Joshua64** [anddea/revanced-patches#685]
### Application

YouTube

### Question description

Hello 
After some patches now i payed attention and now, in the patch 2.227.0-dev.6, the notification bar have the same color as the lighttheme color (baby pink #FFFFB7CE) but this was not specified in the changelog section.
This bug was fixed by someone or the updates fixed this bug without someone noticed?
![Screenshot_20240703_203223_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/20147128/d14fc8a9-07b9-41b4-8114-cd96066b57fa)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Tbh, I never noticed it, I thought it was always like that.
