### ISSUE TITLE
Enable gradient loading screen not working properly 

### ISSUE THREAD

**Issue by UNIVERSA7VLAD** [anddea/revanced-patches#687]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.23.40

### Bug description

When loading the videos, the gradient theme isn't showing. When refreshing the page, the gradient color only works on the upper bar where you can you can chose what type of videos do you want to watch like games and music. It only shows the normal dark grey color.

### Additional context

Has been happening for 2 days. I tried: clearing cache, deleting the app and repatching the app. Nothing worked

### Device Environment

Ulefone Armor 21, android 13, Mediatek Helio G99, Mali-G57 MC2

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
gradient loading is the same in RVX, open the issue in the RVX issue center
