### ISSUE TITLE
feat(YouTube - Action Buttons): Hide label text of action buttons

### ISSUE THREAD

**Issue by harmit03** [anddea/revanced-patches#688]
![Screenshot_20240706-142701_YouTube Music~2](https://github.com/anddea/revanced-patches/assets/65583612/5dd6d26d-17a9-4a61-84f0-a35d9018c26c)
![Screenshot_20240706-142815_YouTube](https://github.com/anddea/revanced-patches/assets/65583612/cffc7afc-e0e7-4268-856e-203528594f5c)
### Application

YouTube

### Feature description

Hide labels in action buttons in player screen

### Motivation

Better accesibility
Compact ui
Less clutter

This is already implemented in YTMusic so it won't be much hard i guess🙂

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
screenshot

**Comment by harmit03** [comment]
> screenshot

Done, though its from yt music

**Comment by Ahmey1400** [comment]
Please add this feature as soon as possible.

**Comment by anddea** [comment]
YouTube and YT Music are different. Same functions are implemented differently for those apps. If it wasn't made already then the solution is not found yet.

**Comment by Francesco146** [comment]
not doable since it's a litho component, there is no point in keeping the issue open. I'll leave the decision to anddea 👋🏻
