### ISSUE TITLE
suggestion: Github Wiki with each setting explained and with an Imgur link with an on/off comparison

### ISSUE THREAD

**Issue by ArcherLegend** [anddea/revanced-patches#69]
### Application

YouTube

### Suggestion description

We should try to make a Wiki of the patches here on Github and keep it updated (something on the lines of the one made by Inotia00 in his repository) which should explain briefly what every single patch does and have Imgur links for every patch showing an on vs off comparison to show more clearly what is done by the patch.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You're free to make a Wiki, some people might find it very useful.

**Comment by ArcherLegend** [comment]
> You're free to make a Wiki, some people might find it very useful.

If I have the time I will, I still need to get around what some settings do before doing that.

**Comment by anddea** [comment]
There's a website explaining a lot of features, so you don't have to create a Wiki. Though some new features from this repo are absent there.

[kazimmt.github.io/RVX-Features/](https://kazimmt.github.io/RVX-Features/)

**Comment by ArcherLegend** [comment]
Yes I found that website shortly after, I was thinking about contacting the person who made that Wiki
