### ISSUE TITLE
bug(YouTube): ReVanced extended settings missing after enabling in toolbar

### ISSUE THREAD

**Issue by shreyjain1998** [anddea/revanced-patches#690]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.23.40

### Bug description

I had turned on `Replace Create button` and `Action type to assign to button` and I'm unable to see ReVanced extended settings option in the YouTube settings page anymore.

Also, I tried to disable above two settings and now I don't have any way to open ReVanced extended settings 🥲.. pls help me if there is still a way to open it..

![IMG_20240705_200412](https://github.com/anddea/revanced-patches/assets/107779107/285adc1f-8fad-47ae-b996-8a47cf13f1ac)

![IMG_20240705_200435](https://github.com/anddea/revanced-patches/assets/107779107/9347d12a-f1e4-499d-b6c7-91eb9a51e435)
<br/><br/><br/>
Ps - Below snaps are from RVX and I have same settings enabled and still can see ReVanced settings. Also, I know these settings are experimental but it was working fine till now and working in RVX as well.

![IMG_20240705_201159](https://github.com/anddea/revanced-patches/assets/107779107/fe560902-a210-4262-a130-ef060b59541a)

![IMG_20240705_200829](https://github.com/anddea/revanced-patches/assets/107779107/0784bc48-385f-4d40-81d3-9d0fb792630a)

### Device Environment

Android 13, HyperOs 1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by shreyjain1998** [comment]
It was actually due to change in `InsertPosition` keys from patch options. I had `General` as value saved from earlier and seems like the format was changed recently. So for now I was able to get the settings back with `@string/general_key` but could you handle the invalid values possibly stored already when using Revancify?

**Comment by Francesco146** [comment]
patch options changed, clean those in your patching tool and should work as expected
