### ISSUE TITLE
question: How to change default settings for apks

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#693]
### Application

YouTube

### Question description

How can i change default settings for apks? Hide cast from player is hidden by default how can i change that?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AbakNacchan** [comment]
If you're using builder, either CLI, Revancify, or RVX Builder you can customize your preferences.

**Comment by Francesco146** [comment]
currently not implemented as a patch option

**Comment by AykhanUV** [comment]
is there a way to change from the source?
