### ISSUE TITLE
bug: mmt blue splash animation doesnt work

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#697]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

19.25.39

### Bug description

When i patched it and opened, 

### Error logs

- Device Info
ReVanced Manager: 1.20.4
Model: SM-A336E
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: bill.youtube v19.25.39 (Suggested: Any)
Patches version: v2.227.0-dev.11
Patches added: Custom branding icon YouTube, Custom branding name YouTube, Force hide player buttons background, Hide Shorts dimming, MaterialYou
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Remove unused library: false
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 56 patches
Compiling patched dex files
Compiled 9 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installed

### Device Environment

Android 14, oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Ahmey1400** [comment]
Also i have a screen record


https://github.com/anddea/revanced-patches/assets/143447608/59fa1c53-79b6-4795-a937-8a25d7ed28eb

**Comment by Ahmey1400** [comment]
This is a screenshot of it

![VideoCapture_20240706-235947](https://github.com/anddea/revanced-patches/assets/143447608/10e44a36-2fe4-41b5-9a99-67cad9224643)

**Comment by AbakNacchan** [comment]
All MMT animated splash icon is missing actually.

**Comment by Ahmey1400** [comment]
Is only mmt splash is missing ?

**Comment by AbakNacchan** [comment]
> Is only mmt splash is missing ?

Yes.

**Comment by Ahmey1400** [comment]
I hope @anddea will fix it as soon as possible

**Comment by AbakNacchan** [comment]
@Francesco146 kindly look at this problem.

**Comment by Francesco146** [comment]
fixed the issue, it happened during the last RVX merge, there was a bit of a mess, and now it should be back to normal. i'm only leaving this issue open because i still need to do a few things but for now it's okay

**Comment by AbakNacchan** [comment]
> fixed the issue, it happened during the last RVX merge, there was a bit of a mess, and now it should be back to normal. i'm only leaving this issue open because i still need to do a few things but for now it's okay

Waiting for the release then.

Also I'd notice a problem with de-rDE translation, I didn't know the details, but I thought it was there when I use builder.

**Comment by Francesco146** [comment]
currently it is working, i didn't merge RVX changes in this context because we have already a PR (https://github.com/anddea/revanced-patches/pull/689) that would override it.
