### ISSUE TITLE
bug: Cannot patch in termux/revancify

### ISSUE THREAD

**Issue by MegaBigBossMan** [anddea/revanced-patches#699]
### Type

Error while patching

### Tools used

Revancify

### Application

Latest patch version from dev patch v2.227.0-dev.13
Deleted options to try to fix. Did not work. 

[patch_log.txt](https://github.com/user-attachments/files/16117444/patch_log.txt)

### Bug description

Revancify fails to patch app using newest dev patches. 

### Error logs

```shell
Attached previously.
```

### Solution

[patch_log.txt](https://github.com/user-attachments/files/16117447/patch_log.txt)

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MegaBigBossMan** [comment]
Hello. The issue is still happening even with the new patch push.

**Comment by Francesco146** [comment]
use English translation for no

**Comment by MegaBigBossMan** [comment]
> use English translation for now

The app is in English. I only use English. The app still will not patch and has the same error. 

Please see log attached. 
[patch_log.txt](https://github.com/user-attachments/files/16117556/patch_log.txt)
