### ISSUE TITLE
bug: revancify still failing to patch

### ISSUE THREAD

**Issue by MegaBigBossMan** [anddea/revanced-patches#704]
### Type

Error while patching

### Tools used

Revancify

### Application

Please see patch log report attached. Revancify fails to patch. All patches are English.
[patch_log.txt](https://github.com/user-attachments/files/16117851/patch_log.txt)

### Bug description

Revancify fails to patch. See attached patch log.
[patch_log.txt](https://github.com/user-attachments/files/16117852/patch_log.txt)

### Error logs

```shell
Attached.
```

### Additional context

Please see the attached log. The issue is the same as the previous patch release. 

### Device Environment

Android 13.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
What do you mean that it's failing? They are just wanrings in your logs, patching is successful. I'll take a look later to eliminate warnings.
