### ISSUE TITLE
question: force wordmark header patch disappeared

### ISSUE THREAD

**Issue by andylee516** [anddea/revanced-patches#706]
### Application

YouTube

### Question description

why did force wordmark header patch removed at 2.220.7 dev15? Is there a way to create our own custom header which is not based on app icon?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It is removed, because it's integrated inside custom branding iocn patch.

**Comment by andylee516** [comment]
> It is removed, because it's integrated inside custom branding iocn patch.

so we can't apply custom header using zip file?

**Comment by anddea** [comment]
You can in Custom branding icon patch.

**Comment by andylee516** [comment]
> You can in Custom branding icon patch.

custom branding icon patch was not at termux, but it showed at rvx manager. So i patched with rvx manager with including custom branding icon patch and located the header zip file that i wanted. However, it showed successful patch and no problem with the patch log, but when i opened the patched app, it did not applied;;

**Comment by anddea** [comment]
Maybe you did something wrong. I tested it, and it worked fine for me. For further assistance, consider reaching out to community members on platforms like Telegram, Reddit, etc.

**Comment by andylee516** [comment]
> Maybe you did something wrong. I tested it, and it worked fine for me. For further assistance, consider reaching out to community members on platforms like Telegram, Reddit, etc.

[patch_log.txt](https://github.com/user-attachments/files/16163714/patch_log.txt)
this is patchlog dev18, i have no idea whats wrong;;

**Comment by anddea** [comment]
Your patch log clearly says that your provided icon path is invalid. 

https://github.com/anddea/revanced-patches/issues/686#issuecomment-2210351369

Did you ask the community for help? You need to understand that instead of making new things we're forced to spend our time helping with such things. Such questions are not related to the development. Please, always ask community first.

**Comment by andylee516** [comment]
sorry but 1more question. I had succeeded in custom icon branding as duplicating folder and renaming to premium. However, the patch was failed at last. Can you check this?
[patch_log.txt](https://github.com/user-attachments/files/16171712/patch_log.txt)
