### ISSUE TITLE
feat(YouTube - Player Buttons): Add Lock Screen button in the player

### ISSUE THREAD

**Issue by sr-shishir** [anddea/revanced-patches#707]
### Application

YouTube

### Feature description

Lock screen option is currently available in player settings (accessible from gear icon), but it's to long to reach there. Sometimes it makes confused that where is that lock screen option. 🤔 So, I want to say that if you add lock screen button in the player then it would be very easy to quickly access & lock the screen seamlessly. I made two concepts for you. The rest is your choice.

![IMG_20240707_184405](https://github.com/anddea/revanced-patches/assets/139035194/9293aded-b227-4a62-a290-ced5049d1f9e)

### Motivation

This feature can save time & quickly can lock the screen. Hope it will be implemented 😊

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not planned at this point, the benefits are too low
