### ISSUE TITLE
feat: YouTube Music - DeArrow): Add alternative URL for blocked countries

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#708]
### Application

YouTube Music

### Feature description

Can you add this feature for Youtube Music https://github.com/anddea/revanced-patches/issues/667?

### Motivation

This problem also affected YouTube Music. Images are not displayed because the domain with images is blocked in Russia. And if in YouTube Revanced this problem is solved (In the settings you can enable an alternative domain for images, then in YouTube Music there is no such option.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
rvx has already a pr for this. when he'll merge that, I'll port it here.
