### ISSUE TITLE
Don't show this reminder again for GmsCore battery optmisation missing in 2.227.0-dev16

### ISSUE THREAD

**Issue by ArcherLegend** [anddea/revanced-patches#709]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 19.25.39
RevancedExtended release 2.227.0-dev16

### Bug description

The possibility to permanently hide the popup asking to remove battery optimisation from GmsCore when opening RevancedExtended is no longer present and the battery optimisation reminder pops up every time RevancedExtended is opened.

### Solution

Adding the possibility to remove the popup via the "Don't show this again" option like in release 2.226.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
This option was not removed. Clear your manager, make sure you use the right client.
