### ISSUE TITLE
bug: Maximize Icon color on Mini Player is not reverted

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#712]
### Type

Cosmetic

### Tools used

CLI

### Application

Latest supported ver. 

### Bug description

The maximize icon on mini player on dark mode is not reverted to white color. 

![Screenshot_20240709_162154_YouTube~2](https://github.com/anddea/revanced-patches/assets/153147835/c75eb5a3-9208-4e8a-85bb-27a46a1dfddd)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
open this issue to rvx issue center
