### ISSUE TITLE
feat(YouTube Music - Custom branding): Improve AFN icons

### ISSUE THREAD

**Issue by hdd45** [anddea/revanced-patches#721]
### Application

YouTube Music

### Suggestion description

Please improve the YouTube music branding icon quality (mainly afn icons).
![image](https://github.com/anddea/revanced-patches/assets/51121709/22303a24-21df-4ad9-93b6-2cda8e86d0f7)
![image](https://github.com/anddea/revanced-patches/assets/51121709/3ee892ec-2140-4ff9-8400-df7d1e9212d8)

Looks too poor in app.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AbakNacchan** [comment]
Not using Music, but is Music using different icons than YouTube?

**Comment by anddea** [comment]
This request should be passed to the original author - [xafn](https://github.com/xafn). Maybe I or some other community members  will reproduce these icons, not in the plans though for now.

**Comment by anddea** [comment]
You can open a PR then, but you need to make all types of this icon: header, splash, launcher.

**Comment by hdd45** [comment]
@Francesco146 why "wont fix"? 
Improved the icons and created a pull request for it.

**Comment by Francesco146** [comment]
i didn't see it, I don't use YTM and i won't make any patch for it. the tag is just that, but PRs are welcome

**Comment by hdd45** [comment]
@Francesco146 here is the Pull-request, can you  review.
https://github.com/anddea/revanced-patches/pull/724
