### ISSUE TITLE
Cutom branding splash screen

### ISSUE THREAD

**Issue by Gubbbka** [anddea/revanced-patches#723]
### Application

YouTube

### Feature description

![IMG_20240713_075440_568](https://github.com/user-attachments/assets/43885934-957a-4c45-8d7a-27bb7c2a81d7)

![IMG_20240713_075432_969](https://github.com/user-attachments/assets/8652392d-7061-4a22-966a-c9fe9903ce1a)
At the moment we can change icon and header via path file. But splash screen unpossible to customize. Is there way to implement path bar there? If yes it could be good cosmetic addition

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
you can customize the splash screen with the `Custom branding icon` patch. if you have a custom splash screen, you can open a PR like #689
