### ISSUE TITLE
question: why i cant patch yt at 19.25.39

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#726]
### Application

YouTube

### Question description

When i try to patch it says latest version is 19.16.39

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Probably because one of the patches is stuck on 19.16, old thumbnail for example, it doesn't mean you cannot patch 19.25, you can. 

Ask these question from communities on Reddit and Telegram instead. This is mostly for development now.

**Comment by Ahmey1400** [comment]
Ok, but every patch says it
![Screenshot_20240714_164034_RVX Manager](https://github.com/user-attachments/assets/68c92a3e-edda-4559-923f-bc339517b5cc)

**Comment by Ahmey1400** [comment]
Now I understand, in inotia's repo, they wrote that they pulled back it to 19.16.39 due to a/b tests.
