### ISSUE TITLE
bug: cairo seekbar not working

### ISSUE THREAD

**Issue by Berlinkk** [anddea/revanced-patches#727]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.26.42

### Bug description

cairo seekbar not working 
Patch version - V2.227.0-dev. 20

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
wrong yt version 

https://github.com/inotia00/ReVanced_Extended/issues/2241
