### ISSUE TITLE
question: Why dropped support

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#728]
### Application

YouTube

### Question description

support for 19.25.39 dropped can i ask why?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2241
