### ISSUE TITLE
Pach 2.227.0.dev.20

### ISSUE THREAD

**Issue by antmasterkey** [anddea/revanced-patches#729]
### Application

YouTube

### Question description

Pach 2.227.0.dev.20 only accepts YouTube 19.16.39
![IMG_20240714_125044.jpg](https://github.com/user-attachments/assets/06a460ef-eff9-4af7-9beb-86737e62a848)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2241
