### ISSUE TITLE
bug: Miniplayer patch broken 

### ISSUE THREAD

**Issue by imvoldemort** [anddea/revanced-patches#730]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.26.42

### Bug description

Double tap and drag and drop actions don't work anymore. Miniplayer hides automatically while dragging anywhere and double tap action doesn't do anything.

### Device Environment

Android 10, MIUI 12.5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
wrong app version 

https://github.com/inotia00/ReVanced_Extended/issues/2241
