### ISSUE TITLE
feat: Add Bypass Restrictions Patch

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#735]
### Application

YouTube

### Feature description

A patch to [bypass YouTube restrictions](https://github.com/ReVanced/revanced-patches/pull/3442). 

### Motivation

To watch restricted video, of course. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
the alternative thumbnails/images patch has been merged already.
