### ISSUE TITLE
feat(YouTube - Themes): Add a custom image as a theme

### ISSUE THREAD

**Issue by goshakotanov** [anddea/revanced-patches#739]
### Application

YouTube

### Feature description

<details>
  <summary>Image as reference</summary>

  ![Screenshot_2024-07-16-14-05-13-954_org telegram messenger](https://github.com/user-attachments/assets/b84a4931-2e9e-47ff-be23-dec82b445822)

</details>

### Motivation

Adding a feature that allows applying a yt theme with your own image (like it releazed with icon and header via path file)
### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not planned at this point, not doable. jpgs are not used in any android resources
