### ISSUE TITLE
bug: Subscriptions section Red Dot issue

### ISSUE THREAD

**Issue by Spaceshiprace** [anddea/revanced-patches#74]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

v19.05.36

### Bug description

it keeps showing that red dot on subscriptions section even though there's no new upload from the channels that I'm subscribed to

![Screenshot_2024-03-17-16-56-51-655_anddea youtube_1](https://github.com/anddea/revanced-patches/assets/156727749/068eb9c7-728e-4f5d-a642-8fbd7951ccae)

### Error logs

```shell
idk
```

### Solution

?

### Device Environment

Android 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Red dot appears if any community post, or shorts was posted, or new voting, or any other activity was made, some of them are hidden in the ReVanced settings, that's why you don't see anything new but red dot appears.

**Comment by Spaceshiprace** [comment]
yeah I know but I'm subscribed to 2 channel and they literally didn't post nothing all things that you mentioned.. ???

**Comment by anddea** [comment]
Maybe it's a YouTube bug, because there have to be something. Can you verify on the stock app that there's nothing new, just to be sure?

**Comment by Spaceshiprace** [comment]
yeah as you said, I checked it and its also on the regular yt.
Can you check by yourself to see if its just me who has that bug ?

**Comment by anddea** [comment]
Probably that's just some invisible channel updates, it's not a bug, its a feature of YouTube itself.

**Comment by Spaceshiprace** [comment]
what I gotta do to see that invisible update so that dot stop appearing everytime I open the app

**Comment by Spaceshiprace** [comment]
Nah, Its a bug cuz I checked with another account that has no subscriptions and it still shows that red dot
