### ISSUE TITLE
bug: seekbar being stucked 

### ISSUE THREAD

**Issue by andylee516** [anddea/revanced-patches#742]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

19.16.39 version

### Bug description

![IMG_20240719_013037_761](https://github.com/user-attachments/assets/d61700ab-a432-4709-8563-eb23769e4ac0)
the length of seekbar became shorter and it buried below the space. Do we have solution for this?

### Device Environment

android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I cannot reproduce it but as far as I know it happens sometimes and might be the YouTube issue. Do you know if it happens because of some specific patch? Or maybe someone from community knows why it happens?

**Comment by andylee516** [comment]
> I cannot reproduce it but as far as I know it happens sometimes and might be the YouTube issue. Do you know if it happens because of some specific patch? Or maybe someone from community knows why it happens?

not sure about which specific patch occurs this problem, but this issue happens occasionally, not always.

**Comment by Francesco146** [comment]
can you reproduce it in RVX?
