### ISSUE TITLE
bug: custom icon error

### ISSUE THREAD

**Issue by betterdelay** [anddea/revanced-patches#744]
### Type

Error while patching

### Tools used

RVX Manager

### Application

yt 19.16.39 anddea 2.227.0 dev23

### Bug description

![Screenshot_20240719_065230_RVX Manager](https://github.com/user-attachments/assets/c1a9870e-32ed-4a29-b677-9589eda60a67)
![Screenshot_20240719_065241_RVX Manager](https://github.com/user-attachments/assets/6ce01598-6bb5-4009-b877-d871b85c8f26)
![Screenshot_20240719_065256_RVX Manager](https://github.com/user-attachments/assets/b62ab299-89e7-427c-9391-3b281889e586)
![Screenshot_20240719_065307_RVX Manager](https://github.com/user-attachments/assets/2829e701-9b8b-48f4-a492-3f53ac2e5177)
![Screenshot_20240719_065647_RVX Manager](https://github.com/user-attachments/assets/347d3686-e87f-48f1-9d25-b1d4062658ce)

I want to use the original icon as a visual preferences icon, but it fails when I proceed with the patch

### Device Environment

android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You cannot use custom icon for visual prefs icons as of now.
