### ISSUE TITLE
bug: Accent Stroke Color remains always Blue.

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#746]
### Type

Other

### Tools used

Revancify

### Application

Latest Supported

### Bug description

In Inverted, it shows inverted stroke color like White for Black BG and vice versa.

But in Accent, it always shows Blue color, instead of accent color which device follows. Previously it works perfectly. I noticed it today.
![Screenshot_20240722_225115](https://github.com/user-attachments/assets/d067f6ac-d361-4e66-9a3c-6c355915a7b3)

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Maybe YouTube changed it. Because I didn't create accent color and didn't changed it, I use default one by YouTube, I think it's used over the app, in settings maybe and somewhere else. What color did you expect? I think it was blue for me all the time.

**Comment by vippium** [comment]
> Maybe YouTube changed it. Because I didn't create accent color and didn't changed it, I use default one by YouTube, I think it's used over the app, in settings maybe and somewhere else. What color did you expect? I think it was blue for me all the time.

Currently, it remains blue for everyone. But, the time when you introduced it, it keep changing with device accent color. Means Material Color. Maybe something which is triggering it to not change color and remains blue.

**Comment by anddea** [comment]
Was it the same YT version as now? Can you repatch with older patches that worked before as you say and verify?

**Comment by vippium** [comment]
> Can you repatch with older patches that worked before as you say and verify?

And how to do that?

**Comment by anddea** [comment]
You can manually download from GitHub and paste it in the patching tool directory replacing neweer patches and integrations. Patches and integrations should be around the same date. Disable auto updates in your patching tool before that.
