### ISSUE TITLE
Animated splash screen doesn't work

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#748]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

The animated screensaver does not work even though the function is enabled in the settings

https://github.com/user-attachments/assets/79cd5ca8-2bfb-4c61-b0ad-d326b59b53ae

![Screenshot_2024-07-24-11-13-59-724_com google android youtube-edit](https://github.com/user-attachments/assets/a8d83adb-0ec2-4994-8a7b-affb9dd3a2d7)

### Additional context

Revanced Patches 2.227.0-dev.24

### Device Environment

Android 14 HyperOS 1.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by bozander** [comment]
> I cannot reproduce this issue, it works as expected on my side. Maybe you can provide more details? 

Sometimes it works, sometimes it doesn't.  Now the animation works once and that’s it.  Does not work any more

**Comment by anddea** [comment]
It's probably because YouTube loads faster. The animation should be 1 sec, but sometimes feed is loaded faster, that's why it skips half of the animation sometimes. It's not really a bug I guess.
