### ISSUE TITLE
question: How to make the player btn background transparent in RVX builder

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#757]
### Application

YouTube

### Question description

As title says. What value should I set for it. I make it blank but patching error occur

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You have to ask such questions on Telegram or Reddit. 

```
@android:color/transparent
```

**Comment by vippium** [comment]
> You have to ask such questions on Telegram or Reddit.
> 
> ```
> @android:color/transparent
> ```

Ahh....Sorry. I forgot to ask there. Nxt time
