### ISSUE TITLE
bug: "Download video" not being hidden from feed flyout menu

### ISSUE THREAD

**Issue by 54m4d** [anddea/revanced-patches#759]
### Type

Other

### Tools used

RVX Manager

### Application

v19.16.39  -  v2.228.0-dev.2

### Bug description

Hi, when adding `Download video` to the feed flyout menu filter, the `Download video` option does not get hidden. However, other elements, e.g. `Report` etc..., work as expected.

### Error logs

```shell
N/A
```

### Solution

If reproducible, check how `Download video` can be properly targeted and filtered.

### Device Environment

Multi

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not releated to this repo since it's not releated to a unique feature of this repo. open this issue in RVX issue center

**Comment by anddea** [comment]
I cannot reproduce it, the feature/option work fine for me.
