### ISSUE TITLE
feat(YouTube - Shorts):Add dowload overlay button

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#760]
### Application

YouTube

### Feature description

Add a download overlay button for short videos

### Motivation

It is more intuitive and quicker to download.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
dup of https://github.com/anddea/revanced-patches/issues/763
