### ISSUE TITLE
feat(YouTube - Visual preferences icons): Update `Stock` icon for `Extended icon`

### ISSUE THREAD

**Issue by stainlf** [anddea/revanced-patches#764]
### Application

YouTube

### Feature description

https://github.com/inotia00/ReVanced_Extended/issues/2181
By resolving the above issue, When the custom branding icon becomes YouTube as well, the RVX Settings icon is applied properly.

However, the current stock icon does not harmonize with other RVX icons, so I would like to change it to the icon below. (Also YouTube Music)
![Original](https://github.com/user-attachments/assets/53439e0e-f59d-4838-ad0e-bd8d216ffdf3)

### Motivation

I wish it would change to a more presentable appearance. Thanks.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
can you explain the feature better? the stock icon is not "applied", if it's selected, then the icon of the apk is not modified. Are you suggesting to use the stock icon as the ReVanced extended icon?

**Comment by Francesco146** [comment]
got it 👍🏻

**Comment by Francesco146** [comment]
mh, from what I understand, you apply the patch "Custom branding icon" with the "Stock" icon. in visual preference icon you select "Custom branding icon" but it isn't applied. I'm having some trouble understand your words, can you use deepl.com and translate better?

**Comment by anddea** [comment]
The icon is applied as it should be, he just requests to use another icon from his original post, more rounded.

**Comment by anddea** [comment]
This white circle will blend in with background if light theme is enabled. Should we use this instead?


<details>
<summary>Icon</summary>

![1](https://github.com/user-attachments/assets/1b456765-e899-4625-81e3-6e2c543acc23)
</details>

**Comment by anddea** [comment]
The icon with a red circle looked worse, so I used your icon with a white circle. In light theme, it will look like a small YouTube icon without a circle. I'm not sure if anyone cares about this or if anyone uses the light theme at all.
