### ISSUE TITLE
Newer Reddit version via RVX Manager

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#765]
### Application

Other

### Question description

Why is there no newer versions of reddit accepted beyond v2024.17 via RVX Manager? That's quite old now.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
read the announcement inside rvx issue center. not related to this repo
