### ISSUE TITLE
Compatible patches with new revanced manager 

### ISSUE THREAD

**Issue by Moonknight982** [anddea/revanced-patches#766]
### Application

YouTube

### Question description

Will there compatible patches with new revanced manager aka compose manager

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
it hasn't been released yet, depends on the implementation
