### ISSUE TITLE
question: How To Use Change Version Code Patch For YouTube? 

### ISSUE THREAD

**Issue by AbakNacchan** [anddea/revanced-patches#767]
### Application

YouTube

### Question description

First of all, I need details on JSON file. Second, I don't know how to put version code in Boolean. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
include the universal patch the highest version code will be set

**Comment by AbakNacchan** [comment]
> include the universal patch the highest version code will be set

How? Since there is no option on the RVX Patcher for instance.

**Comment by Francesco146** [comment]
in rvx manager there's a setting in the settings page. idk about rvx patcher
