### ISSUE TITLE
bug(YouTube Music - Custom branding icon): Low quality of `AFN` icon 

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#768]
### Application

YouTube Music

### Suggestion description

Yt music afn logo is very low quality plus when using one ui color palette feature it even looks worse
Can you make logo better
![IMG_20240731_194125](https://github.com/user-attachments/assets/540266cf-59bf-4a45-9506-61a93f93d6f4)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
What patches version are you using?

**Comment by AykhanUV** [comment]
I have used 2.228.0-dev.3 and yes it has always been like this on my samsung device(one ui 5.1)  even no color palette setting, no problems on my poco x6 pro (hyper os)

**Comment by anddea** [comment]
The ordinary colored icon should be the same as all other icons. Monochrome icon though might be with lower quality as we don't have SVG icon for it. 

What about other icons, are they low quality too, or only AFN? Colored and monochrome / themed icon?

**Comment by Francesco146** [comment]
stale
