### ISSUE TITLE
Split "Remove background playback restrictions" into 2 patches

### ISSUE THREAD

**Issue by MtndaleRedneck** [anddea/revanced-patches#769]
### Application

YouTube

### Suggestion description

Right now "Remove background playback restrictions" does 2 things it allows all videos to be played in the background, and it also allows kids videos to be played in the background or in the mini player. I'd like to keep the kids in miniplayer option but don't like background playback. I don't want to see the playback notification always in the notification shade.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
you can disable the background playback in YouTube settings

**Comment by MtndaleRedneck** [comment]
> you can disable the background playback in YouTube settings

That disables background playback, but you still get the controls in the notification shade while the app is open.

**Comment by Francesco146** [comment]
unfortunately, i cannot think of how to make this division possible, since the two processes are intrinsically linked, closing as not planned - stale
