### ISSUE TITLE
feat: autoscroll youtube shorts 

### ISSUE THREAD

**Issue by sdsucks** [anddea/revanced-patches#77]
### Application

YouTube

### Feature description

when turned on, autoscroll to the next shorts after one ends
like these extensions

[https://github.com/panthebig/Youtube-Shorts-Autoscroller-Chrome-Extension](https://github.com/panthebig/Youtube-Shorts-Autoscroller-Chrome-Extension)
[https://github.com/donwiktorb/Auto-Youtube-Shorts-Scroll](https://github.com/donwiktorb/Auto-Youtube-Shorts-Scroll)

### Motivation

my arm hurts manually scrolling youtube shorts in bed

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Damn! I'm confused if this will be useful or harmful, LOL!

**Comment by win64exe** [comment]
add pls

**Comment by Elektroney** [comment]
bump

**Comment by Fred6388** [comment]
Close, it's already added

**Comment by Elektroney** [comment]
> Close, it's already added

Sorry but i cant seem to find it in the most recent version mind telling me where to look or how the feature is called

**Comment by anddea** [comment]
Settings > Extended > Shorts > Change Shorts repeat state, or just search "repeat", "shorts repeat", etc.

**Comment by anddea** [comment]
The patch name is `Shorts components`, use any preferred patching tool
