### ISSUE TITLE
bug: forced disable caption isn't working for shorts

### ISSUE THREAD

**Issue by rsaurav12** [anddea/revanced-patches#771]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39
Patch 2.228.0-dev.2
Integration 0.155.0-dev.1

### Bug description

1. Enable "disable forced auto caption" in settings 
2. Subtitles stills shows automatically in shorts 
![Screenshot_2024-08-01-04-02-10-242_anddea youtube](https://github.com/user-attachments/assets/9ebde73e-7ac8-43ea-a9bf-983ea27fb963)
![Screenshot_2024-08-01-04-02-37-161_anddea youtube](https://github.com/user-attachments/assets/6dcc003a-c08e-4a16-bc47-27a45f382c7b)

### Device Environment

Android 12
Miui 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
tap and hold and disable captions. if that doesn't hold when you close the app, open this issue in RVX, it's not related to a unique feature of this repo
