### ISSUE TITLE
feat(YouTube): Implement `GoodbyeDPI` service

### ISSUE THREAD

**Issue by bozander** [anddea/revanced-patches#774]
### Application

YouTube

### Feature description

Please add option to enable  https://github.com/ValdikSS/GoodbyeDPI to YouTube Revanced 

### Motivation

YouTube has started to slow down in Russia (thanks to the Federal Service for Communications, Information Technology and Mass Media of the Russian Federation). As a result of the measures taken against YouTube, it is visible that YouTube Revanced is constantly playing with freezes. It is simply impossible to watch content. I think many users from Russia will thank you for adding this function. Thanks in advance. Best regards.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Although it's a good idea, adding something like VPN or proxy is too excessive. It's like having a whole other service inside YouTube. You can use ByeDPI for Android or the Nekobox plugin for it, or any VPN service. 

I'll keep it open for now under consideration, or maybe some other contributors might want to implement something like that."

**Comment by Francesco146** [comment]
i'm on the same page as @anddea, unfortunately i wouldn't know how to make this feature possible, on a practical level i mean
