### ISSUE TITLE
question: How to open CLI

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#775]
### Application

Other

### Question description

How do you even open cli? I double click and nothing comes up i have downloaded every requires app

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You cannot open it, CLI (Command Line Interface) is a terminal command utility, and there's a documentation on ReVanced Team's GitHub page. If you cannot understand it anyway, contact their support on Discord.
