### ISSUE TITLE
feat: Hide Text Shows After Selection of Video Quality or Speed

### ISSUE THREAD

**Issue by harry-osborn1** [anddea/revanced-patches#779]
### Application

YouTube

### Feature description

Whenever we select video quality or playback speed, some text shows on screen which becomes annoying.  

***text shows like:***

**For Video Quality**:

*'Changing default mobile data/wifi quality to 480p etc'*

(because I use "remember vid quality changes" setting and this text doesn't show if you've not turned on this setting)

**For Speed**:

*'Changing default speed to 1.2x. etc.'*

because I use "remember Playback speed changes" setting and this text doesn't show if you've not turned on this setting)

**So there should be one setting where we can turn on/off this setting so if anybody doesn't wanna see these text then they'll have a choice **

     *[This is my first request ever in github so, sorry in advanced if I did something not right]*

![Screenshot_20240802-104824](https://github.com/user-attachments/assets/1cf62c3e-b037-4719-8b8c-258ec6f86b1e)
![Screenshot_20240802-104753](https://github.com/user-attachments/assets/3cc3265d-bd23-401f-b295-2f8051fec452)

### Motivation

*why this feature is necessary/important*

 Because it becomes very annoying when I always see these text even I know that which 'video quality or speed' I'm choosing.

So this feature should be implemented.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
done, check the latest dev release that will be published
