### ISSUE TITLE
bug: cannot hide mix playlist at fullscreen related videos

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#780]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Yt: 19.16.39

### Bug description

Hide mix playlist doesnt work correct

Screenshot: 
![Screenshot_20240804_173306_YouTube RVX](https://github.com/user-attachments/assets/651f992b-0984-4d60-942d-bda10c2bfe3d)

### Device Environment

Android 14 oneui6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not releated to this repo since it's not releated to a unique feature of this repo. open this issue in RVX issue center

**Comment by Ahmey1400** [comment]
When i searched it inotia doesnt add this option so can i open this as a suggestion to this repo

**Comment by Francesco146** [comment]
check this: https://github.com/anddea/revanced-patches/discussions/446

then check better in RVX, if it doesn't have it, the most you can do is open a feature request.

**Comment by Ahmey1400** [comment]
According to #556 inotia doesnt accept it bug either suggestion so can i open this as feature request to this repo

**Comment by anddea** [comment]
Did you use the custom filter from the issue you mentioned? And it doesn't work for you?

**Comment by Ahmey1400** [comment]
Neither of they worked, there is no way to hide them

**Comment by Ahmey1400** [comment]
I think you can add this as a feature
