### ISSUE TITLE
bug: Override download action button menu is gone.

### ISSUE THREAD

**Issue by kyan5221** [anddea/revanced-patches#781]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

youtube 
![Screenshot_20240805_183457](https://github.com/user-attachments/assets/0bffe473-488d-4527-9a2b-ab3c98631704)
v19.16.39

### Bug description

'Override download action button' menu has been gone in new release.
![Screenshot_20240805_183446](https://github.com/user-attachments/assets/af45e6c4-ffe7-4f6b-84b2-e46002da0c32)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by andylee516** [comment]
me too

**Comment by Francesco146** [comment]
it has been moved to general, with the other Hook download actions settings

**Comment by kyan5221** [comment]
> it has been moved to general, with the other Hook download actions settings

then pleaee remove `experimental flags` on the bottom.

**Comment by zerozero0022** [comment]
> > it has been moved to general, with the other Hook download actions settings
> 
> then pleaee remove `experimental flags` on the bottom.

experimental flags
• it is a feature that some users want.
• but... inotia doesn't get bug reports because if there's an unexpected issue, it's hard to fix.

If the header is deleted, can someone fix the issue?
