### ISSUE TITLE
feat: custom toasts colour

### ISSUE THREAD

**Issue by Graywizard888** [anddea/revanced-patches#782]
### Application

YouTube

### Feature description

Change custom color to all toasts appearing in YouTube like, changing video quality and skip preload buffer,etc,just like force snack bar theme patch, also changing video quality toast doesn't appearing even I enabled the option.

![Screenshot_2024-08-05-23-04-28-156_com google android youtube](https://github.com/user-attachments/assets/23c4783c-a608-4778-88dc-3ed9dd33aa06)

### Motivation

More customizations.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
these toasts are displayed by your OS, revanced has no control over it
