### ISSUE TITLE
bug: Shorts buttons

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#786]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

Im selecting orginal outline for custom shorts buttons but it appears as orginal youtube shorts buttons

### Device Environment

Android 14, HyperOS 1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Original outline is now YouTube outline. 

https://github.com/anddea/revanced-patches/wiki/Icons#youtube-outline
