### ISSUE TITLE
suggestion: Show only .txt file in `Import & Export Settings` setting.

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#789]
### Application

Other

### Suggestion description

Can be copied or taken from inotia's repo as in his YT, it only shows .txt files, rather than showing all files.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
we share the same code as RVX

**Comment by vippium** [comment]
> we share the same code as RVX

If same code is shared, then why there is difference in picking up file. Isn't there something?
