### ISSUE TITLE
bug: overrided download button doesnt work

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#793]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

19.16.39

### Bug description

When i turn on override download button download button dont do anything

### Device Environment

Android 14 oneui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Ahmey1400** [comment]
Why do you closed it

**Comment by Francesco146** [comment]
test the new release
