### ISSUE TITLE
feat: bypass video region restrictions

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#794]
### Application

YouTube

### Feature description

Like bypass image region restrictions but for videos

### Motivation

For some countries, yt videos are banned such as russia, 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
nod doable without a VPN or proxy, which isn't doable in an app like revanced
