### ISSUE TITLE
bug: App crashes when casting video

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#798]
### Type

Error at runtime

### Tools used

CLI

### Application

Youtube 19.16.39, also i tested on 19.25.39, 19.26.42

### Bug description

When i try to cast video the app crashes

### Additional context

Casting worked on [v2.228.0-dev.6](https://github.com/anddea/revanced-patches/releases/tag/v2.228.0-dev.6)
but this bug started happening after [v2.228.0-dev.7](https://github.com/anddea/revanced-patches/releases/tag/v2.228.0-dev.7) and others that came out after
I used cli 4.6.1 for this

### Device Environment

1-Poco X6 Pro Android 14, HyperOS 1
2-Samsung S22 Ultra Android 14, OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
not related to a unique feature of this repo, open this in RVX issue center
