### ISSUE TITLE
question: custom branding icon settings not available inside options.json

### ISSUE THREAD

**Issue by AliBASE** [anddea/revanced-patches#799]
### Application

YouTube

### Question description

OS = Windows
Youtube version = 19.16.39
Patch version = v2.228.0-dev.11
Cli version = 4.6.1

For some reason the "Custom branding icon YouTube" not added into the options.json file, that includes the custom header & the branding name, all are missed,i did clean patch, removed the old options.json file, the temporary youtube folder, keystore

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You have to include the patch before the options.json is generated.

**Comment by AliBASE** [comment]
Fixed!. You need to update the patch name for these:
"Custom branding icon YouTube" > "Custom branding icon for YouTube"
"Custom branding name YouTube" > "Custom branding name for YouTube".
