### ISSUE TITLE
bug: `Change toggle type` appears in settings although `Change player flyout panel toggles` is unselected

### ISSUE THREAD

**Issue by Kuddus73** [anddea/revanced-patches#8]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Patches v2.220.9a3

### Bug description

The option `Change toggle type` appears in settings (_Setting > ReVanced Extended > Flyout menu > Player flyout menu **(Additional settings)**_) even when `Change player flyout panel toggles` patch isn't included in the manager when patching.

(Also, even if it is present in the settings, the above option doesn't work since when it is enabled, the toggles inside `Additional settings` menu don't get changed to text.)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Should be fixed in https://github.com/anddea/revanced-patches/releases/tag/v2.220.9a4. Let me know if it still persists.
