### ISSUE TITLE
feat: Add keywords filtering for comments

### ISSUE THREAD

**Issue by Kevinr99089** [anddea/revanced-patches#80]
### Application

YouTube

### Feature description

In France (which is probably also the case in your country) Bots flood comment space with se*ual bots, or bots that always add something like "congratulations, you've made 100K views without using a view boost with You Vues".

### Motivation

There is a filter to hide terms in video titles, and this feature request aims to extend this functionality to video comments (or add an option to do so).
In order to filter terms for comments too, to limit fake news, generic terms and hide bots, I think this option might be a good idea.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Added in [v2.222.0-dev.7](https://github.com/anddea/revanced-patches/releases/tag/v2.222.0-dev.7)
