### ISSUE TITLE
bug (YT) : Size of `Mute Button` of Thin Overlay Buttons should be increased.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anddea/revanced-patches#801]
### Type

Cosmetic

### Tools used

Revancify

### Application

YT v19.16.39

### Bug description

These two should be made bigger in size:

https://github.com/anddea/revanced-patches/blob/dev/src%2Fmain%2Fresources%2Fyoutube%2Foverlaybuttons%2Fthin%2Fdrawable-xxxhdpi%2Frevanced_overlay_button_mute_volume.png

https://github.com/anddea/revanced-patches/blob/dev/src%2Fmain%2Fresources%2Fyoutube%2Foverlaybuttons%2Fthin%2Fdrawable-xxxhdpi%2Frevanced_overlay_button_mute_volume_off.png

Currently, the neighbouring buttons look bigger, so Mute Button should match their size.

![IMG_20240812_172334_552](https://github.com/user-attachments/assets/c6d81cdf-5a7c-4ed9-8843-66bf206e914a)

### Error logs

```shell
No logs.
```

### Solution

All icons of Thin Overlay Buttons should look of equal size.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro (Android 12).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
the resoultion of the icon is the same as the others, these are illusions that requires breking the standard 36x36

**Comment by Aryan-Chauhan** [comment]
> the resoultion of the icon is the same as the others, these are illusions that requires breking the standard 36x36

Resolution shouldn't be changed.

Icon should be made bigger within that same resolution.

**Comment by Francesco146** [comment]
making the icon bigger requires changing the resolution. that icon comes directly from google's icons, I didn't draw that. multiple icons comes from that actually. if you have an icon with the same resolution that, in you opinion, looks better, open a PR. we're sticking to google' standard for now
