### ISSUE TITLE
bug: Community posts not being hidden

### ISSUE THREAD

**Issue by probablytukars** [anddea/revanced-patches#802]
### Type

Error at runtime

### Tools used

Revanced Manager

### Application

YouTube v19.25.39

### Bug description

Community posts are not being hidden despite the options in the settings being turned on to hide posts.

I have all options turned on to hide community posts, but they are still being shown.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
The last supported version is 19.16. YouTube versions above 19.16 have several A/B tests, so bug reports won't be accepted for those versions at this time. If you can reproduce the issue on version 19.16 or lower, please reopen this issue. Nevertheless, we will review it later, and when we decide to support version 19.25, this issue should be resolved by then. Thank you for your report.

**Comment by anddea** [comment]
Use this custom filter for now 

```
images_post_root.eml
```
