### ISSUE TITLE
feat: YouTube Music Suggestion

### ISSUE THREAD

**Issue by ImpenetrableNoble** [anddea/revanced-patches#804]
### Application

YouTube Music

### Feature description

I've been encountering a YouTube Music issue that I reported to Inotia. Unfortunately, he closed the report due to YouTube Music's banner patching and suggested submitting a feature request instead.

I believe it would be beneficial for all RVX version codebases to isolate and modify the specific lines controlling the preview subscription.

This would prevent RVX users from being inadvertently placed in a beta test and required to pay for subscriptions when using YouTube music. 

### Motivation

It's unfair for RVX users of YouTube music to pay for a subscription to be limited to preview features, they should have full access to every patch available.

![Screenshot_20240819_232624](https://github.com/user-attachments/assets/700db809-3916-447e-ac1c-fb27f4f4a022)
![Screenshot_20240820_014603](https://github.com/user-attachments/assets/fab8a17c-188d-41b9-bbd7-bc0411976c80)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
> suggested submitting a feature request instead

He accepts feaure requests for YouTube Music, so I guess he meant to reopen this as a feture request in his issue center. So consider reopening it there as a feature request and if he closes it again, then reopen this issue here.
