### ISSUE TITLE
feat:YT -- Add Hide `Use this Sound` patch in Shorts Components

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#807]
### Application

YouTube

### Feature description

Discription will be available at [Inotia's Repo Issue $2349](https://github.com/inotia00/ReVanced_Extended/issues/2349)

As inotia declined to add this as a toggle in shorts component and provided only custom filter to hide it. 

This is here so that a patch can be added to shorts component to hide it (instead of custom filter)

### Motivation

Will directly allow users to hide the button like `Paid Promotion` button. If this is going to be available Only as custom filter, then it will be hard for users to hide it and increase in opening questions tagged issues,

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
solved in the PR with rvx changes
