### ISSUE TITLE
suggestion: Provide info for setting Sources (and patching) in README.md and the wiki

### ISSUE THREAD

**Issue by KobeW50** [anddea/revanced-patches#808]
### Application

Other

### Suggestion description

**Problem**

This repository lacks information users need to set the sources in patching tools. It also does not specify if inotia00's patching tools should be used (RVX Manager, rvx-builder, etc.), or if the ReVanced tools should be used. (In the Telegram, some of the pinned messages say to use the compose manager from ReVanced)

**Solution**

Add a table or screenshot to the README and/or the Wiki that shows users how to set the Sources. Here is the markdown you can use to display a table:

```
|||
|---|---|
| Patches organization | `anddea` |
| Patches source | `revanced-patches` |
| Integrations organization | `anddea` |
| Integrations source | `revanced-integrations` |
```

Here is a screenshot you can use:

![anddea_sources_example](https://github.com/user-attachments/assets/69a0e32f-76af-4dae-bc46-7dce35192f9d)

Additionally, specify whether to use inotia00's or ReVanced's patching tools.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Never thought it was a big problem. People can use any patching tool available, as it’s compatible with everything, at least for now.

Maybe [the Wiki](https://github.com/anddea/revanced-patches/wiki) would be a better place for that information? We can then update the main README by simply adding a link to the Wiki.

Also, the information about sources is provided [in the pinned `Discussions` question](https://github.com/anddea/revanced-patches/discussions/215). We can use the same easy-to-copy-and-paste format from this discussion in the Wiki. What do you think?

**Comment by KobeW50** [comment]
Sounds good. Thank you

**Comment by KobeW50** [comment]
I opened a PR for this (it also contains stuff for the wiki)
