### ISSUE TITLE
bug: YouTube community posts can't be hidden

### ISSUE THREAD

**Issue by smed79** [anddea/revanced-patches#810]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

The function to hide community posts doesn't work.

Settings 

![001](https://github.com/user-attachments/assets/0c1c0eab-5895-494b-a922-73429f05975d)

Example 

![002](https://github.com/user-attachments/assets/fe56d78a-8583-41c5-834d-227ec5ebdc5d)

### Error logs

```shell
-
```

### Solution

-

### Additional context

Revanced Patches 2.228.0-dev.12 (2024-08-16)

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I'll fix it later, use this custom filter for now

```
images_post_root.eml
```

**Comment by Francesco146** [comment]
solved in the PR with rvx changes

**Comment by smed79** [comment]
Thank you very much 🙏
