### ISSUE TITLE
bug: Spoofing side effects display is buggy.

### ISSUE THREAD

**Issue by akir45** [anddea/revanced-patches#813]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39
patch v2.228.0-dev.13

### Bug description

Spoofing side effects display is buggy.
![Screenshot_2024-09-02-08-13-27-981_anddea youtube](https://github.com/user-attachments/assets/59c9748c-e9d2-40c1-8170-0d08e70972ea)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AykhanUV** [comment]
Issue still not fixed in dev2

**Comment by anddea** [comment]
Cannot reproduce it on my side. Maybe it's an issue on your side with caching? Provide screenshots with the patches information as well.

**Comment by AykhanUV** [comment]
Yeah I don't have any problems on my poco x6 pro, but on samsung s22 ultra and samsung a51 it is buggy. And it shows as the screenshot akir45 provided
