### ISSUE TITLE
bug: Cairo Seekbar option not working/showing

### ISSUE THREAD

**Issue by youarefinished** [anddea/revanced-patches#817]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube vv19.16.39 and YouTube vv19.28.42

### Bug description

I understand that vv19.28.42 is not officially supported so I am reporting about vv19.16.39 which is the current officially supported version.

So I built it using Revancify, used all patches except Material You.

Whem I tried to search for "Cairo f seekbar" option in settings, it isn't there although it is there in vv19.28.42 but enabling it doesn't work and I still get the normal seekbar.

But in vv19.16.39, I don't even get the option to enable it.

### Device Environment

Android 13, Custom Rom

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Cairo seekbar is an experimental feature that comes after v19.16.39, that's why it's not present in 19.16 and there can be issues with new versions too.

**Comment by youarefinished** [comment]
Thank you for clearing the doubt about v19.16.39 and I can understand that even new versions may have issues with it but I just wanted to make sure if I was doing something wrong while building it as build available on evanced.net built with your sources has it working on my device yet when I build it, it doesn't work on my versions.
