### ISSUE TITLE
bug: Skipping error when enjoying music on YouTube music

### ISSUE THREAD

**Issue by DJ133104** [anddea/revanced-patches#828]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39
 enjoying music on YouTube music jumped to Google play, not to the patched ytmusic

### Bug description

YouTube 19.16.39
 enjoying music on YouTube music jumped to Google play, not to the patched ytmusic

### Solution

/Customize Jump App Name

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Please report it [here](https://github.com/inotia00/ReVanced_Extended/issues).
