### ISSUE TITLE
bug: "'LithoFilterPatch' that raised an exception" when patching Youtube

### ISSUE THREAD

**Issue by ArcherLegend** [anddea/revanced-patches#83]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Youtube V19.09.37

### Bug description

When using Revanced Extended Manager or revanced-builder with the last patches available there are errors during the patching process and the patched app crashes when started if installed as a result.
[Patching log.txt](https://github.com/anddea/revanced-patches/files/14639097/Patching.log.txt)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Do not update with pre-release dev version of patches. It's bad that RVX Manager shows pre-release, original ReVanced Manager doesn't.

**Comment by anddea** [comment]
I removed dev release, it should work on 2.221.1.

**Comment by ArcherLegend** [comment]
By removing the dev release it now works, thank you for all the job you are doing.
