### ISSUE TITLE
feat: Selective Hiding of Community Posts

### ISSUE THREAD

**Issue by filipstojakovic** [anddea/revanced-patches#830]
### Application

YouTube

### Feature description

Currently, users can hide individual videos from their subscription feed, which is helpful when avoiding unwanted content or videos they’ve already watched. However, this functionality is not available for community posts. When you click on the three dots for a community post, the only option available is "Report." There is no way to selectively hide individual posts without reporting them or blocking all community content from that channel.

<img src="https://github.com/user-attachments/assets/a40e82ab-7996-4d9f-9d37-6fdaf4372d45" alt="image description" width="200" />

### Motivation

I propose adding an option to hide specific community posts from the subscription feed. This would allow users to manage their feed more effectively, without the need to remove all community posts or resort to reporting content unnecessarily.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You can selectively hide community posts in the channel, home feed, related videos, and subscriptions feed. Isn't that what you meant?

**Comment by filipstojakovic** [comment]
> You can selectively hide community posts in the channel, home feed, related videos, and subscriptions feed. Isn't that what you meant?

i can't selectively hide community posts, as you can see in picture above i only have "Report" option
