### ISSUE TITLE
bug: Can't change default setting for YTM

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#834]
### Type

Other

### Tools used

CLI

### Application

YouTube Music 7.16.52

### Bug description

When i try to change default settings for ytm [here](https://github.com/anddea/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/music/settings/Settings.java) changes does not affect in app itself but this works for youtube patches is this only bug in ytm?

I also wanna add that when app first opens after install everthing is as i set, but after opening settings tab everthing goes back to default

### Device Environment

Andoid 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AykhanUV** [comment]
I found [prefs.xml](src/main/resources/youtube/settings/xml/revanced_prefs.xml) for youtube but can't see it in music folder

**Comment by anddea** [comment]
> You need to edit related patch files in order to update default values for YTM. 

Files that end with *Patch.kt have settings addition code. 

Example:
https://github.com/anddea/revanced-patches/blob/9915487b82b62ea2629b4bba9fe78891f35aa456/src/main/kotlin/app/revanced/patches/music/ads/general/AdsPatch.kt#L179-L183

**Comment by anddea** [comment]
With Gradle. Run any command in Terminal on Linux/macOS

```bash
./gradlew assemble
``` 
```shell
./gradlew build
``` 

For Windows use `gradlew.bat` instead of `./gradlew`. Compiled jar file will be in the build directory.

**Comment by AykhanUV** [comment]
i get error message
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve app.revanced:revanced-patcher:19.3.1.
     Required by:
         root project :
      > Could not resolve app.revanced:revanced-patcher:19.3.1.
         > Could not get resource 'https://maven.pkg.github.com/revanced/registry/app/revanced/revanced-patcher/19.3.1/revanced-patcher-19.3.1.pom'.
            > Username must not be null!
            
            
i have tried to put my username and personal key in build.gradle.kts but i still get this error

**Comment by AykhanUV** [comment]
I added 
gpr.user = "username"
gpr.key = "token"
to gradle.properties and resolved it
