### ISSUE TITLE
question: What's version for cairo seekbar?

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#835]
### Application

YouTube

### Question description

I have tried 19.26.42 for [this](https://github.com/anddea/revanced-patches/commit/b956855183f3f6c85a41e0d3812da6ff71ec8157) patch but i don't see option to change the colors only enabling it, im asking what version does this work in?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
it was 19.23.xx and above but support for this setting has been dropped and won't work
