### ISSUE TITLE
bug: (YouTube - Sharing or Opening a link closes the Application) 

### ISSUE THREAD

**Issue by Jaydan101** [anddea/revanced-patches#836]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 19.16.39

### Bug description

I will attach a video as well. 

This is not the first time I have noticed this bug. I have noticed it for quite a while now. I was just too lazy to report it  

While I am playing a youtube video, if I share the link of that video or click a link in the description box while playing a video, the video will go into PIP mode or Background play mode and then instantly close on it's own when I enter another app. Whether that app is a messaging application or a browser. 

https://github.com/user-attachments/assets/c61e4437-fab2-4ac1-94bd-6fae8cbd5b75

### Device Environment

Samsung Galaxy S23U Android 14, One UI 6.1 (6.1.1 new update)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
are you using the pre-release version? if not try there. this bug isn't reproducible on my phone, but PiP support has been lacking since months. if the bug still reproduces after updating, consider open the bug report in RVX issue center since we share the same codebase. (attaching some logs would be nice)
