### ISSUE TITLE
Support for System Font in Reddit

### ISSUE THREAD

**Issue by quik-dusk** [anddea/revanced-patches#837]
### Application

Reddit

### Feature description

Currently Reddit uses its own font. I'm requesting for a support for custom fonts or the use of smartphone system Font across all the texts inside the reddit app.

### Motivation

This makes the app experience more cohesive and makes it feel more personalized. The current Reddit font really looks so mechanistic and outdated.

I took this inspiration from Infinity for Reddit that also supports system fonts.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by Francesco146** [comment]
reddit patches are not planned
