### ISSUE TITLE
feat: rounded corners in vídeo playback

### ISSUE THREAD

**Issue by Joshua64** [anddea/revanced-patches#841]
### Application

YouTube

### Feature description

![Screenshot_2024-09-26-15-25-07-147_com gof global](https://github.com/user-attachments/assets/a8abeaf6-10dd-4956-b778-cae81239a487)

The rounded corners in this video in the picture in picture mode

![Screenshot_2024-09-26-15-28-52-272_app rvx android youtube](https://github.com/user-attachments/assets/97813cb7-316e-485b-a0c1-e3c6bc54b059)

Is possible to use (or apply) rounded corners to vídeo playback in the portrait mode ? and is possible to apply in full screen mode ? Like one of the rounded corners apps in the Playstore does ?

### Motivation

Better to look to the videos i guess :)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
pip is controlled by your device, we can't edit it
