### ISSUE TITLE
question: Cairo start color

### ISSUE THREAD

**Issue by andylee516** [anddea/revanced-patches#847]
### Application

YouTube

### Question description

for the patch 'cairo seekbar colors', which side means the cairo start color; the leftside or rightside of seekbar?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by andylee516** [comment]
it doesn't work at 19.16.39 right?

**Comment by anddea** [comment]
Yes, Cairo is not available on older versions.
