### ISSUE TITLE
feat: Add 'youtube alt' icon in visual preferences icon settings 

### ISSUE THREAD

**Issue by imvoldemort** [anddea/revanced-patches#849]
### Application

YouTube

### Feature description

Add 'youtube alt' icon in visual preferences icon settings from inotia's pattches.
![IMG_20241001_193017](https://github.com/user-attachments/assets/c9e12725-a235-4673-afa1-95a2d1b0b3e2)

### Motivation

It looks very rich and matches with the Visual preferences icons very well.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
yt alt has been removed because it can be use against the repo by a DMCA. no YT icons are allowed since it's a violation of their copyright

**Comment by anddea** [comment]
I don't think they can put down the repo because of this icon. These icons are recreated (not copied), like the Shorts icon, the original YouTube pref icon, etc. 

The icon seems bigger than the other icons, though. I think I'll make it smaller and add it later.

**Comment by imvoldemort** [comment]
Thanks

**Comment by AbakNacchan** [comment]
@anddea, yt_alt icon is not working on YT Music. Missing resources or something.

**Comment by AbakNacchan** [comment]
> There is no YT Alt icon for YTM. Only YouTube.

The problem is when I applied the icon using JSON file since the both option are the same — not differentiated.

**Comment by anddea** [comment]
Should I separate them? One will be "Visual Icons for YouTube", and the second will be "...for YouTube Music". Hence, they will be different.

**Comment by Francesco146** [comment]
yes, in my opinion is the best option

Il Ven 4 Ott 2024, 11:05 Aaron Veil ***@***.***> ha scritto:

**Comment by Francesco146** [comment]
yes it's the best option imo

**Comment by anddea** [comment]
Will do that later. I didn't want to change it, because then everyone will have to delete options.json or clear patch options again. But that will be the best solution.
