### ISSUE TITLE
bug: View Products banned is not hidden (ads)

### ISSUE THREAD

**Issue by smed79** [anddea/revanced-patches#853]
### Type

- Other

### Tools used

- RVX Manager v1.22.2

### Application

- YouTube v19.16.39
- RV Patches v2.230.0-dev.4 (2024.10.04)

### Bug description

**View products** banner that overly the video player is not hidden.

![hvpd](https://github.com/user-attachments/assets/79b8ac31-b7ce-461c-9267-cb63d6516cc0)

![vpd](https://github.com/user-attachments/assets/8d1c2660-4d2f-4e7a-a49f-9ebf58342e67)

### Additional context

Example video when you can reproduce 

- `https://youtu.be/tsdpdtmigXM`
- `https://youtu.be/sM_lWr6iRds`

### Device Environment

- Android 14.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Reopen this issue [here](https://github.com/inotia00/ReVanced_Extended/issues).

**Comment by smed79** [comment]
[inotia00 / ReVanced_Extended # 2437](https://da.gd/OSuen)

**Comment by smed79** [comment]
Fixed in https://github.com/inotia00/revanced-integrations/commit/0ae3afab4fe36a3fea4332a4809e29dfd8e41d57
