### ISSUE TITLE
suggestion: add audio player

### ISSUE THREAD

**Issue by BlackSparkz** [anddea/revanced-patches#854]
### Application

YouTube

### Suggestion description

Add option to play video as audio like libretube

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
so just having the video pitch black?

**Comment by anddea** [comment]
Closing this issue due to lack of response from the author.
