### ISSUE TITLE
question: what is "return youtube username"

### ISSUE THREAD

**Issue by Ahmey1400** [anddea/revanced-patches#857]
### Application

YouTube

### Question description

What does this setting do, i cant find any info about it

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
It says in the title and description for the setting, it replaces username handle with the actual name of a channel, instead of `@SomeUsername` you'll see `Some Name` in comments section.

**Comment by Ahmey1400** [comment]
I get it, thanks
