### ISSUE TITLE
feat: option to only hide feed filters under search bar 

### ISSUE THREAD

**Issue by rsaurav12** [anddea/revanced-patches#858]
### Application

YouTube

### Feature description

Need an option to only hide feed filters.
And comment filters should not hidden and kept untouched. 
![Screenshot_2024-10-19-20-50-21-478_app rvx android youtube](https://github.com/user-attachments/assets/9ce8891a-23e2-4576-b0c1-7ca04be2c796)

### Motivation

These are unnecessary filters but comment  filters are quite good

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I'm not entirely sure what you mean. There is keyword filtering for the feed as well. If you are referring to the categories under the logo and search bar (such as All, Gaming, etc.), you can find these settings under YT Settings > RVX Settings > Feed > Category bar. Is that what you were asking about?
