### ISSUE TITLE
bug: Swap Create and Notifications button option (if disabled) causes any played video on a specific account to have a10 second buffer before actually starting the video

### ISSUE THREAD

**Issue by AcaGamer5** [anddea/revanced-patches#859]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Version: YouTube ReVanced Extended - Anddea v19.25.39
MicroG Version: MicroG 0.3.1.4.240913
ReVanced Manager Version: Revanced Manager 1.9.25

### Bug description

The Swap Create and Notifications button option (if disabled) causes any played video on a specific account to have an around 10 second buffer before actually starting the video. This buffer does not do anything in terms of loading the video, it just causes it to stop and play the buffer animation for 10 seconds upon starting the video from any point. 

Deleting the cache on MicroG or the modified YouTube app does not seem to help in long term, only allowing one video to play normally, before the 10 second buffer is back again.

After several attempts, just having the Swap Create and Notifications option disabled seems to trigger the buffer.

This issue has occurred one day after installing the app.

### Device Environment

Device Model: Mi 10T Lite
MIUI Version: MIUI Global 14.0.2 Stable
Android Version: 12 SKQ1.211006.001

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
19.25.39 is not supported officially as it may have bugs. Report this issue [here](https://github.com/inotia00/ReVanced_Extended/issues).
