### ISSUE TITLE
feat: splash icon animation

### ISSUE THREAD

**Issue by TeaqariaWTF** [anddea/revanced-patches#86]
### Application

YouTube

### Feature description

Can you add opening icon animation support for YouTube and Music app?
### Motivation

https://github.com/anddea/revanced-patches/assets/90970076/f3720fe8-7830-4f30-b453-54018c4c689f

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Did you make this animation yourself?

**Comment by TeaqariaWTF** [comment]
No, I didn't make this animation.

Opening animation that a developer named MMT implemented in his YouTube app

**Comment by anddea** [comment]
@kazimmt is it your creation? Would you like to add it here as an author?

**Comment by kazimmt** [comment]
> @kazimmt is it your creation? Would you like to add it here as an author?

I always add em manually. Don't add it as a patch. It may cause c&d. (I don't know)

**Comment by kazimmt** [comment]
Btw, That's all you need to add
[animation.zip](https://github.com/anddea/revanced-patches/files/14781930/animation.zip)

**Comment by anddea** [comment]
Added animation in the latest dev, let me know if you face any issues.

@kazimmt, thank you for sharing animation files. There was no `avd_anim.xml` file but I created it myself. I added you as an author to the commit. Can you also check for relevancy of your icons, let me know if something's missing or anything new that you'd like to add.

**Comment by Aryan-Chauhan** [comment]
> Btw, That's all you need to add
> [animation.zip](https://github.com/anddea/revanced-patches/files/14781930/animation.zip)
> 

Hi, kazimmt

I'm currently using your animated splash screen in RVX, it's great.

But the boundary is not smooth, it looks even/rough even if you don't look closely.

Device: Realme 7 Pro
OS: Android 12 (skin name is Realme UI 3.0)
Smallest width: 360dp

![1711771846235.png](https://github.com/anddea/revanced-patches/assets/91815107/32cb9f09-a6f5-452b-b636-a5fadb96a67a)

**Comment by TeaqariaWTF** [comment]
> Added splash animation in the latest dev, let me know if you face any issues.
> 
> @kazimmt, thank you for sharing animation files. There was no `avd_anim.xml` file but I created it myself. I added you as an author to the commit. Can you also check for relevancy of your icons, let me know if something's missing or anything new that you'd like to add.

How can I activate this new opening animation?
@anddea

**Comment by anddea** [comment]
@TeaqariaWTF just select MMT in `Custom branding icon YouTube `

**Comment by TeaqariaWTF** [comment]
How to turn off the old animated splash 


https://github.com/anddea/revanced-patches/assets/90970076/cb47e4cd-11e6-433b-864d-8e920877bc52

@anddea

**Comment by Aryan-Chauhan** [comment]
> How to turn off the old animated splash 
> 
> 
> https://github.com/anddea/revanced-patches/assets/90970076/cb47e4cd-11e6-433b-864d-8e920877bc52
> 
> @anddea 

Go to Settings/ReVanced Extended/Miscellaneous/Enable New Splash Animation.

Turn it off.

**Comment by anddea** [comment]
> How to turn off the old animated splash

You have to enable `Add splash animation` in Manager or whatever you use (it is enabled by default), then new animation for MMT will work, but if you want to turn off the progress bar loading screen, just do what Aryan_Chauhan said.

**Comment by TeaqariaWTF** [comment]
Bu şekilde ekledim


![Screenshot_20240406-215751_Iceraven](https://github.com/anddea/revanced-patches/assets/90970076/4a6ade17-c7ae-4954-8517-56657c92fa13)
