### ISSUE TITLE
question: Confused If anddea Has A Official Telegram Channel and Group or not

### ISSUE THREAD

**Issue by Parsa307** [anddea/revanced-patches#862]
### Application

Other

### Question description

Hello!

I have been confused if Anddea has a official telegram channel or not or a group
![Screenshot_20241029-162324_Nekogram](https://github.com/user-attachments/assets/f784853d-a0b1-4c42-8bc6-50aaf9db58a9)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Parsa307** [comment]
And the owner is Xisr

**Comment by Francesco146** [comment]
not official, but it's the only one

**Comment by Parsa307** [comment]
> not official, but it's the only one

Thanks

**Comment by anddea** [comment]
Francesco, Xisr, anddea, ReX, some other community members who contributed to the project or helped other members are there, so you can call it official.
