### ISSUE TITLE
bug: [hide recommended videos] videos in search with blank Title/Channel name/Date appear when enabled

### ISSUE THREAD

**Issue by YAKSL** [anddea/revanced-patches#864]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 16.19.30

### Bug description

when 'Hide Recommended Videos' is enabled to hide 'people also searched for' instead of the said videos being hidden, they still appear in search but with blank Titles, Channel Name and Dates

when enabled:
![Screenshot_2024-10-30-09-52-11-54_0635f5993b1f7a268b0ea09a0649cdab](https://github.com/user-attachments/assets/5e9b7cc7-9ed7-448d-b5d1-948a6c50d2ec)

when disabled:
![IMG_20241030_095411](https://github.com/user-attachments/assets/6044f9c0-a61c-4f8e-8b57-c94243d55cb3)
the patch in question:
![Screenshot_2024-10-30-09-46-57-69_0635f5993b1f7a268b0ea09a0649cdab](https://github.com/user-attachments/assets/921bf6cd-b302-46fc-835f-4357950c0831)

### Additional context

Revanced Patches: 2.229.0
Revanved Integrations: 0.156.0

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
> YouTube 16.19.30

The lowest supported version is `18.29.38`.

Since the issue is reproducible on other versions, report this issue [here](https://github.com/inotia00/ReVanced_Extended/issues).

**Comment by YAKSL** [comment]
> > YouTube 16.19.30
> 
> The lowest supported version is `18.29.38`.
> 
> Since the issue is reproducible on other versions, report this issue [here](https://github.com/inotia00/ReVanced_Extended/issues).

i meant 19.16.39 (instead of 16.19.30) i was typing out from memory. i updated the issue, sorry for that.
![Screenshot_2024-10-30-10-24-29-38_0635f5993b1f7a268b0ea09a0649cdab](https://github.com/user-attachments/assets/dde42127-347d-4d57-bf97-25fb1b33ef7f)
