### ISSUE TITLE
bug: YT icon keeps reverting back to XISR yellow even when custom branding icon is disabled

### ISSUE THREAD

**Issue by Git-ship-it-coder** [anddea/revanced-patches#872]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39 (Recommended version)

### Bug description

Used patches:
Alternative thumbnails . Ambient mode control • Bypass image region restrictions Change player flyout menu toggles Change share sheet Change start page Custom double tap length . Description components . Disable QUIC protocol Disable auto audio tracks . Disable auto captions Disable haptic feedback . Disable resuming Shorts on startup . Disable splash animation • Enable OPUS codec Enable debug logging Enable external browser . Enable gradient loading screen . Enable open links directly • Force player buttons background . Force snackbar theme . Fullscreen components . GmsCore support . Hide action buttons • Hide ads Hide comments components . Hide feed components . Hide feed flyout menu . Hide layout components . Hide player buttons . Hide player flyout menu . Hook YouTube Music actions . Hook download actions . Layout switch • Miniplayer . Navigation bar components Overlay buttons • Player components . Remove background playback restrictions . Remove viewer discretion dialog . Return YouTube Dislike Theme . Toolbar components . Translations for YouTube Video playback • Visual preferences icons for YouTube

Description:
Even thought I am patching the suggested version of youtube (nodpi) (v19.16.39) without selecting the custom branding icon patch...

![Screenshot_20241119_152420_RVX Manager](https://github.com/user-attachments/assets/5ac96db1-a9a4-4d90-b58f-d30424623fe9)

It keeps showing as XISR yellow in my home launcher and even in RVX manager!! This is even happening with patched YT music. Even when i enable the custom branding icon patch and select other icons like MMT and revancify etc... it keeps showing as XISR yellow!!!

![Screenshot_20241119_153005_One UI Home](https://github.com/user-attachments/assets/fd89c2f1-bc03-4a2b-b9b0-c11c3cf87932)

[Home launcher]

![Screenshot_20241119_153805_RVX Manager](https://github.com/user-attachments/assets/0fe66200-3e58-4b25-8f15-86de13b65831)

[RVX Manager]

I am sort of a newbie to all this stuff so I dont really know what can be causing this problem. I hope I have correctly attached all the info needed for someone to assist me on this.

### Error logs

```shell
- Device Info
RVX Manager: 1.22.2
Model: SM-S911B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v2.231.0
Patches added: Default
Patches removed: Custom Shorts action buttons
Default patch options changed: Force player buttons background [Background color: @android:color/transparent], Visual preferences icons for YouTube [RVX settings menu icon: extension], Overlay buttons [Change top buttons: true], Settings for YouTube [Insert position: @string/about_key]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: false
Use pre-release: false
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 56 patches
Compiling patched dex files
Compiled 9 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```

### Solution

No clue...

### Additional context

I am using a third party icon pack known as dove icon pack.
https://play.google.com/store/apps/details?id=com.jndapp.dove.iconpack

It has an icon available for modded versions of youtube as u can see here.

![Screenshot_20241119_154547_Dove](https://github.com/user-attachments/assets/ee80a66c-0f54-467d-8a4e-6f24ad576975)

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I cannot reproduce this issue on my side. Clear data of the Manager, or reinstall it. Let me know, if it fixed anything. Custom branding icon is disabled by default and icons change on my side.

**Comment by Git-ship-it-coder** [comment]
I've already reinstalled rvx manager, deleted the logs and cache from the app and outside the app from system ui as well. cleared data. i dont know what else could be the problem. i hope it gets solved by its own after some time. thank you for responding tho.
