### ISSUE TITLE
feat: Let me categorize my YouTube Subscriptions

### ISSUE THREAD

**Issue by Temp-Account07** [anddea/revanced-patches#873]
### Application

YouTube

### Feature description

-be able to organize your Subscriptions (and later maybe playlists too)

Categories with subcategories

![Screenshot_20241120_190133_YouTube~2](https://github.com/user-attachments/assets/580460b4-13a4-4bad-8bb0-6b18563301d7)

### Motivation

-can look for specific topics without being disctracted
-would save so much time

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Temp-Account07** [comment]
I recently found the chrome extension that i used in the picture its https://pockettube.io/

![image](https://github.com/user-attachments/assets/714b9be6-3149-4cbb-8d10-bbf636d846e9)

**Comment by Francesco146** [comment]
not doable, website of yt and it's app shares nothing in the code

**Comment by Temp-Account07** [comment]
> not doable, website of yt and it's app shares nothing in the code

https://play.google.com/store/apps/details?id=com.youtubesubscriptionmanager&hl=de&pli=1

There is this app that can do it started as chrome extension and now also on android and ios, 
i just wanted to not having to use 2 different apps

**Comment by Francesco146** [comment]
it's a different app, that renders the yt website on your phone. its not doable implementing the whole app in a subsection of yt's original app

**Comment by Temp-Account07** [comment]
> it's a different app, that renders the yt website on your phone. its not doable implementing the whole app in a subsection of yt's original app

Ok that makes sense, thanks for clearing it up
