### ISSUE TITLE
feat: Volume Icon Should Show Speed

### ISSUE THREAD

**Issue by nochlab1** [anddea/revanced-patches#875]
### Application

YouTube

### Feature description

Hi i am wondering if the icon for changing speed can have a option to switch it to show the current playback speed instead of an icon
Thanks

### Motivation

I can see my speed easily 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
can't do that, we'd need an image for all possible speeds, that can also be in decimal format. undoable as you proposed it
