### ISSUE TITLE
question: How to change default settings for apk?

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#879]
### Application

Other

### Question description

How can i change default settings for the apk now? Before merge i had to change in integrations for youtube. For YTM both integrations and patches now what?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
The structure is similar, but the files are merged and placed into their respective folders: patches directory for patches and extensions directory for integrations. `Settings.java` and other needed files are still there.

**Comment by AykhanUV** [comment]
How can i build from source?
