### ISSUE TITLE
bug: (Shorts Component) - Showing Jumbled Characters in Channel name.

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#880]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Latest Supported

### Bug description

After updating to the latest patches, Channel name is not showing properly. Instead of the channel name (or handle name), it is showing Jumbled characters.

![Screenshot_20241211_235841](https://github.com/user-attachments/assets/33977fef-c88e-43ad-b70d-f43a2b38bdb1)

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I can't reproduce this issue. Latest YouTube version (19.34) is still unstable. There are bigger issues than this one, still I can't reproduce it on 19.34.

**Comment by KobeW50** [comment]
> it is showing Jumbled characters.


The characters is the unique video identifier that can be seen in the video URL: `https://youtube.com/shorts/MGCJp3rL44I`

**Comment by anddea** [comment]
> Channel name is not showing properly

Do you see this issue with the default settings? If not, you might want to specify which settings you have changed.

**Comment by vippium** [comment]
> > Channel name is not showing properly
> 
> Do you see this issue with the default settings? If not, you might want to specify which settings you have changed.

This will also happen with default settings. [Check this](https://imgur.com/a/BXMsdTI)
2. And also, there is a bug with splash screen in light theme. The old splash doesn't work with light theme. It just shows a blank plain splash screen. It works with dark theme.

**Comment by vippium** [comment]
> Does it happen on older versions for you? I still can't reproduce. Based on that video, it appears only when you enable channel handle, and for me it works as intended.

Ya...it only happens while enabling the channel handle. It works fine with older version

**Comment by anddea** [comment]
It's because the `Return YouTube Channel Name` setting is an Experimental feature, Experimental means, if it's broken no one will maintain it.
