### ISSUE TITLE
bug: (Visual Preference Icons) - Not showing `RVX Letters and RVX Books Letters` Icons

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#881]
### Type

Other

### Tools used

RVX Manager

### Application

Latest Supported

### Bug description

Not showing after 3,0 update. If we use id of those, then they will work. But not showing directly in RVX manager.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Fixed in the latest `dev`
