### ISSUE TITLE
bug: cairo seekbar bug

### ISSUE THREAD

**Issue by Adity1243** [anddea/revanced-patches#882]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v19.32.36

### Bug description

The custom cairo seekbar colour returns to default red colour  before disappering.

### Error logs

```shell
.
```

### Solution

.

### Additional context

.

### Device Environment

Oneplus 12R , oxygen os 15

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Adity1243** [comment]
https://github.com/user-attachments/assets/b49d48d9-4cb8-4080-97ba-e2ed2b374811

**Comment by Adity1243** [comment]
Sorry about recording i dont how its sended like this.

**Comment by anddea** [comment]
Unfortunately, I can't watch your recording, maybe upload it somewhere else, like imgur?

**Comment by Adity1243** [comment]
> Unfortunately, I can't watch your recording, maybe you could upload it somewhere else, like imgur?
> 
> In 19.30+ versions cairo seekbar has the same behavior going white or custom color (if set), but in 19.23 for example (since I tested this version), it doesn't change cairo color. I don't know if I understood you correctly.

Here's imgur video bug recorded link :-
https://imgur.com/a/35BVHe6

**Comment by Adity1243** [comment]
The seekbar turns default red colour before disappering.

**Comment by Adity1243** [comment]
I think its related to version incompatibility i patced dev-2 patches with youtube version 19.20.39 and its fixed also afn blue animation is also fixed.
