### ISSUE TITLE
gradient loading screen doesn't work

### ISSUE THREAD

**Issue by Wojtaz0w** [anddea/revanced-patches#884]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Version 19.34.42
anddea.youtube

### Bug description

![Screenshot_20241212-133137](https://github.com/user-attachments/assets/6572c24a-0d3f-4502-b0bf-fde3d1e95126)
![Screenshot_20241212-142923](https://github.com/user-attachments/assets/cab87851-4b2d-45d2-97d2-4e891bc79ff0)
![Screenshot_20241212-143015](https://github.com/user-attachments/assets/77ca2740-d895-4808-bab7-a1561ca5f74e)
It sometimes works under video player, but not in the main feed.

### Device Environment

Android 15 QPR 2 Beta 1 
Pixel 9

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Reopen this issue [here](https://github.com/inotia00/ReVanced_Extended/issues).
