### ISSUE TITLE
bug(YT): Old Splash Screen not showing in light mode.

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#886]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Latest Supported in Dev

### Bug description

Old Splash Screen is not working in Light mode. It is working fine in dark mode.

https://github.com/user-attachments/assets/bf4e80ee-fb7a-4fab-a78d-91c1e1feb769

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Please reopen this issue [here](https://github.com/inotia00/ReVanced_Extended/issues).
