### ISSUE TITLE
question: cli failed to patch with Custom header

### ISSUE THREAD

**Issue by AliBASE** [anddea/revanced-patches#888]
### Application

YouTube

### Question description

YouTube Version = 19.16.39
Patch Version = 3.0.0-dev.4
Cli Version = 5.0.1
I have this error "custom header for YouTube" disabled.the custom icon is applied, but the custom header didn't, and both have the same value in the options.json "vanced_black"

Code:
`
java -jar cli.jar patch -p patches.rvp -o "Revanced.apk" youtube_19.16.39.apk" -e "Custom branding icon for YouTube" -e "Custom branding name for YouTube" -e "Custom package name".
`

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
In your cli command you need to add -e "Custom header for YouTube", in options.json there should be "custom_branding_icon", which is the default option.

**Comment by AliBASE** [comment]
Solved, thx!
