### ISSUE TITLE
feat(YouTube - Action button): Hide action button labels

### ISSUE THREAD

**Issue by GitGitu79** [anddea/revanced-patches#892]
### Application

YouTube

### Feature description

Hide action button label below player leaving only the icon.
![Screenshot_20241214_141737_YouTube](https://github.com/user-attachments/assets/430b6567-96ee-4190-91f0-d5cfb0184a5f)

### Motivation

Because YouTube music have this feature. I thought YouTube should also have it.
![Screenshot_20241214_141457_YouTube Music](https://github.com/user-attachments/assets/25c72f91-2605-4fe4-8f72-28fc97be9b3f)
![Screenshot_20241214_141650_YouTube Music](https://github.com/user-attachments/assets/89b84625-fc6e-4e7d-a552-9880e757a867)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Unfortunately, not possible. Read issues below. 

https://github.com/anddea/revanced-patches/issues/688

https://github.com/inotia00/ReVanced_Extended/issues/966#issuecomment-1627486199
