### ISSUE TITLE
feat (Youtube - Player): add option to remove haptic feedback from speed overlay

### ISSUE THREAD

**Issue by jua2ja2** [anddea/revanced-patches#895]
### Application

YouTube

### Feature description

Add an option to remove haptic feedback from speed overlay, where speed overlay refers to the feature where the video speeds up when long pressed. 

### Motivation

I personally dislike haptic feedback, and I'm sure I'm not the only one.  There are already many options to remove haptic feedback from other parts of the app, all of which I have turned off, but not speed overlay. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
What about options in RVX Settings > Player > Haptic feedback, don't they work? I don't have haptic feedback at all if all options are enabled.

**Comment by jua2ja2** [comment]
I have all turned 5 of these settings (they are saying haptic feedback is disabled 5 times). I can confirm that at the very least the first one works, as I do notice it controls haptic feedback on chapter select. Regardless of these settings I still DO have haptic feedback on speed overlay, when I hold on the screen to speed up the video. If this isn't intended, it needs to then be classified as a bug.

Disabling system wide vibrations does remove the haptic feedback as a workaround, but also disables every type of system vibrations, which isn't the desired outcome. 

I'm using app version 19.32.36, Samsung Galaxy S22.

**Comment by anddea** [comment]
If you still encounter this issue in the latest `dev` release, reopen this issue [here](https://github.com/inotia00/ReVanced_Extended/issues).
