### ISSUE TITLE
feat: disable autodub

### ISSUE THREAD

**Issue by u2716** [anddea/revanced-patches#896]
### Application

YouTube

### Feature description

option to disable autodub/choose original audio by default

### Motivation

Youtube uses the ai dubbed audio by default and there's no option to change audio track on the mobile app.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
There's already "Disable forced auto audio tracks" in RVX Settings > General.

**Comment by u2716** [comment]
I thought that option had a different purpose, because it doesn't work. I'll try opening an issue on rvx then.
