### ISSUE TITLE
question: Spoof steaming data

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#897]
### Application

YouTube

### Question description

Why "Miscellaneous - Spoof streaming data" got removed in extensions/integrations? I mean it like i can't choose default type anymore

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AykhanUV** [comment]
I mean it [here](https://github.com/anddea/revanced-patches/blob/094ef254f3128cf0101ece77c2ee203febd73d0e/extensions/shared/src/main/java/app/revanced/extension/youtube/settings/Settings.java#L568)

**Comment by anddea** [comment]
It is now a shared patch between YouTube and YouTube Music, moved to [BaseSettings.java](https://github.com/anddea/revanced-patches/blob/094ef254f3128cf0101ece77c2ee203febd73d0e/extensions/shared/src/main/java/app/revanced/extension/shared/settings/BaseSettings.java#L44)

**Comment by AykhanUV** [comment]
Hey how can i change type now? I searched in files and found

public static ClientType SpoofStreamingDataDefaultClient() {
        return ClientType.IOS;
    }

If this is correct can you tell me values i can put?

**Comment by anddea** [comment]
You can use ANDROID_VR, ANDROID_UNPLUGGED. 

https://github.com/anddea/revanced-patches/blob/4cf965eaa292cbe660e379aa38f8c09581df8fb6/extensions/shared/src/main/java/app/revanced/extension/shared/patches/client/AppClient.java#L118-L151

In the same file where you found this piece of code
https://github.com/anddea/revanced-patches/blob/4cf965eaa292cbe660e379aa38f8c09581df8fb6/extensions/shared/src/main/java/app/revanced/extension/shared/patches/PatchStatus.java#L11-L13

You have import statement for it, that way you can understand where to look
https://github.com/anddea/revanced-patches/blob/4cf965eaa292cbe660e379aa38f8c09581df8fb6/extensions/shared/src/main/java/app/revanced/extension/shared/patches/PatchStatus.java#L3
