### ISSUE TITLE
question: How can i build

### ISSUE THREAD

**Issue by AykhanUV** [anddea/revanced-patches#899]
### Application

Other

### Question description

How can i build .rvp from source properly? I build it using ./gradlew build and get 3 files, when i upload it and open in RVX manager i can't see apps in patcher section

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
You need to upload only one .rvp file and patches.json to make it appear in the Manager.

This repository automatically publishes needed files in order for them to be visible in the Manager. You can see the exact command [here](https://github.com/anddea/revanced-patches/blob/094ef254f3128cf0101ece77c2ee203febd73d0e/.github/workflows/release.yml#L41C14-L41C50). The `build` and `assemble` commands should work with the CLI but, I guess, not with the Manager, as they don't generate patches.json. I believe, the `publish` command should work and generate json file as well. Correct me if I'm wrong.

**Comment by AykhanUV** [comment]
I did as you said, first ran "./gradlew generatePatchesFiles clean" and got "patches.json" file but did not get any .rvp so i ran "./gradlew build" and uploaded it to fork of this repo still can't see it

**Comment by Jeromi-e** [comment]
Same issue I'm facing right now, can't see app list nor patch list in manager

**Comment by anddea** [comment]
`clean` command deletes the build directory.

```bash
./gradlew tasks --all | grep "clean"
```

```bash
extensions:shared:clean - Deletes the build directory.
extensions:shared:stub:clean - Deletes the build directory.
patches:clean - Deletes the build directory.
```

**Comment by AykhanUV** [comment]
I think there is problem with the source, i fresh downloaded it and just did "./gradlew generatePatchesFiles" right away and uploaded both still getting that error, but when i do your ones from releases page it works

**Comment by Jeromi-e** [comment]
@anddea Did what you said, still same issue. Do i have to be on Linux for this? I'm on Windows 11 rn
Or maybe i need different gradle or java version?

**Comment by anddea** [comment]
You need to upload patches.json file as well along with .rvp. What about publish command?

**Comment by AykhanUV** [comment]
I'm already doing that but problem is with .rvp file it's size is different from one you released. Publish command gives many errors

**Comment by Jeromi-e** [comment]
From my experience patches,json is not required for app list to show in manager i downloaded just .rvp from dev5 and only that worked

**Comment by anddea** [comment]
I don't publish locally built releases, all releases are built inside GitHub, so I answered your question theoretically. Now, that I tested it, you can definitely use `publish` (as it is something like a master task) and if you see errors, you can exclude failing tasks, like

```bash
./gradlew publish -x signReVancedPatchesPublication -x publishReVancedPatchesPublicationToDummyMavenLocalRepository -x publishReVancedPatchesPublicationToGitHubPackagesRepository
```

And patches.json file is not needed at all. That was my mistake. I know some people use just build command and it works for them, so it might differ in different cases, like environment, OS, etc. 

You might wanna ask other people as well, especially those who publish releases manually. Maybe you'll find a better way. And then you can let us know as well for other people coming and questioning the same thing.

**Comment by anddea** [comment]
You can use 
```bash
./gradlew buildAndroid
```
That works for me as well and no need for `publish` command.

**Comment by AykhanUV** [comment]
Worked for me thanks
