### ISSUE TITLE
About Default video quality 

### ISSUE THREAD

**Issue by Mohammed1520** [anddea/revanced-patches#9]
### Application

YouTube

### Question description

When shifting between WIFI and Mobile data . Video quality isn't changed automatically as intended and i need to change it manually
For example when i play video 720p through wifi and change to Mobile data it still 720 and Doesn't change to the intended Mobile data quality
Is there a solution 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Mohammed1520** [comment]
Quality doesn't change even i eant to change it manually. For example I have played Video on 720 
When i try to change it to 360 it still on 720 .. this bug seems to be present in REX and Revanced

**Comment by Mohammed1520** [comment]
Update .. it seems that this setting has an issue in REX and also ReVanced. 
When i try to change the quality of any video manually, it doesn't change like in this screenshot
My default quality on wifi is 720 . Whenever I try to change it from video settings it n
![Screenshot_20240313_161227_anddea youtube_edit_15211745634135](https://github.com/anddea/revanced-patches/assets/107951133/33160962-2ae3-4ba8-8e69-9a272a0ca530)
ever changes and still on 720

**Comment by anddea** [comment]
Quality is changed when you play a new video. Check if it works. If you turn on Wi-Fi in the middle of a video then it won't change for currently playing one.

**Comment by Mohammed1520** [comment]
I know this . But the problem now is that the quality can't be changed like the previous screenshot

**Comment by Mohammed1520** [comment]
It takes long time *about one minute* for changed quality to be applied.

**Comment by anddea** [comment]
> It takes long time _about one minute_ for changed quality to be applied.

It can be because video was buffered before in one quality and when you changed it will play in buffered quality and then will change it, so it might be minutes until quality shows different value.
