### ISSUE TITLE
bug: YouTube background playback notification still shown and YouTube stays active in background even when app is closed when background playback turned off

### ISSUE THREAD

**Issue by racnes** [anddea/revanced-patches#90]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v19.09.37

### Bug description

YouTube background playback notification still shown and YouTube stays active in background even when app is closed when background playback turned off. I showed it detailed in the video below.

That bug was not happening while I'm on original YT and inotia's 19.02.39 RVX patches. When I removed and reinstalled the 19.09.37 version with your patches, problem solved but shortly after I got same bug again.

[Video explanation](https://streamable.com/93qpry)

### Device Environment

Android 14, Samsung Galaxy A73

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
this happens on regular YT? RVX?

**Comment by anddea** [comment]
It might be the YouTube issue, or RV background playback. If you still face this issue, reopen in inotia's repo.
