### ISSUE TITLE
bug: Low View Filter Not Working in Recommendations After Watching a Video

### ISSUE THREAD

**Issue by kineci** [anddea/revanced-patches#902]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

When the **"low view filter"** feature is enabled in the app, videos with a low number of views (e.g., less than 300) are still being recommended after watching a video. This issue persists even when the filter is set correctly in the settings. The expected behavior is for such videos to be hidden from recommendations, but they continue to appear.

---

## Steps to Reproduce  
1. Open the **Video Filter** settings.
2. Enable the **"Weniger als Anrufe"** filter and set it to hide videos with fewer than 300 views.
3. Watch any video.
4. After the video ends, check the recommended videos section.

---

## Expected Result  
Videos with views below the specified threshold (e.g., 300 views) should **not appear** in the recommended video section.

---

## Actual Result  
Videos with fewer than 300 views **continue to appear** in the recommended section.

---

## Screenshots  

1. **Filter Settings Applied:**  
   The filter is set to hide videos with fewer than 300 views.  
![Screenshot_20241219-013812](https://github.com/user-attachments/assets/e1da93da-4d3b-4b48-9001-d46875a65370)
![Screenshot_20241219-013821](https://github.com/user-attachments/assets/537e8e57-6da5-48fb-b1e1-3ba9a4d1b199)
![Screenshot_20241219-013827](https://github.com/user-attachments/assets/49ea8199-7dd0-4d49-b08c-ec04995b2945)
   

2. **Recommendation Issue:**  
   Despite the filter, videos with <300 views are being recommended.  
![Screenshot_20241219-013627~2](https://github.com/user-attachments/assets/8e932db9-d149-4093-ad50-a218b23d9fa9)
![Screenshot_20241218-093114~2](https://github.com/user-attachments/assets/5faa8c3f-ce81-4aed-b2d4-242b7734d102)

---

## Device Language

- **Language:** German (Deutsch)  

### Additional context

- The issue appears consistently **after watching videos**.  
- The filter works correctly on the **home page** and **search results** but not in **post-video recommendations**.

### Device Environment

OxygenOS v11.1.2.2

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Your keys mapping is wrong. For German it should be
```
Mio. -> 1 000 000
Mrd. -> 1 000 000 000
Aufrufe -> views
```

You can update this translation in translation for your language. The string of the key is `revanced_hide_video_view_counts_multiplier_default_value`.

Let me know, if it worked for you or you're still facing issues.
