### ISSUE TITLE
suggestion(YT/Replace Create Button): Little enhancement on Settings icon

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#903]
### Application

YouTube

### Suggestion description

When we replace the create icon with settings, it doesn't match the icon type on home screen but it matches on the You tab. Just it needs a little fix. 
![Screenshot_20241219_150540](https://github.com/user-attachments/assets/ae7cc5af-9f50-4c8c-a218-1a6661c564e0)
![Screenshot_20241219_150543](https://github.com/user-attachments/assets/5b877c1a-a952-439d-b818-21e644ee3392)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Please always open issues [here](https://github.com/inotia00/ReVanced_Extended/issues) first. If it's rejected there, then reopen it here.

**Comment by vippium** [comment]
> Please always open issues [here](https://github.com/inotia00/ReVanced_Extended/issues) first. If it's rejected there, then reopen it here.

🫣 I'll keep it in mind next time.
