### ISSUE TITLE
bug: the color is pink for the navigation bar notifications inside youtube

### ISSUE THREAD

**Issue by husseinxali** [anddea/revanced-patches#905]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube

### Bug description

After the last update, the navigation bar notifications is pink not red

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
No additional data is provided like app version, screenshot or anything. I can't reproduce this issue, the notification dot is red for me.

**Comment by husseinxali** [comment]
I applied now the latest patch on YT 19.44.39, and same.

Device s24 ultra

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anddea** [comment]
The YouTube is changing its branding color, so that might be it. Still I can't reproduce it on my side. 

Try to report it [here](https://github.com/inotia00/ReVanced_Extended/issues).

**Comment by husseinxali** [comment]
Thanks, I will

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
