### ISSUE TITLE
bug: youtube music no option to hide the text label of player icons

### ISSUE THREAD

**Issue by husseinxali** [anddea/revanced-patches#906]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube Music

### Bug description

The option to hide the text label of player icons is not there

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
I can't reproduce this issue, the option is in RVX Settings > Action bar > Hide action button labels. You didn't not provide any other information such as app version, patches version, etc.

**Comment by husseinxali** [comment]
YTM 7.25.52

I applied the last patch and this option you mentioned  is not appearing.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anddea** [comment]
7.25.52 does not support action button labels, read [this](https://github.com/inotia00/ReVanced_Extended/issues/2554).

**Comment by husseinxali** [comment]
Thx bro

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
