### ISSUE TITLE
bug: buffering issue

### ISSUE THREAD

**Issue by Adity1243** [anddea/revanced-patches#909]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube v19.38.41

### Bug description

The video starts buffering at some time of playing video also if i seek or fast forward the video the video starts buffering also happing on seekbar fast forward.

### Error logs

```shell
.
```

### Solution

.

### Additional context

.

### Device Environment

Oneplus 12R, oxygen os 15

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Try to change spoof streaming data type / default client. If you still face this issue, reopen it [here](https://github.com/inotia00/ReVanced_Extended/issues).

**Comment by Adity1243** [comment]
Not happeninh on other clients but ios is good spoof client otherwise on other client the sound gets lowered in videos also no AV01 codec
