### ISSUE TITLE
bug(YTM): `Custom Header` is not working

### ISSUE THREAD

**Issue by vippium** [anddea/revanced-patches#910]
### Type

Other

### Tools used

RVX Manager

### Application

Latest Supported

### Bug description

Not applying custom header. 

https://github.com/user-attachments/assets/0137bda3-3e07-4869-90cd-424fca27a12b

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Cannot reproduce this issue. Should be something wrong on your side. You did not provide any additional information to further inspect. If you still face this issue, reopen it [here](https://github.com/inotia00/ReVanced_Extended/issues).
