### ISSUE TITLE
feat: Add youtube official cairo icons on setting page

### ISSUE THREAD

**Issue by imvoldemort** [anddea/revanced-patches#913]
### Application

YouTube

### Feature description

Add an option to select the youtube official cairo icons on setting page

### Motivation

YouTube official cairo icons are organised by categories

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Could you elaborate? Screenshots maybe or something?

**Comment by imvoldemort** [comment]
Here are some snaps:
![IMG_20241225_185137](https://github.com/user-attachments/assets/4b6a8033-c65b-4504-af24-fde50708c50c)
![IMG_20241225_185150](https://github.com/user-attachments/assets/131bb19a-ae68-4aeb-94e0-e17fe129cfcd)

**Comment by anddea** [comment]
Are these official icons by YouTube? What version is that? I didn't see them. And why do you want them to add, if they're going to be added later anyway (if it's a/b feature).

**Comment by imvoldemort** [comment]
They're appearing on official YouTube v19.50.40.
In that case, I just need to deselect the 'settings for YouTube' option fron the patches to get the youtube official setting page and icons right?

**Comment by anddea** [comment]
I'm not sure, seems like this new setting page is so different, that maybe that icon patch won't even work. But yes, if you disable the patch, you won't get icons from patch, and all original icons will be there instead.

**Comment by imvoldemort** [comment]
Thanks

**Comment by anddea** [comment]
The Cairo settings are disabled by patch in ReVanced and RVX, so actually you won't see these settings if you patch. Since it has some issues it won't work in RVX for now. 

Read this comment:
https://github.com/anddea/revanced-patches/blob/b5ca533f685aed7d0aae40a5e87bb5a09bba93d7/patches/src/main/kotlin/app/revanced/patches/youtube/utils/fix/cairo/CairoSettingsPatch.kt#L20-L23
