### ISSUE TITLE
bug: Some icons are not working error

### ISSUE THREAD

**Issue by OtakuArab** [anddea/revanced-patches#919]
### Type

Error while patching

### Tools used

RVX Manager

### Application

V19.44.39

### Bug description

Black YouTube icon and some icons do not work. Error appears when editing by RVX Manager 
![Screenshot_٢٠٢٤-١٢-٢٧-١٣-٣٧-٠٠-٢٢٠_app rvx manager flutter](https://github.com/user-attachments/assets/74c52404-3c44-4c73-ae51-6efe1a17bcdb)
![Screenshot_٢٠٢٤-١٢-٢٧-١٣-٣٩-٤٧-٥٨١_app rvx manager flutter](https://github.com/user-attachments/assets/de328d3f-0d08-4266-96ad-367431d10dd3)
Other icons work without problems.

### Solution

I expect that there are many icons that have the same problem.

### Device Environment

MIUI Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched apps.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by anddea** [comment]
Restore old splash animation should be disabled for YouTube Black icon.
