### ISSUE TITLE
bug: Cairo Seekbar Color Issue 

### ISSUE THREAD

**Issue by Aurora3rs** [anddea/revanced-patches#921]
The start and end color of the Cairo Seekbar are reversed which shouldn't be the case, unless I'm mistaken. See the 2 photo comparing the _supposedly_ buggy one with the normal one.

Patched using RVX Manager
YT Version is 19.44.39 (v.3.1.0-dev.2)
Device is HUAWEI P40 Lite, EMUI 12 (Android 10)

![Picsart_24-12-27_16-11-42-565.jpg](https://github.com/user-attachments/assets/235266df-7af9-46ae-9223-7a9e52dc66d6)

![Picsart_24-12-27_16-13-43-468.jpg](https://github.com/user-attachments/assets/3a169f74-a137-4610-80f0-ee8fd488fa38)

**Comment by anddea** [comment]
It was recently reversed, because start color wasn't at the start / on the left of the seekbar. Right now it should be correct, start color at the start of the seelbar. Is it different for you?

**Comment by Aurora3rs** [comment]
Are you referring to this [recent change](https://github.com/anddea/revanced-patches/commit/e9bd106114c1669426d10830b544d7936a0728a1)? If yes, then it is different for me, the magenta (pink) is at the start (on the left) while the red cairo is at the end (on the right) which should be the other way (at least that's how it is on _unpatched_ YouTube). 

Currently, my YouTube looks like in the picture _"How it looks"_ which I uploaded above, but my YouTube should be looking like in the picture _"How it should look"_.

**Comment by Aurora3rs** [comment]
Thanks! ❤️

**Comment by anddea** [comment]
Thank you for your report, I totally forgot to reverse default values.
